## Hilbert schemes: definition, existence theorem {#fga3.iv-3}

Let $X$ be a prescheme over another prescheme $S$, and $\sh{F}$ a quasi-coherent module on $X$.
We denote by
$$
  \Quot(\FXS)
$$
the set of quasi-coherent modules given by quotients of $\sh{F}$ that are flat over $S$.
Now let $S'\to S$ be a base change morphisms, and set $X'=X\times_S S'$, and $\sh{F}'=\sh{F}\otimes_{\OO_S}\OO_{S'}$, so that $X'$ is a prescheme over $S'$ endowed with a quasi coherent module $\sh{F}'$, and we can consider $\Quot(\FXSp)$.
\oldpage{221-11}
We set
$$
  \shQuot_{\FXS}(S') = \Quot(\FXSp)
$$
(where $X'=X\times_S S'$, as above).

Now, if $S''\to S'$ is an $S$-morphism, then $X''=X\times_S S''$ is isomorphic to $X'\times_{S'}S''$, and $\sh{F}''$ is isomorphic to $\sh{F}'\otimes_{\OO_{S'}}\OO_{S''}$, and, since the inverse image functor $\sh{G}'\mapsto\sh{G}'\otimes_{\OO_{S'}}\OO_{S''}$ from the category of quasi-coherent modules on $X''$ is right exact, and sends $S'$-flat modules to $S''$-flat modules, we obtain a natural map
$$
  \Quot(\FXSp) \to \Quot(\sh{F}''/X''/S'')
$$
and so $\shQuot_{\FXS}(S')$ is a \em{contravariant functor in $S'$} (where $S'$ is a prescheme over $S$), with values in the categories of sets.
In what follows, we suppose that $X$ is \em{projective} over a \em{Noetherian} $S$, with $\sh{F}$ \em{coherent};
for simplicity, we will limit ourselves to considering those $S'$ which are \em{locally Noetherian} over $S$.

::: {.itenv #fga3.iv-theorem-3.1 title="Theorem 3.1" latex="{Theorem 3.1}"}
Under these conditions, the contravariant functor $\shQuot_{\FXS}$ on the category of locally Noetherian $S$-preschemes is \em{representable} by an $S$-prescheme $\repQuot_{\FXS}$, given by the sum of a sequence of projective $S$-schemes (and a fortiori $\repQuot_{\FXS}$ is locally of finite type over $S$).
:::

We will obtain such a decomposition in the following way.
Let $\OO_X(1)$ be an invertible sheaf on $X$ that is very ample with respect to $S$.
For every polynomial $P(n)$ with rational coefficients, let $\Quot^P(\FXS)$ be the subset of $\Quot(\FXS)$ consisting of coherent quotients $\sh{G}$ of $\sh{F}$ that are flat over $S$ and whose Hilbert polynomial at each $s\in S$ is equal to $P$.
We then set
$$
  \shQuot_\FXS^P(S') = \Quot^P(\FXSp)
$$
and thus obtain a subfunctor of $\shQuot_\FXS$.
The invariance property of Hilbert polynomials (recalled in [§2](#fga3.iv-2)) implies the following:
*For $\shQuot_\FXS$ to be representable, it is necessary and sufficient that the $\shQuot_\FXS^P$ be representable, and then the $S$-prescheme $\repQuot_{\FXS}$ which represents it is isomorphic to the prescheme given by the sum of the $\repQuot_{\FXS}^P$ that represent the functors $\shQuot_\FXS^P$*.
With this, [Theorem 3.1](#fga3.iv-theorem-3.1) will be a consequence of the following theorem:

::: {.itenv #fga3.iv-theorem-3.2 title="Theorem 3.2" latex="{Theorem 3.2}"}
\oldpage{221-12}
With the above notation, the functor $\shQuot_\FXS^P$ is representable by a projective $S$-prescheme $\Quot_\FXS^P$.
:::

The rest of this section is dedicated to the proof of [Theorem 3.2](#fga3.iv-theorem-3.2).

Let $\nu$ be an integer.
For every $S'$ over $S$, we denote by $A_\nu(S')$ the set of quotients $\sh{G}=\sh{F}'/\sh{H}$ of $\sh{F}'=\sh{F}\otimes_{\OO_S}\OO_{S'}$ that are coherent, flat over $S'$, and satisfy the following conditions:

a. $\RR^i f'_*(\sh{G}(n))=0$ for $i>0$ and $n\geqslant\nu$;
b. $\RR^i f'_*(\sh{H}(n))=0$ for $i>0$ and $n\geqslant\nu$;
c. $f'_*(\sh{H}(\nu+k))=\mathcal{S}'_k f'_*(\sh{H}(\nu))$ for $k\geqslant0$.

For this last condition, we suppose that $X$ is written as the homogeneous prime spectrum of a quasi-coherent positively-graded algebra $\mathcal{S}_\bullet$ over $S$ that is generated by $\mathcal{S}_1$, and we set $\mathcal{S}'=\mathcal{S}\otimes_{\OO_S}\OO_{S'}$, so that $X'$ is the homogeneous prime spectrum of $\mathcal{S}'$.
To prove [Theorem 3.2](#fga3.iv-theorem-3.2), we can easily reduce to the case where $X=\PP_S^r$ (since $S$ is a union of open subsets $U$ such that $X|U$ is a closed subscheme of $\PP_U^r$, and $\OO_X(1)$ is induced by $\OO_{\PP_U^r}(1)$), and where $\sh{F}$ is of the form $(\OO_{\PP_S^r})^N$, and thus flat over $S$.
Then, in the above, the sheaves $\sh{H}$ are also flat over $S'$.
It then follows from the Künneth relations [[GD1960](GD1960), III, §7] and from (b) that the conditions (a) and (b) are stable under base change, and imply that, for $n\geqslant\nu$, forming $f'_*(\sh{G}(n))$ and $F'_*(\sh{H}(n))$ commutes with extension of the base (*loc. cit.*).
In other words, \em{$A_\nu(S')$ is a contravariant functor in $S'$, and in a precise sense a subfunctor of $A(S')=\shQuot_{\FXS}^P(S')$}.
For varying $\nu$, we thus obtain an increasing sequence of subsets $A_\nu(S')$ of $A(S')$, whose union is $A(S')$ by a well known theorem of Serre [[GD1960](GD1960), III, §2].
Note now that, if $\sh{G}$ is a coherent quotient of $\sh{F}'$ which is flat over $S$, and $s$ an element of $S$ such that the base change $\Spec(k(s))\to S$ gives rise to a quotient $\sh{G}_s$ of $\sh{F}_s$ satisfying conditions (a), (b), and (c), i.e. is in $A_\nu\Spec(k(s))$, then there exists an open neighbourhood $U$ of $s$ such that these same conditions are satisfied by $\sh{G}|(f')^{-1}(U)$, i.e. this quotient is in $A_\nu(U)$;
for (a) and (b), this follows in fact from the "Theorem of holomorphic functions" [[GD1960](GD1960), III, §7], and (c) follows from the Nakayama lemma and the fact that we know that $f'_*(\sh{H}(n+k))=S'_kf'_*(\sh{H}(n))$ anyway for $n$ large enough and $k\geqslant0$ [[GD1960](GD1960), III,§2].
\oldpage{221-13}
From these remarks, we conclude the following (compare with [[Gro1960a](Gro1960a), IV]).
*For the functor $A$ to be representable, it is necessary and sufficient that the functors $A_\nu$ be representable, and then the $S$-prescheme $Q$ that represents $A$ is the increasing union of the opens $Q_\nu$ that represent the $A_\nu$.*

Let
$$
  M_\bullet
  = \sum_{n\geqslant0} f_*(\sh{F}(n))
  = \mathcal{S}_\bullet^N
$$
so that we have
$$
  M'_\bullet
  = M_\bullet\otimes_{\OO_S}\OO_{S'}
  = \sum_{n\geqslant0} f'_*(\sh{F}(n))
  = {\mathcal{S}'_\bullet}^N.
$$

It follows from (a) that we have

a'. $f'_*(\sh{G}(n))$ is locally free of rank $P(n)$ for $n\geqslant\nu$ [[GD1960](GD1960), III, §7]

and it follows from (b),for $i=1$, that we have

a''. $f'_*(\sh{G}(n))$ is a quotient module of $M'_n$.

Also, the knowledge of this quotient module, for $n=\nu$, implies, by (c), that the knowledge of the submodules $f'_*(\sh{H}(n))$ of $M_n$ for $n\geqslant\nu$, and thus the knowledge of $\sh{H}$ and consequently of $\sh{G}$.
We thus obtain an \em{injective map}
$$
  A_\nu(S') \to \shGrass_{P(\nu)}(M'_\nu)
$$
from $A_\nu(S')$ to the set of locally free quotient modules of $M'$ of rank $P(\nu)$, whence a \em{functorial} homomorphism
$$
  i_\nu\colon A_\nu(S') \to \shGrass_{P(\nu)}(M_\nu)(S')
$$
where the functor on the right hand side is representable by the Grassmannian scheme $\Grass_{P(\nu)}(M_\nu)$ (compare with [[Gro1960a](Gro1960a), V]), which is projective over $S$.
Then

::: {.itenv #fga3.iv-lemma-3.3 title="Lemma 3.3" latex="{Lemma 3.3}"}
  $A_\nu(S')$ is a representable functor, and the morphism $Q_\nu\to\Grass_{P(\nu)}(M_\nu)$ that represents the homomorphism $i_\nu$ is an immersion (which implies that $Q_\nu$ is quasi-projective over $S$).
:::

This claim is equivalent to the following (compare with [[Gro1960a](Gro1960a), IV]):
If we have a quotient module $N$ of $M'_\nu$ that is locally free of rank $P(\nu)$, then there exists a subprescheme $Z$ of $S'$ such that, for every locally Noetherian prescheme $T'$ over $S'$, the inverse image of $N$ over $T'$ is in $\Im A_\nu(T')$ if and only if $T'\to S'$ is bounded by the subprescheme $Z$.
\oldpage{221-14}
Changing notation, we can suppose that $S'=S$, i.e. we have a quotient $N_\nu$ of $M_\nu$ by a submodule $R_\nu$.
For it to come from an element of $A(s)$, it is necessary and sufficient that it satisfy the following two conditions:

i. $M_{\nu+k}/\mathcal{S}_k R_\nu$ is locally free of rank $P(\nu+k)$ for $k\geqslant0$.
ii. Both the subsheaf $\sh{H}$ of $\sh{F}$ defined by the graded submodule $R_\bullet=\sum_{k\geqslant0}\sh{S}_kR_\nu$ of $M_\bullet$ (cf. [[GD1960](GD1960), II, §3]) and the quotient $\sh{G}=\sh{F}/\sh{H}$ satisfy conditions (a) and (b) above.

These conditions are clearly necessary, and if they are satisfied then the sheaf $\sh{G}$ defined in (ii) above, being isomorphic to the sheaf associated to the graded $\sh{S}_\bullet$-module $N_\bullet$ given by the sum of the $M_{n+k}/\sh{S}_kR$ is \em{flat} over $S$ (since its fibres are direct factors of localisations of $N$ for homogeneous prime ideals of $\mathcal{S}_\bullet$), and correspond to the Hilbert polynomial $P$ by virtue of (i).
Taking (ii) into account, we then see that (a') and (a'') are satisfied, and thus, for $n\geqslant\nu$, the natural homomorphism $N_n\to f_*(\sh{G}(n))$ is a \em{surjective} homomorphism of locally free modules of equal rank, and thus an isomorphism, and thus $f_*(\sh{H}(\nu+k))=\mathcal{S}_kR_\nu$ for all $k\geqslant0$, which proves that $\sh{G}\in A_\nu(S)$ and that $R_\nu$ is the element of $\Grass_{P(\nu)}(M_\nu)$ defined by $\sh{G}$.

Criteria (i) and (ii) above apply equally to the situation obtained after a change of base $S'\to S$.
We will prove first of all the fact that condition (i) is satisfied after the change of base $S'\to S$ can be expressed by saying that $S'\to S$ is bounded by a certain subprescheme $Z$ of $S$;
once we have shown this result, we are led (replacing $S$ with $Z$) to the case where condition (i) is already satisfied on $S$, and since it is stable under change of base, it remains to express condition (ii).
But then, if $U$ denotes the set of $s\in S$ such that the cohomology of the sheaves induced on the fibre $X_s$ by $\sh{G}(n)$ and $\sh{H}(n)$ is zero in dimension $>0$ for $n\geqslant\nu$, then we have already shown that $U$ is open, and condition (ii) will be satisfied after a change of base $S'\to S$ if and only if $S'\to S$ is bounded by $U$, which proves [Lemma 3.3](#fga3.iv-lemma-3.3).
It thus remains to prove the following lemma:

::: {.itenv #fga3.iv-lemma-3.4 title="Lemma 3.4" latex="{Lemma 3.4}"}
Let $S$ be a locally Noetherian prescheme, endowed with a quasi-coherent positively-graded algebra $\mathcal{S}_\bullet$ generated by $\mathcal{S}_1$, and let $M_\bullet$ be a quasi-coherent graded $\mathcal{S}$-module of finite type, $P$ a polynomial with rational coefficients, and $\nu$ and integer.
Then there exists a (clearly unique) subprescheme $Z$ of $S$ that has the following property:
for every prescheme $S'$ over $S$, for $M_n\otimes_{\OO_S}\OO_{S'}$ to be locally free of rank $P(n)$ for all $n\geqslant\nu$, it is necessary and sufficient that $S'\to S$ be bounded by $Z$.
:::

\oldpage{221-15}
We can evidently suppose that $S$ is affine, and thus Noetherian.
Then:

::: {.itenv #fga3.iv-lemma-3.5 title="Lemma 3.5" latex="{Lemma 3.5}"}
For every integer $N\geqslant\nu$, let $U_N$ be the open subset of $S$ consisting of $s\in S$ such that $\rank_{k(s)}M_{ns}\otimes_{\OO_{S,s}}k(s)\leqslant P(n)$ for all $\nu\leqslant n\leqslant N$.
Then the decreasing sequence of open subsets $U_N$ stabilises.
:::

::: {.proof}
We know [[Gro1960b](Gro1960b), IV] that $S$ admits a finite partition into reduced subschemes $S_i$ such that each $M\otimes_{\OO_S}\OO_{S_i}$ is \em{flat} over $S$.
We can thus suppose that $M$ is flat, and thus that the $M_n$ are flat.
Finally, we can evidently suppose that $S$ is connected.
But then [[GD1960](GD1960), III, §7] there exists an integer $n_0$ and a polynomial $Q$ such that
$$
  \rank_{k(s)}M_{ns}\otimes_{\OO_{S,s}}k(s) = Q(n)
  \qquad\text{for }n\geqslant n_0.
$$
Suppose first of all that $P<Q$, and so $P(n)\neq Q(n)$ for large $n$.
Then we evidently have $U_N=\varnothing$ for large enough $N$, and thus a fortiori the sequence of $U_N$ stabilises.
In the contrary case, we have $P(n)\geqslant Q(n)$ for large $n$, and so $U_N=U_{n_0}$ for $N\geqslant n_0$, and the sequence of the $U_N$ again stabilises.
:::

In particular, the set $U_\infty$ of $s\in S$ such that

::: {.eqenv #fga3.iv-equation-asterisk title="" latex=""}
$$
  \rank_{k(s)}M_{ns}\otimes_{\OO_{S,s}}k(s) \leqslant P(n)
  \qquad\text{for all }n\geqslant\nu
\tag{$*$}
$$
:::

is open, since it is the intersection of the $U_N$.
We can then, for the proof of [Lemma 3.4](#fga3.iv-lemma-3.4) replace $S$ with the open subset $U$, which leads us to the case where the inequality in [($*$)](#fga3.iv-equation-asterisk) is satisfied at all $s\in S$.

::: {.itenv #fga3.iv-lemma-3.6 title="Lemma 3.6" latex="{Lemma 3.6}"}
Let $M$ be a module on a locally Noetherian prescheme $S$, and $r$ an integer.
Then there exists a (clearly unique) subprescheme $Z$ of $S$ that has the following property:
for all $S'$ over $S$, for $M\otimes_{\OO_S}\OO_{S'}$ to be locally free of rank $r$, it is necessary and sufficient that $S'\to S$ be bounded by $Z$.
If $\rank_{k(s)}M_s\otimes_{\OO_{S,s}}k(s)\leqslant r$ for all $s$, then $Z$ is a closed subprescheme of $S$ (supposing that $M$ is coherent).
:::

::: {.proof}
\oldpage{221-16}
Indeed, the above reasoning leads us to the case where we have the inequality ($*$) for all $s\in S$ (by replacing, if necessary, $S$ with the open subset consisting of the $s$ where the inequality is satisfied).
We can then suppose that $M$ fits into an exact sequence
$$
  \OO_S^q \to \OO_S^r \to M \to 0
$$
and the condition in question on the $S'$ over $S$ also implies that, in the corresponding exact sequence $\OO_{S'}^q\to\OO_{S'}^r\to M'\to 0$, the second arrow is an isomorphism, i.e. the first is zero.
We then see that the closed subprescheme $Z$ of $S$ defined by the ideal generated by the coefficients of the matrix defining the homomorphism $\OO_S^q\to\OO_S^r$ satisfies the desired condition.
:::

::: {.proof}
Returning to the proof of [(3.4)](#fga3.iv-lemma-3.4) where we left off, we denote by $Z_n$ the \em{closed} subprescheme of $S$ associated, by [(3.6)](#fga3.iv-lemma-3.6), to the module $M_n$ and the integer $r=P(n)$, and by $Z'_N$ the infimum of the $Z_n$ for $\nu\leqslant n\leqslant N$.
Then the $Z_N$ form a decreasing sequence of closed subpreschemes of $Z$, which is thus necessarily stationary.
Let $Z$ be the constant value of the $Z_W$ for large $N$.
This is the desired $Z$ in [(3.4)](#fga3.iv-lemma-3.4).
This finishes the proof of [(3.4)](#fga3.iv-lemma-3.4), and thus also of [(3.3)](#fga3.iv-lemma-3.3)
:::

We have thus proven that \em{$\shQuot_{\FXS}^P$ is representable by an $S$-prescheme $Q$ that is an increasing union of open quasi-projective subpreschemes $Q_\nu$ over $S$}.
To go further, we need to invoke [Theorem 2.1](#fga3.iv-theorem-2.1), whence we easily conclude that $Q$ is \em{quasi-compact} (since it is the image of a prescheme $S'$ of finite type over $S$ that parametrises the family of quotient sheaves of the $\sh{F}_K$ whose Hilbert polynomial is $P$).
Thus $Q$ is equal to one of the $Q_\nu$, and thus quasi-projective over $S$.
To prove that it is projective over $S$, it thus remains to prove that it is \em{proper} over $S$, and for this it suffices to invoke the valuative criterion of properness in the form given in [[GD1960](GD1960), II, 7.3.8].
It suffices to verify the following:

::: {.itenv #fga3.iv-lemma-3.7 title="Lemma 3.7" latex="{Lemma 3.7}"}
Let $S$ be the spectrum of a discrete valuation ring, $s$ its generic point, $X$ a prescheme over $S$, $\sh{F}$ a quasi-coherent module over $X$, and $\sh{G}_s$ a quasi-coherent quotient module of $\sh{F}_s=\sh{F}\otimes_{\OO_S}k(s)$ over $X_s$.
Then there exists a unique quasi-coherent quotient module $\sh{G}$ of $\sh{F}$ that is flat over $S$ and whose restriction to $X_s$ is $\sh{G}_s$.
:::

::: {.proof}
\oldpage{221-17}
Indeed, if $\sh{G}_s=\sh{F}_s/\sh{H}_s$, it suffices to consider the largest subsheaf $\sh{H}$ of $\sh{F}$ that induces $\sh{H}_s$ ([[GD1960](GD1960), I, 9.4.2]) and to take $\sh{G}=\sh{F}/\sh{H}$.
We easily verify that this sheaf works.
:::

[Theorem 3.2](#fga3.iv-theorem-3.2), and thus [Theorem 3.1](#fga3.iv-theorem-3.1), is now completely proven.

The proof also shows, at the same time, the following:

::: {.itenv #fga3.iv-proposition-3.8 title="Proposition 3.8" latex="{Proposition 3.8}"}
Under the conditions of [(3.2)](#fga3.iv-theorem-3.2), let $Q=\repQuot_{\FXS}^P$, $X_Q=X\times_s Q$, $\sh{F}_Q=\sh{F}\otimes_{\OO_S}\OO_Q$, and let $\sh{G}$ be the coherent quotient of $\sh{F}_Q$, which is flat over $Q$, that has $P$ as its relative Hilbert polynomial, so that $(Q,\sh{G})$ represents the functor $\shQuot_{\FXS}^P$.
Then there exists an integer $\nu$ such that, for $n\geqslant\nu$, $(f_Q)_*(\sh{G}(n))$ is a locally free module over $Q$ of rank $P(n)$, and is very ample with respect to $S$, i.e. it defines an immersion of $Q$ into a Grassmannian scheme $\repGrass_{P(n)}(M)$ over $S$.
A fortiori, for $n\geqslant\nu$, the sheaf $\bigwedge^{P(n)}(f_Q)_*(\sh{G}(n))$ over $Q$ is invertible and very ample with respect to $S$.
:::

::: {.proof}
Indeed, we can reduce, as in [(3.2)](#fga3.iv-theorem-3.2), to the case where $\sh{F}$ is flat over $S$, and then it suffices to take an integer $\nu$ such that $A_\nu=A$ (with the notation above).
:::

The most important application of [(3.2)](#fga3.iv-theorem-3.2) is in the case where $\sh{F}=\OO_X$.
We then write
$$
  \begin{aligned}
    \repQuot_{\OO_X/X/S}
    &= \repHilb_{X/S}
  \\\repQuot_{\OO_X/X/S}^P
    &= \repHilb_{X/S}^P
  \end{aligned}
$$
and so we have a decomposition
$$
  \repHilb_{X/S} = \coprod_P \repHilb_{X/S}^P.
$$
By definition, $\repHilb_{X/S}$ represents the functor $\shHilb_{X/S}(S')$ which is given by the set of closed subpreschemes of $X'=X\times_S S'$ that are flat over $S$;
and $\repHilb_{X/S}^P$ represents the subfunctor corresponding to the closed subpreschemes that admit a given Hilbert polynomial $P$.
These preschemes are also called the \em{Hilbert prescheme} of $X$ over $S$ and the \em{Hilbert prescheme of index $P$}, respectively.
The terminology is justified by the role played in the theory by the Hilbert polynomials.
Their difference in nature with the classical Chow varieties (meant to parametrise cycles, not varieties) is analogous to that between \em{the Chow ring} of classes of cycles of a variety and \em{the ring of classes of sheaves} of the variety (as is introduced in the Riemann–Roch theorem [[BS1958]](BS1958));
\oldpage{221-18}
we note that, when $X=\PP_S^r$, with $S$ the spectrum of a field, the knowledge of the Hilbert polynomial of a coherent module $\sh{F}$ over $X$ is equivalent to that of the Chern classes of $\sh{F}$, or even of the class of $\sh{F}$ in the ring of classes of coherent sheaves on $X$.

::: {.rmenv #fga3.iv-remarks-3.9 title="Remarks 3.9" latex="{Remarks 3.9}"}
We also note that the construction of $\repQuot_{\FXS}$ and $\repQuot_{\FXS}^P$ was reduced to the case where $X=\PP_S^r$ and $\sh{F}=\OO_X^N$, with $\OO_X(1)$ being the usual very ample sheaf;
more precisely, the general $\repQuot_{\FXS}$ arise as closed subpreschemes of the above.
Since forming the $\repQuot_{\FXS}^P$ is evidently compatible with base change $S'\to S$, we see that we can reduce to the case where further $S=\Spec(\mathbb{Z})$:
$$
  \sh{Q}_{r,N}^P = \repQuot_{(\OO_{\PP_{\mathbb{Z}}^r})^N/\PP_{\mathbb{Z}}^r/\Spec(\mathbb{Z})}
$$
and, more particularly, the absolute Hilbert schemes:
$$
  \repHilb_r^P = \sh{Q}_{r,1}^P.
$$
A more detailed study of these schemes, starting with determining their connected components (are they connected?), and their irreducible components (by Serre [[Ser1961]](Ser1961), there can exist irreducible components that exist entirely over a prime number $p\neq0$), would be very interesting.
Recall the question of Weil, asking if the irreducible components of the fibres of $\repHilb_r^P$ over the $s\in\Spec(\mathbb{Z})$ correspond to "regular" extensions of the prime field, i.e. if they are "relatively connected".
It could be the case that these questions are more accessible for Hilbert schemes than for "Chow varieties".

*[Comp.]*
The study of connected components of Hilbert schemes over an algebraically closed field was done by Hartshorne, who proves that the $\repHilb_r^P$ are connected, and determines the pairs $(r,P)$ for which $\repHilb_r^P\neq\varnothing$ [[Har1966]](Har1966).
:::


## Variants {#fga3.iv-4}

\todo{the following list should be a, b, etc.}

a. Under the conditions of [(3.1)](#fga3.iv-theorem-3.1), let $U$ be open in $X$, and denote by $A'$ the subfunctor of $A=\shQuot_{\FXS}$ such that $A'(S')$ is the set of quotient modules $\sh{G}$ of $\sh{F}'$ that are flat over $S'$ and whose support is contained inside $U'$.
  We immediately see that $A'$ is representable by an open subset of the prescheme $\repQuot_{\FXS}$ that represents $A$.
  \oldpage{221-19}
  It follows that Theorems [(3.1)](#fga3.iv-theorem-3.1) and [(3.2)](#fga3.iv-theorem-3.2) remain true if we suppose that $X$ is \em{quasi-projective} over $S$ instead of projective over $S$, as long as we also replace in the conclusions the word "projective" by "quasi-projective", and use $\shQuot_{\FXS}(S')$ to mean the set of coherent quotients $\sh{G}$ of $\sh{F}'$ that are flat over $S'$ and \em{whose support is proper over $S'$}.

b. Generally we can impose all sorts of supplementary natural conditions on the quotients $\sh{G}$ of $\sh{F}'=\sh{F}\otimes_{\OO_S}\OO_{S'}$ that are flat over $S'$ and stable under base change, thus obtaining as many subfunctors of $\shQuot_{\FXS}$ as we want to represent.
  The usual criterion allow us, in many cases, to prove that we again obtain functors that are representable by open subsets of $\repQuot_{\FXS}$.
  This is, in particular, the case if we impose one of the following additional properties:

  1. The dimensions of the prime cycles associated to the modules $\sh{G}_{s'}$ (for $s'\in S'$) that are induced on the fibres $X'_{s'}$ belong to a given set of integers.
  2. (In the case where $\sh{F}=\OO_X$, and thus $\sh{G}$ corresponds to a closed subprescheme $Y$ of $X'$); $Y$ is a \em{simple} prescheme [[Gro1960b](Gro1960b), IV] over $S$, resp. \em{normal} over $S$ (i.e. the fibres $Y_{s'}$ are normal "over $k(s)$", i.e. are normal under any extension of base field), resp. (if $X$ is flat over $S$) are local complete $k$-intersections in $X$ with respect to $S$ (i.e. the fibres $Y_{s'}$ are local complete intersections in the $X_{s'}$)

  Other conditions would involve properties of a cohomological nature on the modules $\sh{G}_{s'}$ induced on the $X'_{s'}$, etc.
  Of course, the conjunction of conditions where each is represented by an open $U_i$ of $\repQuot_{\FXS}$ is represented by the open intersection.
  For example, considering, for all $S'$ over $S$, the set of closed subpreschemes $Y$ of $X'=X\times_S S'$ that are étale covers [[Gro1960b](Gro1960b), I] of a given rank $r$ over $S'$, we obtain a representable contravariant functor in $S'$.

c. The preschemes $\repHom_S(X,Y)$, $\prod_{X/S}Z/S$, and $\repIsom_S(X,Y)$, defined in [FGA 3.II, C.2](#fga3.ii-C.2) exist thanks to suitable projective hypotheses, and can be realised as opens in suitable Hilbert preschemes.
  Since we have $\repHom_S(X,Y)=\prod_{X/S}((X\times Y)/X)$, the case of $\Hom_S(X,Y)$ reduces to that of $\prod_{X/S}(Z/X)$.
  We then note that, for all $S'$ over $S$, the set of sections of $Z'=Z\times_S S'$ over $X'=X\times_S S'$ is in bijective correspondence with the set of subpreschemes $\Gamma$ of $Z$ (necessarily closed if $Z$ is separated over $X$) such that the morphism $\Gamma\to X'$ induced by $Z'\to X'$ is an isomorphism.
  \oldpage{221-20}
  In this way, \em{if $X$ is flat and proper over $S$, and $Z$ quasi-projective over $S$, then $\prod_{X/S}(Z/X)$ exists and is realised as an open subprescheme of $\repHilb_{Z/S}$}.
  Thus \em{if $X$ is projective and flat over $S$, and $Y$ quasi-projective over $S$, then $\repHom_S(X,Y)$ exists and is realised as an open subprescheme of $\repHilb_{(X\times_S Y)/S}$}.
  If $X$ and $Y$ are both projective over $S$, then it immediately follows that $\repIsom_S(X,Y)$ also exists, and is represented by an open subset of $\repHom_S(X,Y)$.
  Similarly, if $X$ is flat and projective over $S$, and $Y$ quasi-projective over $S$, then the $S$-prescheme $\repImm_S(X/Y)$ that corresponds to the subfunctor of the functor represented by $\repHom_S(X,Y)$ that corresponds to $S'$-homomorphisms $X'\to Y'$ that are immersions is also representable by an open subset of $\repHom_S(X,Y)$.

  Let $\sh{L}$ (resp. $\sh{M}$) be an invertible sheaf on $X$ (resp. $Y$) that is very ample with respect to $S$, whence we obtain a sheaf $\sh{L}\otimes_{\OO_S}\sh{M}$ on $X\times_S Y$ that is very ample with respect to $S$.
  Then, for any polynomial $P$ with rational coefficients, $\repHilb_{(X\times_S Y)/S}^P$ is defined and is a quasi-projective prescheme over $S$.
  It thus induces, on $\repHom_S(X,Y)$, a subset that is both open and closed, and quasi-projective over $S$, which we denote by $\Hom_S(X,Y)^P$.
  Thus the sections of $\repHom_S(X,Y)^P$ over $S$ are the $S$-morphisms $g\colon X\to Y$ such that, for any integer $n$, we have
  $$
    \chi\Big((\sh{L}\otimes_{\OO_X}g^*(\sh{M}))^{\otimes n}\Big)
    = P(n).
  $$
  In this way we obtain generalisations of Matsusaka's theorem, affirming that the automorphisms of a "polarised" projective variety form an algebraic group, a claim that here has an evidently more precise meaning, since we have a definition of this group as the solution to a universal problem.
  We note also that, over an algebraically closed field, the group of automorphisms considered in the past is that which is induced by the "true" one defined here, by dividing by the nilpotent elements;
  this explains why there is little chance that the historical constructions could be done over a non-perfect base field, since the ideal of nilpotent elements that appears after an extension of the base field is not necessarily "defined over $k$".
  This same remark applies equally to the majority of historical constructions.


## Differential study of Hilbert schemes {#fga3.iv-5}

\oldpage{221-21}
We have the following result:

::: {.itenv #fga3.iv-proposition-5.1 title="Proposition 5.1" latex="{Proposition 5.1}"}
Let $S$ be a prescheme, $S_0$ a subprescheme defined by a square-zero quasi-coherent ideal $\sh{I}$, $X$ an $S$-prescheme, and $\sh{F}$ a quasi-coherent module on $X$.
Let $X_0=\sh{F}\times_S S_0$ and $\sh{F}_0=\sh{F}\otimes_{\OO_S}\OO_{S_0}$.
Finally, let $\sh{G}_0=\sh{F}_0/\sh{H}_0$ be a quasi-coherent quotient module of $\sh{F}_0$ that is flat over $S_0$.
For every open $U$ of $X$, let $\sh{E}(U)$ be the set of quasi-coherent quotient modules $\sh{G}$ of $\sh{F}|U$ that are flat over $S$ and are such that $\sh{G}\otimes_{\OO_S}\OO_{S_0}=\sh{G}_0$;
as $U$ varies, the $\sh{E}(U)$ are the sections of a sheaf $\sh{E}$ on $U$.
With this, the sheaf of groups
$$
  \sh{A} = \repHom_{\OO_{X_0}}(\sh{H}_0,\sh{G}_0\otimes_{\OO_{S_0}}\sh{I})
$$
acts naturally on $\sh{E}$, which thus becomes a "formally $\mathscr{A}$-principal homogeneous" sheaf (i.e. for every open $U$ in $X$, $\sh{E}(U)$ is either empty or an $\sh{A}(U)$-principal homogeneous set).
:::

We thus conclude:

::: {.itenv #fga3.iv-corollary-5.2 title="Corollary 5.2" latex="{Corollary 5.2}"}
Suppose that there exists locally on $X$ an extension $\sh{G}$ of $\sh{G}_0$ to a quotient of $\sh{F}$ that is flat over $S$ (i.e. that the fibres of the sheaf $\sh{E}$ are non-empty).
Then there exists a canonical obstruction class
$$
  c(\sh{G}_0) \in \HH^1(X,\sh{A})
$$
whose vanishing is necessary and sufficient for the existence of a global extension $\sh{G}$ of $\sh{G}_0$ to a quotient of $\sh{F}$ that is flat over $S$.
If this class is zero, then the set $\sh{E}(X)$ of all possible extensions is a principal homogenous set for $\sh{A}(X)=\Hom_{\OO_X}(\sh{H}_0,\sh{G}_0\otimes_{\OO_{S_0}}\sh{I})$.
:::

The existence of a global extension is thus guaranteed, in particular, if $\HH^1(X,\sh{A})=0$.

::: {.itenv #fga3.iv-corollary-5.3 title="Corollary 5.3" latex="{Corollary 5.3}"}
Suppose that $Q=\repQuot_\FXS$ exists (cf. [§4.a](#fga3.iv-4)) --- for example, suppose that $X$ is quasi-projective over some locally Noetherian $S$, and $\sh{F}$ is coherent.
Let $x\in Q$, corresponding to a residue extension $K=k(x)$ of some $k(s)$ (where $s\in S$).
\oldpage{221-22}
Then $x$ is defined by a coherent quotient module $\sh{G}_0=\sh{F}_0/\sh{H}_0$ of the module $\sh{F}_0=F_K$ on the $K$-prescheme $X_K$.
Let $\sh{A}$ be the coherent sheaf on $X_K$ defined by
$$
  \sh{A} = \repHom_{\OO_{X_0}}(\sh{H}_0,\sh{G}_0).
$$

Then the Zariski tangent space of the fibre $Q_s$ at the point $x$ (given by the dual over $K$ of $\mathfrak{m}/\mathfrak{m}^2$, where $\mathfrak{m}$ is the maximal ideal of $\OO_{Q_k,x}$) is canonically isomorphic to $\HH^0(X_k,\sh{A})$.
:::

The result giving the Zariski tangent space can be generalised, and gives a characterisation, for a given $S$-morphism $g\colon S'\to Q$, i.e. a section $g'$ of $Q'=Q\times_S S'$ over $S'$, of the module
$$
  \Omega
  = g^*(\Omega_{Q/S}^1)
  = {g'}^*(\sh{J}/\sh{J}^2)
$$
(where $\sh{J}$ is the ideal on $Q'$ defined by the section $g'$ of $Q'$ over $S'$) by the formula
$$
  \Hom_{\OO_{S'}}(\Omega,\sh{M})
  \simeq \HH^0(X',\sh{A})
$$
which is functorial in the coherent module $\sh{M}$ over $S'$, and where $\sh{A}$ is again the module on $X'=X\times_S S'$ defined by
$$
  \sh{A} = \repHom_{\OO_{X'}}(\sh{H},\sh{G}\otimes_{\OO_S}\sh{M})
$$
($\sh{G}=\sh{F}'/\sh{H}$ being the quotient module of $\sh{F}'=\sh{F}\otimes_{\OO_S}\OO_{S'}$ that corresponds to $g$).
It suffices to apply [(5.1)](#fga3.iv-proposition-5.1) by replacing $S_0$ with $S'$, and $S$ with the prescheme $D(\sh{M})=(S',\OO_{S'}+\sh{M})$, where $\sh{M}$ is considered as a square-zero ideal.

If, in [(5.1)](#fga3.iv-proposition-5.1), we have $\sh{F}=\OO_X$, then the data of $\sh{G}_0$ corresponds to the data of a closed subprescheme $Y_0$ of $X_0$ that is flat over $S_0$, defined by the ideal $\sh{J}_0=\sh{M}_0$, and then [($*$)](#fga3.iv-equation-asterisk) gives
$$
  \sh{A} = \repHom_{\OO_{X_0}}(\sh{J}_0/\sh{J}_0^2,\OO_{Y_0}\otimes_{\OO_{S_0}}\sh{J})
$$
where $\sh{J}/\sh{J}^2$ is thought of as the \em{conormal sheaf} of $Y_0$ in $X_0$, which we also denote by $\sh{N}_{Y_0/X_0}$;
\oldpage{221-23}
it is then interesting to consider $\sh{A}$ as a module over $Y_0$, and to calculate $\HH^0$ and $\HH^1$ on $Y$.
If $Y_0$ is locally a complete intersection in $X_0$, with $X$ flat over $S$, then, in [(5.1)](#fga3.iv-proposition-5.1), the possibility of a local extension is guaranteed, and $\sh{J}/\sh{J}^2$ is locally free over $Y_0$ and we can write
$$
  \sh{A} = \check{\sh{N}}_{X_0/Y_0}\otimes_{\OO_{S_0}}\sh{J}
$$
where the first factor on the right-hand side is the normal cone of $Y_0$ inside $X_0$.
Using the fundamental criterion of simplicity [[Gro1960b](Gro1960b), III, 3.1], we find, for example:

::: {.itenv #fga3.iv-corollary-5.4 title="Corollary 5.4" latex="{Corollary 5.4}"}
Under the conditions of [(5.3)](#fga3.iv-corollary-5.3), suppose that $\sh{F}=\OO_X$, with $X$ flat over $S$, and that the closed subprescheme $Y_0$ of $X_0$ that corresponds to $\sh{G}_0$ is locally a complete intersection.
Then the Zariski tangent space of $Q_s$ at $x$ is canonically isomorphic to $\HH^0(Y_0,\check{\sh{N}}_{X_0/Y_0})$.
If $\HH^1(Y_0,\check{\sh{N}_{X_0/Y_0}})=0$, then the Hilbert prescheme $X$ is simple over $S$ at the point $x$ (where $\check{\sh{N}}_{X_0/Y_0}$ is the normal sheaf of $Y_0$ inside $X_0$).
:::

::: {.rmenv #fga3.iv-remark-5.5 title="Remark 5.5" latex="{Remark 5.5}"}
This statement applies in particular when $Y_0$ is a complete intersection in $X_0$ defined by \em{one} single equation, i.e. is a positive "Cartier divisor".
Then $\check{\sh{N}}_{X_0/Y_0}$ is isomorphic to the sheaf on $Y_0$ induced by the invertible sheaf $\sh{J}^{-1}$ on $X_0$ defined by the divisor $Y_0$.
This is the situation that we find in particular in the study of families of positive divisors on a non-singular projective variety $X_0$.
The isomorphism between the Zariski tangent space at the point $x$ of $Q$ (or, if one prefers, of the open $D$ of $Q$ that corresponds to the divisors) and $\sh{H}^0(Y_0,\check{\sh{N}}_{X_0/Y_0})$ was known in classical algebraic geometry under the name of "*characteristic homomorphism*" (from the former to the latter).
It was not defined when $x$ was a simple point of the variety of parameters $T$ of a "complete continuous family" of divisors, i.e. from our point of view, of an irreducible component of the scheme $D$, endowed with the induced \em{reduced} structure.
The tangent space of $T$ at $x$ is then a \em{subspace} of the tangent space of $D$ at $x$, and so the characteristic homomorphic of yore is indeed injective, but it is not surjective except for under supplementary conditions, for example if $D$ is integral at $x$.
\oldpage{221-24}
In fact, Zappa [[Zap1945]](Zap1945) constructed an example (with $X$ a non-singular projective surface over the \em{field of complex numbers}) where even at the generic point of $T$ the characteristic homomorphism is not surjective.
*This thus implies that $D$ is not integral even at the generic point of the irreducible component in question.*
This shows in a particularly striking manner how varieties with nilpotent elements are necessary for understanding the most classical phenomena of the theory of surfaces.

*[Comp.]*
Concerning the example of Zappa, we note that Mumford has even constructed an irreducible component of the Hilbert scheme for $\PP_\mathbb{C}^3$ (whose general points represent non-singular curves of degree $14$ and genus $24$), which is non-reduced at its generic points.
Blowing up the curves obtained, he also obtains a regular projective scheme of dimension $3$ over $\mathbb{C}$, whose formal scheme of modules is non-reduced at its generic point, or, equivalently, such that its local variety of modules, in the sense of analytic geometry, over $\mathbb{C}$ (see \em{Séminaire Cartan} \strong{13}, 1960/61) is non-reduced at all its points.
:::

::: {.rmenv #fga3.iv-remark-5.6 title="Remark 5.6" latex="{Remark 5.6}"}
We have given, in [Remark 5.4](#fga3.iv-remark-5.4), a criterion for simplicity, which applies in particular to schemes of divisors.
Kodaira gave a different criterion in [[Kod1956]](Kod1956), given by the vanishing of $\HH^1(X_0,\sh{L})$, where $\sh{L}=\sh{J}_0^{-1}$ is the invertible sheaf on $X_0$ defined by the divisor $Y_0$;
this criterion holds whenever $S$ is the spectrum of a field of characteristic $0$, and is proved in [[Kod1956]](Kod1956) by transcendental methods in the case where the base field is $\mathbb{C}$.
We note here that, in general, $S$ now arbitrary, Kodaira's condition is a sufficient condition for the canonical morphism $D\to\repPic_{X/S}$ from the prescheme of divisors to the Picard prescheme of $X/S$ to be simple at the point $x$ in question (as we easily verify by the usual criterion for simplicity, once we have the existence of $\repPic_{X/S}$).
Then if, further, $\repPic_{X/S}$ is simple over $S$ at the point given by the image of $x$ (for example if $\repPic_{X/S}$ is simple over $S$), then $D$ is simple over $S$ at $x$.
On the other hand, Cartier has shown that every group prescheme locally of finite type over \em{a field $k$ of characteristic $0$} is simple over $k$.
By combining these two results, we recover the result of Kodaira.
Note that it follows from these remarks that, over a field $K$ of characteristic $p>0$, if $\repPic_{X/S}$ is not simple over $k$ (which is the case whenever $X$ is the Igusa surface), then the condition $\HH^1(X_0,\sh{L})=0$ implies to the contrary that $D$ is not simple at $x$, and even not reduced at $x$ if $K$ is algebraically closed.
:::

To finish, we give the following result, which plays an important role in the differential study of fibred spaces:

::: {.itenv #fga3.iv-proposition-5.7 title="Proposition 5.7" latex="{Proposition 5.7}"}
Let $X$ be a finite prescheme that is flat over $S$ and locally Noetherian, and let $Z$ be a prescheme over $S$ such that $\prod_{X/S}(Z/X)$ exists (which is the case if $Z$ is quasi-projective over $X$).
If $Z$ is simple over $X$, then $\prod_{X/S}(Z/X)$ is simple over $S$.
:::

::: {.proof}
This is an immediate consequence of the definition, and of the usual criterion of simplicity [[Gro1960b](Gro1960b), III, §3.1].
:::

Note that if $X$ is finite and flat over $S$, then the question of the existence of $\prod_{X/S}(Z/X)$ can be dealt with in a very elementary manner, without using the theory of Hilbert schemes.
\oldpage{221-25}
We find, for example, that if $X$ is radicial over $S$, then $\prod_{X/S}(Z/X)$ exists without any restrictions on $Z$.
For example, let $T$ be an $S$-prescheme, and let $T_n$ be "the infinitesimal neighbourhood of order $n$" of the diagonal of $T\times_S T$ in $T\times_S T$, endowed with the morphisms $p_1,p_2\colon T_n\to T$ induced by the two projections.
We can consider $T_n$ as a finite prescheme over $T$ thanks to $p_1$, and we suppose further that $T_n$ is flat over $T$ (which is the case if $T$ is simple over $S$).
For every prescheme $X$ over $T$, set
$$
  (X/T/S)^{(n)} = \prod_{T_n/S}(p_2^*(X/T)/T_n)
$$
which is a prescheme over $T$ called the \em{bundle of germs of sections of order $n$ of $X$ over $T$} (with respect to $S$).
This depends functorially on $X$, and is simple over $T$ if $X$ is.


## Relation to the notion of norm and symmetric products {#fga3.iv-6}

Let $S$ be a prescheme, let $X$ and $Y$ be $S$-preschemes, and let
$$
  u\colon(X/S)^n\to Y
$$
be a \em{symmetric} $S$-morphism from the $n$-th cartesian power of $X/S$ to $Y$.
Suppose, for simplicity, that $S$ is locally Noetherian, and that $X$ and $Y$ are of finite type over $S$.
We can then associate, to every coherent module $\sh{F}$ on $X$ with finite support on $S$ that is furthermore flat over $S$ and of rank equal to $n$ with respect to $S$ (i.e. such that $f_*(\sh{F})$ is a locally free module of rank $n$ on $S$), in a natural way a section of $Y$ over $S$:
$$
  \sh{N}_{X/S}^u(\sh{F}) \in \Gamma(Y/S).
$$
We will not give here the details of the definition, but instead content ourselves with noting that the formalism to which one arrives is a natural generalisation of the usual formalism of norms and traces.
When the symmetric $n$-th power of $X$ over $S$ exists (for example, if the orbits of the symmetric group $\sigma_n$ acting on $(X/S)^n$ are contained inside affine opens), we can take $Y$ to be this symmetric power $\Symm_S^n(X)$, and we obtain a canonical element
$$
  \sh{N}_{X/S}(\sh{F}) \in \Gamma(\Symm_S^n(X)/S)
$$
\oldpage{221-26}
which allows us to recover the $\sh{N}_{X/S}^u(\sh{F})$.
Another important case is that where $X$ is a commutative monoid over $S$, and $X=Y$, and the morphism $u$ comes from the composition law of $X$.
We then simply write $\sh{N}(\sh{F})$ for the section of $X$ over $S$ associated to the module $\sh{F}$ on $X$.

Now suppose that we have a coherent module $\sh{F}$ on $X$ such that $\repQuot_{\FXS}$ exists, or at least such that the functor $\shQuot_{\FXS}^n$, which associates to each $S'$ over $S$ the set of coherent quotient sheaves $\sh{M}$ of $\sh{F}'=\sh{F}\otimes_{\OO_S}\OO_{S'}$ that are flat over $S$ and of relative rank $n$, is representable by an $S$-prescheme $\repQuot_{\FXS}^n$.
(If $X$ is quasi-projective over $S$, then $\repQuot_{\FXS}^n$ indeed exists, and is exactly, with the notation of [§3](#fga3.iv-3), $\repQuot_{\FXS}^P$, where $P$ is the polynomial consisting of the constant term $n$).
Since the formation of the $\sh{N}_{X/S}^u(\sh{M})$ is compatible with base change, we thus obtain a canonical morphism
$$
  \sh{N}_{X/S}^u\colon \repQuot_{\FXS}^n \to Y
$$
and, in particular, if the $n$-th symmetric power of $X$ over $S$ exists,
$$
  \sh{N}_{X/S}\colon \repQuot_{\FXS}^n \to \Symm_S^n(X).
$$
The most important case is that where $\sh{F}=\OO_X$, which gives a morphism
$$
  \sh{N}_{X/S}\colon \repHilb_{X/S}^n \to \Symm_S^n(X).
$$
This is evidently an isomorphism for $n=0$ and $n=1$.
But for $n\geqslant1$, even if $S$ is the spectrum of a field $k$, and $X$ is simple over $S$, it is not in general an isomorphism nor even an injective morphism, since a sub-scheme of dimension $0$ of $X$ (corresponding, for example, to a primary ideal $\sh{I}$ for the maximal ideal in a local ring $\OO_{X,x}$, for a closed point $x$ of $X$) is not known when we know only the cycle that it defines (to be precise, when we know the codimension over $k$ of $\sh{I}$ in $\OO_{X,x}$).
We can only say the following (where $S$ is once more arbitrary):

a. If $X$ is simple over $S$, then the norm morphism defines an isomorphism from the open of $\repHilb_{X/S}^n$ that corresponds to the classification of étale covers of rank $n$ contained inside $X$ (cf. [§4.b](#fga3.iv-4)) to the open of $\Symm_S^n(X)$ that corresponds to the $n$-cycles without multiple components.
b. If furthermore $X$ is of relative dimension $1$ over $S$, then the norm morphism even defines an isomorphism from $\repHilb_{X/S}^n$ to $\Symm_{X/S}^n$.

\oldpage{221-27}
This second fact is due to the fact that a subscheme of dimension $0$ of a non-singular algebraic curve is known whenever we know the corresponding cycle.
The same remark also applies more generally to Cartier divisors that are positive over a non-singular algebraic scheme (and it is not excluded that, in this very particular case, the Chow variety gives the same thing as the Hilbert variety).
