## Example: finite preschemes over $S$ {#fga3.iii-2}

Let $\mathcal{C}$ be the category of finite preschemes over $S$, which is assumed to be locally Noetherian.
Then $\mathcal{C}$ is equivalent to the opposite category of the category of coherent sheaves of commutative algebras on $S$, or, if $S$ is affine of ring $A$, then it is equivalent to the opposite category of the category of finite $A$-algebras over $A$ (i.e. those that are modules of finite type over $A$).
We thus immediately conclude that, in $\mathcal{C}$, finite projective limits and finite inductive limits exist.
This is well known (without any finiteness hypotheses) for the former;
the fibre product of preschemes $X$ and $Y$ over $S$ corresponds to the tensor product $B\otimes_A C$ of corresponding algebras, and the kernel of two morphisms $X\rightrightarrows Y$, defined by two $A$-algebra homomorphisms $u,v\colon C\rightrightarrows B$, corresponds to the quotient of $B$ by the ideal generated by the $u(v)-v(c)$, etc.
For finite inductive limits, it suffices to consider, on one hand, finite sums, which correspond to the ordinary product of $A$-algebras, and, on the other hand, cokernels of pairs of morphisms $X\rightrightarrows Y$, which correspond (as we can immediately see) to the sub-ring of $C$ given by elements where the homomorphisms $u,v\colon C\rightrightarrows B$ agree (with this sub-ring being finite over $A$ thanks to the Noetherian hypothesis).
We also note that we can show, using the Noetherian hypothesis, that finite inductive limits, and, in particular, quotients, thus constructed in the category $\mathcal{C}$ of finite preschemes over $S$ are, in fact, quotients in the category of \em{all} preschemes.

\oldpage{212-05}
As we mentioned in \ref{fga3.i}, \em{there are non-effective epimorphisms in $\mathcal{C}$} (or even non-strict, which is the same, since fibre products exist).
\em{I do not know if equivalence relations are still effective} if we have no flatness hypothesis.
I have only obtained, in this direction, very partial, positive, results, that are vital for the proof of the fundamental theorem of the formal theory of modules (cf. [FGA 3.II, §B, Theorem 1](fga3.ii-b-theorem-1)).
We note that it is easy, in the given problem, to reduce to the case where $S$ is the spectrum of a local Artinian ring, with an algebraically closed residue field.
But even if $A$ is a field, the answer is not known.

We can also consider the case of a prescheme $X$ over $S$ that is no longer assumed to be finite over $S$, but by considering an equivalence relation $R$ on $X$ such that $p_1\colon R\to X$ is a finite morphism.
We then say that $R$ is a \em{finite equivalence relation}.
Supposing, for simplicity, that $S$ and $X$ are affine (which implies that $R$ is affine, so that the situation is reduced to one of pure commutative algebra), \em{we do not know, even in this case, if there exists a quotient $X/R=Y$, and if the canonical morphism $X\to Y$ is finite}.
(The most simple case is that where we suppose that $S$ is the spectrum of a field $k$, and where $X$ is the spectrum of $k[t]$, i.e. the affine line).
Of course, if the two problems above turn out to be true, then we can conclude that, in the situation described, $R$ is effective.
Note that the problem of \em{existence} of a quotient $Y$ and of the \em{finiteness} of $f\colon X\to Y$ are stated in exactly the same terms if, instead of an equivalence graph in $X$, we only have an equivalence pregraph in $X$, in the sense of \ref{fga3.iii-4}.

The question of passing to the quotient by a more or less arbitrary finite equivalence relation arises in the construction of preschemes by "gluing" given preschemes $X_i$ along certain closed sub-preschemes;
the gluing law is expressed precisely by a finite equivalence relation on the prescheme $X$ given by the sum of the $X_i$.
We also expect that the solutions of the problems stated here, as well as of their many variations, will be a preliminary condition for the clarification of a general technique for non-projective constructions, in the direction introduced in \ref{fga3.ii}.

The only general positive fact known to the author is the following:

::: {.itenv #fga3.iii-2-proposition-2.1 title="Proposition 2.1" latex="{Proposition 2.1}"}
  Let $S$ be a locally Noetherian prescheme, $s$ a point of $S$, and $\Omega$ an algebraically closed extension of $k(s)$.
  \oldpage{212-06}
  Consider the corresponding "fibre functor" $F$, that associates, to any $S$-scheme $X$ that is finite over $S$, the set of points of $X/S$ with values in $\Omega$.
  This functor (which is trivially left exact) is _right exact_, i.e. it commutes with finite inductive limits, and, in particular, with the cokernel of pairs of morphisms.
:::

By using this result for all the "geometric points" of $S$, we thus deduce that the "quotient" category $\mathcal{C}'$ of $\mathcal{C}$, given by arguing "modulo surjective radicial morphisms" (i.e. by formally adjoining inverses for such morphisms), is a "geometric" category, i.e. it satisfies the same "finite nature" properties as the category of sets.
In particular, every equivalence relation is effective.
This implies that, if $R$ is an equivalence relation on $X$, where $X$ is finite over $S$, then the canonical morphism $R\to X\times_Y X$ (where $Y=X/R$) is \em{radicial and surjective} (and, in fact, a surjective closed immersion, since it is a monomorphism).


## The case of a group with operators {#fga3.iii-3}

We now suppose that $\mathcal{C}$ is an arbitrary category.
Let $G$ and $X$ be objects of $\mathcal{C}$, and suppose that $G$ is a $\mathcal{C}$-group with operators on the object $X$.
This implies (cf. [FGA 3.II, §A.1](fga3.ii-a.1)) that, for every object $T$ of $\mathcal{C}$, we have a group structure on $G(T)$, and the structure of an operator domain on $X(T)$ acting on $G(T)$, such that, for variable $T$, the structures in question "vary functorially" in $T$.
If the products $G\times G$ and $G\times X$ exist in $\mathcal{C}$, then such a structure can also be defined as a pair of morphisms
##{
  \begin{gathered}
    G\times G\to G
  \\\pi\colon G\times X\to X
  \end{gathered}
}
subject to the condition that, for every object $T$ of $\mathcal{C}$, the corresponding composition laws for the sets $G(T)$ and $X(T)$ make $G(T)$ into a group acting on $X(T)$.
Translating this axiom into the commutativity of certain diagrams in $\mathcal{C}$ is easy, but tedious, and, in fact, perfectly useless in all cases known to me.

Suppose that $G\times X$ exists, and consider the two morphisms
##{
  p_1,p_2\colon G\times X\rightrightarrows X
}
\oldpage{212-07}
with
##{
  \begin{aligned}
    p_1 &= \pr_1
  \\p_2 &= \pi.
  \end{aligned}
}
We immediately note that the pair $(p_1,p_2)$ is an equivalence pair if, and only if, for every object $T$ of $\mathcal{C}$, the map
##{
  G(T)\times X(T)
  \sim (G\times X)(T) \to X(T)\times X(T)
}
defined by this pair is injective, i.e. if the group $G(T)$ acts \em{freely} on the set $X(T)$, i.e. if $g\in G(T)$, $x\in X(T)$, and $g\cdot x=x$, then $g$ is the identity element of the group $G(T)$.
We then say that $G$ \em{acts freely} on $X$ (or that $X$ is a \em{principal $\mathcal{C}$-space under $G$}).
The equivalence relation associated to the pair $(p_1,p_2)$ is then called the \em{equivalence relation defined by the group $G$} acting freely on $X$.
If $X\times X$ also exists, and we consider the morphism
##{
  p\colon G\times X\to X\times X
}
defined by the pair $(p_1,p_2)$, then the condition that $G$ acts freely implies that $p$ is a \em{monomorphism}.

Of course, even if $G$ dose not act freely on $X$, we still wish to have existence criteria for a quotient of $X$ by $G$, i.e. for the cokernel of the above pair $(p_1,p_2)$.

The cokernel in question will often be denoted by $X/G$, or by $X\backslash G$ if $G$ acts on the left (with the previous notation being reserved for when $G$ acts on the right).
We note that, even if the "image" of $G\times X$ under $p$ exists (this image being defined, for example, as the smallest sub-object of $X\times X$ through which we can factor $p$), say, $R$, then this is usually not an equivalence relation on $X$.
If we then try to pass directly to the quotient under $R$ (or, more precisely, under the pair of morphisms from $R$ to $X$ induced by the two projections $\pr_i$), then we lose the particular characteristics of the original pair $(p_1,p_2)$.
It is thus important to find a generalisation of the notion of equivalence relations, appealing directly to the pair defined by a $\mathcal{C}$-group with operators.


## Equivalence pre-relations {#fga3.iii-4}

Recall that a \em{groupoid} is defined to be a category where all the morphisms are isomorphisms.
\oldpage{212-08}
A category should be defined as consisting of two base sets, $X$ and $R$, with the former being the set of \em{objects} and the latter the set of \em{arrows}, endowed with the following structures:
\todo{the following list should be i, ii, etc.}

i. a pair of maps
##{
  p_1,p_2\colon R\rightrightarrows X
}
called the \em{source map} and the \em{target map} ;
ii. a map
##{
  \pi\colon(R,p_2)\times_X(R,p_1) \to R
}
called the \em{composition map}.

These data should satisfy well-known axioms, which we will not repeat here, and which can be expressed in terms of the commutativity of certain diagrams along with the existence of a (necessarily unique) map $D\colon X\to R$ that makes two other diagrams commute, where $D$ corresponds to passing from an object to the corresponding identity map, and satisfies
##{
  p_1\circ D = p_2\circ D = \id_X.
}
To say that a category is a groupoid then, implies the existence of a (necessarily unique) map
##{
  s\colon R\to R
}
called the \em{symmetry} of $R$, that sends every arrow to an inverse arrow, which can be expressed in terms of the commutativity of four other diagrams, built from $s$, $\Delta$, and the above data, and of which the first two can be written as
##{
  \begin{aligned}
    p_1\circ s &= p_2
  \\p_2\circ s &= p_1.
  \end{aligned}
}

Having recalled these notions, the general definitions in [FGA 3.II, §A.1](fga3.ii-a.1) show, in particular, what we should mean by "the structure of a \em{#{\mathcal{C}}-category}" (resp. \em{#{\mathcal{C}}-groupoid}) on a pair of objects $(X,R)$ of an arbitrary category $\mathcal{C}$:
it is, by definition, the data, for every object $T$ in $\mathcal{C}$, of the structure of a category (resp. groupoid) in the set-theoretic sense, whose set of objects is $X(T)$, and set of arrows is $R(T)$, with these structures "varying functorially" in $T$.
This thus implies the definition of two morphisms
##{
  p_1,p_2\colon R\rightrightarrows X
}
\oldpage{212-09}
called the \em{source morphism} and the \em{target morphism}, and, if the fibre product in question exists, a morphism
##{
  \pi\colon (R,p_2)\times_X(R,p_1) \to R
}
called the \em{composition morphism};
these three morphisms then suffice to determine the structure of a category (resp. groupoid) on $(X,R)$, with the condition to place on them being the following: for every $T$, the three corresponding morphisms for $X(T)$ and $R(T)$ define the structure of a category (resp. groupoid) on the pair of sets $(X(T),R(T))$.
If necessary, this can be expressed in terms of the commutativity of certain diagrams, implying a well-determined morphism
##{
  D\colon X\to R
}
and, in the case of groupoids, a well-determined morphism
##{
  s\colon R\to R
}
where the diagrams are as in the "set-theoretic" case.
This tedious interpretation of the axioms is thankfully useless in practice, with the only theoretical interest in the possibility of being able to express the data and the axioms using morphisms and equalities of morphisms between certain fibre products being the following: if we have a left-exact functor $F\colon\mathcal{C}\to\mathcal{C}'$ (i.e. a functor that commutes with finite products and fibre products), then it sends $\mathcal{C}$-categories (resp. $\mathcal{C}$-groupoids) to a $\mathcal{C}'$-categories (resp. $\mathcal{C}'$-groupoids) (under the condition that finite products and fibre products exist in $\mathcal{C}$).

It is important, in practice, to know how to understand the morphisms $p_1$, $p_2$, $\pi$, $D$, and $s$ as \em{simplicial operations} in a suitable semi-simplicial or simplicial objects of $\mathcal{C}$ (or, at least when fibre products exist in $\mathcal{C}$).
To fix terminology, we introduce the category $\mathcal{S}$ of \em{simplex types} as the category whose objects are finite sets of the form
##{
  \Delta_n
  = [0,n]
}
for $n\in\mathbb{Z}$, where $[0,n]$ denotes the interval of integers from $0$ to $n$ (inclusive), and whose morphisms are \em{arbitrary maps} between these finite sets.
We note that the category $\mathcal{S}$ is equivalent to the category of \em{non-empty} finite sets, where we take the morphisms to be maps between finite sets.
In $\mathcal{S}$, the sum of a \em{non-empty} finite family of objects clearly exists, as does the amalgamated sum of two objects over a third (the dual operation to the fibre product).
We denote by $\mathcal{S}'$ the subcategory of $\mathcal{S}$ that has the same objects, but where the morphisms are \em{increasing maps} between the $\Delta_n$.
This category is equivalent to the category of non-empty finite totally ordered sets.
\oldpage{212-10}
In this category, the sum of two objects never exists, and the amalgamated sum of two objects $A$ and $B$ over a third $C$ does not exist in general (take, for example, $C=\Delta_0$, and $A=B=\Delta_1$, with the two structure maps $u\colon C\to A$ and $v\colon C\to B$ being the equal).
However, in certain cases, the amalgamated sum \em{does} exist;
consider
##{
  \begin{gathered}
    A = \Delta_m
    \qquad B = \Delta_n
    \qquad C = \Delta_0
  \\u(0) = m
    \qquad v(0) = 0
  \end{gathered}
}
which is such that
##{
  A\coprod_C B
  = \Delta_{m+n}.
}

A \em{simplicial object} (resp. \em{semi-simplicial object}) in a category $\mathcal{C}$ is defined to be a contravariant functor $K$ from $\mathcal{S}$ (resp. $\mathcal{S}'$) to $\mathcal{C}$.
A simplicial object thus defines a semi-simplicial object by restriction, but the former differs from the latter essentially by the presence of \em{symmetry operations} in the $K_n=K(\Delta_n)$, which correspond to the images under the functor $K$ of the elements of the symmetric group on $n+1$ elements (considered as the automorphism group of $\Delta_n$ in $\mathcal{S}$).

With the above, for all $n$, let $\Delta'_n$ (resp. $\Delta''_n$) be the finite category whose set of objects is $\Delta_n$, and whose set of arrows is defined by the "chaotic order" relation (resp. the natural total order relation) on $\Delta_n$ (i.e. the set of arrows is the graph of the order relation).
It is clear that $\Delta'_n$ (resp. $\Delta''_n$) depends functorially on the object $\Delta_n$ of $\mathcal{S}$ (resp. $\mathcal{S}'$).
So if $Z$ is a category, then $\Hom(\Delta'_n,Z)$ (resp. $\Hom(\Delta''_n,Z)$) is, for varying $\Delta_n$, a functor from the category $\mathcal{S}$ (resp. $\mathcal{S}'$) to the category of sets, i.e. a \em{simplicial set} (resp. \em{semi-simplicial set}), which is said to be \em{associated to the category $Z$}, and denoted by $Z'$ (resp. $Z''$).
We also have an obvious natural homomorphism from the semi-simplicial set associated to $Z'$ to $Z''$, and this is an isomorphism if and only if $Z$ is a groupoid.
Then:

::: {.itenv #fga3.iii-4-proposition-4.1 title="Proposition 4.1" latex="{Proposition 4.1}"}
  The functor $Z\mapsto Z''$ from the category of categories to the category of semi-simplicial sets is fully faithful, and defines an equivalence between the category of \em{categories} and the category of semi-simplicial sets, i.e. contravariant functors $K$ from $\mathcal{S}'$ to $\Set$ \em{that send amalgamated sums $A\coprod_C B$ (of the type described above) to fibre products of sets}.

  \oldpage{212-11}
  Similarly, the functor $Z\mapsto Z'$ from the category of groupoids to the category of simplicial sets is fully faithful, and defines an equivalence between the category of \em{groupoids} and the category of simplicial sets, i.e. contravariant functors $K$ from $\mathcal{S}$ to $\Set$ \em{that send amalgamated sums to fibre products}.
:::

We can thus consider categories as specific examples of semi-simplicial sets, and groupoids as specific examples of simplicial sets, with, of course, the condition that we argue "up to isomorphism", as is rigorous when we interpret certain structures in terms of others.
The usual procedure of reduction to the set-theoretic case then implies:

::: {.itenv #fga3.iii-4-corollary-4.2 title="Corollary 4.2" latex="{Corollary 4.2}"}
  The above claim remains true when we replace categories, groupoids, and simplicial sets with $\mathcal{C}$-categories, $\mathcal{C}$-groupoids, and $\mathcal{C}$-simplicial objects (respectively), \em{provided that} fibre products exist in $\mathcal{C}$.
:::

The semi-simplicial object $K$ in $\mathcal{C}$ associated to a category $(X,R,\ldots)$ in $\mathcal{C}$ can be made explicit by considering the component $K_n=K(\Delta_n)$ of $K$ as being the $(n+1)$-th fibre product of $(R,p_1)$ over $X$, or, even better, by the inductive formula
##{
  \begin{aligned}
    K_0 &= R
  \\K_n &= (K_{n-1},p_n^{(n-1)})\times_X(R,p_1)
  \end{aligned}
}
where the $p_i^{(n-1)}$ (for $0<i<n-1$) are the natural projections from $K_{n-1}$ to $X$ (which can also be defined inductively).
In this way, $p_1$, $p_2$, $\pi$, $D$, and $s$ can be understood as simplicial operations that correspond to morphisms in $\mathcal{S}$, namely: the $0$ face of $\Delta_1$, the $1$ face of $\Delta_1$, the $(0,2)$ face of $\Delta_2$, the degeneracy $\Delta_1\to\Delta_0$, and the symmetry of $\Delta_1$ (respectively).
Every other semi-simplicial (resp. simplicial) operation can be formally obtained from the four (resp. five) aforementioned operations by composition and fibre products.

We now define an \em{equivalence pre-relation} on an object $X$ of a category to be the data of a groupoid whose object of objects is $X$.
Such a data gives, amongst other things, an object $R$ along with two morphisms
##{
  p_1,p_2\colon R\rightrightarrows X.
}
But we note that only these data alone do not determine the structure in question, contrary to what happens for equivalence pairs.
In this talk, we are interested in this notion with the aim of obtaining criteria for the possibility of passing to the quotient, i.e. for being able to form the cokernel of the pair $(p_1,p_2)$.
The statement of this problem thus makes no reference to the additional data inherent to a groupoid.
\oldpage{212-12}
In the proof of the results that will follow, we will, however, make use of this additional data, and, in particular, of the simplicial operations (including the symmetry operations) up to dimension $3$ (the fourth fibre power of $R$ over $X$ will appear).

An equivalence relation on an object $X$ of $\mathcal{C}$ defines an equivalence pre-relation: it suffices to show this in the set-theoretic case, and we then associate, to an equivalence relation on a set $X$, the groupoid whose set of objects is $X$, and whose set of arrows is the graph set of the equivalence relation.

A $\mathcal{C}$-monoid $G$ acting on an object $X$ of $\mathcal{C}$ defines a $\mathcal{C}$-category whose basic objects are $R=G\times X$ and $X$ (under the condition that $G\times X$ exists), and that is a $\mathcal{C}$-groupoid if and only if $G$ is a group.
It again suffices to prove this in the set-theoretic case.
We then define the composition of arrows $(g,a)$ and $(g',g\cdot a)$ as being
##{
  (g',g\cdot a) \circ (g,a)
  = (g'g,a)
}
i.e. if $a,b\in X$ then $\Hom(a,b)$ is, by definition, the transporter of $a$ to $b$, and morphisms compose thanks to the composition of elements of $G$.

::: {.rmenv title="Remark" latex="{Remark}"}
  We can avoid the logical difficulties that arise in a statement such as \ref{fga3.iii-4-proposition-4.1} by implicitly assuming that all the objects in question can be found in a fixed "universe" (that is itself a set).
:::


## Quotient by a finite and flat equivalence relation {#fga3.iii-5}

::: {.itenv #fga3.iii-5-theorem-5.1 title="Theorem 5.1" latex="{Theorem 5.1}"}
  Let $X=\Spec(B)$ be an affine scheme, $\mathcal{R}$ an equivalence pre-relation on $X$, whose component $R_1$ is affine: say, $R_1=\Spec(C)$.
  We suppose that the first projection $p_1\colon R_1\to X$ is a finite and locally free morphism, i.e. that the corresponding homomorphism of rings $p'_1\colon B\to C$ makes $C$ a projective $B$-module of finite type.
  Let $A$ be the subring of $B$ given by the kernel of the pair of homomorphisms $p'_1,p'_2\colon B\rightrightarrows C$ (i.e. the set of elements $b$ such that $p'_1(b)=p'_2(b)$).
  Let $Y=\Spec(A)$, and $f\colon X\to Y$ the morphism defined by the embedding of $A$ into $B$.
  \oldpage{212-13}
  Under these conditions:
  \todo{the following list should be i, ii, etc.}

    i. $B$ is integral over $A$, i.e. $f$ is an integral morphism.
    ii. The morphism $f$ is surjective, and its fibres are the set-theoretic equivalence classes
      $p_2(p_1^{-1}(x))$ in $X$ modulo $\mathcal{R}$, and the topology of $Y$ is the quotient of that of $X$.
    iii. $Y$ is the quotient of $X$ by $\mathcal{R}$ in the category of preschemes.
    iv. If $\mathcal{R}$ comes from an equivalence _relation_, then the morphism $f\colon X\to Y$ is finite and locally free (i.e. $B$ is a projective $A$-module of finite type), and the equivalence relation is effective, i.e. $R_1\to X\times_Y X$ is an isomorphism.
:::

This theorem generalises the well-known theorem concerning the case of a finite group $G$ acting by automorphisms on the ring $B$, and with ring $A$ of invariants, and the proof is analogous to the known proof.
We can make (iii) more precise as follows:

::: {.itenv #fga3.iii-5-corollary-5.2 title="Corollary 5.2" latex="{Corollary 5.2}"}
  The canonical morphism $R_1\to X\times_Y X$ is \em{surjective}.
:::

Let $\mathcal{R}$ continue to be a "finite and locally free" equivalence pre-relation on $X$, but with $X$ now being an arbitrary prescheme.
Suppose that we can find a prescheme $Y$ and a morphism $f\colon X\to Y$ such that $fp_1=fp_2$, and further such that the sequence
##{
  \mathcal{O}_Y \to f_*(\mathcal{O}_X) \rightrightarrows g_*(\mathcal{O}_R)
}
of homomorphisms of sheaves of rings on $Y$ is exact (where $g=fp_i$).
It then follows from the theorem that we have conclusions (i) to (iv) analogous to those of the theorem, and, in particular, by (iii), $Y$ is the quotient of $X$ by $\mathcal{R}$, and thus determined up to unique isomorphism.
Under these conditions, we say that the equivalence pre-relation $\mathcal{R}$ on $X$ is \em{admissible}.
With this definition:

::: {.itenv #fga3.iii-5-theorem-5.3 title="Theorem 5.3" latex="{Theorem 5.3}"}
  Let $X$ be a prescheme, and $\mathcal{R}$ an equivalence pre-relation on $X$ such that $p_1\colon R_1\to X$ is a finite and locally free morphism.
  For $\mathcal{R}$ to be admissible, it is necessary and sufficient for every set-theoretic equivalence class $p_2(p_1^{-1}(x))$ in $X$ modulo $\mathcal{R}$ to be contained in an affine open subset (a condition that is always satisfied if every finite subset of $X$ is contained in an affine open subset, for example if $X$ is quasi-projective over an affine scheme).
:::

We can in fact easily show that every equivalence class modulo $\mathcal{R}$ in $X$ is then contained in an affine open subset that is \em{stable} under $\mathcal{R}$, and we construct the quotient $Y$ by gluing the pieces obtained by applying \ref{fga3.iii-5-theorem-5.1}.

::: {.itenv #fga3.iii-5-corollary-5.4 title="Corollary 5.4" latex="{Corollary 5.4}"}
  \oldpage{212-14}
  Suppose that this condition is satisfied, and, further, that $\mathcal{R}$ comes from an equivalence relation.
  Then the equivalence relation is question is effective, i.e. $R_1\to X\times_Y X$ is an isomorphism, and $f\colon X\to Y$ is a finite and locally free morphism.
:::

We then immediately conclude, by descent, the following:

::: {.itenv #fga3.iii-5-corollary-5.5 title="Corollary 5.5" latex="{Corollary 5.5}"}
  Under the conditions of \ref{fga3.iii-5-corollary-5.4}, for $X$ to be everywhere of rank $n$ over $Y$, it is necessary and sufficient that $(R_1,p_1)$ be everywhere of rank $n$ over $X$.
  If $X$ and $R_1$ are $Z$-preschemes, and $p_1$ and $p_2$ are $Z$-morphisms (and thus $Y$ a $Z$-prescheme), then $X$ is flat over $Z$ if and only if $Y$ is flat over $Z$.
:::

In summary:

::: {.itenv title="Scholium" latex="{Scholium}"}
  The data of a finite, locally free, and surjective morphism $f\colon X\to Y$ of preschemes is equivalent to the data of a prescheme $X$ endowed with an equivalence relation $R$ such that $p_1\colon R\to X$ is finite and locally free, and such that every class $p_2(p_1^{-1}(x))$ is contained in an affine open subset.
:::

::: {.rmenv #fga3.iii-5-remarks-5.6 title="Remarks 5.6" latex="{Remarks 5.6}"}
  1. We have not needed to make any Noetherian hypothesis.

  2. This idea of passing to the quotient contains, as a particular case, the "inseparable descent" of Cartier, which corresponds to the determination of finite and locally free morphisms $f\colon X\to Y$ such that $f_*(\mathcal{O}_X)$ admits a $p$-basis with respect to $\mathcal{O}_Y$ (where $X$ is a given prescheme whose sheaf $\mathcal{O}_X$ is annihilated by the prime number $p>0$).
  We note that this result can also be easily expressed without any regularity hypothesis on the local rings, and without supposing that $X$ is an algebraic scheme over a field.
  The theory of Jacobson–Bourbaki is obtained by taking $X$ to be the spectrum of a field of characteristic $p$.

  3. Gabriel had already obtained a particular case of \ref{fga3.iii-5-theorem-5.3} in the theory of passing to the quotient for finite commutative groups over a field $k$.
  (Compare with \ref{fga3.iii-7-corollary-7.4}).
:::


## Quotient by a proper and flat equivalence relation {#fga3.iii-6}

::: {.itenv #fga3.iii-6-theorem-6.1 title="Theorem 6.1" latex="{Theorem 6.1}"}
\oldpage{212-15}
Let $S$ be a \em{locally Noetherian} prescheme, $X$ a \em{quasi-projective} $S$-scheme, and $\mathcal{R}$ an equivalence pre-relation on $X$, such that:
\todo{the following list should be a, b}

a. #{p_1\colon R_1\to X} is proper and flat; and
b. #{R_1\to X\times_S X} is a finite morphism (or, equivalently, by (a), a morphism with finite fibres, which is a condition that is automatically satisfied if $\mathcal{R}$ comes from an equivalence relation).

Under these conditions:
\todo{the following list should be i, ii, etc.}

  i. #{Y=X/\mathcal{R}} exists, and (if $S$ is Noetherian) is quasi-projective over #{S}.
  \note{\comp The fact that $Y=X/\mathcal{R}$ is quasi-projective over $S$ has only been proven, for now, in the case where $\mathcal{R}$ comes from an equivalence relation.}

  ii. The canonical morphism $f\colon X\to Y$ is surjective, proper, and open, and its fibres are the equivalence classes $p_2(p_1^{-1}(x))$ in $X$ modulo $\mathcal{R}$, and so $Y$ can be identified with the topological quotient space of $X$ by the set-theoretic equivalence relation defined by $\mathcal{R}$.
  Finally, $R_1\to X\times_Y X$ is surjective.

  iii. If $\mathcal{R}$ comes from an equivalence relation, then the equivalence relation in question is effective, i.e. $R_1\to X\times_Y X$ is an isomorphism, and, further, $f\colon X\to Y$ is flat (and thus faithfully flat).
:::

For the proof, we can reduce to \ref{fga3.iii-5-theorem-5.1} by considering suitable quasi-sections of $X$ for $\mathcal{R}$, with the proof being analogous to the construction of algebraic quotient groups in the \em{Séminaire Chevalley}.

In summary:

::: {.itenv title="Scholium" latex="{Scholium}"}
  Let $X$ be quasi-projective over $S$, with $S$ locally Noetherian.
  Then the data of a proper, faithfully flat, and surjective morphism $f\colon X\to Y$ from $X$ to an $S$-prescheme $Y$ is equivalent to the data of an equivalence relation $R$ on $X$ such that $p_1\colon R\to X$ is proper and flat.
:::

The same method gives the following result:

::: {.itenv #fga3.iii-6-theorem-6.2 title="Theorem 6.2" latex="{Theorem 6.2}"}
Let $S$ be a Noetherian prescheme, $X$ a prescheme of finite type over $S$, and $\mathcal{R}$ an equivalence pre-relation on the $S$-prescheme $X$.
Suppose that
\todo{the following list should be a, b}

  a. $p_1\colon R_1\to X$ is flat and of finite type; and
  b. the morphism $R_1\to X\times_S X$ is quasi-finite (i.e. has finite fibres).

Then there exists a \em{dense} open subset $U$ of $X$ that is \em{saturated} for $\mathcal{R}$, such that:
\todo{the following list should be i, ii, etc.}

  i. If $\mathcal{R}_U$ is the equivalence pre-relation induced by $\mathcal{R}$ on $U$, then $U/\mathcal{R}_U$ exists, and is of finite type over $S$.

  ii. The canonical morphism $U\to U/\mathcal{R}_U$ is surjective and open, and its fibres are the set-theoretic equivalence classes for $\mathcal{R}_U$ (and thus $U/\mathcal{R}_U$ is a topological quotient space of $U$ by the set-theoretic equivalence relation defined by $\mathcal{R}_U$).
  Finally, the morphism $(\mathcal{R}_U)_1\to U\times_{U/\mathcal{R}_U}U$ is surjective.

  iii. If $\mathcal{R}$ comes from an equivalence relation, then we can suppose that $U\to U/\mathcal{R}_U$ is faithfully flat and that $\mathcal{R}_U$ is effective.
:::

\oldpage{212-16}
This is a result of an essentially "birational" nature.

::: {.rmenv #fga3.iii-6-remarks-6.3 title="Remarks 6.3" latex="{Remarks 6.3}"}
  1. I do not know if, in \ref{fga3.iii-6-theorem-6.1} and \ref{fga3.iii-6-theorem-6.2}, hypothesis (b) is useless.
  In practice, it obliges us, in the passage to the quotient by groups, to restrict to he case where the stabilisers are all finite groups.

  2. We can ask if there are results analogous to \ref{fga3.iii-6-theorem-6.1} and \ref{fga3.iii-6-theorem-6.2} without any flatness hypothesis.
  I have no counter example in this direction.
  However, even keeping the flatness hypothesis, and restricting to equivalence relations such that $p_1\colon R\to X$ is flat and quasi-finite (but not finite), and with $X$ affine, it can still be the case that $R$ is not effective: take the equivalence relations induced on the affine open subsets covering the Nagata variety (or a group with two elements acting in a "non-admissible" way).
:::


## Applications {#fga3.iii-7}

As we said in the introduction, the most important application of \ref{fga3.iii-6-theorem-6.1} is the construction of Picard schemes, as well as solutions to various other problems of "modules", to which we will later return.

We obtain a simple proof of the following result of Shimura:

::: {.itenv #fga3.iii-7-proposition-7.1 title="Proposition 7.1" latex="{Proposition 7.1}"}
  Let $A$ be an abelian scheme defined over a discrete valuation ring $V$ with field of fractions $K$.
  Then every abelian scheme $B'$ over $K$ that is isogenous to a quotient of $A\otimes_V K$ "simplifies well for $V$", i.e. is isomorphic to some $B\otimes_V A$, where $B$ is an abelian scheme over $V$ (essentially unique, we recall).
:::

::: {.proof}
    We can suppose that $B'$ is the quotient of $A_K$ by a subscheme in groups $C'$.
    (N.B. $C'$ will not, in general, be "reduced", i.e. its local rings will have nilpotent elements).
    Consider the closed subscheme $C$ of $A$ given by "the closure" of $C'$, i.e. the smallest closed subscheme of $A$ such that $C_K$ contains $C'$.
    Then $C_K=C'$, and, since $V$ is a discrete valuation ring, we easily deduce that $C$ is a subscheme in groups of $A$ over $V$.
    Since $A$ is proper over $\Spec(V)=S$, so too is $C$.
    Further, $A$ is projective over $S$.
    \oldpage{212-17}
    We can thus apply \ref{fga3.iii-6-theorem-6.1} in order to construct $A/C=B$, which is the desired $B$.
:::

Finally, essentially known arguments allow us to extract from \ref{fga3.iii-6-theorem-6.2} the following result:

::: {.itenv #fga3.iii-7-theorem-7.2 title="Theorem 7.2" latex="{Theorem 7.2}"}
  Let $S$ be the spectrum of an Artinian ring, $F$ and $G$ group schemes of finite type over $S$, and $u\colon F\to G$ a homomorphism of group schemes over $S$.
  Suppose that
  \todo{the following list should be i, ii, etc.}

    i. #{F} is flat over $S$; and
    ii. the kernel of $u$ is finite.

  Under these conditions, the quotient scheme $G/F$ exists, and the canonical morphism $G\to G/F$ is surjective and open, and its fibres are the set-theoretic equivalence classes defined by the right action of $F$ on $G$.
  Finally, if $u$ is a monomorphism, then the morphism $G\to G/F$ is flat, and the morphism $G\times F\to G\times_{(G/F)}G$ is an isomorphism, or, in other words, $G$ is a principal homogeneous space over $G/F$, with structure group $F$ (acting on the right), or rather $F\times_S(G/F)$ considered as a group scheme over $G/F$ (cf. [FGA 3.I, §B.6](fga3.i-b.6)).
:::

::: {.itenv #fga3.iii-7-corollary-7.3 title="Corollary 7.3" latex="{Corollary 7.3}"}
  Under these conditions, for $G$ to be flat over $S$, it is necessary and sufficient that $G/F$ be flat over $S$.
  If this condition is satisfied, then the passage to the quotient by $F$ commutes with every extension of the base $S$, and if $F$ is an invariant subgroup of $G$, then $G/F$ can be endowed with the structure of a \em{quotient group} of $G$ by $F$.
:::

The situation is particularly simple if $S$ is the spectrum of a field, since then every $S$-prescheme is automatically flat over $S$.
We find:

::: {.itenv #fga3.iii-7-corollary-7.4 title="Corollary 7.4" latex="{Corollary 7.4}"}
  Let $F$ and $G$ be group schemes of finite type over a field $k$, and let $u\colon F\to G$ be a homomorphism of $k$-groups.
  Then $u$ factors as $F\to F'\to G$, where $F\to F'$ is a homomorphism given by passing to the quotient by the closed subgroup $\Ker u$ of $F$, and where $F'\to G$ is a group homomorphism that is a closed immersion.
  The quotient $G/F=G/F'$ exists.
  The usual formalism (as in the Noether theorems) holds amongst algebraic groups over $k$.
:::

This result allows us to treat the passage to the quotient in a uniform way for algebraic (in the classical sense, i.e. irreducible over $k$ and simple over $k$) groups, and the passage to the quotient by "infinitesimal" subgroups considered by Cartier.
\oldpage{212-18}
It is advantageous to consider the "hyperalgebras" introduced by Cartier, following from the work of Dieudonné on formal groups, as groups in the category of formal schemes over $k$, and, if necessary (if they correspond to hyperalgebras of finite rank over $k$), as algebraic groups that are finite over $k$.


## A conjecture {#fga3.iii-8}

::: {.rmenv title="Remark" latex="{Remark}"}
  \comp
  It now appears that the conjectures in this section are false, even for non-singular varieties over a field of characteristic $0$, both for the existence and the quasi-projectivity of the quotient, and even when $G$ acts with a closed graph.
:::

The conjecture in question concerns the need of knowing how to pass to the quotient by the projective group acting on certain subschemes of "Hilbert schemes" (with these "Hilbert schemes" replacing, in the theory of schemes, Chow varieties).

Let $S$ be a prescheme, and $n$ an integer.
To every prescheme $S'$ over $S$, we associate the group $\GL(n,\Gamma(S',\mathcal{O}_{S'}))$ of invertible $(n\times n)$ matrices with values in the ring of sections of $\mathcal{O}_{S'}$.
We thus obtain a contravariant functor in $S'$, which can can easily show to be representable, and so the functor corresponds to a group scheme over $S$ (which is further affine over $S$) which we denote by $\GL(n)_s$.
Its construction is compatible with change of base, so that, in reality, everything comes from a group scheme over $\mathbb{Z}$, denoted by $\GL(n)$.
The group $\GL(1)$, called the \em{multiplicative group}, and often denoted by $\Gm$, corresponds to the functor $S\mapsto\Gamma(S,\mathcal{O}_S)^*$, with the latter being the group of "units" over $S$.
We have an evident homomorphism $\GL(1)\to\GL(n)$, and we can easily construct the quotient group, denoted by $\GP(n-1)$, and called the \emph{projective group of degree $(n-1)$ over $\mathbb{Z}$}.
It represents the functor that sends $S$ to the group of sections of the sheaf $\sGL(n)_S/\sGL(1)_S$, where $\sGL(n)_S$ denotes the sheaf of germs of sections of $\GL(n)_S$ over $S$.
(Note that sections of $\GP(n-1)_S$ over $S$ do not, in general, come from sections of $\GL(n)_S$ over $S$!)
Note that we can prove that $\GL(n-1)$ equally represents the functor $S\mapsto\Aut_S(\mathbb{P}_S^{n-1})$ (where $\mathbb{P}_S^{n-1}$ is the projective-type scheme of relative dimension $(n-1)$ over $S$), at least when $S$ is Noetherian.
It is in this way that it appears in the theory of modules.

Let $S$ be a Noetherian scheme, which we can, if we want, suppose to be affine, and let $X$ be a quasi-projective $S$-prescheme endowed with an invertible sheaf $\sh{L}$ that is very ample with respect to $S$.
\oldpage{212-19}
Suppose that the group $G=\GP(n)_S$ acts on $X$ and $\sh{L}$ simultaneously (in a way that is compatible with its action on $X$), and that it acts _freely_ on $S$.

::: {.itenv #fga3.iii-8-conjecture-8.1 title="Conjecture 8.1" latex="{Conjecture 8.1}"}
  Under the above conditions:

    1. The equivalence relation defined by $G$ is effective, the quotient $Y=X/G$ is of finite type over $S$, and the canonical morphism $f\colon X\to Y$ is flat and surjective (and thus $X$ becomes a homogeneous principal bundle on $Y$, with group $G\times_S Y=\GP(n)_Y$).

    2. Let $\sh{L}'$ be the invertible sheaf on $Y$ induced from $\sh{L}$ by "faithfully flat descent" under $f$ (cf. [FGA 3.I, §B, Theorem 1](fga3.i-b.1-theorem-1)).
    Then $\sh{L}'$ is "pre-ample" on $Y$ with respect to $S$, i.e. there exists an integer $m$ and a quasi-finite morphism from $Y$ to some suitable projective-type scheme $\mathbb{P}_S^N$ such that $(\sh{L}')^{\otimes m}$ is isomorphic to the inverse image of $\mathcal{O}_{\mathbb{P}_S^N}(1)$.
:::

We note that, even if $X$ is separated over $S$, then it can be the case that $Y$ is not separated over $S$ (a situation that arises in not-at-all-pathological "module problems").
If (1) is satisfied, then $Y$ is separated if and only if the equivalence relation defined by $G$ has a closed graph, i.e. if $G\times X\to X\times X$ has a closed image (and is thus a closed immersion).
If $Y$ is separated, then $\sh{L}'$ is pre-ample on $Y$ with respect to $S$ if and only if it is ample, i.e. if a suitable tensor power defines a projective immersion.
In the module problems mentioned in the introduction, we can show that the equivalence relation to which we arrive does indeed have a closed graph.

::: {.rmenv #fga3.iii-8-remarks-8.2 title="Remarks 8.2" latex="{Remarks 8.2}"}f
  We have assumed that $G=\GP(n)_S$ to give a concrete example, and because it is currently the most important case in practice.
  The reasonable hypothesis to make on $G$ seems rather to be that $G$ be one of the "forms" on $S$ of a Tohokû group (whose construction over the integers has also been made by Chevalley).
  The only positive fact that is known to me concerning the above conjecture is the following:
  \em{Let $X$ be an affine scheme over a field $k$ of characteristic $0$, on which the group $\GL(n)_k$ or $\GP(n-1)_k$ acts freely. Then the equivalence relation defined by $G$ is effective, the quotient $X/G$ is affine, and the morphism $X\to X/G$ is flat and surjective.}
  The proof uses the following fact (that, for now, has only been proven in characteristic $0$):
  if we let $G$ act on the affine ring $A$ of $G$, considered as a vector space over $k$, then the trivial representation of $G$ only appears once (in a composition series of a vector subspace of finite dimension over $k$ that is stable under $G$).
  \oldpage{212-20}
  It seems possible that a systematic use of the theory of linear representations of $G$ would give a proof of the conjecture, or at least when we work over a base field.
  When we are no longer working over a base field, the author knows nothing.
:::

::: {.rmenv title="Remark" latex="{Remark}"}
  \comp
  As we note at the end of the next talk, the above conjecture is decidedly false.
  The "positive fact" mentioned in the above remark seems to have been proven simultaneously by various authors (Nagata, Rosenlicht, Grothendieck, ...).
:::
