# Picard schemes: General properties {#fga-3.vi}

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geqslant}{\geqslantslant}
\renewcommand{\leqslant}{\leqslantslant}

\providecommand{\Spec}{\operatorname{Spec}}
\providecommand{\red}{\mathrm{red}}
\providecommand{\Ga}{\operatorname{G_a}}
\providecommand{\Gm}{\operatorname{G_m}}
\providecommand{\HH}{\operatorname{HH}}
\providecommand{\Alb}{\operatorname{Alb}}

<!-- Shortcuts -->

<!-- Content -->

::: {.original-citation}
[FGA 3.VI]
Grothendieck, A.
"Technique de descente et théorèmes d'existence en géométrie algébrique, VI: Les schémas de Picard: Propriétés générales".
_Séminaire Bourbaki_ **14** (1961--62), Talk no. 236.
:::


## 0. Supplements to the previous talk (FGA 3.V) {.unnumbered}

\oldpage{236-01}There has been some progress concerning the questions of existence of Picard preschemes raised in [FGA 3.V](FGA-3-V.html):

a. (Mumford).
  It is not true in general that, if $f\colon X\to S$ is a projective and separable (i.e. flat with separable fibres) morphism, then the Picard prescheme $\repPic_{X/S}$ exists, even if the fibres of $f$ are of dimension $1$ and $S$ is the spectrum of a complete discrete valuation ring.
  A counterexample is given by taking $S=\Spec\mathbb{R}[[t]]$, and taking $X$ to be the subscheme of $\mathbb{P}_S^2$ (with homogeneous variables $x,y,z$) defined by the equation $x^2+y^2=tz^2$, which represents a conic degenerating to two geometrically concurrent lines, but the special fibre over the field $\mathbb{R}$ is nevertheless irreducible (it is given by the equation $x^2+y^2=0$ in $\mathbb{R}$).
  We easily see that, after the étale extension $S'\to S$, with $S'=\Spec\mathbb{C}[[t]]$, the Picard prescheme of $X'/S'$ exists, and we thus obtain an explicit description of it as a sum of copies of $\widetilde{S}$, where $\widetilde{S}$ is induced by $S$ by copying the origin an infinite number of times.
  We easily observe that the descent data on $\repPic_{X'/S'}$ for $S'\to S$ (given here by the actions of the Galois group $\mathbb{Z}/2\mathbb{Z}$ of $S'$ over $S$) is not effective, since the group permutes certain doubled points (so that there are orbits that are not contained in an affine open).
  However, Mumford has shown that, if $f\colon X\to S$ is a separable projective morphism such that, for all $s\in S$, the irreducible components of $X_s$ are geometrically irreducible with respect to $k(s)$, then $\repPic_{X/S}$ exists;
  the proof relies on a refinement of his theorem of passage to the quotient, cf. [Mumford--Tate seminar, 1962].^[*[Trans.]* See translator footnotes in [FGA 3.V](#FGA-3-V.html).]
  Note also that it is still possible that, without any hypotheses on the irreducible components of the fibres $X_s$, the scheme $\repPic_{X/S}^\tau$ (which will be introduced below) still exists.


b. (Murre).\oldpage{236-02}
  If $X$ is a proper scheme over a field, then $\repPic_{X/k}$ exists.
  The proof partially uses the proof of Chevalley [@Che1960], and is fundamentally based on the group structure of the Picard functor.

For certain additional comments concerning the theory of Picard schemes, most notably in relation to abelian schemes, we recommend consulting [Mumford--Tate seminar, 1962].
Finally, a notable shortcoming of the present talk is the absence of "equivalence criteria" that would allow us to compare the Picard scheme of a projective scheme and of its hyperplane sections;
the key theorems for developing such criteria can be found in [@Gro1960b], with which one must combine the existence theorems for Picard schemes.


## Topological properties of preschemes of commutative groups {#fga-3-vi-section-1}

Let $k$ be a field, and $G$ be a prescheme of groups over $k$.
Since the identity element $e$, being rational over $k$, is necessarily closed, it immediately follows that the diagonal of $G\times_k G$ is closed, and so $G$ is *separated*: *every prescheme of groups over a field is separated*.
We denote by $G^0$ the connected component of the identity element $e$.
Since $e$ is rational over $k$, $G^0$ is in fact *geometrically connected*, i.e. $G\mapsto G^0$ is compatible with base change to another field.
It also follows that $G^0$ is stable under multiplication (set-theoretically), and if $G$ is locally Noetherian then $G^0$ is open, and we can consider $G^0$ as an *open subgroup* of $G$.
In what follows, we suppose $G$ to be locally of finite type over $k$;
then $G^0$ is *geometrically irreducible and of finite type over $k$*.
Indeed, we can suppose that $k$ is algebraically closed, and thus that $G$ is reduced (since $G_\red$ is then a subgroup of $G$, taking into account the fact that $G_\red\times_k G_\red$ is also then reduced), and thus simple over $k$ over a non-empty open, and thus everywhere, by translating this open subset.
But then $G$ is locally irreducible, and so its irreducible components are identical to its connected components, and so $G^0$ is irreducible.
So let $U$ be an affine neighbourhood of $e$ in $G^0$;
using the fact that $G^0$ is irreducible, we immediately see that $U\cdot U=D^0$, which proves that $G^0$ is quasi-compact, and thus of finite type over $k$.

Suppose, for simplicity, that $G$ is commutative.
For every integer $n>0$, let $G^{(n)}$ be the inverse image of $G^0$ under the $n$-th power homomorphism $\varphi_n$ to $G$, so $G^{(n)}$ is an open subgroup of $G$.
We set
$$
  \begin{aligned}
    G^\tau
    &= \bigcup_{n>0} G^{(n)}
  \\G^\sigma
    &= \bigcup_{(n,p)=1} G^{(n)}
  \\G^\rho
    &= \bigcup_{h>0} G^{(p^h)}
  \end{aligned}
$$
where $p$ is the characteristic order of the field $k$.
\oldpage{236-03}These are open subgroups of $G$ that satisfy
$$
  \begin{aligned}
    G^\sigma \cap G^\rho
    &= G^0
  \\G^\sigma \cdot G^\rho
    &= G^\tau.
  \end{aligned}
$$

::: {.rmenv #fga-3-vi-remark title="Remark" latex="{Remark}"}
We can construct the quotient group scheme $G/G^0=N$ (cf. [FGA 3.IV](FGA-3-IV.html)) and then define $G^\tau$, $G^\sigma$, and $G^\rho$ as the inverse images in $G$ of the torsion subgroup of $N$ (resp. of its $p$-primary component, resp. of the natural complement of its $p$-primary component, given by the sum of the $q$-primary components for $q$ prime with $q\neq p$).
Note that $N$ is a discrete group scheme that is separable over $k$, thus (once we have chosen an algebraic closure $\overline{k}$ of $k$, giving rise to a Galois group $\pi$) can be identified with an ordinary discrete group on which $\pi$ acts by automorphisms.
It is in this way that we can interpret, in an evident way, the construction of the torsion subgroup and the decomposition of this into its $q$-primary components.
If $G$ is the Picard scheme of a proper scheme $X$ over $k$, then $N$ could be called the (reduced) *Néron--Severi scheme* of $X$ over $k$.
If $G_\red^0$ is a group subscheme of $G^0$, which is the case whenever, in particular, $k$ is parfait, or $G^0$ is proper over $k$ (for example if $X$ is geometrically normal), then we can equally introduce the quotient $N'=G/G_\red^0$, which has the tendency to behave better than $N$ from the specialisation point of view, i.e. as $X$ varies over a family of algebraic schemes.
:::

Now let $S$ be a locally Noetherian prescheme, and $G$ a group prescheme over $S$ that is locally of finite type over $S$.
We do not assume $G$ to be of finite type over $S$, nor separated over $S$.
We then set
$$
  G^0
  = \bigcup_{s\in S} (G_s)^0
$$
and, if $G$ is commutative,
$$
  \begin{aligned}
    G^\tau
    &= \bigcup_{s\in S} (G_s)^\tau
  \\G^\sigma
    &= \bigcup_{s\in S} (G_s)^\sigma
  \\G^\rho
    &= \bigcup_{s\in S} (G_s)^\rho.
  \end{aligned}
$$
\oldpage{236-04}These are subsets of $G$, stable under the multiplication of $G$, which does not obviously imply that they can be defined by means of sub-group preschemes of $G$.
Notably, it seems that *there does not exist in a general sub-group prescheme of $G$ whose underlying set is $G^0$*.
Of course, if one of these sets is open, then, endowed with the induced structure, it is an open sub-group prescheme of $G$.
We will see that this is always the case for $G^\tau$;
in this way, from the point of view of representable functors, in particular *from the "specialisation" point of view, numerical equivalence behaves in a more satisfying manner than algebraic equivalence*.
Here are the principle general properties of the sets that we have just defined:

::: {.itenv #fga-3-vi-theorem-1.1 title="Theorem 1.1" latex="{Theorem 1.1}"}
$G^0$, $G^\tau$, $G^\sigma$, and $G^\rho$ are *locally constructible*.
Furthermore:

i. $G^0$ is quasi-compact over $S$.
  If the $G_s^0$ are proper, and $G$ is separated over $S$, then $G^0$ is proper over $S$ and thus closed in $G$.
ii. $G^\tau$ is open.
  If $G^0$ is closed, then so too is $G^\tau$.
iii. If $G^0$ is closed, then so too is $G^\sigma$, provided that we are in equal characteristic, i.e. that all the residue fields of $S$ have the same characteristic.
  If $G^0$ is closed and $G\to S$ is universally open at the points of $G^\sigma$ (cf. [Corollary 1.5](#fga-3-vi-corollary-1.5) below), then $G^\sigma\to S$ is universally open.
iv. If $G^0$ is closed, then so too is $G^\rho$.
  If we are in equal characteristic, and if, for every integer $n>0$ such that $(n,p)=1$, the $n$-th power homomorphism to $G$ is open, then $G^\rho$ is open.
:::

We now give some hints towards the proof.
The fact that $G^0$ is locally constructible, and quasi-compact over $S$, is contained in the following lemma:

::: {.itenv #fga-3-vi-lemma-1.2 title="Lemma 1.2" latex="{Lemma 1.2}"}
If $S\neq\varnothing$ then there exists a non-empty open $U$ in $S$, a group scheme $H$ of finite type over $U$ with connected fibres, and a homomorphism of group schemes $H\to G|U$ that is an open immersion with image $G^0|U$.
:::

::: {.proof}
To prove this lemma, we can suppose that $S$ is irreducible;
let $\eta$ be its generic point.
If we make the base change $S'=\Spec(\OO_{S,\eta})\to S$ then we find a group scheme $G'$ over a local Artinian ring $\OO_{S,s}=A$ inside which we have an *open* group subscheme ${G'}^0$ *of finite type over $A$*, as we said above.
This thus comes from a group scheme $H$ of finite type over an open neighbourhood $U$ of $\eta$, and the canonical immersion ${G'}^0\to G'$ comes from an open immersion $H\to G|U$, which will be a homomorphism of group schemes for $U$ small enough.
\oldpage{236-05}Since the fibres of $H$ are connected if we take $U$ small enough, and since they are all of the same dimension, namely that of the fibres of $G$, for $U$ small enough, it follows that, for all $s\in U$, the image of $H_s$ in $G_s$ is exactly $G_s^0$ (for $U$ small enough), which proves the lemma.
:::

The second claim in [(1.1), (i)](#fga-3-vi-theorem-1.1) is contained in the following lemma (which we apply to an quasi-compact open neighbourhood of $G^0$ in $G$):

::: {.itenv #fga-3-vi-lemma-1.3 title="Lemma 1.3" latex="{Lemma 1.3}"}
Let $X$ be a separated prescheme of finite type over $S$, with $S$ locally Noetherian, and let $g$ be a section of $X$ over $S$, and $X^0$ the union of the connected components of the $g(s)$ in the $X_s$.
Let $s\in S$ be such that $X_s^0$ is proper over $k(s)$.
Then there exists an open neighbourhood $U$ of $s$ such that $X^0|U$ is proper over $U$, and a fortiori closed in $X|U$.
:::

::: {.proof}
By faithfully flat descent of the base, we can reduce to the case where $S$ is the spectrum of a complete local ring, and $s$ is its closed point.
Applying [@GD1960, III, 5.5.1], we see that $X$ decomposes into a sum of two disjoint opens $X'$ and $X''$, with $X'$ proper over $S$, and such that $X'_s=S_s^0$.
This allows us to reduce to the case where $X=X'$, i.e. where $X$ is proper over $S$.
In this case, we can apply a standard proof, using the valuative criterion of properness of a subset (forgotten in [@GD1960, II]).
:::

We now prove that $G^\tau$ is open, or, equivalently, taking into account the fact that the formation of $G^\tau$ (as that of $G^0$, $G^\sigma$, and $G^\rho$) commutes with base extension: for every sections $g$ of $G$ over $S$, $g^{-1}(G^\tau)$ is open.
This implies two things:

a. Let $y\in S$ be such that $g(y)\in G^\tau$.
  Then, for all neighbours $y'\in\overline{y}$ of $y$, we have $g(y')\in G^\tau$.
b. Let $y'\in S$ be such that $g(y')\in G^\tau$.
  Then, for every generalisation $y$ of $y'$, we have $g(y)\in G^\tau$.

For (a), note that there exists an integer $n>0$ such that $g^n(y)\in G^0$; since $G^0$ is constructible, $(g^n)^{-1}G^0$ is constructible;
it follows that we have $g^n(y')\in G^0$ for all neighbours $y'\in\overline{y}$ of $y$.
For (b), note that the $g(y')^n=g^n(y')$ remain in a quasi-compact open of $G_{y'}$ (since they are contained in a finite number of classes modulo $G_{y'}^0$), and so there exists a quasi-compact open $U$ in $G$ that contains the $g^n(y')$, and thus also their generalisations $g^n(y)$, and so the powers of $g(y)$ remain in a quasi-compact open of $G_y$, which easily implies that $g(y)\in G_y^\tau$.

\oldpage{236-06}Suppose that $G^0$ is closed;
we will show that so too is $G^\tau$.
As we already know that $G^\tau$ is open, thus locally constructible, it remains only to show that it is stable under specialisation, which comes from the fact that it is a union of closed subsets, namely inverse images under the $n$-th power homomorphisms $\varphi_n$ of the closed subset $G^0$.

The same argument shows that $G\sigma$ and $G^\rho$ are closed if $G^0$ is (under the additional hypothesis of equal characteristic in the case of the former), once we have shown that $G^\sigma$ and $G^\rho$ are locally constructible.
But, for $x\in G^\tau$, let $\nu(x)$ be the smallest integer $n>0$ such that the $n$-th power homomorphism $\varphi_n$ sends $x$ to $G$.
Then $G^\sigma$ (resp. $G^\rho$) consists of the $x\in X$ such that $\nu(x)$ is coprime to $p$ (resp. to a power of $p$), and our claim of constructibility then follows from the following, more precise lemma:

::: {.itenv #fga-3-vi-lemma-1.4 title="Lemma 1.4" latex="{Lemma 1.4}"}
The function $\nu$ on $G^\tau$ is locally constructible.
:::

::: {.proof}
This means that, for every integer $n>0$, the set of $x\in G^\tau$ such that $\nu(x)=n$ is locally constructible;
but this is the difference between $\varphi_n^{-1}(G^0)$ and the union of the $\varphi_d^{-1}(G^0)$ where $d$ runs over the proper divisors of $n$;
since $G^0$ is locally constructible, so too are all the $\varphi_i^{-1}(G^0)$, and thus also the aforementioned difference.
:::

Suppose that $G^0$ is closed and that $G\to S$ is universally open at the point of $G^\sigma$;
we will show that $G^\sigma\to S$ is open, i.e. sends a neighbourhood in $G^\sigma$ of any $x\in G^\sigma$ to a neighbourhood of $y=f(x)$.
Since $G^\sigma$ is locally constructible, it suffices to show that, for every generalisation $y'$ of $y$, there exists a generalisation of $x$' of $x$ in $G$ in $y'$.
By base change, this allows us to reduce to the case where $S$ is the spectrum of a discrete valuation ring, and where $y$ and $y'$ are the closed point and the generic point (respectively).
Using the fact that $G\to S$ is open at $x$ (and thus there exists a generalisation $x_1$ of $x$ in $G$ over $y'$), we can further suppose that there exists a section $g$ of $G$ over $S$ such that $x=g(y)$ (after performing another base change).
If $k(y')$ is of characteristic $0$, then it suffices to take any generalisation $x'$ of $x$ in $G$ over $y'$;
it is in $G^\tau$ since $G^\tau$ is open, and thus in $G^\sigma$ since $G_{y'}^\sigma=G_{y'}^\tau$.
If the characteristic of $k(y')$ is $p>0$, then let
$$
  \nu(g(y'))
  = p^hm
  \qquad\text{where }(m,p)=1
$$
\oldpage{236-07}and let $a$ and $b$ be integers such that $ap^h+bm=1$, and set
$$
  \begin{aligned}
    g_1
    &= g^{ap^h}
  \\g_2
    &= g^{bm}
  \end{aligned}
$$
so that $g=g_1g_2$.
By construction, we then have $g_1(y')\in G^\sigma$ and $g_2(y')\in G^\rho$.
Since $G^0$ is closed, it follows that $g_1(y)\in G^\sigma$ and $g_2(y)\in G^\rho$, whence, since
$$
  g(y)
  = g_1(y)g_2(y) \in G^\sigma
$$
we also have that $g_2(y)\in G^\sigma$, and so
$$
  g_2(y)\in G_y^\sigma\cap G_y^\rho
  = G_y^0.
$$
But from the hypothesis, and the fact that $S$ is the spectrum of a discrete valuation ring, it follows that $G\setminus(G_y\setminus G_y^0)$ is an open of $G$ over which $G\to S$ induces an open morphism, and thus, at every point of $G_y^0$, gives a "quasi-section";
then, after possibly another extension of the base $S$, we can suppose that there exists a section $g'_2$ of $G^0$ over $S$ such that $g'_2(y)=g_2(y)$.
Set $g'=g_1g'_2$;
then, by construction, $g'(y)=g(y)=x$, and $g'(y')=g_1(y')g'_2(y')\in G^\sigma$, and so $g(y')=x'$ is a generalisation of $x$ in $G^\sigma$ over $y'$, which proves (iii).

Finally we prove the last claim (iv).
It suffices to prove that, if $x\in G^\rho$, then every generalisation $x'$ of $x$ is in $G^\rho$.
We can suppose (after taking the images under $\varphi_{n^h}$ for suitable $h$) that we even have $x\in G^0$.
Then, for every integer $n>0$ coprime to the characteristic, $x$ is in the image of $\varphi_n$ (since the $n$-th power in a connected group of finite type over a field of characteristic coprime to $n$ is surjective).
Since $\varphi_n$ is open, it follows that $x'$ is also in the image of $\varphi_n$.
More precisely, let $U$ be a quasi-compact open of $G^\tau$ that contains $G_y^0$, and then $x'\in\varphi_n(U)$ for all $n$ coprime to $p$.
Taking $n$ to be a common multiple of the factors of the $\nu(z)$ that are coprime to $p$, for $z\in U$, we see that $x'\in G^\rho$.

The claim [(1.1), (iii)](#fga-3-vi-theorem-1.1) is completed like so:

::: {.itenv #fga-3-vi-corollary-1.5 title="Corollary 1.5" latex="{Corollary 1.5}"}
Let $n>1$ be an integer such that the $n$-th power homomorphism $\varphi_n\colon G\to G$ is universally open (for example, étale).
Let $G^{(n)}=\varphi_n^{-1}(G^0)$, and suppose that the connected fibres $G_s^0$ "do not contain the additive component" (i.e the group induced by field extension from $k(s)$ to the algebraic closure does not contain a subgroup isomorphic to $\Ga$).
\oldpage{236-08}Then $G\to S$ is universally open at the point of $G^{(n^h)}$.
In particular, if the $G_s^0$ do not contain the additive component, and if, for every integer $n>1$, the homomorphism $\varphi_n$ is universally open at the points of residual characteristic coprime to $p$, then $G\to S$ is universally open at the points of $G^\sigma$, and thus [(1.1), (iii)](#fga-3-vi-theorem-1.1) if $G^0$ is closed then $G^\sigma\to S$ is universally open.
In this case, $s\mapsto\dim G_s$ is a locally constant function on $S$.
:::

::: {.proof}
It follows from the hypotheses that the kernel ${}_nG$ of $\varphi_n$ is universally open over $S$, and so $G\to S$ is universally open at the points of ${}_nG$, and thus also (replacing $n$ with $n^h$) at the points of ${}_{(n^h)}G$.
But the hypothesis on the fibres $G_s^0$ tells us exactly that the points of order some power of $n$ in $G_s$ are dense in the union of the $G^{(n^h)}$, whence it easily follows that $G\to S$ is universally open at all points of this union, in particular along the identity section, whence it easily follows that $s\mapsto\dim G_s$ is a locally constant function.
:::

::: {.rmenv #fga-3-vi-remark-1.6 title="Remark 1.6" latex="{Remark 1.6}"}
Recall that a morphism $X\to S$ is said to be universally open if it sends every open to an open, and retains this nice property after any base change $S'\to S$.
This also implies (if $S$ is locally Noetherian and $X\to S$ is locally of finite type) that every irreducible component of $X$ dominates $S$, and that this property is retained after any base change $S'\to S$.
In these two claims, it suffices (thanks to the finiteness hypotheses above) to verify only for the base changes $S'\to S$ where $S'$ is the spectrum of a discrete valuation ring (complete, with algebraically closed residue field, if one wants...).
The definition extends in an evident way to the case of a subset $Z$ of $X$ (such as the subset $G^\sigma$ of $G$).
It is a perfectly normal phenomenon, even if we start with a simple projective morphism $X\to S$ with connected geometric fibres (for example, the fibre square of the modular family of elliptic curves over $S=\Spec\mathbb{C}[j]$), that $\repPic_{X/S}$ is not universally open over $S$, i.e. that there can be irreducible components of $\repPic_{X/S}$that live entirely over a single point of $S$;
this is linked to the fact that the rank of the Néron--Severi group of the fibres of $X/S$ can jump up ("complex multiplication" phenomena).
However, [(1.5)](#fga-3-vi-corollary-1.5) assures us that, in good cases, $\repPic_{X/S}^\sigma$ (and usually, it seems, even $\repPic_{X/S}^\tau$) is universally open over $S$.
:::

\oldpage{236-09}Finally, here is a useful case where, exceptionally, $G^0$ agrees to be open:

::: {.itenv #fga-3-vi-corollary-1.7 title="Corollary 1.7" latex="{Corollary 1.7}"}
Suppose that $G\to S$ is universally open at the points of $G^0$ (cf. [(1.5)](#fga-3-vi-corollary-1.5)) and that the fibres $G_s$ are separable, thus simple over $k(s)$ (this latter condition being automatically satisfied in residual characteristic zero, by a result of Cartier).
Then $G^0$ is open in $G$.
If, further, $S$ is reduced, then $G^0$ is simple (and in particular, flat) over $S$.
:::

::: {.proof}
The first claim can be made more precise by noting that if, for some given $s\in S$, we have that $G\to S$ is universally open at the points of $G_s^0$, and if $G_s^0$ is separable over $k(s)$, then $G^0$ is a neighbourhood of $G_s^0$ (and it so happens that the hypotheses made on $s$ remain satisfied by all neighbouring points).
A proof of this statement, which is independent of all the structure of the group, can be found in [@GD1960, IV, §7].
The last claim in [(1.7)](#fga-3-vi-corollary-1.7), also independent of group structure and of any question of connected components, is a particular case of a flatness criterion given in [@Gro1960b, §5], which implies, more generally:
:::

::: {.itenv #fga-3-vi-corollary-1.8 title="Corollary 1.8" latex="{Corollary 1.8}"}
Let $U$ be an open subset of a fibre $G_s$ such that $G\to S$ is universally open at the points of $U$ (cf. [(1.5)](#fga-3-vi-corollary-1.5)).
If $G_s$ is separable over $k(s)$ and $S$ is reduced at $s$, then $G$ is flat over $S$ at the points of $U$ (and then also simple over $S$ at the points of $U$).
:::

::: {.rmenv #fga-3-vi-remarks-1.9 title="Remarks 1.9" latex="{Remarks 1.9}"}
I do not know, if $G$ is separated over $S$, if $G^0$ or $G^\tau$ is always closed in $G$;
this seems unlikely.
In any case, we find evident counter-examples if we drop the separation hypothesis, for example by taking the affine line with a countably infinite number of copies of the origin, thus obtaining a group scheme $G$ over the affine line whose fibres are all the trivial group, apart from one, which is $\mathbb{Z}$.
This group scheme is an open group subscheme, the closure of the identity section, of the Picard prescheme of the $S$-scheme $X$ that corresponds to a family of conics degenerating to two concurrent lines.

Even starting with a flat and finite group scheme $G$ over the spectrum $S$ of a discrete valuation ring $V$, if $G^0$ is reduced at the identity section, and thus closed, then various conclusions become false if we drop certain hypotheses.
Suppose that $V$ is of equal characteristic $p>0$, and let $G$ be the kernel of the homomorphism $\Ga\to\Ga$ given by the homomorphism of functors $f\mapsto f^p-tf$, where $t$ is a uniformiser of $V$.
\oldpage{236-10}(Recall that, by definition, the "additive group" $\Ga$ over $S$ represents the functor $S'\mapsto\Gamma(S',\OO_{S'})$).
Then, as an $S$-scheme, $G=\Spec V[x]/(x^p-tx)$ is the union of $p$ concurrent "lines", giving a group $\mathbb{Z}/p\mathbb{Z}$ that degenerates to an infinitesimal additive-type group.
In this example, $G^0=G^\sigma$ (and this is one of the $p$ lines), and so $G^0$ is not open in $G$.
In the case of unequal characteristic, with residual characteristic $p>0$, we start with a group scheme $H=\mu_p$ given by the kernel of the $p$-th power in $\Gm$, so that $H=\Spec V[x]/(x^p-1)$, which is again the union of $p$ concurrent lines, giving a group $\mathbb{Z}/p\mathbb{Z}$ (in characteristic $0$) that degenerates to an infinitesimal multiplicative-type group in characteristic $p$.
Let $H'$ be the "constant group scheme" defined by the ordinary finite group $\mathbb{Z}/p\mathbb{Z}$, which is the disjoint sum of $\mathbb{Z}/p\mathbb{Z}$ copies of $S$, or even $\Spec V^{\mathbb{Z}/p\mathbb{Z}}$.
Then $G=H\times_S H'$ describes a group $(\mathbb{Z}/p\mathbb{Z})^2$ in characteristic $0$ that degenerates to an infinitesimal group times $\mathbb{Z}/p\mathbb{Z}$ in characteristic $p$.
Here $G^\rho$ is the union of the identity section and the special fibre, and so $G^\rho$ is not open, even though $G^\sigma$ is the union of the identity section and the general fibre, and is thus not closed, contrary to what is true in the case of equal characteristic in [(1.1), (iii) and (iv)](#fga-3-vi-theorem-1.1).
Of course, these are phenomena linked to characteristic $p>0$.
The above results give:
:::

::: {.itenv #fga-3-vi-corollary-1.10 title="Corollary 1.10" latex="{Corollary 1.10}"}
Suppose that the residual characteristics of $S$ are all $0$, so that $G^\tau=G^\sigma$ and $G^0=G^\rho$.
Then $G^\tau=G^\sigma$ is open, and even open and closed if $G$ is separated over $S$ and the $G_s^0$ are proper;
under these same hypotheses, $G^0=G^\rho$ is proper over $S$ and thus closed in $G$.
Suppose finally that, for every integer $n>1$, the $n$-th power homomorphism in $G$ is universally open, then $G^0$ is open;
if furthermore the $G_s^0$ do not have any additive component (for example the $G_s^0$ are proper, as above), then $G^\tau\to S$ is universally open, and even simple if $S$ is reduced.
:::

Finally we note the following easy result:

::: {.itenv #fga-3-vi-proposition-1.11 title="Proposition 1.11" latex="{Proposition 1.11}"}
There exists an open subset $U$ of $S$ such that the set $G'$ of points of $G$ at which $G$ is simple (resp. flat) over $S$ is the underlying set of an open group subscheme induced by $G|U$.
Furthermore, every section of $G$ over $U$ is a section of $G'$ over $U$.
:::

::: {.itenv #fga-3-vi-corollary-1.12 title="Corollary 1.12" latex="{Corollary 1.12}"}
\oldpage{236-11}If $G$ is simple (resp. flat) over $S$ at the points of the identity section, then it is simple (resp. flat) at the points of every section of $G$ over $S$, and at all points of $G^0$.
If, further, for every integer $n>0$ the $n$-th power homomorphism $\varphi_n\colon G\to G$ is étale at the points of characteristic coprime to $n$, then $G$ is simple (resp. flat) over $S$ at all points of $G^\sigma$.
:::


## Application to the local properties of Picard schemes {#fga-3-vi-section-2}

::: {.itenv #fga-3-vi-theorem-2.1 title="Theorem 2.1" latex="{Theorem 2.1}"}
—

i. Let $f\colon X\to S$ be a proper and simple morphism, and suppose that $\repPic_{X/S}$ exists (for example, if $f$ is projective).
  Then $\repPic_{X/S}$ is separated over $S$, and, for every closed subset $Z$ of $\repPic_{X/S}$ that is of finite type over $S$, we have that $Z$ is proper over $S$.
ii. Let $X$ be a prescheme over a field $k$ that is proper and geometrically normal.
  Then $\repPic_{X/S}^0$ is proper over $k$.
:::

::: {.proof}
For (i), with the valuative criterion of [@GD1960, II, §7] it suffices to prove the following: if $S$ is the spectrum of a complete discrete valuation ring, and $U$ the open consisting of the generic point of $S$, then every rational section of $\repPic_{X/S}$ over $S$, i.e. every section over $U$, extends uniquely to a section over $S$.
Taking into account the definition of $\repPic_{X/S}$, this is equivalent to the following statement: for every invertible module $\sh{L}$ on $V=f^{-1}(U)$, there exists an invertible module on $X$ that extends $\sh{L}$, unique up to isomorphism.
But this follows easily from the description of invertible modules on $V$ (resp. on $X$) in terms of the classes of "Cartier" divisors, taking into account the fact that the local rings of $X$ are regular (since $X$ is simple over $S$, which is regular), and thus factorial, by Auslander, which implies that every divisor on $S$ is a Cartier divisor.
Indeed, every divisor on $V$ can be extended to a divisor on $X$ by taking its "closure".

\oldpage{236-12}For (ii), using Chow's lemma we can reduce to the case where $X$ is projective, and thus embedded into some $\mathbb{P}_k^n$;
we can also assume that $X$ is connected.
If $\dim X=1$, then $X$ is simple over $k$, and we can apply (i).
If $\dim X\geqslant2$, then we can use a variant of the known "equivalence criteria", which implies that there exists a finite number of curves $Y_i$, simple over $X$ (obtained as intersections of $X$ with suitable linear subspaces of $\mathbb{P}_k^n$), such that $\repPic_{X/k}^\tau\to\prod_i\repPic_{Y_i/k}^\tau$ is a monomorphism, and induces a fortiori a monomorphism for the connected components.
Since the codomain is proper over $k$ by the above, and since we are talking about a homomorphism of group schemes, which is necessarily a closed immersion, it follows that $\repPic_{X/k}^0$ is also proper over $k$.
We can avoid recourse to delicate equivalence criteria by using the structure of commutative algebraic groups over an algebraically closed field (thanks to Chevalley--Borel);
we are then reduced to proving that every morphism from the affine line with the origin removed into $\repPic_{X/S}^\tau$ is constant, which is equivalent to saying that every invertible module on $X[t,t^{-1}]$ comes from an invertible module on $X$, which is a result that is well known and elementary and does not even use the fact that $X$ is proper over $k$ (the hypothesis that $X$ is normal allowing us to immediately reduce to the case where $X$ is regular).
:::

::: {.rmenv #fga-3-vi-remark-2.2 title="Remark 2.2" latex="{Remark 2.2}"}
The above proof of (i) holds true even if we only suppose that $f$ is flat and that its fibres $X_s$ are locally complete intersections and simple over $k(s)$ in codimension $\leqslant2$, taking into account the following fact which is proven in [@Gro1960b]: a Noetherian complete intersection local ring that is regular in codimension $\leqslant3$ is factorial ("Samuel's conjecture").
We note that the result becomes false if we replace "codimension $\leqslant2$" by "codimension $\leqslant1$", i.e. by the hypothesis "normal", as we can convince ourself by considering the example of a family of non-singular quadratics that degenerate to a quadratic cone.
:::

::: {.itenv #fga-3-vi-corollary-2.3 title="Corollary 2.3" latex="{Corollary 2.3}"}
Let $f\colon X\to S$ be a proper and normal morphism (i.e. flat with normal geometric fibres), and suppose that $\repPic_{X/S}$ exists.
Then $\repPic_{X/S}^0$ is proper over $S$, thus closed in $\repPic_{X/S}$;
furthermore, $\repPic_{X/S}^\tau$ and $\repPic_{X/S}^0$ are both closed, as is $\repPic_{X/S}^\sigma$ in "equal characteristic".
:::

::: {.proof}
We apply [(1.1)](#fga-3-vi-theorem-1.1) and [(2.1), (ii)](#fga-3-vi-theorem-2.1).
:::

::: {.itenv #fga-3-vi-corollary-2.4 title="Corollary 2.4" latex="{Corollary 2.4}"}
Let $f\colon X\to S$ be a proper and simple morphism such that $\repPic_{X/S}$ exists and is the sum of the schemes $P^{(i)}$ of finite type over $S$ (cf. [FGA 3.V, Proposition 4.1](#fga-3-v-proposition-4.1)).
Then each $P^{(i)}$ is proper over $S$.
:::

::: {.proof}
This follows from [(2.1), (i)](#fga-3-vi-theorem-2.1).
:::

As we noted in [(2.2)](#fga-3-vi-remark-2.2), the above result can be generalised by making less restrictive hypotheses on the fibres of $f$, but becomes false if we only suppose $f$ to be normal.
In this case, I do not know if $\repPic_{X/S}^\tau$ is nevertheless proper over $S$, even if assuming it to be of finite type over $S$.

::: {.itenv #fga-3-vi-theorem-2.5 title="Theorem 2.5" latex="{Theorem 2.5}"}
\oldpage{236-13}Let $f\colon X\to S$ be a proper and flat morphism such that $\repPic_{X/S}$ exists, and, for each integer $n$, let $\varphi_n$ be the $n$-th power homomorphism in this group prescheme.
Then $\varphi_n$ is étale at all points $x\in X$ of residual characteristic coprime to $n$.
:::

By the infinitesimal characterisation of étale morphisms, the above claim is equivalent to the following:

::: {.itenv #fga-3-vi-lemma-2.6 title="Lemma 2.6" latex="{Lemma 2.6}"}
Suppose that $S$ is the spectrum of an Artinian local ring $A$ whose maximal ideal $\mathfrak{m}$ is $(\nu+1)$-th power null, and let $A_{\nu-1}=A/\mathfrak{m}^\nu$ and $X_{\nu-1}=X\otimes_A A_{\nu=1}$.
Let $\sh{L}$ be an invertible module on $X$, and $\sh{L}'_{\nu-1}$ an invertible module on $X_{\nu-1}$ whose $n$-th tensor power is isomorphic to $\sh{L}_{\nu-1}=\sh{L}\otimes_A A_{\nu-1}$.
Then there exists an invertible module $\sh{L}'$ on $X$ whose $n$-th tensor power is isomorphic to $\sh{L}$ (if $n$ is coprime to the residual characteristic of $k=k(\sh{L})$).
:::

::: {.proof}
Set $V=\mathfrak{m}^\nu=\mathfrak{m}^\nu/\mathfrak{m}^{\nu+1}$, which is a vector space over $k=k(A)$.
We start by extending $\sh{L}'_{\nu-1}$ to an arbitrary invertible module over $\sh{L}'$ on $X$.
The obstruction to doing this is found in $\HH^2(X_0,\OO_{X_0})\otimes_k V$, but by the hypothesis on $\sh{L}'_{\nu-1}$ and the fact that $\sh{L}_{\nu-1}$ can be extended, we see that the product of this obstruction with $n$ is zero, and so the obstruction itself must be zero since $n$ is coprime to the characteristic.
The arbitrariness of the extension is found in $\HH^1(X_0,\OO_{X_0})\otimes_k V$, and the deviation $\xi$ of ${\sh{L}'}^{\otimes n}$ from $\sh{L}$ is found in the same module;
if we try to correct $\sh{L}'$ in such a way as to render this deviation zero, then we are led to finding some $\eta$ in the aforementioned module such that $n\eta=\xi$.
But this is again possible thanks to the fact that $n$ is coprime to the characteristic.
:::

::: {.itenv #fga-3-vi-corollary title="Corollary" latex="{Corollary}"}
Under the conditions of [(2.5)](#fga-3-vi-theorem-2.5), suppose further that the Picard schemes of the fibres $X_s$ do not contain any additive component (for example, if the $X_s$ are geometrically normal, cf. [(2.1), (ii)](#fga-3-vi-theorem-2.1)).
Then $\repPic_{X/S}\to S$ is universally open at the points of $\repPic_{X/S}^\sigma$.
If $\repPic_{X/S}^0$ is closed (for example, if the $X_s$ are geometrically normal, cf. [(2.3)](#fga-3-vi-corollary-2.3)), then $\repPic_{X/S}^\sigma$ is itself universally open over $S$.
Finally, in the case of equal characteristic, $\repPic_{X/S}^\rho\to S$ is universally open.
:::

::: {.proof}
We apply [(1.5)](#fga-3-vi-corollary-1.5) and [(1.1)](#fga-3-vi-theorem-1.1).
:::

::: {.itenv #fga-3-vi-corollary-2.7 title="Corollary 2.7" latex="{Corollary 2.7}"}
\oldpage{236-14}Let $f\colon X\to Y$ be a proper and flat morphism such that $\repPic_{X/S}$ exists.
Then the function $s\mapsto\dim\repPic_{X_s/k(s)}$ on $S$ is upper semi-continuous (i.e. it can jump upwards, but not downwards), and it is even continuous (i.e. locally constant) if the $\repPic_{X_s/k(s)}$ do not contain any additive component.
:::

::: {.proof}
The first claim is trivially true, or almost so, for every group prescheme locally of finite type over a locally Noetherian base, since it suffices to look along the identity section.
The second claim follows from [(2.5)](#fga-3-vi-theorem-2.5).
:::

::: {.rmenv #fga-3-vi-remark-2.8 title="Remark 2.8" latex="{Remark 2.8}"}
Let $s,s'\in S$ be such that $s$ is a specialisation of $s'$.
Then [(2.7)](#fga-3-vi-corollary-2.7) is equivalent to an inequality (resp. equality) between the dimensions of the Picard schemes of $X_{s'}$ and of its "specialisation" $X_s$.
Serre noted, even before the construction of Picard schemes, that the invariance of the dimensions of the Picard varieties of the $X_s$ in the case of a *simple* morphism $f\colon X\to S$ was a formal consequence of the theory of specialisation of the fundamental group ([@Gro1960b, X]), classical relations à la Kummer between the points of finite order on the Picard variety, and the abelianisation of the fundamental group ([@Gro1960b, XI]).
If we denote by $\alpha$, $\mu$, and $\lambda$ the dimensions of the abelian, multiplicative, and additive parts (respectively) of $\repPic_{X_s/k(s)}$, and we similarly define $\alpha'$, $\mu'$, and $\lambda'$, then the known relations can be expressed as the following inequalities:
$$
  \alpha+\mu+\lambda
  \geqslant \alpha'+\mu'+\lambda'
\tag{$\ast$}
$$
(satisfied provided that $\repPic_{X/S}$ exists, and thus probably in all cases), and this inequality, for $\lambda=\lambda'=0$, reduces to an equality, satisfied under the same existence hypotheses:
$$
  \alpha+\mu
  = \alpha'+\mu'.
$$
We also have
$$
  2\alpha+\mu
  \leqslant 2\alpha'+\mu'
\tag{$\ast\ast$}
$$
\oldpage{236-15}by the argument of Serre, if the $X_s$ are separable (without even supposing the existence of $\repPic_{X/S}^\tau$), or if the ${}_n\repPic_{X/S}$ (kernels of the $\varphi_n$ into the Picard functor) are *separated* over $S$ (taking into account the fact that they are étale over $S$, thanks to [(2.5)](#fga-3-vi-theorem-2.5)).
We are inclined to conjecture that ($\ast$) is an equality in all cases, or at least if the $X_s$ are separable, and also that we have inequalities
$$
  \begin{aligned}
    \alpha &\leqslant \alpha'
  \\\lambda &\geqslant \lambda'
  \end{aligned}
\tag{$\ast\ast\ast$}
$$
which should be satisfied whenever we have a group prescheme that is locally of finite type over locally Noetherian $S$, in which the dimension of the fibres is constant (see [(1.3)](#fga-3-vi-lemma-1.3) for a positive result in this direction).
:::

::: {.rmenv #fga-3-vi-remark-2.9 title="Remark 2.9" latex="{Remark 2.9}"}
In all known cases, $\repPic_{X/S}^\tau$ is universally open over $S$, but we should probably not have excessive illusions, even if $f\colon X\to S$ is simple;
in any case, Mumford has constructed an example (it is true with $S$ non-reduced, in fact with $S$ the spectrum of an Artinian ring) where $\repPic_{X/S}^\tau$ is not flat over $S$, by infinitesimally varying the Igusa surface.
The point envisaged by Mumford can also be found in $\repPic_{X/S}^\rho$, and it remains possible (for $f\colon X\to S$ simple) that $\repPic_{X/S}$ is flat over $S$ at the points of $\repPic_{X/S}^\sigma$;
the speaker doubts, however, that this is always the case, even when restricting to the points of $\repPic_{X/S}^0$ and supposing $S$ to be the spectrum of a discrete valuation ring.
The question is linked to the study of fixed points of an abelian scheme under a finite automorphism group, a situation for which we seem to lack examples.
It seems that even by restricting to simple and projective $f\colon X\to S$, the results of local regularity on $\repPic_{X/S}$ stated in the present section, and the conjectures raised in [(2.8)](#fga-3-vi-remark-2.8), basically exhaust what can be said on this subject without more particular hypotheses on the nature of the fibres of $f$.
We recall, however, that, if the geometric fibres of $\repPic_{X/S}$ are *reduced* and have no additive component, then it follows from [(1.8)](#fga-3-vi-corollary-1.8) and [(2.5)](#fga-3-vi-theorem-2.5) that $\repPic_{X/S}$ is simple over $S$ at the points of $\repPic_{X/S}^\sigma$ whenever $S$ is reduced;
this result still holds even, if $f\colon X\to S$ is normal, without any hypothesis on $S$, and we will see in [(3.5)](#fga-3-vi-theorem-3.5).
On this note, we point out:
:::

::: {.itenv #fga-3-vi-proposition-2.10 title="Proposition 2.10" latex="{Proposition 2.10}"}
—

i. If $\repPic_{X/S}$ is simple (resp. flat) over $S$ at the points of the identity section, then it is simple (resp. flat) at all points of $\repPic_{X/S}^\sigma$, and at the points of every section of $\repPic_{X/S}$ over $S$.
ii. \oldpage{236-16}Let $s\in S$ be such that $\HH^2(X_s,\OO_{X_s})=0$.
  Then there exists an open neighbourhood $U$ of $s$ such that $\repPic_{X/S}|U$ is simple over $U$.
iii. Let $X$ be a proper scheme over a field.
  Then we have
  $$
    \dim\repPic_{X/k}
    \leqslant \dim\HH^1(X,\OO_X)
  $$
  with equality if and only if $\repPic_{X/k}$ is simple over $k$;
  this is always the case if $k$ is of characteristic $0$.
:::

::: {.proof}
Claim (i) follows from [(2.5)](#fga-3-vi-theorem-2.5) and [(1.12)](#fga-3-vi-corollary-1.12), and (ii) follows from the infinitesimal criterion for simple morphisms and a well-known obstruction calculation, taking into account the fact that (by the "semi-continuous theorem") the hypothesis made on $s$ will still hold true for neighbouring points.
Finally, (iii) follows from the fact that $\HH^1(X,\OO_X)$ is isomorphic to the Zariski tangent space at the identity element of $\repPic_{X/k}$;
the last claim is a particular case of a theorem of Cartier, saying that a "formal group" in characteristic $0$ is formally simple over $k$.
:::


## The canonical abelian subscheme of $\repPic_{X/S}$, and the Albanese scheme {#fga-3-vi-section-3}

::: {.itenv #fga-3-vi-proposition-3.1 title="Proposition 3.1" latex="{Proposition 3.1}"}
Let $k$ be a field, and let $G$ a group scheme of finite type over $k$ that is commutative and "without additive component".
Then $G_\red^0$ is separable over $k$, and thus a simple group scheme over $k$>
:::

::: {.proof}
Since the claim is trivial if $k$ is perfect, and in particular for $G_{\overline{k}}$, where $\overline{k}$ is the algebraic closure of $k$, it suffices to show that $(G_{\overline{k}}^0)_\red$ comes from a subscheme of $G$.
But from the hypothesis that $G_{\overline{k}}$ contains no additive component it easily follows that there exists an integer $m$ such that $(G_{\overline{k}}^0)_\red$ is the "scheme-theoretic" image of the $m$-th power homomorphism in $G_{\overline{k}}$.
Since the latter homomorphism comes from the analogous homomorphism for $G$, the scheme-theoretic image of this provides the desired object.
:::

::: {.itenv #fga-3-vi-corollary-3.2 title="Corollary 3.2" latex="{Corollary 3.2}"}
Let $X$ be a normal and proper scheme over $k$ such that $\repPic_{X/k}$ exists.
Then there exists an abelian subscheme of $\repPic_{X/k}$ whose underlying set is $\repPic_{X/k}^0$.
:::

::: {.proof}
By [(2.1), (ii)](#fga-3-vi-theorem-2.1), since $\repPic_{X/k}^0$ is proper over $k$, it satisfies the conditions of [(3.1)](#fga-3-vi-proposition-3.1).
:::

\oldpage{236-17}The above result shows that, in certain cases, the classical "Picard variety" (which is $(\repPic_{X/\overline{k}})_\red^0$ in the current theory) "is defined over $k$", without supposing the field $k$ to be perfect.

Now let $f\colon X\to S$ be a proper and flat relative scheme, with $\OO_S\simto f_*(\OO_X)$ for simplicity, such that $\repPic_{X/S}$ exists and that $\repPic_{X/S}^0$ is proper over $S$.
Suppose further, for [(3.3), (ii)](#fga-3-vi-theorem-3.3), that there exists an open of $\repPic_{X/S}$ containing $\repPic_{X/S}^0$ that is quasi-projective over $S$;
this condition is satisfied, as we have seen, if $f$ is projective and with separable or irreducible geometric fibres.
Recall that an *abelian scheme* over $S$ is a group scheme over $S$ that is proper and simple over $S$ with connected geometric fibres.
We propose to examine whether or not there exists a group subscheme $A$ of $\repPic_{X/S}$ that is an abelian scheme and whose underlying set is $\repPic_{X/S}^0$.
We have just seen that such an $A$ always exists if $S$ is the spectrum of a field.
Here is what we know how to say in the general case envisaged here:

::: {.itenv #fga-3-vi-theorem-3.3 title="Theorem 3.3" latex="{Theorem 3.3}"}
Under the above conditions:

i. If there exists an abelian subscheme of $\repPic_{X/S}$ whose underlying set is $\repPic_{X/S}^0$, then it is unique.
  Its formation is thus compatible with base change.
ii. For there to exist such an abelian subscheme, it is necessary and sufficient that it exist after every base change $S'\to S$, where $S'$ is local Artinian;
  if $S$ is the spectrum of a local ring, it even suffices to test with the $S'=\Spec(A_n)$ where $A_n=A/\mathfrak{m}^{n+1}$.
  If $S$ is reduced, then it equally suffices to test with the $S'$ that are the spectrum of a discrete valuation ring (complete, with algebraically closed residue field, if one desires).
iii. Suppose that $A$ exists, and let $B=\Alb^0(X/S)$ be the dual abelian scheme (i.e. $B=\Pic_{A/S}^0$ [Mumford--Tate seminar, 1962]).
  Then we can canonically construct a principal homogeneous space $P=\Alb^1(X/S)$ for $B$, and an $S$-morphism $X\to P$ that is universal for the $S$-morphisms from $X$ to para-abelian schemes (i.e. to principal homogeneous spaces for abelian schemes).
  The formation of $\Alb^0(X/S)$, $\Alb^1(X/S)$, and $X\to\Alb^1(X/S)$ commutes with base change.
:::

::: {.proof}
We sketch the proof:

i. This is a general property of rigidity for abelian subschemes of commutative group schemes: if two such subschemes agree set-theoretically at a point $s\in S$, then they agree over the entire connected component of $s$ ([Mumford--Tate seminar, 1962]).
  (This result generalises a classical theorem of Chow).
ii. Using Hilbert schemes, we see that the functor that, to every $S'$ over $S$ associates the set (consisting of either one or zero elements) of canonical abelian subschemes of $(\repPic_{X/S})\times_S S'$ is representable by a scheme $T$ of finite type over $S$.
  By (i), $T\to S$ is a monomorphism, and by [(3.2)](#fga-3-vi-corollary-3.2), it is surjective.
  To say that there exists a canonical abelian subscheme of $\repPic_{X/S}$ implies that $T$ is a section over $S$, or that $T\to S$ is an isomorphism.
  This is equivalent to saying that $T\to S$ is étale, or, in the case where $S$ is reduced, that $T\to S$ is proper.
  Whence immediately (ii).
iii. Simply using the definition of $\repPic_{X/S}$, we note that, for every abelian scheme $C$ over $S$, the data of an $S$-morphism from $X$ to a principal homogeneous space for $C$ is equivalent to the data of a group homomorphism $C'\to\repPic_{X/S}$, where $C'$ is the dual abelian scheme of $C$.
  But if the canonical abelian subscheme $A$ of $\repPic_{X/S}$ exists, then these homomorphisms necessarily factor through $A$ (and we can see by again using the points of finite order).
  Whence immediately (iii).
:::

::: {.rmenv #fga-3-vi-remarks-3.4 title="Remarks 3.4" latex="{Remarks 3.4}"}
We denote by $\repPic_{X/S}^{00}$ the canonical abelian subscheme of $\repPic_{X/S}$, if it exists.
This is, unfortunately, not always the case, as we can see by infinitesimally varying the Igusa surface (by first-order modular deformation).
It is however possible that $\repPic_{X/S}^{00}$ exists at least if $S$ is reduced, or, equivalently, by (ii), if $S$ is the spectrum of a discrete valuation ring.
So let $X_0$ and $X_1$ be the special and generic fibres of $X$ (respectively), and let $A_1=\repPic_{X_1/K_1}$, where $K$ is the field of fractions of the valuation ring $V$.
By Koizumi, there exists an abelian scheme $A$ over $S$, essentially unique, whose general fibre is $A_1$, and we easily see as in [(2.1), (i)](#fga-3-vi-theorem-2.1) (supposing from now on that $X$ is simple over $S$) that the identity morphism of $A_1$ extends to a morphism
$$
  A \to \repPic_{X/S}.
$$
From this, we obtain a homomorphism
$$
  A_0 \to \repPic_{X_0/k}^{00}
\tag{$\ast$}
$$
which we can easily show to be a surjective homomorphism with kernel equal to a finite $p$-group, where $p$ is the characteristic of the residue field $k$ (still by using the points of finite order).
\oldpage{236-19}With this, the following conditions on $X/S$ are equivalent:

a. The above homomorphism ($\ast$) is an isomorphism (which Shimura expresses by saying that the formation of the "Picard variety" is "compatible with specialisations").
b. $\repPic_{X/S}^{00}$ exists (and is then exactly $A$).
c. (For memory) The $\repPic_{X_n/S}^{00}$ exist.

By the remark that we made concerning the kernel of ($\ast$), condition (a) is satisfied if the residual characteristic is zero, but this result will be notably generalised in [(3.5)](#fga-3-vi-theorem-3.5).

Of course, if $\repPic_{X/S}$ is simple over $S$ at the points of $\repPic_{X/S}^0$, then the latter is open in $\repPic_{X/S}$ (cf. [(1.7)](#fga-3-vi-corollary-1.7)) and is thus, endowed with the induced structure, an abelian subscheme of $\repPic_{X/S}$, and thus equal to $\repPic_{X/S}^{00}$, which exists in this case.
But we have much better:
:::

::: {.itenv #fga-3-vi-theorem-3.5 title="Theorem 3.5" latex="{Theorem 3.5}"}
Under the conditions of [(3.3)](#fga-3-vi-theorem-3.3), let $s\in S$ be such that $\repPic_{X_s/k(s)}$ is simple over $k(s)$ (or, equivalently, such that $\dim\repPic_{X_s/k(s)}=\dim\HH^1(X_s,\OO_{X_s})$).
Then there exists an open neighbourhood $U$ of $s$ such that $\repPic_{X/S}$ is simple over $S$ at the points of $\repPic_{X/S}^0|U$, which is thus an open abelian subscheme in $\repPic_{X/S}|U$.
A fortiori, $\repPic_{X|U/U}^{00}$ exists.
:::

::: {.proof}
We describe the principle of the proof.
The above allows us to reduce to the case where $S$ is the spectrum of an Artinian local ring $A$, and we argue by induction on the infinitesimal order of $A$.
We can thus suppose that $\repPic_{X_n/A_n}^0$ is simple over $A_n$, and reduce to proving that $\repPic_{X_{n+1}/A_{n+1}}^0$ is simple over $A_{n+1}$.
Note that, for this, it suffices to construct an abelian scheme $P_{n+1}$ over $A_{n+1}$ that extends $P_n=\repPic_{X_n/A_n}^0$, along with an invertible module $\sh{L}_{n+1}$ on $X_{n+1}\times_{A_{n+1}}P_{n+1}$ that extends the invertible module $\sh{L}_n$ on $X_n\times_{A_n}P_n$ that arises in the definition of the Picard scheme $\repPic_{X_n/A_n}$ as the solution to a universal problem.
(N.B. We can suppose that $X$ is endowed with a section over $S$...).
For this construction, we must use the following key result: *every abelian scheme defined over a quotient of an Artinian local ring can be extended* (in other words, the absolute "formal scheme of modules" ([FGA 3.II](FGA-3-II.html)) for an abelian scheme over an algebraically closed field is simple over the ring of Witt vectors over $k$);
\oldpage{236-20}this result can be obtained by using the general formal properties of the obstruction to lifting, and the group operations.
With this result, we start by extending $P_n$ arbitrarily to $P_{n+1}$;
we then find an obstruction to lifting $\sh{L}_n$, found in $\HH^2(X_0\times P_0,\OO_{X_0\times P_0})\otimes_k V$ (where $V=\mathfrak{m}^{n+1}/\mathfrak{m}^{n+2}$), and more precisely in the subspace $\HH^1(X_0,\OO_{X_0})\otimes\HH^1(P_0,\OO_{P_0})\otimes_k V$ (taking into account the fact that the restriction of $\sh{L}_n$ to the two factors $X_n$ and $P_n$ is trivial).
But this latter space is exactly $\HH^1(P_0,\sh{G}_{P_0/k})\otimes V$, where $\sh{G}_{P_0/k}$ is the tangent sheaf to $P_0/k$, and thus also the space that expresses the indeterminacy that there was in the lifting of $P_n$ to $P_{n+1}$ ([FGA 3.II](FGA-3-II.html)).
So we can correct this lifting (in exactly one way, as should be the case) in such a way as to kill the obstruction to lifting $\sh{L}_n$.
:::

::: {.itenv #fga-3-vi-corollary-3.6 title="Corollary 3.6" latex="{Corollary 3.6}"}
Under the conditions of [(3.5)](#fga-3-vi-theorem-3.5), $\RR^1 f_*(\OO_X)$ is a locally free module on $S$ in a neighbourhood of $s$, and its formation commutes with base change.
:::

::: {.proof}
This module is exactly the tangent module to $\repPic_{X/S}$ along the identity section.
:::

::: {.rmenv #fga-3-vi-remark-3.7 title="Remark 3.7" latex="{Remark 3.7}"}
Using the same argument as for [(3.5)](#fga-3-vi-theorem-3.5), we can show that, if $S'$ is a subscheme of $S$ defined by a nilpotent coherent ideal, and if we suppose only that $\repPic_{X'/S'}^0$ exists and has simple fibres, then $\repPic_{X/S}^0$ necessarily exists and is an abelian scheme over $S$.
This allows us to construct Picard schemes in certain cases, despite the absence of any projective hypothesis;
for example, the dual abelian scheme of an abelian scheme over an Artinian ring always exists.
Using [(3.6)](#fga-3-vi-corollary-3.6) in the case where $X$ is an abelian scheme over $S$, and using the known structure of $\HH^\bullet(X_s,\OO_{X_s})$ as an exterior algebra over $\HH^1(X_s,\OO_{X_s})$ (Rosenlicht--Serre), we find that $\RR^if_*(\OO_X)$ is locally free for *all* $i$, and more precisely that it is isomorphic to the $i$-th exterior power of $\RR^1f_*(\OO_X)$.
:::

::: {.rmenv #fga-3-vi-remark-3.8 title="Remark 3.8" latex="{Remark 3.8}"}
In the case of a simple projective morphism $f\colon X\to S$, with $S$ reduced and of residual characteristics zero, the result of [(3.6)](#fga-3-vi-corollary-3.6) was already known, by transcendental methods, as a consequence of Hodge theory.
In fact, all the $\RR^pf_*(\Omega_{X/S}^q)$ are then locally free.
\oldpage{236-21}We have, however, counterexamples in the case of unequal characteristics for "locally free $\RR^1f_*(\OO_X)$", by Serre varieties ([@Ser1958b, p.50]).
It seems that we do not have any counterexample in equal characteristic.
:::

::: {.itenv #fga-3-vi-corollary-3.8 title="Corollary 3.8" latex="{Corollary 3.8}"}
Under the conditions of [(3.5)](#fga-3-vi-theorem-3.5), $\repPic_{X/S}|U$ is simple over $U$ at all points of $\repPic_{X/S}^\sigma|U$.
:::

::: {.proof}
We apply [(2.10), (i)](#fga-3-vi-proposition-2.10).
:::

In particular, taking [(2.10), (iii)](#fga-3-vi-proposition-2.10) into account:

::: {.itenv #fga-3-vi-corollary-3.9 title="Corollary 3.9" latex="{Corollary 3.9}"}
Suppose that $S$ is of residual characteristics zero.
Then $\repPic_{X/S}^\tau$ is simple over $S$.
:::

::: {.rmenv #fga-3-vi-remark-3.10 title="Remark 3.10" latex="{Remark 3.10}"}
We thus deduce, for example, that if $\repPic_{X/S}$ is also *proper* over $S$, then the Néron--Severi torsion group of geometric fibres of $f$ is constant on every connected component of $S$ (which is also evident by transcendental methods when $f$ is simple and projective).
We note that the direct use of [(2.5)](#fga-3-vi-theorem-2.5) allows us to show, more generally, that, if $\repPic_{X/S}$ is proper over $S$ (for example, if $f\colon X\to S$ is simple and projective), and if $q$ is a prime number distinct from the residual characteristics of $S$, then the $q$-primary component of the Néron--Severi torsion groups of geometric fibres of $X/S$ is constant on every connected component of $S$.
It is no longer, however, the case in characteristic $p>0$ for the $p$-primary component of the torsion group.
However, it remains possible that the rank over the $k(s)$ of $\repPic_{X_s/k(s)}/\repPic_{X_s/k(s)}^{00}=T_{X_s/k(s)}$ is locally constant;
when $S$ is reduced, we  can show that this is equivalent to showing that $\repPic_{X/S}^{00}$ exists and that $\repPic_{X/S}$ is *flat* over $S$, and it suffices to test in the cases where $S$ is the spectrum of a discrete valuation ring.
This is what I have verified in the few examples that I have looked at;
but since the corresponding statement with $S$ Artinian is false (cf. Remarks [(2.9)](#fga-3-vi-remark-2.9) and [(3.4)](#fga-3-vi-remarks-3.4)), we must not get carried away.
:::


## The finiteness theorem for the Picard scheme {#fga-3-vi-section-4}

Let $f\colon X\to S$ be a projective and flat morphism such that $\repPic_{X/S}$ exists.
Then the "Hilbert polynomials" $Q\in\mathbb{Q}[t]$ allow us to decompose $\repPic_{X/S}$ into a sum of opens $\repPic_{X/S}^Q$.
If we do not make any further hypotheses, ensuring for example that $\repPic_{X/S}$ is separated over $S$, then it will not be true in general that these opens are of finite type over $S$;
we obtain a counterexample when $X$ is "a conic degenerating to two lines".
\oldpage{236-22}It is possible, however, that this is the case if $f$ is *separable* and has *irreducible geometric fibres*.
The question is linked to knowing if $\repPic_{X/S}^\tau$ is of finite type over $S$, which can be true without any hypotheses on the fibres of $X/S$.
When $f\colon X\to S$ is simple, we note that $\repPic_{X/S}^\tau$ is contained in one of the $\repPic_{X/S}^Q$ (thanks to the fact that, on a non-singular projective variety, "torsion" equivalence is finer than (in fact, "identical to", thanks to Matsusaka) numerical equivalence for divisors), and is thus of finite type over $S$ if the $\repPic_{X/S}^Q$ are.
Note that these finiteness questions that we have just highlighted still make sense even without supposing the existence of $\repPic_{X/S}$, since they can be expressed by saying that certain families of invertible modules are "limited", in the sense of [FGA 3.IV](FGA-3-IV.html):
Consider, for every algebraically closed field $k$, the integral subschemes of $\mathbb{P}_k^r$ of dimension $n$ and degree $d$, and the invertible modules on these preschemes that have a Hilbert polynomial $Q$ (where $r$, $n$, $d$, and $Q$ are given), and show that the family of these modules (considered as coherent modules on the $\mathbb{P}_k^r$) is *limited*, i.e. can be parametrised by a scheme of finite type over $\mathbb{Z}$.

Using the method of Matsusaka [@Mat1957], a rather technical proof (using the "equivalence criteria" in a suitable form) allow us to answer in the affirmative when we restrict to the non-singular subvarieties of $\mathbb{P}_k^r$.
More precisely, we obtain the following result:

::: {.itenv #fga-3-vi-theorem-4.1 title="Theorem 4.1" latex="{Theorem 4.1}"}
Let $f\colon X\to S$ be a simple projective morphism with connected geometric fibres, with $S$ Noetherian.
Let $\OO_X(1)$ be a very ample module on $X$ with respect to $S$, and $E$ a subset of $\repPic_{X/S}$ corresponding to a family $(\sh{L}_i)$ of invertible modules on the geometric fibres $\overline{X}_{s_i}$ of $X/S$, with $D_i$ a (not-necessarily positive) divisor on $\overline{X}_{s_i}$ that defines $\sh{L}_i$, and let $a_n^{(i)}t^n+\ldots+a_0^{(i)}$ be the Hilbert polynomial of $\sh{L}_i$, and let $\xi=\xi_i$ be a divisor that defines $\OO_X(1)$, i.e. a hyperplane section.

Then the following conditions are equivalent:

a. $Q$ is quasi-compact, i.e. contains an open of finite type over $S$, i.e.. the family $(\sh{L}_i)$ is limited.
b. $E$ is contained in the union of a finite number of the sets $\repPic_{X/S}^Q$, for $Q\in\mathbb{Q}[t]$, i.e. the set of Hilbert polynomials of the $\sh{L}_i$ is finite.
c. (If the fibres of $X/S$ are all of the same dimension $n$).^[*[Trans.]* Conditions (c) and (d) were originally called (b') and (b'').]
  The coefficients $a_{n-1}^{(i)}$ and $a_{n-2}^{(i)}$ of the Hilbert polynomials of the $\sh{L}_i$ are contained in a finite set.
d. (If the fibres of $X/S$ are all of the same dimension $n$).
  The integers $\xi^{n-1}D_i$ and $\xi^{n-2}D_i^2$ (the projective degrees of $D_i$ and of $D_i^2$) are bounded above.
:::

::: {.itenv #fga-3-vi-corollary-4.2 title="Corollary 4.2" latex="{Corollary 4.2}"}
Let $f\colon X\to S$ be a simple projective morphism, with connected geometric fibres.
Then the schemes $\repPic_{X/S}^Q$ (for $Q\in\mathbb{Q}[t]$) and $\repPic_{X/S}^\tau$ are projective over $S$.
:::

::: {.proof}
Since they are of finite type over $S$, by [(4.1)](#fga-3-vi-theorem-4.1), we can apply [(2.4)](#fga-3-vi-corollary-2.4).
:::

::: {.rmenv #fga-3-vi-remark-comp title="Remark" latex="{Remark}"}
*[Comp.]*
\oldpage{C-07}The questions of finiteness of the type highlighted in this section have been all but totally resolved since the editing of this present talk.
We note here the principal facts no known in this direction.
To simplify the statements, we implicitly assume that all the Picard preschemes that arise in the statements exist, even though an evident modification of these statements would allow us to get rid of any existence hypothesis.
In what follows, $S$ denotes a Noetherian scheme, and $X$ and $Y$ are proper schemes over $S$.

i. Let $f\colon X\to Y$ be a surjective morphism.
  Then $f^*\colon\repPic_{Y/S}\to\repPic_{X/S}$ is a morphism of finite type.

ii. \oldpage{C-08}Suppose that $Y$ is projective over $S$, endowed with an invertible module that is ample with respect to $S$, and let $X$ be the scheme of zeros of an arbitrary section of this module.
  Let $f\colon X\to Y$ be the canonical immersion.
  Finally, suppose that the irreducible components of the fibres of $Y/S$ are of dimension $\geqslant3$.
  Then $f^*\colon\repPic_{Y/S}\to\repPic_{X/S}$ is of finite type.

iii. Suppose that $X$ is projective over $S$, and that all its geometric fibres are integral and of dimension $n$.
  Let $\OO_X(1)$ be an ample invertible module on $X$, allowing us to define Hilbert polynomials.
  Let $M$ be a subset of $\repPic_{X/S}$.
  Then $M$ is quasi-compact if and only if, in the Hilbert polynomials $a_0x^n+a_1x^{n-1}+a_2x^{n-2}+\ldots+a_n$ of the elements of $M$, the coefficients $a_1$ and $a_2$ are bounded.

iv. For every integer $n\neq0$, the $n$-th power homomorphism in the group prescheme $\repPic_{X/S}$ is a morphism of finite type.

Note that (i) and (ii) also imply (under the hypotheses given in their respective statements) that *a subset $M$ of $\repPic_{Y/S}$ is quasi-compact if and only if its image in $\repPic_{X/S}$ is quasi-compact*.
We thus conclude that an invertible module $\sh{L}$ on $Y$ is $\tau$-equivalent to $0$ if and only if its inverse image in $X$ is;
in other words, $\repPic_{Y/S}^\tau$ is the inverse image of $\repPic_{X/S}^\tau$.
In particular, to show that the first prescheme is of finite type over $S$, it suffices to prove this for the second, since $\repPic_{Y/S}\to\repPic_{X/S}$ is of finite type.
Then using (i), Chow's lemma, and (iii), we find:

v. $\repPic_{X/S}^\tau$ is of finite type over $S$.

Generally, the conjunction of (i) for a finite morphism and (ii) allows us to reduce, for the majority of finiteness questions, to the case where $X/S$ has integral and normal geometric fibres of dimension $\leqslant2$;
often, even, applying (i) for a surjective but not-necessarily finite morphism, along with the resolution of singularities of algebraic surfaces (due, in arbitrary characteristic, to Abhyankar), we can reduce to the case where $X/S$ is even simple, and thus has non-singular geometric fibres of dimension $2$.
This allows us, for example, taking into account (v) and the Picard--Igusa inequality bounding the rank of the Néron--Severi group of a non-singular projective surface, to prove the following generalisation of the Néron finiteness theorem:

vi. Let $X/S$ be proper over $S$, but otherwise arbitrary.
  \oldpage{C-09}Then the Néron--Severi groups $\repPic_{X_i/k_i}/\repPic_{X_i/k_i}^0$ of the geometric fibres $X_i/k_i$ of $X/S$ are of finite type, and their rank and the order of their torsion subgroups are bounded.

The same method of reduction to the case of non-singular surfaces, and known theorems for this case (such as the Néron finiteness theorem, and the fact that the intersection form on the Néron--Severi group is non-degenerate) implies:

vii. Let $X$ be a proper scheme over an algebraically closed field.
  Then there exists a finite number of integral closed curves $C_i$ (for $1\leqslant i\leqslant r$) in $X$, such that the following property is satisfied:
  for every subset $M$ of $\repPic_{X/k}$, $M$ is quasi-compact if and only if the integers $\deg\sh{L}_{C'_i}$ (for $\sh{L}\in M$) are bounded (where $C'_i$ denotes the normalisation of $C_i$).

In the above we can take $r$ to be the rank of the Néron--Severi group.
Once we know that this group is of finite type, (vii) reduces to the fact that the linear forms on the Néron--Severi group defined by the curves $C$ in $X$ do not simultaneously vanish except for on the torsion elements of the Néron--Severi group.
In the case where $X$ is non-singular and projective, this result, as well as (v), was due to Matsusaka.
Using (vii), we easily obtain the following characterisation of invertible modules that are $\tau$-equivalent to $0$ on $X$:

viii. Let $X/k$ be a proper scheme over a field, and $\sh{L}$ an invertible module on $X$.
  Then the following conditions are equivalent:

  a. $\sh{L}$ is $\tau$-equivalent to $0$.
  b. For every coherent module $F$, we have $\chi(F\otimes\sh{L})=\chi(F)$, where $\chi$ denotes the Euler--Poincaré characteristic (or, condition (b'), we can simply take $F=\OO_Y$, where $Y$ is an integral closed subscheme of dimension $1$ in $X$).
  c. For every $Y$ as above, writing $Y'$ to mean the normalised curve, we have $\deg\sh{L}_{Y'}=0$.

  If $X/k$ is projective and endowed with an ample invertible module $\OO_X(1)$, then the above conditions are also equivalent to the following:

  d. For every integer $m$, $\sh{L}^{\otimes m}(1)$ is ample.
  e. (If $X$ is integral).
    For every pair of integers $(m,n)$, we have
    $$
      \chi(\sh{L}^{\otimes m}(n))
      = \chi(\OO(n))
    $$
    \oldpage{C-10}(i.e. (b) is true for $F=\sh{L}^{\otimes m}(n)$).

  For the sufficiency of this last condition, note that it implies that the Hilbert polynomials of the $\sh{L}^{\otimes m}$ are all equal, and thus, by the Mumford criterion (iii), the $\sh{L}^{\otimes m}$ remain in a quasi-compact subset of $\repPic_{X/k}$, i.e. we have (a).
  Conditions (b), (b'), and (c) should be considered as variants (for an arbitrary proper scheme) of the notion of *numerical equivalence*, usually defined for non-singular projective varieties.
  For such varieties, the equivalence of (a) and (c) was evidently well known (Matsusaka).

Criterion (e) from the above also implies the following result:

ix. Let $f\colon X\to S$ be a flat projective morphism whose geometric fibres are integral.
  Then $\repPic_{X/S}^\tau$ is open *and closed* in $\repPic_{X/S}$.

We restrict ourselves to some comments on the proofs of the key results (i), (ii), and (iii) (result (iv) is a little bit different from the others, and can be proven using only (i) for radicial surjective finite morphisms, or, more precisely, for a Frobenius morphism).
For (i), we use, in an essential way, the ideas of non-flat descent (see [FGA 3.I, p.9](#fga-3-i-section-A.2.c)).
One finds that (thinking only of finiteness results) the lack of effectivity criteria for descent data is inoffensive.
Mumford has recently proven a slightly weaker form of (iii), where the criterion makes use of *all* the coefficients of the Hilbert polynomial.
His argument is extremely simple, and is inspired by the proof of an amplitude criterion by Nakai (stated by the latter for non-singular surfaces, and generalised by Mumford to arbitrary projective morphisms).
It seems to me that this argument only works under a gentle additional restriction on the fibres of $X/S$ (Serre's ($\text{S}_2$) property), which is satisfied if the geometric fibres are normal.
We then use this restricted criterion in the proof of (ii): criterion (i) allows us to reduce to the case where $Y/S$ is flat with integral and normal geometric fibres, and applying the Mumford criterion we easily reduce to the case where $X/S$ satisfies the same conditions.
From the dimension hypothesis it then follows that the geometric fibres of $Y$ and of $X$ are of depth $\geqslant2$ at their closed points, which allows us to apply the "equivalence criteria" under the form that is given in [@Gro1960b, XII], and finishes the proof of (ii).
Once we have (i) and (ii), it is not difficult in the Mumford criterion to discard the hypothesis that the fibres be normal, and to prove it under the stronger form given in (iii).
\oldpage{C-11}We note finally that the proof of (i) and (ii) also shows that, in the case where $S$ is the spectrum of a field $k$, the morphism $\repPic_{Y/k}\to\repPic_{X/k}$ is *affine* (and not only of finite type).
:::
