## Relative Picard groups and functors {#fga-3-v-section-1}

\oldpage{232-01}
For every prescheme (more generally, every ringed space) $X$, we define the (*absolute*) *Picard group* of $X$, denoted by $\Pic(X)$, to be the group of isomorphism classes of invertible (i.e. locally isomorphic to $\OO_X$) modules on $X$.
We thus have a canonical isomorphism

::: {.eqenv #fga-3-v-equation-1.1 title="" latex=""}
$$
  \Pic(X)
  \simto \HH^1(X,\OO_X^\times)
\tag{1.1}
$$
:::

where $\OO_X^\times$ denotes the sheaf of units of $\OO_X$ (which can be identified with the sheaf of automorphisms of the invertible module $\OO_X$).
Note that $X\mapsto\Pic(X)$ is a contravariant functor in $X$ in the evident way, and that the isomorphism [(1.1)](#fga-3-v-equation-1.1) is functorial.

If $X$ is a prescheme over a prescheme $S$, then, for variable $S'$ in the category $\Sch_{/S}$ of preschemes over $S$, we have a contravariant functor $S'\mapsto\Pic(X\times_S S')$ thanks to the above.
This functor has no chance of being "representable" ([FGA 3.II, A](#fga-3-ii-section-A.1)) since, as a consequence of the existence of *non-trivial automorphisms* of invertible modules that we propose to classify, this functor is not of a *"local nature"* ([@Gro1960a, IV, 5.4]).
There is thus an opportunity to "make it local", by introducing, for every relative prescheme $X/S$, a group of a relative nature

::: {.eqenv #fga-3-v-equation-1.2 title="" latex=""}
$$
  \Pic'(X/S)
  = \HH^0(S,\RR^1f_*(\OO_X^\times))
\tag{1.2}
$$
:::

(where $f\colon X\to S$ is the structure morphism) (cf. [FGA 3.II, C.3](#fga-3-ii-section-C.3)).
In *loc. cit.* this group is called the relative Picard group, but it will be preferable to call it here the *restricted relative Picard group* of $X/S$, for reasons that will be made clear.
As $S'$ varies over $\Sch_{/S}$, $S'\mapsto\Pic'(X\times_S S'/S')$ is a contravariant functor in $S'$, denote also by $\shPic'_{X/S}$, thus given essentially by the formula

::: {.eqenv #fga-3-v-equation-1.3 title="" latex=""}
$$
  \shPic'_{X/S}(S')
  = \Pic(X\times_S S'/S').
\tag{1.3}
$$
:::

\oldpage{232-02}
This functor is now "of local nature", given that did what was necessary to make this happen.
Intuitively, the right-hand side of [(1.3)](#fga-3-v-equation-1.3) can be understood as the set of "algebraic families" of classes of invertible sheaves on (the fibres of) $X/S$, indexed by the parameter prescheme $S'/S$.
When the functor $\shPic'$ is representable, the prescheme over $S$ that represents it is denoted by $\repPic_{X/S}$, and is called the *Picard prescheme* of $X$ over $S$, and so we then have

::: {.eqenv #fga-3-v-equation-1.4 title="" latex=""}
$$
  \Hom_S(S',\repPic_{X/S})
  \cong \shPic'_{X/S}(S')
  = \Pic'(X\times_S S'/S').
\tag{1.4}
$$
:::

There are, however, important cases where $\shPic'_{X/S}$ is not representable (example: the "Brauer--Severi" variety over a field $k$, without a rational point over $k$), but where there nevertheless exists a natural definition of a relative Picard prescheme.
This is due to the fact that, in the definition of the functor $\shPic'$ from the absolute Picard groups $\Pic(X\times_S S'/S')$, we have not localised enough;
more precisely, $\shPic'$ is not in general "compatible with faithfully flat descent".
We now explain the details.

Let $(\sh{M})$ be the set of morphisms of preschemes that are *faithfully flat and quasi-compact*;
this set is stable under base change and composition.
Let $P$ be a contravariant functor from $\Sch_{/S}$ to the category of sets, and, for every $S$-morphism $u\colon T'\to T$ with $u\in(\sh{M})$, consider the diagram

::: {.eqenv #fga-3-v-equation-1.5 title="" latex=""}
$$
  P(T)
  \to P(T')
  \rightrightarrows P(T'\times_T T')
\tag{1.5}
$$
:::

which is given by $P$ applied to the diagram
$$
  T
  \from T'
  \underset{\pr_2}{\overset{\pr_1}{\leftleftarrows}} T'\times_T T'.
$$
If $P$ is representable, it follows from the theory of descent ([FGA 3.I, B, Theorem 2](#fga-3-i-section-B.1-theorem-2)) that the diagram [(1.5)](#fga-3-v-equation-1.5) is exact for all $u\in(\sh{M})$.
We express this fact by saying that $P$ is compatible with $(\sh{M})$, in the event that $P$ is "compatible with faithfully flat descent", or that the *"presheaf"* $P$ on $\Sch_{/S}$ is a *"sheaf"* for the notion of localisation given by the set $(\sh{M})$.
If $P$ is arbitrary, then a standard procedure, well known in the case of usual topological localisation, allows us to associate to it a "sheaf" $\sh{P}$ and a homomorphism of functors $P\to\sh{P}$ that is universal in an obvious sense.
The construction of $\sh{P}$ can be made explicit in the following way: to define $\sh{P}(T)$, we denote, for all $T'$ over $T$ such that the morphism $u\colon T'\to T$ is in $(\sh{M})$, by $\overline{\HH}^0(T'/T,P)$ the subset of $P(T')$ consisting of the elements $\xi$ such that their images $\xi_1,x_2$ in $P(T'\times_T T')$ are such that there exists a morphism $v\colon T''\to T'\times_T T'$ in $(\sh{M})$ such that $\xi_1$ and $\xi_2$ have the same image in $P(T'')$.

\oldpage{232-03}
(N.B. The set $\overline{\HH}^0$ thus defined is larger than the set $\HH^0(T'/T,P)$ introduced in [FGA 3.I, A.4.a](#fga-3-i-section-A.4.a)).
As $T'$ varies over fixed $T$ (always with $u\in(\sh{M})$), the $\overline{\HH}^0(T'/T,P)$ form an inductive system (when the set of the $T'$ is endowed with a preorder defined by domination), and we set

::: {.eqenv #fga-3-v-equation-1.6 title="" latex=""}
$$
  \sh{P}(T)
  = \varinjlim_{T'} \overline{\HH}^0(T'/T,P).
\tag{1.6}
$$
:::

The functoriality in $T$ of this expression is evident.

When
$$
  P(T)
  = \Pic(X\times_S T)
$$
the contravariant functor on $\Sch_{/S}$ defined by [(1.6)](#fga-3-v-equation-1.6) is called the *relative Picard functor* of $X$ over $S$, and denoted by $\shPic_{X/S}$, and we define the *relative Picard group* of $X$ over $S$, denoted by $\Pic(X/S)$, the group $\shPic_{X/S}(S)$.
We then have an evident bijection

::: {.eqenv #fga-3-v-equation-1.7 title="" latex=""}
$$
  \shPic_{X/S}(T)
  \simto \Pic(X\times_S T/T).
\tag{1.7}
$$
:::

An element of $\Pic(X/S)$ is thus defined by means of an element $\xi'$ of a group $\Pic(X\times_S S')$ (where $S'\to S$ is faithfully flat and quasi-compact) such that we can find a faithfully flat quasi-compact morphism $S''\to S'\times_S S'$ such that the two inverse images of $\xi'$ in $\Pic(X\times_S S'')$ are the same.
An element $\xi'$ of $\Pic(X\times_S S')$ and an element $\xi_1$ of $\Pic(X\times_S S_1)$ (satisfying the conditions that we have just stated) define the same element of $\Pic(X/S)$ if and only if there exists a faithfully flat quasi-compact morphism $S'_1\to S'\times_S S_1$ such that the images of the two elements in question in $\Pic(X\times_S S'_1)$ are equal.
It is often convenient to work instead with the functor $P'=\shPic'_{X/S}$ introduced above, and we immediately note that the canonical morphism $P\to P'$ defines an *isomorphism*

::: {.eqenv #fga-3-v-equation-1.8 title="" latex=""}
$$
  \sh{P}
  \simto \sh{P}'
\tag{1.8}
$$
:::

which gives a description of $\shPic_{X/S}$ in terms of $\shPic'_{X/S}=P'$ that is usually more convenient.
By [(2.3)](#fga-3-v-corollary-2.3) below, if we replace $P$ by $P'$ in the description of $\Pic(X/S)$ that we have just given then we can take $S''=S'\times_S S'$ and $S'_1=S'\times_S S_1$, at least under the conditions given in *loc. cit.*.
\oldpage{232-04}


If the functor $\shPic_{X/S}$ is representable, we say that $X/S$ admits a Picard prescheme, and the prescheme over $S$ that represents the functor is called the *Picard prescheme* of $X$ over $S$, and denoted by $\repPic_{X/S}$.
For this, it evidently suffices that $P'=\shPic_{X/S}$ be representable, since then $P'$ is already a "sheaf", and equation [(1.8)](#fga-3-v-equation-1.8) proves that the morphism $P'\to\sh{P}'$ can be identified with the canonical morphism

::: {.eqenv #fga-3-v-equation-1.9 title="" latex=""}
$$
  \shPic'_{X/S}
  \to \shPic_{X/S}
\tag{1.9}
$$
:::

which is then an isomorphism.
This means that our terminology is compatible with that introduced above with [(1.4)](#fga-3-v-equation-1.4).
In general, when $\repPic_{X/S}$ exists it is defined by the functorial isomorphism

::: {.eqenv #fga-3-v-equation-1.10 title="" latex=""}
$$
  \Hom_S(S',\repPic_{X/S})
  \simto \Pic(X\times_S S'/S').
\tag{1.10}
$$
:::


## Relations between the various relative and absolute Picard groups {#fga-3-v-section-2}

::: {.itenv #fga-3-v-proposition-2.1 title="Proposition 2.1" latex="{Proposition 2.1}"}
Let $f\colon X\to S$ be a morphism such that $\OO_S\simto f_*(\OO_X)$.
Then we have an exact sequence
$$
  0
  \to \Pic(S)
  \to \Pic(X)
  \to \Pic'(X/S).
$$
If $X$ admits a section over $S$, then the last morphism is surjective, i.e. we have an isomorphism
$$
  \Pic'(X/S)
  \simto \Pic(X)/\Pic(S).
$$
:::

::: {.proof}
The exact sequence can be considered as the low degrees of the exact sequence that corresponds to the Leray spectral sequence for $f$ and $\OO_X$.
The second claim is equally formal.
:::

::: {.itenv #fga-3-v-proposition-2.2 title="Proposition 2.2" latex="{Proposition 2.2}"}
Let $f\colon X\to S$ be a quasi-compact separated morphism such that $\OO_S\simto f_*(\OO_X)$, and let $S'\to S$ be a faithfully flat quasi-compact morphism.
Then

i. $\Pic'(X/S)\to\Pic'(X\times_S S'/S')$ is injective;
ii. If $X$ locally admits a section over $S$ (i.e. every $s\in S$ has an open neighbourhood $U$ such that $X|U$ has a section over $U$), then the diagram
  $$
    \Pic'(X/S)
    \to \Pic'(X\times_S S'/S')
    \rightrightarrows \Pic'(X\times_S S''/S'')
  $$
  (where $S''=S'\times_S S'$) is exact.
:::

::: {.proof}
The first claim follows, thanks to the elementary properties of faithfully flat descent, from the following general remark.
\oldpage{232-05}
If $f\colon X\to S$ is a morphism such that $\OO_S\simto f_*(\OO_X)$, then the functor $\sh{F}\mapsto f^*(\sh{F})$, from the category of locally free modules of finite type on $S$ to the category of locally free modules of finite type on $X$, is fully faithful, and its essential image is given by the modules $\sh{G}$ on $X$ such that $f_*(\sh{G})$ is locally free and such that the canonical homomorphism
$$
  f^*f_*(\sh{G})
  \to \sh{G}
$$
is an isomorphism.
The second statement was proven by the theory of descent in [FGA 3.I, B.4](#fga-3-i-section-B.4).
:::

The results of [(2.2)](#fga-3-v-proposition-2.2) can also be stated as follows:

::: {.itenv #fga-3-v-corollary-2.3 title="Corollary 2.3" latex="{Corollary 2.3}"}
Under the conditions of [(2.2)](#fga-3-v-proposition-2.2), the canonical homomorphism [(1.9)](#fga-3-v-equation-1.9) $\shPic'_{X/S}\to\shPic_{X/S}$ is injective, and even bijective if $X$ locally admits a section over $S$.
(In the latter case, the relative Picard group $\Pic(X/S)$ is identified with the restricted relative Picard group $\Pic'(X/S)$.)
:::

Combining this with [(2.1)](#fga-3-v-proposition-2.1), we thus obtain:

::: {.itenv #fga-3-v-corollary-2.4 title="Corollary 2.4" latex="{Corollary 2.4}"}
Under the conditions of  [(2.2)](#fga-3-v-proposition-2.2), we have an exact sequence
$$
  0
  \to \Pic(S)
  \to \Pic(X)
  \to \Pic(X/S).
$$
If $X$ admits a section over $S$, then the last homomorphism is surjective, i.e. we have an isomorphism
$$
  \Pic(X/S)
  \simto \Pic(X)/\Pic(S).
$$
:::

::: {.rmenv #fga-3-v-remark-2.5 title="Remark 2.5" latex="{Remark 2.5}"}
Let $f\colon X\to S$ be a morphism such that $\OO_S\simto f_*(\OO_X)$, and let $g$ be a section of $X$ over $S$.
Let $\sh{L}$ be an invertible module on $X$.
We define the *$g$-rigidification* of $\sh{L}$ to be an isomorphism $\OO_S\simto g^*(\sh{L})$, and a *$g$-rigidified invertible module* to be an invertible module $\sh{L}$ on $X$ endowed with a $g$-rigidification.
Every automorphism of such a structure is trivial, and $\Pic'(X/S)$ can be identified with the set of isomorphism classes of $g$-rigidified invertible modules on $S$.
(It is this fact that allows us to use the theory of descent to prove [(2.2), (ii)](#fga-3-v-proposition-2.2).)
This gives a new interpretation of $\Pic(X/S)$, at least when $f$ is further quasi-compact and separated, so that $\Pic(X/S)\simto\Pic'(X/S)$ by [(2.3)](#fga-3-v-corollary-2.3).
:::

::: {.rmenv #fga-3-v-remark-2.6 title="Remark 2.6" latex="{Remark 2.6}"}
Let $f\colon X\to S$ be a morphism as in [(2.2)](#fga-3-v-proposition-2.2), and let $S'\to S$ be a faithfully flat quasi-compact morphism such that there exists an $S$-morphism $S'\to X$, i.e. such that there exists a section of $X'=X\times_S S'$ over $S'$.
\oldpage{232-06}
Let $S''=S'\times_S S'$, and $X''=X\times_S S''$, and consider the exact sequence
$$
  \Pic(X/S)
  \to \Pic(X'/S')
  \rightrightarrows \Pic(X''/S'').
$$
Applying [(2.4)](#fga-3-v-corollary-2.4), we obtain the exact sequence
$$
  \Pic(X/S)
  \to \Pic(X')/\Pic(S')
  \rightrightarrows \Pic(X'')/\Pic(S'').
$$
In particular, every element of the relative Picard group already "comes from" an element of $\Pic(X')$.
This gives a substantial simplification of the description of the relative Picard group given in the previous section, and even of the Picard functor of $X$ over $S$, since, for all $T$ over $S$, we can apply the above to $X\times_S T/T$ and to the morphism $T'=S'\times_S T\to T$.
If, for example, $f$ itself is faithfully flat, then we can take $S'=X$, which allows us, whenever $f$ is further of finite type (resp. simple, etc.), to restrict, in the description of the relative Picard functor $T\mapsto\Pic(X\times_S T/T)$, to the base changes $T'\to T$ that are of finite type (resp. simple, etc.).
If $f$ is projective and flat, and $S$ locally Noetherian, then we can prove that we can take in the above a $S'\to S$ such that $S'$ is the direct sum of *flat covers* $S'_i$ of opens $S_i$ of $S$ that cover $S$;
if $f$ is further separable, then we can take $S'_i$ to be étale over $S_i$.
:::


## The principal existence theorem: statement {#fga-3-v-section-3}

We do not have, not even conjecturally, an existence statement for Picard preschemes that encompasses all known cases.
A "practically necessary" condition, if we can say that, is that $f\colon X\to S$ be *proper* (ensuring essential finiteness properties) and *flat*.
These conditions are not sufficient, even if $S$ is the spectrum of the algebra of dual numbers $k[t]/(t^2)$ over a field $k$ (say, the field $\mathbb{C}$ of complex numbers), and $X$ is of dimension $1$.
At the moment of writing this present talk, the most important existence theorems for the Picard prescheme follow from the following theorem:

::: {.itenv #fga-3-v-theorem-3.1 title="Theorem 3.1" latex="{Theorem 3.1}"}
Let $f\colon X\to S$ be a morphism of locally Noetherian preschemes.
\oldpage{232-07}
Suppose that

i. $f$ is projective
ii. $f$ is flat
iii. the geometric fibres of $f$ are integral.

Under these conditions, $\repPic_{X/S}$ exists.
:::

The proof, which will be sketched in the following two sections, will at the same time show the following:
Let $\xi$ be the section of $\repPic_{X/S}$ that corresponds to a very ample sheaf $\OO_X(1)$ over $X/S$ (i.e. induced by a projective embedding $X\to\mathbb{P}(\sh{E})$);
then there exists an open subset $U$ of $\repPic_{X/S}$, disjoint union of quasi-projective open subsets of $S$, such that $U$ is stable under translation by $\xi$, and such that $\repPic_{X/S}$ is the increasing union of opens $U\setminus n\xi$ (each isomorphic to $U$).
It thus follows, in particular, that, under the conditions of [(3.1)](#fga-3-v-theorem-3.1), that $\repPic_{X/S}$ is *separated* over $S$.

::: {.rmenv #remark-3.2 title="Remark 3.2" latex="{Remark 3.2}"}
We see from examples (with $S$ the spectrum of a discrete valuation ring, and $X$ of relative dimension $1$ over $S$, for example), that if we omit hypothesis (iii) in [(3.1)](#fga-3-v-theorem-3.1) and replace it with the weaker hypothesis that, for all $s\in S$, the homomorphism $k(s)\to\HH^0(X_s,\OO_{X_s})$ be an isomorphism, then $\repPic_{X/S}$ is not necessarily separated over $S$;
both in the case where the geometric fibres of $f$ are reduced, but where a generic integral geometric fibre "blows up" by specialisation into two irreducible components, and in the case where the geometric fibres of $f$ are irreducible, but where a generic integral geometric fibre specialises to a "multiple fibre".
The first case happens, for example, with a conic that degenerates into two concurrent lines; an example of the second was shown to me by D. Mumford, with an elliptic curve that degenerates to a double elliptic curve.
These examples work in any characteristic.
:::

::: {.rmenv #fga-3-v-remark-3.3 title="Remark 3.3" latex="{Remark 3.3}"}
Under the conditions of [(3.1)](#fga-3-v-theorem-3.1), I do not know if $\repPic_{X/S}$ is a disjoint union of opens that are of finite type, thus quasi-projective, over $S$.
We note that the study of the Hilbert polynomials $Q\in\mathbb{Q}[t]$ allows us, as in the case of Hilbert schemes ([FGA 3.IV](FGA-3-IV.html)), to give a decomposition of $\repPic_{X/S}$ as a disjoint sum of opens $\repPic_{X/S}^Q$, and it seems plausible that these opens are quasi-projective over $S$;
this is what we will see at least in the next talk when $f$ is a simple morphism.
We draw attention to the fact that if we replace hypothesis (i) by the hypothesis "$X$ is *locally* projective over $S$" (which is sufficient to prove [(3.1)](#fga-3-v-theorem-3.1), since the question of existence of $\repPic_{X/S}$ is clearly local on $S$) however, then it is easy to give examples where *$\repPic_{X/S}$ contains connected components that are not of finite type over $S$*.
\oldpage{232-08}
For example, let $X_0$ be a non-singular projective algebraic variety over an algebraically closed field $k$, endowed with an automorphism $u$ and an element $\xi$ of the Néron--Severi group of $X_0$ such that the $u^n(\xi)$ are pairwise distinct.
We can, for example, take $X_0$ to be the product of an elliptic curve $E$ with itself, and $u$ to be the automorphism $(x,y)\mapsto(x,y+x)$ of $E\times E$.
Let $S$ be the union of two non-singular irreducible curves that meet at two points $a$ and $b$.
There is a connected principal covering $P$ on $S$ of the group $\mathbb{Z}$, and using the action of $\mathbb{Z}$ on $X_0$ defined by $u$ we thus obtain an associated bundle on $S$, with fibre $X_0$ (trivial on $S\setminus\{a\}$ and $S\setminus\{b\}$), which is in fact an *abelian* scheme over $S$ in the particular case in question.
We easily see that $\repPic_{X/S}$, which is also the bundle associated to $P$ and to the action of $\mathbb{Z}$ on $\repPic_{X_0/k}$ via $u$, contains a connected component that is isomorphic to $P\times\repPic_{X_0/k}^0$ (where $\repPic^0$ denotes the connected component of the identity element in $\repPic$), which is not of finite type over $S$.
(One can equally produce analogous phenomena in various cases of non-separated Picard preschemes over $S$, as described in [(3.3)](#fga-3-v-remark-3.3)).

*[Comp.]*
The question raised here has been answered in the positive by Mumford (see the next talk).
:::


## Relative Cartier divisors and projective bundles {#fga-3-v-section-4}

We will only need to use positive divisors, and we omit the qualification of "positive" in the rest of this section.

Let $X$ be a prescheme.
A *Cartier divisor*, or simply divisor, on $X$ is a closed subprescheme $D$ of $X$ defined by an ideal $\sh{J}$ that is an *invertible* module, i.e. locally generated by a section that is a *non-zero divisor* of $\OO_X$.
To $D$ we associate the invertible module
$$
  \sh{L}(D)
  = \sh{J}^{-1}
$$
and the canonical injection $\sh{J}\to\OO_X$ gives a canonical homomorphism
$$
  s_D\colon \OO_X
  \to \sh{J}^{-1}
  = \sh{L}(D)
$$
i.e. $s_D\in\Gamma(X,\sh{L}(D))$.
The data of a divisor is essentially *equivalent* to the data of an invertible module $\sh{L}$ on $X$ endowed with a section $s$ that is nowhere a zero divisor, by associating to such a pair $(\sh{L},s)$ the "divisor" of $s$, denoted by $\div(s)$.
\oldpage{232-09}
For a given invertible $\sh{L}$ on $X$, the set of divisors $D$ that define $\sh{L}$ is in bijective correspondence with the quotient set $\Gamma(X,\sh{L})^\times/\Gamma(X,\OO_X^\times)$, where $\Gamma(X,\sh{L})^\times$ denotes the subset of $\Gamma(X,\sh{L})$ consisting of sections that are nowhere zero divisors.

Now suppose that we have a morphism $f\colon X\to S$ that is locally of finite type, and suppose, for simplicity, that $S$ is locally Noetherian.
Let $\sh{J}$ be a coherent ideal on $X$, with $D$ the subscheme of $X$ that it defines, and let $x\in X$ and $s=f(x)$.
We will show that the following conditions are equivalent:

i. $\sh{J}$ is invertible at $x$ (i.e. $\sh{J}_x$ is generated by a regular element of $\OO_{X,x}$) and $D$ is flat over $S$ at $x$.
ii. $X$ and $D$ are flat over $S$ at $x$, and $D_s$ is a Cartier divisor on the fibre $X_s$ at the point $x$.
iii. $X$ is flat over $S$ at $x$, and $\sh{J}_x$ is generated by an element $f_x$ that induces on $X_s$ a non-zero divisor germ.

We then say that $D$ is a *relative Cartier divisor* or simply a relative divisor, on $X/S$ at the point in question.
We note that, in (i), $D$ is also a relative divisor at points in a neighbourhood of $x$, so if $X$ and $D$ are flat over $S$, with $D$ proper over $S$, then the set of $s\in S$ such that $D_s$ is a Cartier divisor in $X_s$ (i.e. such that $D$ is a relative Cartier divisor at the points of $X_s$) is an open subset of $S$.
We have also done what is necessary in the definition above in order to ensure that the notion of relative Cartier divisor be stable under arbitrary base change $S'\to S$.
So consider the set $\Div(X/S)$ of relative divisors on $X/S$, and then the contravariant functor in $S'$ (that varies over $S$) defined by
$$
  \shDiv_{X/S}(S')
  = \Div(X\times_S S'/S').
$$
Suppose that $X$ is flat and proper over $S$.
Then by the characterisation (ii) of relative Cartier divisors, $\shDiv_{X/S}$ can be considered as a sub-functor of the functor $\shHilb_{X/S}$ defined in [FGA 3.IV](FGA-3-IV.html), and the inclusion morphism
$$
  \shDiv_{X/S}
  \to \shHilb_{X/S}
$$
is "representable by open immersions" (cf. [@Gro1960a, IV, 3.13]) by the above remarks.
Using the principal existence theorem of [FGA 3.IV](FGA-3-IV.html), we find:

::: {.itenv #fga-3-v-proposition-4.1 title="Proposition 4.1" latex="{Proposition 4.1}"}
Suppose that $f\colon X\to S$ is projective and flat.
\oldpage{232-10}
Then the functor $\shDiv_{X/S}$ is representable, and, more precisely, is represented by an open of $\repHilb_{X/S}$.
:::

For a given very ample sheaf $\OO_X(1)$ over $X/S$, using the canonical decomposition of $\repHilb_{X/S}$ into a sum of opens $\repHilb_{X/S}^Q$ corresponding to Hilbert polynomials $Q\in\mathbb{Q}[t]$, we obtain an analogous decomposition
$$
  \repDiv_{X/S}
  = \sqcup_{Q\in\mathbb{Q}[t]} \repDiv_{X/S}^Q
$$
into a sum of disjoint opens that are *quasi-projective* over $S$.

Using the map $D\mapsto\sh{L}(D)$, we obtain a functorial homomorphism
$$
  \shDiv_{X/S}
  \to \shPic_{X/S}
\tag{+}
$$
that we propose to study;
it appears to be relatively representable ([@Gro1960a, IV, 3]) under rather general conditions.
We thus start with an element $\xi$ of $\shPic_{X/S}(S')$, supposing, to simplify notation, that $S'=S$;
we will show that the corresponding sub-functor of $\shDiv_{X/S}$ is representable.
Consider first of all the case where $\xi$ is defined by an invertible module $\sh{L}$ on $X$.
Suppose that $X$ is proper and flat over $S$, and that the geometric fibres of $X$ over $S$ are integral, which also implies ([@GD1960, III, 7]) that $\OO_S\simto f_*(\OO_X)$, and that this remains true after any base change $S'\to S$.
Then the relative Cartier divisors $D$ on $X/S$ such that $\sh{L}(D)$ and $\sh{L}$ define the same element of $\Pic(X/S)=\shPic_{X/S}(S)$, i.e. by [(2.4)](#fga-3-v-corollary-2.4) such that $\sh{L}(D)$ and $\sh{L}$ are locally isomorphic over $S$, are in bijective correspondence with the sections of the quotient sheaf $f_*(\sh{L})^\times/\sh{O}_S^\times$.
This correspondence is compatible with base change.
General arguments of "Künneth" type from *loc. cit.*^[*[Trans.]* The original also cites here a seminar on algebraic geometry at Harvard University by Mumford and Tate in the spring of 1962, but the notes from this were never completed and so there is no real existing citation. This citation appears again throughout both this present talk and the next.] show that the property of $X/S$ and the flatness of $\sh{L}$ over $S$ imply the existence of a coherent module $\sh{Q}$ on $S$, defined up to unique isomorphism, and an isomorphism of sheaves
$$
  f_*(\sh{L})
  \simto \shHom_{\OO_X}(\sh{Q},\OO_S)
$$
and the formation of $\sh{Q}$ is furthermore compatible with base change.
Here $f_*(\sh{L})^\times$ denotes the subsheaf of sets of $f_*(\sh{L})$ whose sections over $U$ are the sections of $\sh{L}$ over $f^{-1}(U)$ that define relative Cartier divisors on $f^{-1}(U)/U$, i.e. that induces sections that are non-zero divisors on the $X_s$ (for $s\in U$).
\oldpage{232-11}
Using the hypothesis that the fibres $X_s$ are integral, this simply implies that the induced sections on the fibres $X_s$ are not identically zero, or, in terms of local homomorphisms $\sh{Q}\to\OO_S$, that these homomorphisms are surjective (Nakayama).
This shows that the set of sections of $f_*(\sh{L})^\times/\OO_S^\times$ is in bijective correspondence with the set of *invertible quotient modules of $\sh{Q}$*, or, by the definition of the projective bundle $\mathbb{P}(\sh{Q})$ associated to the coherent module $\sh{Q}$ (cf. [@Gro1960a, V, 2]), with the set of sections of $\mathbb{P}(\sh{Q})$ over $S$.
This description is compatible with taking inverse images, and we thus obtain the theorem below.

::: {.itenv #fga-3-v-theorem-4.3 title="Theorem 4.3" latex="{Theorem 4.3}"}
Let $f\colon X\to S$ be a flat proper morphism with integral geometric fibres, with $S$ locally Noetherian, and let $\sh{L}$ be an invertible module on $X$.
For every $S'$ over $S$, let $T(S')$ be the set of relative divisors $D$ on $X\times_S S'/S'$ such that $\sh{L}(D)$ is locally isomorphic to $\sh{L}\otimes_{\OO_S}\OO_{S'}$ over $S'$ (i.e. such that $\sh{L}(D)$ and $\sh{L}\otimes_{\OO_S}\OO_{S'}$) define the same element of $\Pic(X\times_S S'/S')$.
Then there exists a coherent module $\sh{Q}$ on $S$, determined up to unique isomorphism, such that the functor $T$ is represented by the projective bundle $\mathbb{P}(\sh{Q})$.
:::

::: {.itenv #fga-3-v-corollary-4.4 title="Corollary 4.4" latex="{Corollary 4.4}"}
If we suppose that $f$ is projective, then the functorial homomorphism $\shDiv_{X/S}\to\shPic_{X/S}$ is representable by projective morphisms.
:::

If $X$ admits a section (resp. locally admits a section) over $S$, then the above homomorphism is representable by projective bundles (resp. by local projective bundles) thanks to [(4.3)](#fga-3-v-theorem-4.3) and [(2.1)](#fga-3-v-proposition-2.1).
In the case where $f$ is quasi-projective, we can easily reduce to the previous case by a descent method, using the finite flat local quasi-sections of $X$ over $S$.

::: {.rmenv #fga-3-v-remark-4.5 title="Remark 4.5" latex="{Remark 4.5}"}
Under the conditions of [(4.3)](#fga-3-v-theorem-4.3), the module $\sh{Q}$ on $S$ is not in general locally free, as we can see by the fact that the dimension of the reduced fibres of $\sh{Q}$, i.e. those of $\HH^0(X_s,\sh{L}_s)$ for varying $s\in S$, can *jump*.
Given a coherent module $\sh{Q}$ on the locally Noetherian prescheme $S$, we can easily show that, for any given $s\in S$, $\sh{Q}$ is free at $s$ if and only if $\mathbb{P}(\sh{Q})$ is flat over $S$ at the points over $s$ (in which case it is even simple over $S$ at the points over $s$);
when this happens, with $\sh{Q}$ defined in terms of $\sh{L}$ as above, this also implies that forming the direct image $f_*(\sh{L})$ *"commutes with base change on a neighbourhood of $s$"*, or that $f_*(\sh{L})_s\to\HH^0(X_s,\sh{L}_s)$ is surjective.
\oldpage{232-12}
This will be the case if, for example, $\HH^1(X_s,\sh{L}_s)=0$.
Subject to the existence of the preschemes in question, these criteria apply in particular to the universal situation $\repDiv_{X/S}\to\repPic_{X/S}$, and give a necessary and sufficient condition (resp. sufficient) for this morphism to be simple at a given point of $\repDiv_{X/S}$.
:::


## Proof of the principal existence theorem {#fga-3-v-section-5}

Under the conditions of [(3.1)](#fga-3-v-theorem-3.1), choose some module $\OO_X(1)$ that is very ample over $X/S$, and let $\xi$ be the corresponding element of $\Pic(X/S)$.
For brevity, let $\sh{P}(S')=\Pic(X\times_S S'/S')$, and suppose, for simplicity, that $X/S$ admits a section.
Let $\sh{P}^+(S')$ be the subset of $\sh{P}(S')$ consisting of classes of the $\sh{L}$ that are invertible on $X\times_S S'$ such that
$$
  \begin{aligned}
    \RR^i f'_*(\sh{L}(n)) &= 0
    \qquad\text{for }i>0\text{ and all }n\geqslant0
  \\f'_*(\sh{L}(n)) &\neq0
    \qquad\text{for all }n\geqslant0.
  \end{aligned}
$$
These conditions are stable under base change, and thus define a subfunctor $\sh{P}^+$ of $\sh{P}$ that is evidently stable under translation by $\xi$.
Using Serre's "Theorems A and B" ([@GD1960, III, 2]) and generalities ([@Gro1960a, IV, 5]), we easily see that $\sh{P}$ is representable if and only if $\sh{P}^+$ is, and so $\sh{P}^+$ will be representable by an open $U$ of the prescheme $\repPic_{X/S}$ that represents $\sh{P}$, and the latter will be an increasing union of opens $U\setminus n\xi$.

For brevity, let $\sh{D}=\shDiv_{X/S}$, and let $\sh{D}^+$ be the inverse image of $\sh{P}^+$ under the canonical morphism $\sh{D}\to\sh{P}$.
So we have a morphism
$$
  \sh{D}^+
  \to \sh{P}^+
\tag{+}
$$
and we already know that $\sh{D}^+$ is representable by an open $D^+$ of the prescheme $D=\repDiv_{X/S}$ (and, more precisely, by *projective bundles associated to locally free modules* that are everywhere non-zero);
this is due to the fact that, if $\sh{L}$ on $X\times_S S'$ is, as at the start of this section, then $f'_*(\sh{L})$ is a *locally free* non-zero module, whose formation commutes with base change;
with the notation of [(4.3)](#fga-3-v-theorem-4.3), $\sh{Q}$ is then isomorphic to the dual of $f'_*(\sh{L})$.
Using the general criterion ([@Gro1960a, IV, 4.7]), we can thus conclude that $P^+$ is representable.
In *loc. cit.*, we take $\mathcal{S}$ to be the set of faithfully flat quasi-compact morphisms of preschemes (which are indeed effective epimorphisms, by [FGA 3.I, B](#fga-3-i-section-B.1)).
\oldpage{232-13}
Condition (a) of *loc. cit.*, namely that $(+)$ is representable by morphisms that are elements of $\mathcal{S}$, is satisfied as we have just seen;
condition (b) says that the functor $\sh{P}^+$ is is compatible with faithfully flat quasi-compact descent, which is immediate.
It remains only to prove condition (c) of *loc. cit.*, namely that the equivalence $R$ in the prescheme $D^+$ induced by the $\mathcal{S}$-representable morphism ($+$) is $\mathcal{S}$-effective, i.e. is effective and such that $D^+\to D^+/R$ is in $\mathcal{S}$.
For this, note first of all that the opens ${D^+}^Q$ of $D^+$ that correspond to the virtual Hilbert polynomials $Q\in\mathbb{Q}[t]$ are stable under $R$ (since the fibres of $R$ are connected), which reduces the problem to proving that, for all $Q$, the induced equivalence relation $R^Q$ on ${D^+}^Q$ is $\mathcal{S}$-effective.
But now ${D^+}^Q$ is quasi-projective, and the equivalence relation $R^Q$ is projective and flat.
We are thus under the hypothesis of [FGA 3.III, Theorem 6.1](#fga-3-iii-theorem-6.1), which implies the desired result.

In the general case where $X/S$ does not necessarily admit a section, we can easily reduce to the above case by the technique of descent, where we can repeat the above proof with the modification that is imposed upon the definition of $\sh{P}^+$.

::: {.rmenv #fga-3-v-remarks-5.1 title="Remarks 5.1" latex="{Remarks 5.1}"}
The method that we followed is essentially that of Matsusaka for the projective construction of Picard varieties.
The result that we invoke from [FGA 3.III](FGA-3-III.html) that allows us to pass to the effective quotient can also easily be deduced from the existence theorem for Hilbert schemes (cf. for example [Mumford--Tate seminar, 1962]).
(Classically, these quotients are constructed by using Chow coordinates).
Note that the formation of the open $\repPic_{X/S}^+$ of $\repPic_{X/S}$ and its decomposition into opens ${\repPic_{X/S}^+}^Q$ that are quasi-projcetive over $S$ following the Hilbert polynomials for the *divisors* that define the invertible modules in question, is compatible with base change (which allows us to apply the technique of descent).
:::

::: {.rmenv #fga-3-v-remarks-5.2 title="Remarks 5.2" latex="{Remarks 5.2}"}
It is not out of the question that $\repPic_{X/S}$ exists whenever $f\colon X\to S$ is proper and flat and such that the homomorphisms $k(s)\to\HH^0(X_s,\OO_{X_s})$ (for $s\in S$) are isomorphisms (this latter condition also then implying that $\OO_S\simto f_*(\OO_X)$, and that this remains true after any base change $S'\to S$).
This at least is what we can prove in the setting of analytic spaces, if $f$ is further assumed to be projective, by a differential method (that of Chow, if I am not mistaken) explained in [@Gro1960a, IX, 3.1].
\oldpage{232-14}
In this method, the passage to the quotient by a *proper* and flat equivalence relation in an open of the scheme of divisors is replaced by the passage to the quotient by the projective group in the scheme of immersions of $X$ into $\mathbb{P}_S^r$.
This method can probably be adapted to the case of schemes, using the results of Mumford on the passage to the quotient by the projective group [@Mum1961];
for now, there is no written proof, except when $X$ has "lots of local sections" over $S$, for example if $X$ is separable over a complete local ring with algebraically closed residue field.
In principle, the method in question is of more general scope, since it also gives the existence of Picard preschemes in the case where these are not separated, and where the first method thus necessarily fails.
(Technically, the difficulty comes from the fact that, when the geometric fibres of $f$ are not integral, then the functor envisaged in [(4.3)](#fga-3-v-theorem-4.3) is no longer representable by the projective bundle $\mathbb{P}(\sh{Q})$ itself, but by an *open* of this, which leads to the delicate question of the passage to the quotient by an equivalence relation that is flat but not proper).

*[Comp.]*
As I point out at the start of the next talk, the existence conjecture suggested here is false, but Mumford has proven a slightly weaker theorem using his methods.
:::

::: {.rmenv #fga-3-v-remark-5.3 title="Remark 5.3" latex="{Remark 5.3}"}
Note that the proof given here uses neither the preliminary construction of Jacobians of curves or families of curves nor the theory of abelian varieties or abelian schemes, and in this way it essentially distinguishes itself from traditional treatments, such as those in the book by Lang [@Lan1959] or the article by Chevalley [@Che1960], which follow the path sketched by Weil.
Even in the case of Jacobians of non-singular curves over an algebraically closed field (the complex numbers, say), the construction given here for the Jacobian is the only one known that comes with the very strong properties that we took as definition in [§1](#fga-3-v-section-1) (essentially those of Chevalley, but taking into account the "variety of parameters" with nilpotent elements).
The fact that the construction of Picard schemes should precede, not follow, the theory of abelian varieties is clear a priori, by the fact that, in general, Picard schemes are not, nor do they reduce to, abelian schemes, as we already see in the case of singular curves over an algebraically closed field, where we find the "generalised Jacobians" of Rosenlicht, which are not abelian varieties.
Furthermore, the theory of abelian varieties, and more generally of abelian schemes, becomes much simpler once we have a theory of Picard schemes in general.
In particular, the theory of duality for abelian schemes, and notably the results of Cartier type, then become slightly more formal (cf. for example [Mumford--Tate seminar, 1962]).
:::

::: {.rmenv #fga-3-v-remarks-5.4 title="Remarks 5.4" latex="{Remarks 5.4}"}
\oldpage{232-15}

The "compatibility principle" of Igusa for the Jacobian of a curve degenerating to a singular curve can only be well understood as an existence theorem of the Picard scheme of a relative scheme in curves $X/S$ that are not necessarily simple over $S$.
This is thus a particular case of the principal existence theorem [(3.1)](#fga-3-v-theorem-3.1) when the specialised curve is integral (i.e. in classical terms, irreducible of multiplicity $1$).
We note that, for now, the case of a reducible special curve (even when the components are of multiplicity $1$, i.e. when the special curve is separable over the residue field) is not covered by the known existence theorems, except for in the case where we are over a *complete* discrete valuation ring with algebraically closed residue field, cf. [(5.2)](#fga-3-v-remarks-5.2).
This question of existence certainly arises in a geometric construction, in the theory of schemes, of Baily--Satake "compactifications" of modular schemes of curves of genus $g$.
(This compactification is known for now only for $g=1$, thanks to work of Igusa).
:::


## Relative existence theorems {#fga-3-v-section-6}

We will sketch here some useful cases where the existence of certain Picard schemes implies the existence of certain others, which allows us to deduce from the principal existence theorem [(3.1)](#fga-3-v-theorem-3.1) various other existence theorems.

::: {.itenv #fga-3-v-proposition-6.1 title="Proposition 6.1" latex="{Proposition 6.1}"}
Let $f\colon X\to S$ be a flat projective morphism such that, in the Stein factorisation $f=f''f'$, the morphism $f'\colon X\to S'$ is *flat* and has integral geometric fibres (and thus satisfies the hypotheses of [(3.1)](#fga-3-v-theorem-3.1)), and such that the finite morphism $f''\colon S'\to$ is flat.
Then $\repPic_{X/S}$ exists and (with the notation introduced in [FGA 3.II, C.2](#fga-3-ii-section-C.2)) we have a canonical isomorphism
$$
  \repPic_{X/S}
  \simto \prod_{S'/S} \repPic_{X/S'}.
$$
:::

::: {.proof}
To prove this, we first establish an isomorphism of functors
$$
  \shPic_{X/S}
  \simto \prod_{S'/S} \shPic_{X/S'}
$$
and then use [(3.1)](#fga-3-v-theorem-3.1), which implies that $\shPic_{X/S'}$ is representable;
we use the structure explained in [§3](#fga-3-v-section-3) of $\repPic_{X/S'}$ (which implies that every finite subset of a fibre of $\repPic_{X/S'}$ over $S$ is contained in an affine open) for the existence of $\prod_{S'/S}\repPic_{X/S'}$.
:::

\oldpage{232-16}

For example, if $X$ is a scheme given by a *sum* of schemes $X_i$ over $S$ that satisfy the conditions of [(3.1)](#fga-3-v-theorem-3.1), then the statement of [(6.1)](#fga-3-v-proposition-6.1) reduces to the trivial statement
$$
  \repPic_{X/S}
  \simto \prod_i \repPic_{X_i/S}.
$$

::: {.itenv #fga-3-v-corollary-6.2 title="Corollary 6.2" latex="{Corollary 6.2}"}
Let $f\colon X\to S$ be a projective flat morphism with locally integral geometric fibres (for example, a projective and normal morphism).
Then $\repPic_{X/S}$ exists.
:::

::: {.proof}
In this case, $S'$ is an étale covering of $S$ (which is true once $f$ is separable, i.e. flat with reduced geometric fibres), and we see that the structure theorem stated in [§3](#fga-3-v-section-3) for $\repPic_{X/S}$ still holds, thanks to the analogous structure of $\repPic_{X/S'}$.
:::

Applying a descent procedure gives a relative existence theorem, whose scope depends on the solution to questions about non-flat descent that were raised in [FGA 3.I, §A.2.c](#fga-3-i-section-A.2.c), and of which we content ourselves here to explain only a particular case:

::: {.itenv #fga-3-v-proposition-6.3 title="Proposition 6.3" latex="{Proposition 6.3}"}
Let $f\colon X\to S$ be a proper morphism, and let $X_1$ and $X_2$ be subpreschemes of $X$ that are flat over $S$, defined by coherent ideals $\sh{J}_1$ and $\sh{J}_2$ (respectively) such that $\sh{J}_1\cap\sh{J}_2=(0)$ and such that $\OO_X/(\sh{J}_1+\sh{J}_2)$ is flat over $S$ (i.e. the subprescheme of $X$ that is the sup of $X_1$ and $X_2$ is $X$ itself, whereas their inf $Z$ is flat over $X$).
Suppose further that, for all $s\in S$, the homomorphisms $k(s)\to\HH^0(X_{i_s},\OO_{X_{i_s}})$ are bijective for $i=1,2$.
Then the natural homomorphism of functors
$$
  \shPic_{X/S}
  \to \shPic_{X_1/S} \times \shPic_{X_2/S}
$$
is representable by affine morphisms, so if $\repPic_{X_1/S}$ and $\repPic_{X_2/s}$ exist, then so too does $\repPic_{X/S}$, and the canonical morphism
$$
  \repPic_{X/S}
  \to \repPic_{X_1/S} \times \repPic_{X_2/S}
$$
is affine.
:::

::: {.proof}
By faithfully flat descent, we can reduce to the case where $Z$ admits a section over $S$, thus defining sections of $X$, $X_1$, and $X_2$ over $S$, and allowing us to eliminate the automorphisms in the structures in question, as explained in [(2.5)](#fga-3-v-remark-2.5).
\oldpage{232-17}
The proof then consists of noting that the data of a "rigidified" invertible module $\sh{L}$ on $X$ is equivalent to the data of a triple $(\sh{L}_1,\sh{L}_2,u)$, where $\sh{L}_i$ is a "rigidified" module on $X_i$, and $u$ is an isomorphism from $\sh{L}_1|Z$ to $\sh{L}_2|Z$ that is compatible with the rigidifications.
It remains only to verify that, for $\sh{L}_1$ and $\sh{L}_2$ fixed, the data of $u$ can be expressed as a section of a suitable scheme over $S$ that is affine over $S$, which is easy.
:::

From [(6.3)](#fga-3-v-proposition-6.3) we easily conclude:

::: {.itenv #fga-3-v-corollary-6.4 title="Corollary 6.4" latex="{Corollary 6.4}"}
Let $X$ be a proper and separable scheme over a field $k$, and let $X_i$ be the irreducible components of $X$.
If the $\repPic_{X_i/k}$ exist, then so too does $\repPic_{X/k}$, and the canonical morphism
$$
  \repPic_{X/k}
  \to \prod_i \repPic_{X_i/k}
$$
is affine.
:::

Combined with [(6.2)](#fga-3-v-corollary-6.2), this shows, for example, the existence of $\repPic_{X/k}$ whenever $X$ is a projective scheme that is separable over a field $k$.
If $X$ is no longer separable over $k$, then we equally have a reduction result, using the argument of Oort [@Oor1962].
The method equally applies for a scheme with arbitrary base (a useful case, for example, in proving in the following talk the finiteness result stated in [(3.3)](#fga-3-v-remark-3.3)).
To avoid an overly technical statement, we restrict ourselves to the case where we are over a base field:

::: {.itenv #fga-3-v-proposition-6.5 title="Proposition 6.5" latex="{Proposition 6.5}"}
Let $X$ be a proper scheme over a field $k$, and $X_0$ a subscheme that has the same underlying set (thus defined by a nilpotent ideal on $X$).
Then the functorial morphism $\shPic_{X/k}\to\shPic_{X_0/k}$ is representable by affine morphisms.
In particular, if $\repPic_{X_0/k}$ exists, then so too does $\repPic_{X/k}$, and the morphism $\repPic_{X/k}\to\repPic_{X_0/k}$ is affine.
:::

Combining this with [Corollary 6.4](#fga-3-v-corollary-6.4), we easily conclude:

::: {.itenv #fga-3-v-corollary-6.6 title="Corollary 6.6" latex="{Corollary 6.6}"}
Let $X$ be a projective prescheme over a field $k$>
Then $\repPic_{X/k}$ exists.
:::

::: {.rmenv #fga-3-v-remark-6.6 title="Remark 6.6" latex="{Remark 6.6}"}
It is extremely plausible that, for every *proper* scheme $X$ over a field $k$, $\repPic_{X/k}$ exists.
The results above allow us to reduce, for this question, to the case where $k$ is algebraically closed, and where $X$ is integral.
We then know that there exists an integral scheme $X'$ that is *projective* over $k$, and a dominant morphism $g\colon X'\to X$ (Chow's lemma).
\oldpage{232-18}
It would thus suffice to show that the corresponding functorial morphism $\shPic_{X/k}\to\shPic_{X'/k}$ is representable (and, probably, representable by affine morphisms), since we already know that $\shPic_{X'/k}$ is representable.
This raises questions about non-flat descent that are not answerable as of now.
Note that, if we restrict to considering the restriction of the functor $\shPic_{X/k}$ to reduced preschemes (with $X$ proper and integral over an algebraically closed field $k$), then we do indeed obtain a representable functor, as shown by Chevalley [@Che1960] in the case where $X$ is normal, and by Seshadri [@Ses1962] by a descent method in the general case.
But with our notation, the scheme constructed by these authors is not $\repPic_{X/k}$, but instead $(\repPic_{X/k})_\red$, i.e. the reduced scheme corresponding to $\repPic_{X/k}$.

*[Comp.]*
As we point out at the start of the next talk, the question raised here has just been answered in the affirmative by Murre.
:::

::: {.rmenv #fga-3-v-remark-6.7 title="Remark 6.7" latex="{Remark 6.7}"}
More generally, let $f\colon X'\to X$ be a surjective morphism of proper preschemes over $k$.
Then considering non-flat descent leads us to conjecture that $\repPic_{X/k}\to\repPic_{X'/k}$ is an *affine* morphism, which would in particular imply (by dividing into the connected components of the identity elements) that the corresponding homomorphism on the Néron--Severi groups is injective modulo torsion.
We can verify this by the theory of intersections when $X$ and $X'$ are non-singular.
The answer does not seem to be known in any other case.

*[Comp.]*
The question raised here has been answered in the affirmative (cf. the last paragraph of the comments in the next talk).
:::

::: {.rmenv #fga-3-v-remark-6.8 title="Remark 6.8" latex="{Remark 6.8}"}
Contrary to what we might think, the consideration of Picard schemes of algebraic schemes with nilpotent elements is useful, and even indispensable, for various questions.
If $X$ is a projective scheme, simple over $k$, say, and $Y$ a hyperplane section, then we can consider the "infinitesimal neighbourhoods" $X_n$ of $Y$ of all orders, as well as the Picard schemes $\repPic_{X_n/k}$;
when $X$ is irreducible of dimension $\geqslant4$ (resp. $\geqslant3$), the canonical morphism
$$
  \repPic_{X/k}
  \to\repPic_{X_n/k}
  \qquad\text{for large }n
$$
is an isomorphism (resp. induces an isomorphism between the inverse images of the torsion subgroups of the Néron--Severi groups), and this result will be useful in the qualitative study of Picard schemes in the following talk.
Similarly, the consideration of Picard schemes of certain curves with nilpotent elements and the fundamental theorems of formal geometry [@Gro1958a] allow us to prove, in the case of equal characteristic, a conjecture of Mumford, namely that for every complete normal Noetherian local ring $A$ of dimension $2$, the group of classes of divisors of $A$ can be considered as the set of rational points over $k$ of an algebraic group $G$ over the residue field $k$ (with $G$ being canonically determined once we have a field of representatives in $A$).
\oldpage{232-19}
In the case where $A$ is of arbitrary dimension, it is plausible that there exists an algebraic pro-group over $k$ that plays the same role as $G$ above, which is constructed, in the case where we can "desingularise" $\Spec(A)$, as a projective limit of Picard schemes of suitable projective schemes (with nilpotent elements) over $k$.
:::
