--- 
title: "Foundations of Algebraic Geometry"
author: "A. Grothendieck"
date: "1957--1962"
bibliography: ["source/FGA-all.bib"]
link-citations: true
reference-section-title: "Bibliography"
csl: maths-translations.csl
github-repo: "thosgood/fga"
favicon: "favicon.ico"
---

::: {.abstract #translators-note title="Translator's note" latex=""}
An English translation of Grothendieck's Fondements de la Géometrie Algébrique.
The original notes have been scanned and uploaded by the Grothendieck Circle [here](https://webusers.imj-prg.fr/~leila.schneps/grothendieckcircle/FGA.pdf).

Note that in this present version the volume numbering has changed: FGA 1 and FGA 2 appear as chapters 1 and 2 (respectively), and FGA 3.I to FGA 3.VI appear as chapters 3 through 8 (respectively).
Furthermore, the numbering of citations within the text has changed, since the eight individual original bibliographies have been merged into a single one.

*The translator ([Tim Hosgood](https://thosgood.com)) takes full responsibility for any errors introduced, and claims no rights to any of the mathematical content herein.*

Version: [`GIT_COMMIT_HASH_VARIABLE`](https://github.com/thosgood/fga/commit/GIT_COMMIT_HASH_VARIABLE)
:::

# Foreword {-}

\oldpage{C-01}

In the _Séminaire Bourbaki_, between 1957 and 1962, we gave eight talks on the foundations of algebraic geometry.
With the exception of the first, these talks are expressed in the language of _schemes_.
All of the stated results will find their place in Jean Dieudonné and Alexander Grothendieck's "Éléments de géométrie algébrique".
However, none of the essence of any of these talks is currently found in any of the chapters (neither published nor still in preperation) of the EGA, nor in any other book or article, and this will probably remain the case for a few more years still.
This is the main reason that persuaded us to combine these talks, giving readers access to a number of ideas and key results of the theory of schemes whilst awaiting a well-written summary.
Also, reading these chapters will allow the reader to quickly familiarise themselves with the aforementioned results and ideas, without being bothered by the necessarily cumbersome details of a systematic treatment, and also endow them with vital motivations for the study of such a treatment.

For the sake of the reader, we have assembled here some comments and errata, grouped by section, that, most notably, show the progress accomplished since the editing of this text, as well as indicating some supplementary references.^[_[Trans.]_ Rather than translating the comments and errata here, we have inserted them throughout the text in the relevant places; we preface them with "_[Comp.]_" (for "Complément") except for small corrections, which we have inserted silently.]

Many of the results appearing in these articles have been discussed in detail in the _Séminaire de Géométrie Algébrique du Bois Marie_, as well as in the two subsequent seminars at Harvard, in 1961--62 (the first by myself, and the second by Mumford--Tate), the notes for which are currently in preparation by Lichtenbaum.
