# Duality theorems for coherent algebraic sheaves [FGA 1] {#FGA-1}

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\from}{\leftarrow}
\providecommand{\bb}{\mathbf}

\providecommand{\Ext}{\operatorname{Ext}}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\Tor}{\operatorname{Tor}}
\providecommand{\shExt}{\underline{\Ext}}
\providecommand{\shHom}{\underline{\Hom}}
\providecommand{\RR}{\operatorname{R}}
\providecommand{\HH}{\operatorname{H}}

<!-- Content -->

::: {.original-citation}
Grothendieck, A.
"Théorème de dualité pour les faisceaux algébriques cohérents".
_Séminaire Bourbaki_ **9** (1956--57), Talk no. 149.
:::

\oldpage{149-01}

The results that follow, inspired by Serre's "theorem of algebraic duality", were discovered in the winter of 1955 and the winter of 1956.
They can be established very simply, thanks to reasonably elementary results on the cohomology of projective spaces [@1-3] and an intensive use of Cartan--Eilenberg's homological algebra, in the form given in [@1-2].


## $\Ext$ of sheaves of modules {#FGA-1-section-1}

_(cf. @1-2, chap. 3 and 4)_

Let $X$ be a topological space endowed with a sheaf $\scr{O}$ of unital (but not necessarily commutative) rings.
We consider the abelian category $\cal{C}^\scr{O}$ of sheaves of $\scr{O}$-modules, which are also referred to as $\scr{O}$-modules.
We know that every object of this category admits an injective resolution, which allows us to define the $\Ext$ functors that have the well-known formal properties.
More precisely, to avoid confusion, we denote by $\Hom_\scr{O}(X;\scr{A},\scr{B})$, or simply $\Hom(X;\scr{A},\scr{B})$, the abelian _groups_ of $\scr{O}$-homomorphisms from $\scr{A}$ to $\scr{B}$, whereas $\shHom_\scr{O}(\scr{A},\scr{B})$ denotes the _sheaf_ of germs of homomorphisms from $\scr{A}$ to $\scr{B}$ (where $\scr{A},\scr{B}\in \cal{C}^\scr{O}$).
We define, for fixed $\scr{A}\in \cal{C}^\scr{O}$, functors $h_\scr{A}$ and $\underline{h}_\scr{A}$, with values in the category $\cal{C}$ of abelian groups and the category $\cal{C}^Z$ of abelian sheaves on $X$ (respectively), by the formulas:
$$
  \begin{aligned}
    h_\scr{A}(\scr{B}) &= \Hom_\scr{O}(X;\scr{A},\scr{B})
  \\\underline{h}_\scr{A}(\scr{B}) &= \shHom_\scr{O}(\scr{A},\scr{B}).
  \end{aligned}
\tag{1.1}
$$
The functors $h_\scr{A}$ and $\underline{h}_\scr{A}$ are left exact and covariant, and so we consider their right-derived functors, denoted by $\Ext_\scr{O}^p(X;\scr{A},\scr{B})$ and $\shExt_\scr{O}^p(\scr{A},\scr{B})$ (respectively).
We then have, by definition,

::: {.eqref #FGA-1-equation-1.2 title="" data-latex=""}
$$
  \begin{gathered}
    \Ext_\scr{O}^p(X;\scr{A},\scr{B}) = (\RR^p h_\scr{A})(\scr{B}) = \HH^p(\Hom_\scr{O}(X;\scr{A},C(\scr{B})))
  \\\shExt_\scr{O}^p(\scr{A},\scr{B}) = (\RR^p \underline{h}_\scr{A})(\scr{B}) = \HH^p(\shHom_\scr{O}(\scr{A},C(\scr{B})))
  \end{gathered}
\tag{1.2}
$$
:::

where $\RR^p$ denotes the passage to right-derived functors, and where $C(\scr{B})$ denotes an arbitrary injective resolution of $\scr{B}$ in $\cal{C}^\scr{O}$.
We denote by $\Gamma\colon\cal{C}^Z\to\cal{C}$ the "sections" functor;
recall that its right-derived functors are denoted by $B\mapsto\HH^p(X,\scr{B})$:
$$
  \HH^p(X,\scr{B}) = (\RR^p\Gamma)(\scr{B}) = \HH^p(\Gamma(C(\scr{B}))).
\tag{1.3}
$$

\oldpage{149-02}

We evidently have $h_\scr{A}=\Gamma\underline{h}_\scr{A}$;
we can also show that $\underline{h}_\scr{A}$ sends injective objects to $\Gamma$-acyclic objects.
From this, it is a well-known result that:

:::: {.itenv #FGA-1-proposition-1 title="Proposition 1" data-latex="{Proposition 1}"}
For every $\scr{O}$-module $\scr{A}$, there exists a cohomological spectral functor on $\cal{C}^\scr{O}$ that abuts to the graded functor $(\Ext_\scr{O}^\bullet(X;\scr{A},\scr{B}))$, and whose initial page is

::: {.eqref #FGA-1-equation-1.4 title="" data-latex=""}
$$
  E_2^{p,q}(\scr{A},\scr{B}) = \HH^p(X,\shExt_\scr{O}^q(\scr{A},\scr{B})).
\tag{1.4}
$$
:::
::::

From this, we obtain "_boundary homomorphisms_", as well as a short exact sequence, which we will not write.

:::: {.itenv #FGA-1-proposition-1-corollary-1 title="Corollary 1" data-latex="{Corollary 1}"}
If $\scr{A}$ is locally isomorphic to $\scr{O}^n$, then we have canonical isomorphisms

::: {.eqref #FGA-1-equation-1.5 title="" data-latex=""}
$$
  \Ext_\scr{O}^p(X;\scr{A},\scr{B}) \xleftarrow{\sim} \HH^p(x,\shHom_\scr{O}(\scr{A},\scr{B}))
\tag{1.5}
$$
:::

(given by the boundary homomorphisms of the spectral sequence).
In particular, we have a canonical isomorphism
$$
  \Ext_\scr{O}^p(X;\scr{O},\scr{B}) = \HH^p(X,\scr{B}).
\tag{1.6}
$$
::::

To use these results, we need to know how to explicitly describe the $\Ext_\scr{O}^p(\scr{A},\scr{B})$.
They are functors that we calculate locally, i.e. if $V$ is an open subset of $X$, then
$$
  \shExt_\scr{O}^p(\scr{A},\scr{B})|U = \shExt_{\scr{O}|U}^p(\scr{A}|U,\scr{B}|U),
$$
as follows from the fact that the restriction to $U$ of an injective $\scr{O}$-module is an injective $(\scr{O}|U)$-module.
Furthermore, for fixed $x\in X$, we have functorial homomorphisms

::: {.eqref #FGA-1-equation-1.7 title="" data-latex=""}
$$
  \shHom_\scr{O}(\scr{A},\scr{B})_x \to \Hom_{\scr{O}_x}(\scr{A}_x,\scr{B}_x)
\tag{1.7}
$$
:::

that uniquely extend to homomorphisms of cohomological functors (in $\scr{B}$):

::: {.eqref #FGA-1-equation-1.8 title="" data-latex=""}
$$
  \shExt_\scr{O}^p(\scr{A},\scr{B})_x \to \Ext_{\scr{O}_x}^p(\scr{A}_x,\scr{B}_x).
\tag{1.8}
$$
:::

::: {.itenv #FGA-1-proposition-2 title="Proposition 2" data-latex="{Proposition 2}"}
If $\scr{A}$ is isomorphic, in a neighbourhood of $x$, to the cokernel of some homomorphism $\scr{O}^m\to\scr{O}^n$, then [(1.7)](#FGA-1-equation-1.7) is an isomorphism for all $p$.
This is the case, in particular, if $\scr{A}$ is a coherent $\scr{O}$-module [@1-3].
:::

\oldpage{149-03}

::: {.itenv #FGA-1-proposition-3 title="Proposition 3" data-latex="{Proposition 3}"}
Let $\scr{L}_\bullet=(\scr{L}_i)$ be a left resolution of the $\scr{O}$-module $\scr{A}$ by $\scr{O}$-modules that are all locally isomorphic to some $\scr{O}^n$.
Then $\shExt_\scr{O}(\scr{A},\scr{B})$ can be identified with $\HH^\bullet(\shHom_\scr{O}(\scr{L}_\bullet,\scr{B}))$, and $\Ext_\scr{O}(X;\scr{A},\scr{B})$ can be identified with the hypercohomology of $X$ with respect to the complex $\shHom_\scr{O}(\scr{L}_\bullet,\scr{B})$.
:::

::: {.proof}
The proof is standard: we consider the bicomplex $\shHom_\scr{O}(\scr{L}_\bullet,C(\scr{B}))$, where $C(\scr{B})$ is an injective resolution of $\scr{B}$, as well as the natural homomorphisms into this bicomplex from $\shHom_\scr{O}(\scr{L}_\bullet,\scr{B})$ and $\shHom_\scr{O}(\scr{A},C(\scr{B}))$.
}
:::

To finish, we note that the two $\Ext$ functors introduced in [(1.2)](#FGA-1-equation-1.2) are not only cohomological functors in $\scr{B}$, but in fact _cohomological bifunctors_, covariant in $\scr{B}$, and contravariant in $\scr{A}$.


## The composition law in $\Ext$ {#FGA-1-section-2}

The results of this section are due, independently, to Cartier and Yoneda;
see a talk by Cartier [@1-1] for more details.
Let $\cal{C}$ be an abelian category, and let $K$ and $L$ be two graded objects of $\cal{C}$.
We denote by $\Hom(K,L)$ the graded abelian group whose degree-$n$ component consists of homogeneous homomorphisms of degree $n$ from $K$ to $L$ (i.e. systems $(u_i)$ of homomorphisms $K^i\to L^{i+n}$).
If $K$ and $L$ are complexes (with differentials of degree $+1$, to fix conventions), then we endow $\Hom(K,L)$ with the differential operator given by
$$
  \delta(u) = \mathrm{d}u + (-1)^{n+1}u\mathrm{d}
  \quad\text{where }n=\deg(u)
\tag{2.1}
$$
which makes it a complex with a differential of degree $+1$.
The cycles of degree $n$ are the maps of degree $n$ that anticommute with $u$ (as homogeneous maps).
We can then consider $\HH^\bullet(\Hom(K,L))$, which is an invariant of the homotopy types of $K$ and $L$, and which we sometimes denote by $\HH^\bullet(K,L)$.
If we have a third complex $M$, then the composition of homomorphisms defines a pairing $\Hom(K,L)\times\Hom(L,M)\to\Hom(K,M)$ which is compatible with the differential maps, whence, by passing to the cohomology of pairings,

::: {.eqref #FGA-1-equation-2.2 title="" data-latex=""}
$$
  \HH^\bullet(K,L)\times\HH^\bullet(L,M) \to \HH^\bullet(K,M)
\tag{2.2}
$$
:::

which we write as $(u,v)\mapsto vu$.
These pairings satisfy an evident associativity property;
in particular, $\HH^\bullet(K,K)$ is an associative graded unital ring, and $\HH^\bullet(K,L)$ (resp. $\HH^\bullet(L,K)$) is a graded right (resp. left) module over this ring, etc.
In dimension $0$, [(2.2)](#FGA-1-equation-2.2) reduces to the composition of permissible homomorphisms of complexes.
Finally, an exact sequence of complexes $0\to K'\to K\to K''\to0$ such that, for all $i$, $K'^i$ can be identified with a direct factor of $K^i$, gives rise to an exact sequence of complexes of groups $\Hom(K'',L)$, etc., whence a coboundary map $\HH^i(K',L)\to\HH^{i+1}(K'',L)$.
We similarly define the boundary maps relative to an exact sequence in $L$.
The pairings in [(2.2)](#FGA-1-equation-2.2) are compatible, in the usual sense, with these coboundary maps.

\oldpage{149-04}

Now suppose that $\cal{C}$ is a category such that every element $A$ of $\cal{C}$ admits an injective resolution $C(A)$.
We then note that, using one of the many variants of the theorem of bicomplexes,
$$
  \HH^\bullet(C(A),C(B)) = \HH^\bullet(\Hom(C(A),C(B)))
$$
is canonically isomorphic to
$$
  \HH^\bullet(\Hom(A,C(B))) = \Ext^\bullet(A,B).
$$
The coboundary maps described above give coboundary maps of the $\Ext$.
Furthermore, the pairings in [(2.2)](#FGA-1-equation-2.2) give associative pairings here:
$$
  \Ext^\bullet(A,B)\times\Ext^\bullet(B,C) \to \Ext^\bullet(A,C)
\tag{2.3}
$$
and these are compatible with the coboundary maps.
In particular, $\Ext^\bullet(A,A)$ is an associative graded unital ring, etc.
(We can show in an analogous manner that the $\Ext$ functors behave like derived functors of an arbitrary functor;
we do not make use of this fact here).

In the case where the category in question is the category $\cal{C}^\scr{O}$ of $\scr{O}$-modules on $X$, we then obtain pairings
$$
  \Ext_\scr{O}^p(X;\scr{A},\scr{B})\times\Ext_\scr{O}^q(X;\scr{B},\scr{C}) \to \Ext_\scr{O}^{p+q}(X;\scr{A},\scr{C})
\tag{2.4}
$$
that can be calculated as already described.
The same method, but replacing the category of abelian groups with the category of abelian sheaves on $X$, and the $\Hom$ functors by the $\shHom$ functors, again defines pairings, having the same formal properties, and of a "local nature" this time:
$$
  \shExt_\scr{O}^p(\scr{A},\scr{B})\times\shExt_\scr{O}^q(\scr{B},\scr{C}) \to \shExt_\scr{O}^{p+q}(\scr{A},\scr{C}).
\tag{2.5}
$$
These can be understood by noting that the homomorphisms in [(1.8)](#FGA-1-equation-1.8) are compatible with the pairings between the $\Ext$.

\oldpage{149-05}

Finally, recall that we also have a multiplicative structure between functors $\HH^p(X,A)$, namely the cup product.
We note then that the spectral sequences of [Proposition 1](#FGA-1-proposition-1) are compatible with the multiplicative structures;
more precisely, we have a pairing from the spectral sequence $E(A,B)$ with the spectral sequence $E(B,C)$ to the spectral sequence $E(A,C)$ that abuts to the pairing between the global $\Ext$, and whose initial page comes from the cup product and the local $\Ext$ pairings in the right-hand side of [(1.4)](#FGA-1-equation-1.4).
It then follows, in particular, that the "boundary homomorphisms"
$$
  \Ext_\scr{O}^n(X;\scr{A},\scr{B}) \to \HH^0(X;\shExt_\scr{O}^n(\scr{A},\scr{B}))
\tag{2.6}
$$
$$
  \HH^n(X,\shHom_\scr{O}(\scr{A},\scr{B})) \to \Ext_\scr{O}^n(X;\scr{A},\scr{B})
\tag{2.7}
$$
are compatible with the multiplicative structures.
So, if we restrict to sheaves that are locally isomorphic to some $\scr{O}^m$, then this completely explains the composition of the global $\Ext$ by means of the cup product, taking into account the isomorphisms of [(1.5)](#FGA-1-equation-1.5).


## Results concerning local cohomology {#FGA-1-section-3}

Let $A$ be a unital commutative ring endowed with an ideal $\frak{J}$.
We will define, for any $A$-module $M$, functorial homomorphisms

::: {.eqref #FGA-1-equation-3.1 title="" data-latex=""}
$$
  \begin{aligned}
    \Ext_A^p(A/\frak{J},M) &\to \Hom_A(\wedge^p\frak{J}/\frak{J}^2,M\otimes A/\frak{J})
  \\\Tor_p^A(A/\frak{J},M) &\from (\wedge^p\frak{J}/\frak{J}^2)\otimes\Hom_A(A/\frak{J},M)
  \end{aligned}
\tag{3.1}
$$
:::

where the tensor and exterior products are taken over the ring $A$;
note also that $\frak{J}/\frak{J}^2$ is in fact an $A/\frak{J}$-module, and that its exterior powers as an $A$-module agree with its exterior powers as an $A/\frak{J}$-module.
The definition of the homomorphisms in [(3.1)](#FGA-1-equation-3.1) come from the definition, for every system $x=(x_1,\ldots,x_p)$ of points of $\frak{J}$, of homomorphisms $\varphi_x$ given by

::: {.eqref #FGA-1-equation-3.2 title="" data-latex=""}
$$
  \begin{aligned}
    \varphi_x\colon \Ext_A^p(A/\frak{J},M) &\to M\otimes A/\frak{J}
  \\\varphi_x\colon \Hom_A(A/\frak{J},M) &\to \Tor_p^A(A/\frak{J},M)
  \end{aligned}
\tag{3.2}
$$
:::

\oldpage{149-06}

such that the following conditions are satisfied:

i. $\varphi_{x_1,\ldots,x_p}$ depends on the system of the $x_i\in\frak{J}$ in an alternating $A$-multilinear way;

ii. $\varphi_{x_1,\ldots,x_p}$ is zero when any of the $x_i$ is in $\frak{J}^2$.

In fact, ii. follows from i., since $a\varphi_x=0$ for $a\in\frak{J}$, as we see by noting that all the modules in [(3.2)](#FGA-1-equation-3.2) are annihilated by $\frak{J}$.

To define the $\varphi_x$, we consider the complex $K_x$ whose underlying $A$-modules are the $\wedge A^p$, and whose differential is the interior product $i_x$ by $x$, considered as a linear form on $A^p$ with components $x_1,\ldots,x_p$.
The differential is of degree $-1$, the degrees of the complex are positive, and the cohomology of this complex in dimension $0$ is $A/(x_1A+\ldots+x_pA)$.
Since the $x_i$ are in $\frak{J}$, we obtain an augmentation $K_{x,0}\to A/\frak{J}$.
Thus $K_x$ is a _free_ augmented complex, with augmentation module $A/\frak{J}$.
We thus obtain known homomorphisms
$$
  \begin{aligned}
    \Ext_A^\bullet(\HH_0(K_x),M) &\to \HH^\bullet(\Hom_A(K_x,M))
  \\\Tor_\bullet^A(\HH_0(K_x),M) &\from \HH_\bullet(K_x\otimes M)
  \end{aligned}
$$
whence, by composing with the homomorphisms to the $\Ext$ and the $\Tor$ induced by the augmentation homomorphism $\HH_0(K_x)\to A/\frak{J}$, we obtain homomorphisms

::: {.eqref #FGA-1-equation-3.3 title="" data-latex=""}
$$
  \begin{aligned}
    \psi_x\colon \Ext_A^\bullet(A/\frak{J},M) &\to \HH^\bullet(\Hom_A(K_x,M))
  \\\psi_x\colon \Tor_\bullet^A(A/\frak{J},M) &\from \HH_\bullet(K_x\otimes M).
  \end{aligned}
\tag{3.3}
$$
:::

But we immediately note that, in the maximal dimension $p$, the cohomology of the right-hand side is $M(x_1M+\ldots+x_pM)$ (resp. the set of elements of $M$ that are annihilated by each of the $x_i$).
Since the $x_i$ are in $\frak{J}$, we thus obtain homomorphisms

::: {.eqref #FGA-1-equation-3.4 title="" data-latex=""}
$$
  \begin{aligned}
    \HH^p(\Hom_A(K_x,M)) &\to M\otimes A/\frak{J}
  \\\HH_p(K_x\otimes M) &\from \Hom_A(A/\frak{J},M).
  \end{aligned}
\tag{3.4}
$$
:::

By composing the homomorphisms in [(3.3)](#FGA-1-equation-3.3) and [(3.4)](#FGA-1-equation-3.4) we obtain the homomorphisms in [(3.2)](#FGA-1-equation-3.2) that we wanted to define.
The verification of i. is tedious, but does not present any difficulties.

\oldpage{149-07}

::: {.itenv #FGA-1-proposition-4 title="Proposition 4" data-latex="{Proposition 4}"}
Let $A$ be a commutative unital ring, and let $(x_1,\ldots,x_p)$  be a sequence of elements of $A$ such that, for $1\leq i\leq p$, the image of $x_i$ in the quotient of $A$ by the ideal generated by $(x_1,\ldots,x_{i-1})$ is not a zero divisor.
Let $\frak{J}$ be the ideal generated by the $x_i$.
Then $\frak{J}/\frak{J}^2$ is a free $(A/\frak{J})$-module, with basis given by the canonical images of the $x_i$;
the complex $K_x$ is a free resolution of $A/\frak{J}$;
and, for every $A$-modules $M$, the homomorphisms in [(3.1)](#FGA-1-equation-3.1) in dimension $p$ are bijective.
The same is true for the analogous homomorphisms defined for arbitrary degree $i$ as long as $\frak{J}\cdot M=0$.
:::

(The essential point, from which all others follow, is the acyclicity of $K_x$, which is a well-known fact, under the conditions given).

::: {.itenv #FGA-1-proposition-4-corollary-1 title="Corollary 1" data-latex="{Corollary 1}"}
With $A$ and $\frak{J}$ as above, suppose further that $A$ is a regular affine algebra of $\dim n$ over a perfect field $k$, and that $A/\frak{J}$ is a regular affine algebra.
Denote by $\Omega^i(A)$ and $\Omega^i(A/\frak{J})$ the modules of Kähler differentials.
Then we have a canonical isomorphism
$$
  \Ext_A^p(\Omega^{n-p}(A/\frak{J}),\Omega^n(A)) = A/\frak{J}.
\tag{3.5}
$$
which is compatible with localisation.
:::

::: {.proof}
Indeed, $\Omega^{n-p}(A/\frak{J})$ is a free $(A/\frak{J})$-module of rank $1$, and, similarly, $\Omega^n(A)$ is a free $A$-module of rank $n$, and so the left-hand side is equal to
$$
  \Ext_A^p(A/\frak{J},A) \otimes \Omega^{n-p}(A/\frak{J})' \otimes \Omega^n(A)
$$
(where the "$'$" notation denotes the dual $(A/\frak{J})$-module).
The tensor product of these last two factors can be identified with $\wedge^p(\frak{J}/\frak{J}^2)$, and so the whole thing can be identified with $\Ext_A^p(A/\frak{J},\wedge^p(\frak{J}/\frak{J}^2))$, and thus, by [the proposition](#FGA-1-proposition-4), with
$$
  \Hom_A(\wedge^p \frak{J}/\frak{J}^2,\wedge^p \frak{J}/\frak{J}^2)
$$
i.e. to $A/\frak{J}$.
:::

In particular, there is a distinguished element in $\Ext_A^p(\Omega^{n-p}(A/\frak{J}),\Omega^n(A))$, corresponding to the unit of $A/\frak{J}$, called the _fundamental class_ of the ideal $\frak{J}$ in $A$.
(In fact, it can be defined under rather more general conditions).
We can write [Corollary 1](#FGA-1-proposition-4-corollary-1) in a more geometric and global form:

:::: {.itenv #FGA-1-proposition-4-corollary-2 title="Corollary 2" data-latex="{Corollary 2}"}
Let $X$ be a non-singular variety over an algebraically-closed field $k$, $Y$ a closed non-singular subvariety of $X$, $\scr{O}_X$ the structure sheaf of $X$, and $\scr{O}_Y$ the structure sheaf of $Y$, considered as a quotient sheaf of $\scr{O}_X$.
Let $n$ be the dimension of $X$, and $n-p$ the dimension of $Y$.
Let $\Omega_X$ (resp. $\Omega_Y$) be the sheaf of germs of regular differential forms on $X$ (resp. $Y$).
Then we have canonical isomorphisms
$$
  \shExt_{\scr{O}_X}^p(\Omega_Y^{n-p},\Omega_X^n) = \scr{O}_Y
\tag{3.6}
$$
as well as

\oldpage{149-08}

::: {.eqref #FGA-1-equation-3.6bis title="" data-latex=""}
$$
  \Ext_{\scr{O}_X}^p(\scr{O}_Y,\Omega_X^n) = \Omega_Y^{n-p}.
\tag{3.6 bis}
$$
:::
::::

Equation [(3.6 bis)](#FGA-1-equation-3.6bis) can serve as the _definition_ of $\Omega_Y^{n-p}$ when $Y$ is a singular variety.
More precisely:

::: {.itenv #FGA-1-proposition-5 title="Proposition 5" data-latex="{Proposition 5}"}
Let $X$ be a non-singular algebraic variety of dimension $n$, and let $Y$ be an algebraic subset of dimension $q=n-p$ of $X$.
Let $\scr{F}$ be a coherent algebraic sheaf on $X$ with support contained in $Y$, and let $\scr{L}$ be a locally-free algebraic sheaf on $X$.
Then the sheaves $\shExt_{\scr{O}_X}^i(\scr{F},\scr{L})$ are zero for $i<p$, and, when $i=p$, there is a canonical isomorphism
$$
  \shExt_{\scr{O}_X}^p(\scr{F},\scr{L}) = \shHom_{\scr{O}_X}(\scr{F},\shExt^p(\scr{O}_X/\frak{J},\scr{L}))
\tag{3.7}
$$
where $\frak{J}$ denotes an arbitrary sheaf of ideals on $X$ that annihilates $\scr{F}$ and has $Y$ as its set of zeros.
In particular, if $\scr{F}$ is a coherent algebraic sheaf on $Y$, then
$$
  \shExt_{\scr{O}_X}^p(\scr{F},\scr{L}) = \shHom_{\scr{O}_Y}(\scr{F},\shExt^p(\scr{O}_Y,\scr{L})).
\tag{3.7 bis}
$$
Finally, with $\scr{F}$ still a coherent algebraic sheaf on $Y$, the sheaves $\scr{E}^i=\shExt_{\scr{O}_X}^{p+i}(\scr{F},\Omega_X^n)$ do not depend on the choice of immersion of the algebraic space $Y$ into the non-singular algebraic variety $X$.
:::

::: {.proof}
Since the question is local, we can assume that $X$ is affine and that $\scr{L}=\scr{O}_X$.
This then reduces to a problem of commutative algebra, and, more specifically, of local algebra:
if $A$ is a regular locality, and $M$ an $A$-module whose support is of dimension $\leq q=n-p$, then we have to prove that $\Ext_A^i(M,A)=0$ for $i<p$ and that $\Ext_A^p(M,A)=\Hom_A(M,\Ext^p(A/\frak{J},A))$, where $\frak{J}$ is an arbitrary ideal of "dimension" $\leq q$ that annihilates $M$.
For the first claim, we proceed by induction on $q$:
an immediate _dévissage_ leads to the case where $M$ is of the form $A/\frak{J}$, and thus leads, by replacing $\frak{J}$ with a smaller ideal and using the induction hypothesis, as well as the exact sequence of the $\Ext$, to the case where $\frak{J}$ is generated by a "system of parameters", as in [Proposition 4](#FGA-1-proposition-4), where the result is immediate.
The previous result implies that, if $\frak{J}$ is a fixed ideal of "dimension" $\leq q$, then the contravariant functor $E(M)=\Ext_A^p(M,A)$ to the category of $(A/\frak{J})$-modules is left exact;
furthermore, it sends direct sums to direct products, from which it easily follows that $E(M)=\Hom_A(M,E(A))$.
Finally, the last claim of [Proposition 5](#FGA-1-proposition-5) is more subtle, and follows from an intrinsic characterisation of the $E^i(F)$ via a local duality theorem which cannot be stated here.
:::

\oldpage{149-09}

:::: {.itenv #FGA-1-proposition-5-corollary title="Corollary" data-latex="{Corollary}"}
Denote by $\omega_Y^q$ the sheaf $\Ext_{\scr{O}_X}^p(\scr{O}_Y,\Omega_X^n)$.
Then there is a functorial isomorphism for coherent algebraic sheaves $\scr{F}$ on $Y$:

::: {.eqref #FGA-1-equation-3.8 title="" data-latex=""}
$$
  \shExt_{\scr{O}_X}^p(\scr{F},\Omega_X^n) = \shHom_{\scr{O}_X}(\scr{F},\omega_Y^q).
\tag{3.8}
$$
:::
::::


## Cohomology class associated to a subvariety {#FGA-1-section-4}

In all that follows, $X$ denotes an algebraic set of dimension $n$, defined over a field $k$ that we assume, for simplicity, to be algebraically closed.
Except for in [§6](#FGA-1-section-6), we assume that $X$ is non-singular.
We denote by $\scr{O}_X$ the structure sheaf of $X$, and by $\Omega_X^\bullet=\bigcup_p\Omega_X^p$ the sheaf of germs of differential forms on $X$.
If $Y$ is a closed subset of $X$, then we identify coherent algebraic sheaves on $Y$ with coherent algebraic sheaves on $X$ that are zero outside of $Y$;
we do this, in particular, with $\scr{O}_Y$ and $\Omega_Y$.

:::: {.itenv #FGA-1-lemma-1 title="Lemma 1" data-latex="{Lemma 1}"}
Let $\scr{F}$ be a coherent algebraic sheaf on $X$ whose support is of dimension $\leq n-p$, and let $\scr{L}$ be a coherent algebraic sheaf on $X$ that is locally free.
Then $\shExt_{\scr{O}_X}^i(X;\scr{F},\scr{L})$ is zero for $i<p$, and there is a canonical isomorphism
  
::: {.eqref #FGA-1-equation-4.1 title="" data-latex=""}
$$
  \Ext_\scr{O}^p(X;\scr{F},\scr{L}) = \HH^0(X,\shExt_\scr{O}^p(\scr{F},\scr{L})).
\tag{4.1}
$$
:::

If $\scr{F}$ is a coherent algebraic sheaf on a closed subset $W$ of $X$ of dimension $\leq n-p$, then we have a canonical isomorphism

::: {.eqref #FGA-1-equation-4.1bis title="" data-latex=""}
$$
  \shExt_{\scr{O}_X}^p(\scr{F},\scr{L}) = \shHom_{\scr{O}_X}(\scr{F}\otimes\scr{L}'\otimes\Omega_X^n,\omega_Y^{n-p})
\tag{4.1 bis}
$$
:::

where $\omega_Y^{n-p}$ is the sheaf on $Y$ defined in [the corollary to Proposition 5](#FGA-1-proposition-5-corollary) (which can be identified with $\Omega_Y^{n-p}$ if $Y$ is non-singular).
::::

::: {.proof}
The formula in [(4.1)](#FGA-1-equation-4.1) is an immediate consequence of the spectral sequence from [Proposition 1](#FGA-1-proposition-1), as well as [Proposition 5](#FGA-1-proposition-5);
by the formula in [(3.8)](#FGA-1-equation-3.8), we can write
$$
  \begin{gathered}
    \shExt_{\scr{O}_X}^p(\scr{F},\scr{L})
    = \scr{L}\otimes(\Omega_X^n)'\otimes\shExt_{\scr{O}_X}(\scr{F},\Omega_X^n)
  \\= \scr{L}\otimes(\Omega_X^n)'\otimes\shHom_{\scr{O}_X}(\scr{F},\omega_Y^q)
  \\= \shHom_{\scr{O}_X}(\scr{F}\otimes\scr{L}'\otimes\Omega_X^n,\omega_Y^q)
  \end{gathered}
$$
where $q=n-p$, whence the formula in [(4.1 bis)](#FGA-1-equation-4.1bis).
:::

\oldpage{149-10}

Setting, in particular, $\scr{F}=\scr{O}_Y$ and $\scr{L}=\Omega_X^p$, we obtain (taking into account the fact that $\Omega_X^n\otimes(\Omega_X^p)'=\Omega_X^{n-p}$) a canonical isomorphism

::: {.eqref #FGA-1-equation-4.2 title="" data-latex=""}
$$
  \Ext_{\scr{O}_X}^p(X;\scr{O}_Y,\Omega_X^p) = \Hom_{\scr{O}_X}(X;\Omega_X^{n-p},\omega_Y^{n-p}).
\tag{4.2}
$$
:::
   
Now suppose, for simplicity, that $Y$ is _non-singular_, so that $\omega_Y^{n-p}=\Omega_Y^{n-p}$.
There is a natural homomorphism from $\Omega_X^{n-p}$ to $\Omega_Y^{n-p}$, whence a canonical section $s_Y$ of the sheaf $\shExt_{\scr{O}_X}^p(\scr{O}_Y,\Omega_X^p)$, that we call, if all the components of $Y$ are of dimension $n-p$, the _fundamental section_ of the sheaf $\shExt_{\scr{O}_X}^p(\scr{O}_Y,\Omega_X^p)$.
By [(4.1)](#FGA-1-equation-4.1), this section defines an element of $\Ext_{\scr{O}_X}^p(X;\scr{O}_Y,\Omega_X^p)$.
But the natural homomorphism $\scr{O}_X\to\scr{O}_Y$ defines a homomorphism
$$
  \Ext_{\scr{O}_X}^p(X;\scr{O}_Y,\Omega_X^p) \to \Ext_{\scr{O}_X}^p(X;\scr{O}_X,\Omega_X^p) = \HH^p(X,\Omega_X^p).
$$
We thus obtain an element of $\HH^p(X,\Omega_X^p)$, denoted by $P_X(Y)$, that we call the _cohomology class of $Y$ in $X$_;
it is induced by the section $s_Y$ of $\shExt_{\scr{O}_X}^p(\scr{O}_Y,\Omega_X^p)$ by the following diagram of homomorphisms:

::: {.eqref #FGA-1-equation-4.3 title="" data-latex=""}
$$
  \begin{CD}
    \Ext_{\scr{O}_X}^p(X;\scr{O}_Y,\Omega_X^p) @>\sim>> \HH^0(X,\shExt_{\scr{O}_X}^p(\scr{O}_Y,\Omega_X^p))
  \\@VVV
  \\\begin{gathered}
      \Ext_{\scr{O}_X}^p(X;\scr{O}_X,\Omega_X^y)
      \\=\HH^p(X,\Omega_X^p)
    \end{gathered}
  \end{CD}
\tag{4.3}
$$
:::

We define a _non-singular cycle_ of dimension $n-p$ to be any element of the free abelian group generated by the non-singular irreducible subvarieties of dimension $n-p$ in $X$.
Then the function $Y\mapsto P(Y)$ can be extended to a homomorphism from the group of non-singular cycles of dimension $n-p$ on $X$ to the group $\HH^p*X,\Omega_X^p)$.

Let $Z^{n-p}$ and $Z'^{n-p'}$ be non-singular cycles of dimension $n-p$ and $n-p'$ (respectively);
we say that they _intersect transversally_ if every component of $Z$ intersects transversally with every component of $Z'$.
Then the cycle $Z\cdot Z'$ is defined, and is a non-singular cycle of dimension $n-p-p'$.
With this, we have:

\oldpage{149-11}

:::: {.itenv #FGA-1-theorem-1 title="Theorem 1" data-latex="{Theorem 1}"}
If $Z^{n-p}$ and $Z'^{n-p'}$ are non-singular cycles that intersect transversally, then

::: {.eqref #FGA-1-equation-4.4 title="" data-latex=""}
$$
  P_X(Z\cdot Z') = P_X(Z)\cdot P_X(Z')
\tag{4.4}
$$
:::

where the product on the right-hand side is the cup product:
$$
  \HH^p(X,\Omega_X^p)\times\HH^{p'}(X,\Omega_X^{p'}) \to \HH^{p+p'}(X,\Omega_X^{p+p'}).
$$
(We assume that $X$ is isomorphic to a locally closed subset of a projective space).
::::

This last hypothesis is used only to be able to conclude that every coherent algebraic sheaf on $X$ is a quotient of a locally-free coherent algebraic sheaf (Serre) and thus admits a left resolution by locally-free sheaves.

:::: {.proof}
To prove [Theorem 1](#FGA-1-theorem-1), we can assume that $Z$ and $Z'$ are irreducible non-singular subvarieties $Y$ and $Y'$ that intersect transversally.
Let $\scr{L}_\bullet$ be a left resolution of $\scr{O}_Y$ by locally-free sheaves;
then, by [Proposition 3](#FGA-1-proposition-3), the diagram of homomorphisms in [(4.3)](#FGA-1-equation-4.3) can be identified with the diagram
$$
  \begin{CD}
    (\underline{\RR}^p\Gamma)\big(\shHom_{\scr{O}_X}(\scr{L}_\bullet,\Omega_X^p)\big) @>\beta>> \Gamma\big(\HH^p\big(\shHom_{\scr{O}_X}(\scr{L}_\bullet,\Omega_X^p)\big)\big)
  \\@V\alpha VV .
  \\(\RR^p\Gamma)(\Omega_X^p)
  \end{CD}
$$
where $\beta$ is an isomorphism, and where $\Gamma$ is the "group of sections" functor on the category of abelian sheaves on $X$, $\underline{\RR}^p\Gamma$ is its hypercohomology in dimension $p$, and $\RR^p\Gamma$ is its $p$-th derived functor.
For simplicity, we assume that $\scr{L}_0=\scr{O}_X$, and that the augmentation $\scr{L}_0\to\scr{O}_Y$ is the natural homomorphism (which we can indeed safely assume);
then $\alpha$ is induced by the homomorphism of complexes $\scr{O}_X\to\scr{L}$ (with $\scr{O}_X$ being thought of as a complex concentrated in degree $0$), taking into account the fact that $\underline{\RR}^p\Gamma(\scr{K})=\RR^p\Gamma(\scr{K}_0)$ if $\scr{K}$ is a complex of sheaves concentrated in degree $0$.
The homomorphism $\beta$ is a well-known "boundary map".
Consider an analogous diagram, relative to a locally-free resolution $\scr{L}'_\bullet$ of $\scr{O}_Y$, and consider the commutative diagram of pairings:

::: {.eqref #FGA-1-equation-4.5 title="" data-latex=""}
$$
  \scriptsize
  \begin{CD}
    \RR^p\Gamma(\Omega_X^p)
    @<<<
    \underline{\RR}^p\Gamma\big(\shHom_{\scr{O}_X}(\scr{L}_\bullet,\Omega_X^p)\big)
    @>\sim>>
    \Gamma\big(\HH^p\big(\shHom_{\scr{O}_X}(\scr{L}_\bullet,\Omega_X^p)\big)\big)
  \\@. @. @.
  \\\times @. \times @. \times
  \\@. @. @.
  \\\RR^{p'}\Gamma(\Omega_X^{p'})
    @<<<
    \underline{\RR}^{p'}\Gamma\big(\shHom_{\scr{O}_X}(\scr{L}'_\bullet,\Omega_X^{p'})\big)
    @>\sim>>
    \Gamma\big(\HH^{p'}\big(\shHom_{\scr{O}_X}(\scr{L}'_\bullet,\Omega_X^{p'})\big)\big)
  \\@VVV @VVV @VVV
  \\\RR^{p+p'}\Gamma(\Omega_X^{p+p'})
    @<<<
    \underline{\RR}^{p+p'}\Gamma\big(\shHom_{\scr{O}_X}(\scr{L}_\bullet\otimes\scr{L}'_\bullet,\Omega_X^{p+p'})\big)
    @>\sim>>
    \Gamma\big(\HH^{p+p'}\big(\shHom_{\scr{O}_X}(\scr{L}_\bullet\otimes\scr{L}'_\bullet,\Omega_X^{p+p'})\big)\big)
  \end{CD}
\tag{4.5}
$$
:::

\oldpage{149-12}
The pairings in the two columns on the right are induced by the pairing of complexes of sheaves
$$
  \shHom_{\scr{O}_X}(\scr{L}_\bullet,\Omega_X^p) \times \shHom_{\scr{O}_X}(\scr{L}'_\bullet,\Omega_X^{p'}) \to \shHom_{\scr{O}_X}(\scr{L}_\bullet\otimes\scr{L}',\Omega_X^{p+p'})
$$
that we define by using the exterior product $\Omega_X^p\times\Omega_X^{p'}\to\Omega_X^{p+p'}$;
the pairing in the first column is the cup product (relative to the exterior product).
I claim that the last line of [(4.5)](#FGA-1-equation-4.5) can be identified with the diagram of isomorphisms analogous to [(4.3)](#FGA-1-equation-4.3), where $Y$ is replaced by $Y\cap Y'$ and $p$ by $p+p'$.
For this, it suffices to show that $\scr{L}\otimes\scr{L}'$ is a resolution (evidently locally-free) of $\scr{O}_{Y\cap Y'}$.
But then
$$
  \HH_0(\scr{L}\otimes\scr{L}') = \scr{O}_Y\otimes\scr{O}_{Y'} = \scr{O}_{Y\cap Y'}
$$
and
$$
  \HH_i(\scr{L}\otimes\scr{L}') = \Tor_i^{\scr{O}_X}(\scr{O}_Y,\scr{O}_{Y'}) = 0
$$
for $i>0$, from the fact that $Y$ and $Y'$ intersect transversally.
Then [Theorem 1](#FGA-1-theorem-1) follows from the formula:

::: {.eqref #FGA-1-equation-4.6 title="" data-latex=""}
$$
  s_{Y}\cdot s_{Y'} = s_{Y\cdot Y'}
\tag{4.6}
$$
:::

(where the product on the left-hand side is that from the last column of [(4.5)](#FGA-1-equation-4.5)).
This formula in [(4.6)](#FGA-1-equation-4.6), which is of a purely local nature, can easily be proven by taking $\scr{L}_\bullet$ and $\scr{L}'_\bullet$ to be the resolutions described in [Proposition 4](#FGA-1-proposition-4).
We can similarly prove (even more easily) that $Z\mapsto P_X(Z)$ is compatible with the cartesian product:

::: {.eqref #FGA-1-equation-4.7 title="" data-latex=""}
$$
  P_{X\times X'}(Z\times Z')  = P_X(Z)\otimes P_{X'}(Z')
\tag{4.7}
$$
:::

(a formula which holds true if $Z$ (resp. $Z'$) is a non-singular cycle on the non-singular variety $X$ (resp. $X'$), with $Z\times Z'$ being thought of as a non-singular cycle on $X\times X'$).
From [(4.4)](#FGA-1-equation-4.4) and [(4.7)](#FGA-1-equation-4.7), it follows that $P_X(Z)$ is also compatible with the operation given by taking the "inverse image" under a morphism $f\colon X\to X'$ of non-singular varieties:

::: {.eqref #FGA-1-equation-4.8 title="" data-latex=""}
$$
  P_X(f^{-1}(Z')) = f^*(P_{X'}(Z))
\tag{4.8}
$$
:::

a formula which holds true if $Z$ is a non-singular cycle on $X'$ such that $f$ is "transversal" to $Z$, i.e. such that the graph of $f$ is transversal to the cycle $X\times Z'$ in $X\times X'$.
::::

\oldpage{149-13}

::: {.itenv #FGA-1-theorem-1-corollary-1 title="Corollary 1" data-latex="{Corollary 1}"}
Let $X$ and $X'$ be non-singular varieties that are locally-closed in a projective space, and suppose that $X'$ is complete.
Let $U$ be a non-singular cycle on $X\times X'$, and let $a$ and $b$ be points of $X'$ such that $U$ intersects transversally with the cycles $X\times(a)$ and $X\times(b)$.
Let $Z$ and $Z'$ be non-singular cycles on $X$ such that $Z\times(a)=(X\times(a))\cdot U$ and $Z\times(b)=(X\times(b))\cdot U$.
Then
$$
  P_X(Z) = P_X(Z').
$$
:::

::: {.proof}
Let $f_a\colon X\to X\times X'$ be defined by $f_a(x)=(x,a)$.
Then, by [(4.8)](#FGA-1-equation-4.8), we have $P(Z)=f_a^*(P(U))$;
similarly, $P(Z')=f_b^*(P(U))$.
But then, using the Künneth formula
$$
  \HH^\bullet(X\times X',\Omega_{X\times X'}^\bullet)
  = \HH^\bullet(X,\Omega_X^\bullet)\otimes\HH^\bullet(X',\Omega_{X'}^\bullet)
$$
and the fact that $\HH^0(X',\Omega_{X'})$ is simply the scalars, we easily see that $f_a^*=f_b^*$, whence the result.
:::

For all $x\in X$, $(x)$ is a non-singular subvariety of $X$ of codimension $n$, and thus defines an element $\varepsilon_x$ of $\HH^n(X,\Omega_X^n)$.
If $X$ is a non-singular projective variety, then it follows from the above [Corollary 1](#FGA-1-theorem-1-corollary-1) that $\varepsilon_x$ does not depend on the chosen point $x$, and we thus denote it by $\varepsilon_X$ and call it the _fundamental class_ of $\HH^n(X,\Omega_X^n)$.

::: {.rmenv #FGA-1-section-4-remark title="Remark" data-latex="{Remark}"}
To have a satisfying theory, we must define $P_X(Z)$ for arbitrary cycles $Z$, and prove [Theorem 1](#FGA-1-theorem-1) for proper intersections of cycles.
(At the time of writing this talk, this has still not been done in full generality).
Assuming that we have done this, the above [Corollary 1](#FGA-1-theorem-1-corollary-1) becomes the following:
_if $Z$ and $Z'$ are two algebraically-equivalent cycles, then $P_X(Z)=P_X(Z')$_
(a claim which does not seem to follow from the above, even if $Z$ and $Z'$ are non-singular).
:::

::: {.rmenv title="Remark" data-latex="{Remark}"}
[Comp.] As I pointed out in my conference at the international Congress of Mathematicians in 1958^[Grothendieck, A. "The cohomology theory of abstract algebraic varieties", in _Proceedings of the international Congress of Mathematicians [1958, Edinburgh]_, Cambridge University Press (1960), 103--118.], the questions raised here are now completely resolved.

The reader will find more information on the duality of coherent sheaves in _loco citato_, p. 112--115, as well as in EGA III.2, and in SGA (1962).
A more systematic treatment can be found in a later chapter of EGA (chapter IX in the provisional plan).
:::


## The duality theorem {#FGA-1-section-5}

In this section, $X$ denotes a non-singular projective variety of dimension $n$.

::: {.itenv #FGA-1-theorem-2 title="Theorem 2" data-latex="{Theorem 2}"}
The fundamental class $\varepsilon_X$ of $\HH^n(X,\Omega_X^n)$ is a basis of this vector space.
:::

(The proof of this will be given later on).
With the above theorem, we can thus identify $\HH^n(X,\Omega_X^n)$ with the field $k$.
We now consider the pairings described in [§2](#FGA-1-section-2), which give, in particular, a pairing
\oldpage{149-14}
$$
  \Ext_{\scr{O}_X}^p(X;\scr{O}_X,\scr{F})\times\Ext_{\scr{O}_X}^{n-p}(X;\scr{F},\Omega_X^n) \to \Ext_{\scr{O}_X}^n(X;\scr{O}_X,\Omega_X^n)
$$
i.e.

::: {.eqref #FGA-1-equation-5.1 title="" data-latex=""}
$$
  \HH^p(X,\scr{F})\times\Ext_{\scr{O}_X}^{n-p}(X;\scr{F},\Omega_X^n) \to \HH^n(X,\Omega_X^n).
\tag{5.1}
$$
:::

Taking [Theorem 2](#FGA-1-theorem-2) into account, this pairing defines a homomorphism

::: {.eqref #FGA-1-equation-5.2 title="" data-latex=""}
$$
  \Ext_{\scr{O}_X}^{n-p}(X;\scr{F},\Omega_X^n) \to (\HH^p(X,\scr{F}))'.
\tag{5.2}
$$
:::

This homomorphism is functorial in $\scr{F}$, and commutes with the coboundary maps relative to the exact sequences $0\to\scr{F}'\to\scr{F}\to\scr{F}''\to0$.

::: {.itenv #FGA-1-theorem-3 title="Theorem 3" data-latex="{Theorem 3}"}
The homomorphism in [(5.2)](#FGA-1-equation-5.2) is an isomorphism.
:::

In particular, we recover the following result of Serre:

::: {.itenv #FGA-1-theorem-3-corollary title="Corollary" data-latex="{Corollary}"}
Let $E$ be an algebraic vector bundle on $X$, and $\scr{O}_X(E)$ the sheaf of germs of regular sections of $X$.
Then we have canonical isomorphisms^[[Trans.] This equation is labelled (5.3) in the original copy of the notes, but this seems to be a typo, since a later equation shares the same number, and any references to (5.3) seem to indeed point to the later equation instead of this one.]
$$
  (\HH^p(X,\scr{O}_X(E)))' = \HH^{n-p}(X,\Omega_X^n\otimes\scr{O}_X(E')).
$$
:::

::: {.proof}
It suffices to apply [Theorem 3](#FGA-1-theorem-3) and [Corollary 1 of Proposition 1](#FGA-1-proposition-1-corollary-1).
:::

[Theorem 2](#FGA-1-theorem-2) and [Theorem 3](#FGA-1-theorem-3) will follow from the following claim:

:::: {.itenv #FGA-1-D title="(D)" data-latex="{(D)}"}
The homomorphism

::: {.eqref #FGA-1-equation-5.2bis title="" data-latex=""}
$$
  \Ext_{\scr{O}_X}^{n-p}(X;\scr{F},\Omega_X^n) \to (\HH^p(X,\scr{F}))'\otimes\scr{L}
\tag{5.2 bis}
$$
:::

(where $\scr{L}=\HH^n(X,\Omega_X^n)$) induced by the pairing in [(5.1)](#FGA-1-equation-5.1) is an isomorphism.
::::

We will show that [(D)](#FGA-1-D) implies [Theorem 2](#FGA-1-theorem-2).
Let $k_x=\scr{O}_{(x)}$ be the structure sheaf of the variety consisting of a single point $x\in X$, and consider the canonical homomorphism $\scr{O}_X\to k_x$, and the associated homomorphism

::: {.eqref #FGA-1-equation-5.3 title="" data-latex=""}
$$
  \HH^0(X,\scr{O}_X) \to \HH^0(X,k_x).
\tag{5.3}
$$
:::

Its transpose can be identified with the homomorphism

::: {.eqref #FGA-1-equation-5.4 title="" data-latex=""}
$$
  \Ext_{\scr{O}_X}^n(X;k_x,\Omega_X^n)\otimes\scr{L}' \to \Ext_{\scr{O}_X}^n(X;\scr{O}_X,\Omega_X^n)\otimes\scr{L}'
\tag{5.4}
$$
:::

induced by the homomorphism between the $\Ext^n$ associated to $\scr{O}_X\to k_x$, i.e.

::: {.eqref #FGA-1-equation-5.5 title="" data-latex=""}
$$
  \Ext_{\scr{O}_X}^n(X;k_x,\Omega_X^n) \to \Ext_{\scr{O}_X}^n(X;\scr{O}_X,\Omega_X^n)
\tag{5.5}
$$
:::

\oldpage{149-15}
Since [(5.3)](#FGA-1-equation-5.3) is an isomorphism, so too is [(5.4)](#FGA-1-equation-5.4), and thus so too is [(5.5)](#FGA-1-equation-5.5).
Since $s_{(x)}$ is a basis of $\Ext_{\scr{O}_X}^n(X;k_x,\Omega_X^n)$ by [(4.2)](#FGA-1-equation-4.2), it indeed follows that its image $\varepsilon_X$ is a basis of $\HH^n(X,\Omega_X^n)$.

It remains only to prove the statement of [(D)](#FGA-1-D), which will follow in a purely formal way from some elementary facts summarised in the following lemmas.
Here we suppose that $X$ is a closed subset (singular or not) of the projective space $\bb{P}$ of dimension $r$.
We use the notation $\scr{O}_\bb{P}(m)$ to denote the sheaf on $\bb{P}$ denoted by $\scr{O}(m)$ in [@1-3], and the notation $\scr{O}_X(m)$ for the analogous sheaf on $X$.

::: {.itenv #FGA-1-lemma-2 title="Lemma 2" data-latex="{Lemma 2}"}
The statement of [(D)](#FGA-1-D) is true if $X=\bb{P}$ and $\scr{F}=\scr{O}_\bb{P}(m)$.
:::

::: {.proof}
This lemma can be proved by a direct calculation.
The explicit calculation of the $\HH^i(\bb{P},\scr{O}_\bb{P}(m))$ can be found in [@1-3], but it also can be done in a simpler way.
Computing the cup product $\HH^i(\bb{P},\scr{O}_\bb{P}(m))\times\HH^j(\bb{P},\scr{O}_\bb{P}(m)') \to \HH^{i+j}(\bb{P},\scr{O}_\bb{P}(m+m'))$ (which is necessary to calculate the pairing in [(5.1)](#FGA-1-equation-5.1)) does not present any difficulty.
:::

::: {.itenv #FGA-1-lemma-3 title="Lemma 3" data-latex="{Lemma 3}"}
Every coherent algebraic sheaf $\scr{F}$ on $X$ is isomorphic to a sheaf that is some quotient of $\scr{O}_X(-m)^k$, and we can take $m$ to be as large as we wish.
:::

::: {.proof}
This follows from the fact that $\scr{F}\otimes\scr{O}_X(m)$ is "generated by its sections" for large enough $m$;
see [@1-3].
:::

::: {.itenv #FGA-1-lemma-4 title="Lemma 4" data-latex="{Lemma 4}"}
Let $i>0$.
Then $\HH^{r-i}(\bb{P},\scr{O}_\bb{P}(-m))=0$ for large enough $m$;
and, for every coherent algebra sheaf $\scr{B}$ on $X$, we have that $\Ext_{\scr{O}_X}^i(X;\scr{O}_X(-m),\scr{B})=0$ for large enough $m$.
:::

::: {.proof}
The first claim follows from the explicit calculations mentioned above;
for the second, we note that we have an isomorphism
$$
  \Ext_{\scr{O}_X}^i(X;\scr{O}_X(-m),\scr{B}) = \HH^i(X,\scr{B}\otimes\scr{O}(m))
$$
([Corollary 1 of Proposition 1](#FGA-1-proposition-1-corollary-1)), whence the conclusion, by a well-known result of [@1-3].
:::

Combining the previous two lemmas, we find:

::: {.itenv #FGA-1-lemma-3-and-lemma-4-corollary title="Corollary" data-latex="{Corollary}"}
Let $i>0$.
Then the functor $\scr{F}\mapsto\HH^{r-i}(\bb{P},\scr{F})$ on the category of coherent algebraic sheaves on $\bb{P}$ is coeffaceable, and so too is the functor $\Ext_{\scr{O}_X}^i(X;\scr{F},\scr{B})$ on the category of coherent algebraic sheaves on $X$.
:::

\oldpage{149-16}

::: {.itenv #FGA-1-lemma-5 title="Lemma 5" data-latex="{Lemma 5}"}
Let $\scr{A}$ and $\scr{B}$ be coherent algebraic sheaves on $X$, and let $\scr{A}(m)=\scr{A}\otimes\scr{O}_X(m)$.
Then, for large enough $m$, the canonical homomorphism
$$
  \Ext_{\scr{O}_X}^i(X;\scr{A}(-m),\scr{B})
  \to \HH^0(X,\shExt_{\scr{O}_X}^i(\scr{A}(-m),\scr{B}))
  = \HH^0(X,\shExt_{\scr{O}_X}^i(\scr{A},\scr{B})(m))
$$
is an isomorphism.
:::

::: {.proof}
This follows immediately from the spectral sequence in [Proposition 1](#FGA-1-proposition-1) applied to $\scr{A}(-m)$ and $\scr{B}$, since we then have that
$$
  E_2^{p,q}(\scr{A}(-m),\scr{B})
  = \HH^p(X,\shExt_{\scr{O}_X}^q(\scr{A}(-m),\scr{B}))
  = \HH^p(X,\shExt_{\scr{O}_X}^q(\scr{A},\scr{B})(m))
$$
which is zero for $p>0$ and large enough $m$.
:::

We now prove [(D)](#FGA-1-D) in the case where $X=\bb{P}$.
We will first prove that [(5.2 bis)](#FGA-1-equation-5.2bis) is an isomorphism for $p=n$;
since both sides are then left-exact functors (since $\HH^{r+i}(\bb{P},\scr{F})=0$), it follows from [Lemma 3](#FGA-1-lemma-3) that it suffices to prove the claim for $\scr{F}=\scr{O}_\bb{P}(-m)$, but this is covered by [Lemma 2](#FGA-1-lemma-2).
Since the homomorphisms in [(5.2 bis)](#FGA-1-equation-5.2bis) are functorial and compatible with the coboundary maps, and since, for $p<n$, both sides of [(5.2 bis)](#FGA-1-equation-5.2bis) are coeffaceable functors in $\scr{F}$ (the [corollary to Lemmas 3 and 4](#FGA-1-lemma-3-and-lemma-4-corollary)), it follows, by a standard argument, that [(5.2 bis)](#FGA-1-equation-5.2bis) is an isomorphism for all $p$.
This proves the duality theorem for the projective space.

Now suppose that $X$ is arbitrary, but non-singular.
By the duality theorem for $\bb{P}$, we have an isomorphism
$$
  \HH^n(X,\scr{F})
  = \HH^n(\bb{P},\scr{F})'
  = \Ext_{\scr{O}_\bb{P}}^{r-n}(\bb{P};\scr{F},\Omega_\bb{P}^r).
$$
By [Lemma 1](#FGA-1-lemma-1), the far-right-hand side can be identified with
$$
  \Hom_{\scr{O}_\bb{P}}(\bb{P};\scr{F},\omega_X^n)
  = \Hom_{\scr{O}_X}(X;\scr{F},\Omega_X^n)
  = \Ext_{\scr{O}_X}^0(X;\scr{F},\Omega_X^n)
$$
whence we have an isomorphism

::: {.eqref #FGA-1-equation-5.6 title="" data-latex=""}
$$
  \HH^n(X,\scr{F})'
  = \Hom_{\scr{O}_X}(X;\scr{F},\Omega_X^n)
  = \Ext_{\scr{O}_X}^0(X;\scr{F},\Omega_X^n).
\tag{5.6}
$$
:::

Taking $\scr{F}=\Omega_X^n$, we obtain an isomorphism

::: {.eqref #FGA-1-equation-5.7 title="" data-latex=""}
$$
  \eta\colon \HH^n(X,\Omega_X^n) \xrightarrow{\sim} k.
\tag{5.7}
$$
:::

\oldpage{149-17}
We can prove that the isomorphism in [(5.6)](#FGA-1-equation-5.6) is exactly [(5.2 bis)](#FGA-1-equation-5.2bis) with $p=n$ and $\scr{L}=k$, by [(5.7)](#FGA-1-equation-5.7).
Subsequently, [(5.2 bis)](#FGA-1-equation-5.2bis) is an isomorphism for $p=n$.
To prove that it is an isomorphism for all $p$, it again suffices to prove that, for $p<n$, the two sides of [(5.2 bis)](#FGA-1-equation-5.2bis) are coeffaceable functors in $\scr{F}$, and, a fortiori (taking [Lemma 3](#FGA-1-lemma-3) into account), that the two sides are zero when we take $\scr{F}=\scr{O}_X(-m)$ with large enough $m$.
But, for the left-hand side, this is true by [Lemma 4](#FGA-1-lemma-4), and for the right-hand side we can write, using the duality theorem for $\bb{P}$,
$$
  \HH^p(X,\scr{O}_X(-m))'
  = \Ext_{\scr{O}_\bb{P}}^{r-p}(\bb{P};\scr{O}_X(-m),\Omega_\bb{P}^r).
$$
The right-hand side is zero for $p<n$ and large enough $m$, as follows from [Lemma 5](#FGA-1-lemma-5) (where in fact $X=\bb{P}$) and from the fact that $\scr{O}_X$ is of cohomological dimension $\leq r-n$ when thought of as a coherent algebraic sheaf on $\bb{P}$ (since $X$ is non-singular), whence
$$
  \shExt_{\scr{O}_\bb{P}}^{r-p}(\scr{O}_X,\Omega_\bb{P}^r) = 0
  \quad\text{for }p<n.
$$


## The duality theorem for singular varieties {#FGA-1-section-6}

Let $X$ be a closed subset of dimension $n$ of the projective space $\bb{P}$ of dimension $r$.
Equation [(5.6)](#FGA-1-equation-5.6) can then be written as

::: {.eqref #FGA-1-equation-6.1 title="" data-latex=""}
$$
  \HH^n(X,\scr{F})'
  \simeq \Hom_{\scr{O}_X}(X;\scr{F},\omega_X^n)
  = \Ext_{\scr{O}_X}^0(X;\scr{F},\omega_X^n)
\tag{6.1}
$$
:::

where we set^[[Trans.] This equation is labelled (6.2) in the original, but this seems to be a typo, since a later equation shares the same number, and any references to (6.2) seem to indeed point to the later equation instead of this one.]
$$
  \omega_X^n = E^0(\scr{O}_X) = \shExt_{\scr{O}_\bb{P}}^{r-n}(\scr{O}_X,\Omega_\bb{P}^r).
$$
As mentioned in [Proposition 5](#FGA-1-proposition-5), the sheaf thus defined does not depend on the chosen immersion of $X$ into the non-singular variety $\bb{P}$.
Taking $\scr{F}=\omega_X^n$ in [(6.1)](#FGA-1-equation-6.1), we find that
$$
  \HH^n(X,\omega_X^n)' \simeq \Hom_{\scr{O}_X}(X;\omega_X^n,\omega_X^n)
\tag{6.2}
$$
whence the existence of a distinguished element in $\HH^n(X,\omega_X^n)$, corresponding to the identity morphism from $\omega_X^n$ to itself:

::: {.eqref #FGA-1-equation-6.3 title="" data-latex=""}
$$
  \eta\colon \HH^n(X,\Omega_X^n) \to k.
\tag{6.3}
$$
:::

\oldpage{149-18}
Then consider the pairings defined by the composition of the $\Ext$:
$$
  \HH^p(X,\scr{F}) \times \Ext_{\scr{O}_X}^{n-p}(X;\scr{F},\omega_X^n)
  \to \HH^n(X,\omega_X^n)
\tag{6.4}
$$
and compose them with the homomorphism $\eta$ in [(6.3)](#FGA-1-equation-6.3); we thus obtain functorial homomorphisms

::: {.eqref #FGA-1-equation-6.5 title="" data-latex=""}
$$
  \Ext_{\scr{O}_X}^{n-p}(X;\scr{F},\omega_X^n) \to \HH^p(X,\scr{F})'
\tag{6.5}
$$
:::

which are compatible with the boundary maps (generalising [(5.2)](#FGA-1-equation-5.2)).
We can prove that, for $p=n$, we thus obtain the isomorphism in [(6.1)](#FGA-1-equation-6.1).
With this, we have:

::: {.itenv #FGA-1-theorem-3bis title="Theorem 3 bis" data-latex="{Theorem 3 bis}"}
For any given integer $k\geq0$, the four following conditions on $X$ are equivalent:

i. The functorial homomorphism in [(6.5)](#FGA-1-equation-6.5) is an isomorphism for $n-k\leq p\leq n$.

ii. $\HH^p(X,\scr{O}_X(-m)) = 0$ for $n-k\leq p<n$ and large enough $m$.

iii. The functor $\HH^p(X,\scr{F})$ on the category of coherent algebraic sheaves on $X$ is coeffaceable for $n-k\leq p<n$.

iv. $E^i(\scr{O}_X) = \shExt_{\scr{O}_\bb{P}}^{r-n+i}(\scr{O}_X,\omega_\bb{P}^r) = 0$ for $0<i\leq k$.
:::

::: {.proof}
i.$\implies$ii. by [Lemma 4](#FGA-1-lemma-4);
ii.$\implies$iii. by [Lemma 3](#FGA-1-lemma-3);
iii.$\implies$i. by a well-known standard argument, taking into account the fact that the two sides of [(6.5)](#FGA-1-equation-6.5) are then coeffaceable functors for $n-k\leq p< n$ (the first being so by [Lemma 4](#FGA-1-lemma-4));
finally, ii.$\iff$iv. follows from [the corollary to the following proposition](#FGA-1-proposition-6-corollary).
:::

:::: {.itenv #FGA-1-proposition-6 title="Proposition 6" data-latex="{Proposition 6}"}
Let $\scr{F}$ be a coherent algebraic sheaf on $X$, and let $i$ be an integer.
Then, for large enough $m$, we have an isomorphism

::: {.eqref #FGA-1-equation-6.6 title="" data-latex=""}
$$
  \HH^i(X,\scr{F}(-m))' \simeq \HH^0(X,E^{n-i}(\scr{F})(m))
\tag{6.6}
$$
:::

where we set
$$
  E^j(\scr{F}) = \shExt_{\scr{O}_\bb{P}}^{r-n+j}(\scr{F},\Omega_\bb{P}^r)
\tag{6.7}
$$
(compare with [Proposition 5](#FGA-1-proposition-5) in [§3](#FGA-1-section-3)).
::::

::: {.proof}
Indeed, by the duality theorem for $\bb{P}$, the left-hand side of [(6.6)](#FGA-1-equation-6.6) is isomorphic to $\Ext_{\scr{O}_\bb{P}}^{r-i}(\bb{P};\scr{F}(-m),\Omega_\bb{P}^r)$, and so [(6.6)](#FGA-1-equation-6.6) follows from [Lemma 5](#FGA-1-lemma-5).
:::

\oldpage{149-19}

::: {.itenv #FGA-1-proposition-6-corollary title="Corollary" data-latex="{Corollary}"}
For $\HH^i(X,\scr{F}(-m))$ to be zero for large enough $m$, it is necessary and sufficient for $E^{n-i}(\scr{F})$ to be zero.
:::

Recall that the $E^j(\scr{F})$ do not depend on the projective immersion in question.
The condition of the corollary is purely local, and so, if it is satisfied for $\scr{F}$, then it is also satisfied for every sheaf that is locally isomorphic to some $\scr{F}^n$.
In particular, if this condition is satisfied for $\scr{O}_X$, then it is satisfied for every locally-free coherent algebraic sheaf.
This is the case, for example, for all $i<n$ if $X$ is non-singular;
and for $i=0$ if no component of $X$ consists of a single point;
and for $i=0,1$ if $S$ is normal and all its components are of dimension $>1$ (see [@1-3]).
For it to be satisfied for $i<k$, it is necessary and sufficient, by definition, for the local rings $\scr{O}_x$ ($x\in X$) to be of "homological codimension $\geq k$" (see [@1-4] for details on this notion).
If $k=n$, then this implies, by [Theorem 3 bis](#FGA-1-theorem-3bis), that the duality theorem is true for $X$, i.e. that [(6.5)](#FGA-1-equation-6.5) is an isomorphism for all $p$ and for all $\scr{F}$.
We can give many equivalent conditions on the local rings $\scr{O}_x$ for this to be the case (Nagata);
for example, those that satisfy the Cohen-Macaulay equidimensionality theorem.
It is also the case, for example, if $X$ is locally a "complete intersection" in a non-singular ambient variety.


## Poincaré duality {#FGA-1-section-7}

Let $X$ be a non-singular projective variety of dimension $n$.
Then $\HH^\bullet(X)=\HH^\bullet(X,\Omega_X^\bullet)$ is a finite-dimensional bigraded anticommutative algebra, that we grade by the total degree, so that $\HH^{p,q}(X)=\HH^p(X,\Omega_X^q)$ is of degree $p+q$;
the degrees of $\HH^\bullet(X)$ are concentrated between $0$ and $2n$.
By [Theorem 2](#FGA-1-theorem-2) and [the corollary to Theorem 3](#FGA-1-theorem-3-corollary), $\HH^\bullet(X)$ is a "Poincaré algebra" of dimension $2n$, i.e. $\HH^{2n}(X)$ is endowed with an isomorphism to the base field $k$, and the product $\HH^m(X)\times\HH^{2n-m}(X)\to\HH^{2n}(X)=k$ is a duality between $\HH^m(X)$ and $\HH^{2n-m}(X)$.
Furthermore, if $Y$ is another non-singular projective variety, then the Künneth formula for coherent algebraic sheaves gives
$$
  \HH^\bullet(X\times Y) = \HH^\bullet(X)\otimes\HH^\bullet(Y)
\tag{7.1}
$$
which is an isomorphism that is compatible with the Poincaré algebra structures.
Furthermore, $\HH^\bullet(X)$ is, as a commutative algebra, a covariant functor in $X$, since a morphism $f\colon Y\to X$ defines, in an evident way, a homomorphism of graded algebras
\oldpage{149-20}
$$
  f^*\colon \HH^\bullet(X)\to\HH^\bullet(Y).
\tag{7.2}
$$
Since we are working with Poincaré algebras, we obtain, by transposition, a homomorphism of vector spaces

::: {.eqref #FGA-1-equation-7.3 title="" data-latex=""}
$$
  f_*\colon \HH^\bullet(Y)\to\HH^\bullet(X).
\tag{7.3}
$$
:::

We have seen in [§4](#FGA-1-section-4) that the effect of $f^*$ on cohomology classes that correspond to non-singular cycles can be interpreted geometrically by taking the cohomology classes that correspond to their inverse images.
It is important, in our current study, to show that [(7.3)](#FGA-1-equation-7.3) corresponds similarly to the "direct image" operation on cycles.
This follows (under suitable non-singularity conditions, at least) from the following particular case:

::: {.itenv #FGA-1-theorem-4 title="Theorem 4" data-latex="{Theorem 4}"}
If $f$ is the identity map from a non-singular subvariety $Y^m$ of $X^n$ to $X^n$, then, denoting by $1_Y$ the unit element of $\HH(Y)$, we have
$$
  f_*(1_Y) = P_X(Y)
\tag{7.4}
$$
where the right-hand side is the cohomology class in $X$ associated to $Y$.
:::

This formula is equivalent to
$$
  \langle \xi^{m,m}, P_X(Y) \rangle \varepsilon_Y
  = f_*(\xi^{m,m})
  \quad\text{where }\xi^{m,m}\in\HH^m(X,\Omega_X^m)
\tag{7.4 bis}
$$
where $\varepsilon_Y$ is the fundamental element of $\HH^m(Y,\Omega_Y^m)$, and this, in the case of non-singular projective varieties, gives a new definition of the cohomology class associated to $Y$.

::: {.proof}
To prove [Theorem 4](#FGA-1-theorem-4), we consider, by [Theorem 3](#FGA-1-theorem-3), the transpose of the homomorphism
$$
  \HH^m(X,\Omega_X^m) \to \HH^m(Y,\Omega_Y^m) = \HH^m(X,\Omega_Y^m)
$$
as the homomorphism
$$
  \begin{CD}
    @.
    \Ext_{\scr{O}_X}^{n-m}(X;\Omega_Y^m,\Omega_X^n)
    @>\sim>>
    \Hom_{\scr{O}_X}(X;\Omega_Y^m,\Omega_Y^m)
  \\@. @VVV @.
  \\\HH^{n-m}(X,\Omega_X^{n-m})
    @>\sim>>
    \Ext_{\scr{O}_X}^{n-m}(X;\Omega_X^m,\Omega_X^n)
  \end{CD}
\tag{7.5}
$$
We can verify that the element $1_Y$ of the dual of $\HH^m(Y,\Omega_Y^m)$ is identified with the element of the right-hand side corresponding to the identity endomorphism of $\Omega_Y^m$, and also that the image of this element in $\HH^{n-m}(X,\Omega_X^{n-m})$ is indeed $P_X(Y)$.
:::

These relations (which could have been given in [§4](#FGA-1-section-4)) can be stated, and are indeed true, for arbitrary non-singular varieties, with the second, for example, following from the commutativity of the following diagram of canonical endomorphisms:
\oldpage{149-21}
$$
  \footnotesize
  \begin{CD}
    \Ext_{\scr{O}_X}^{n-m}(X;\Omega_X^m,\Omega_X^n)
    @<<<
    \Ext_{\scr{O}_X}^{n-m}(X;\Omega_Y^m,\Omega_X^n)
    @>\sim>>
    \Hom_{\scr{O}_X}(X;\Omega_Y^m,\Omega_Y^m)
  \\@VVV @. @VVV
  \\\Ext_{\scr{O}_X}^{n-m}(X;\scr{O}_X,\Omega_X^{n-m})
    @<<<
    \Ext_{\scr{O}_X}^{n-m}(X;\scr{O}_Y,\Omega_X^{n-m})
    @>\sim>>
    \Hom_{\scr{O}_X}(X;\Omega_X^m,\Omega_Y^m)
  \end{CD}
\tag{7.6}
$$

We thus obtain an exact equivalent of the formalism of Poincaré duality for compact oriented varieties.
In particular, [Theorem 4](#FGA-1-theorem-4) allows us to determine the cohomology class associated to the diagonal of $X\times X$.
By a well-known argument, we thus deduce, for example, a _Lefschetz formula_:

::: {.itenv #FGA-1-theorem-5 title="Theorem 5" data-latex="{Theorem 5}"}
Let $f$ be an endomorphism of a non-singular projective variety $X$ such that the fixed points of $f$ are of multiplicity $1$.
Then the number of these fixed points is congruent, modulo the characteristic of $k$, to the alternating sum of the traces of the endomorphisms of the $\HH^i(X)$ defined by $f$.
:::

The restriction on $f$ that we have to make is related to the difficulties mentioned in [the remark in §4](#FGA-1-section-4-remark).
We note, however, that the Lefschetz formula still holds true if $f$ is "homotopic" to an endomorphism whose fixed points are all of multiplicity $1$.


## Generalisation of the duality theorem {#FGA-1-section-8}

Let $X$ be a non-singular algebraic variety such that every coherent algebraic sheaf $\scr{F}$ on $X$ is isomorphic to a locally-free coherent algebraic sheaf (which is the case if $X$ is locally closed in some projective space).
Then every coherent algebraic sheaf $\scr{F}$ on $X$ admits a finite resolution $\scr{L}$ by locally-free sheaves, and, for any two such resolutions, we can always find a third, along with homomorphisms, from it to the first two, that are compatible with the augmentations.
Similarly, if $\scr{L}$ is a finite locally-free resolution of $\scr{F}$, and if we have a homomorphism $\scr{F}'\to\scr{F}$, then there exists a finite locally-free resolution $\scr{L}'$ of $\scr{F}'$ along with a homomorphism $\scr{L}'\to\scr{L}$ that is compatible with $\scr{F}'\to\scr{F}$, that we can even assume to be surjective if $\scr{F}'\to\scr{F}$ is surjective.
This allows us to define, given integers $r,s\geq0$, two cohomological multifunctors, with arguments $\scr{A}_1,\ldots,\scr{A}_r;\scr{B}_1,\ldots,\scr{B}_s$ in the category of coherent algebraic sheaves on $X$;
one takes values in the category of coherent algebraic sheaves on $X$, and the other in the category of modules over $\HH^0(X,\scr{O}_X)$.
We define them by the formulas
\oldpage{149-22}

::: {.eqref #FGA-1-equation-8.1 title="" data-latex=""}
$$
  \begin{aligned}
    &\underline{T}_r^{s\bullet}(\scr{A}_1,\ldots,\scr{A}_r;\scr{B}_1,\ldots,\scr{B}_s)
  \\&= \HH^\bullet(\shHom_{\scr{O}_X}(\underline{L}(\scr{A}_1)\otimes\ldots\otimes\underline{L}(\scr{A}_r), \underline{L}(\scr{B}_1)\otimes\ldots\otimes\underline{L}(\scr{B}_s))),
  \\&T_r^{s\bullet}(\scr{A}_1,\ldots,\scr{A}_r;\scr{B}_1,\ldots,\scr{B}_s)
  \\&= \underline{\RR}^\bullet\Gamma(\shHom_{\scr{O}_X}(\underline{L}(\scr{A}_1)\otimes\ldots\otimes\underline{L}(\scr{A}_r), \underline{L}(\scr{B}_1)\otimes\ldots\otimes\underline{L}(\scr{B}_s)))
  \end{aligned}
\tag{8.1}
$$
:::

where $\underline{L}(\scr{F})$ denotes a finite locally-free resolution of the coherent algebraic sheaf $\scr{F}$, and $\underline{\RR}^\bullet\Gamma(\scr{K})$ denotes the hypercohomology of the space $X$ with respect to the complex of sheaves $\scr{K}$.
If $r$ (resp. $s$) is zero, then we replace the tensor product of the $\underline{L}(\scr{A}_i)$ (resp. of the $\underline{L}(\scr{B}_j)$) by $\scr{O}_X$.
In particular, $\underline{T}_0^0$ and $T_0^0$ are graded functors with no arguments:
$\underline{T}_0^0$ is concentrated in degree $0$, where it is the sheaf $\scr{O}_X$;
and $T_0^0$ is equal to $\HH^\bullet(X,\scr{O}_X)$.
The fact that the right-hand sides of [(8.1)](#FGA-1-equation-8.1) do not depend on the chosen resolutions is evident for $\underline{T}$ (since the question is then local), and for $T$ it follows from preceding general remarks, taking into account the spectral sequence for the hypercohomology of the complex of sheaves $\scr{K}=\shHom_{\scr{O}_X}(\underline{L}(\scr{A}_1)\otimes\ldots,\underline{L}(\scr{B}_1)\otimes\ldots$ that abuts to the hypercohomology of $X$ with respect to $\scr{K}$, and whose initial page is $\HH^p(X,\HH^q(\scr{K}))$, i.e.

::: {.eqref #FGA-1-equation-8.2 title="" data-latex=""}
$$
  E_2^{p,q} = \HH^p(X,(\underline{T}_r^s)^{(q)}(\scr{A}_1,\ldots,\scr{A}_r;\scr{B}_1,\ldots,\scr{B}_s)).
\tag{8.2}
$$
:::

We then see that this spectral sequence itself does not depend on the chosen resolutions, and its abutment is the left-hand side of [(8.1)](#FGA-1-equation-8.1).
We can easily define the coboundary maps relative to miscellaneous arguments $\scr{A}_i,\scr{B}_j$ by noting that every exact sequence $0\to\scr{F}'\to\scr{F}\to\scr{F}''\to0$ can be resolved by an exact sequence of finite locally-free complexes.

We define, on the system of functors $\underline{T}_r^{s\bullet}$ (resp. $T_r^{s\bullet}$), operations that are analogous to those of tensor calculus, and whose definitions are immediate from the defining formulas in [(8.1)](#FGA-1-equation-8.1).
We thus have a _composition_ (generalising that which was described in [§2](#FGA-1-section-2)):

::: {.eqref #FGA-1-equation-8.3 title="" data-latex=""}
$$
  \begin{gathered}
    T_r^{s\bullet}(\scr{A}_1,\ldots,\scr{A}_r;\scr{B}_1,\ldots,\scr{B}_s)
    \times T_{r'}^{s'\bullet}(\scr{A}'_1,\ldots,\scr{A}'_{r'};\scr{B}'_1,\ldots,\scr{B}'_{s'})
  \\\to T_{r+r'}^{(s+s')\bullet}(\scr{A}_1,\ldots,\scr{A}_r,\scr{A}'_1,\ldots,\scr{A}'_{r'};\scr{B}_1,\ldots,\scr{B}_s,\scr{B}'_1,\ldots,\scr{B}'_{s'})
  \end{gathered}
\tag{8.3}
$$
:::

that satisfies the evident properties of associativity, compatibility with the functorial homomorphisms and the coboundary homomorphisms, and spectral sequences.
Similarly, we have symmetry operations, whose explicit descriptions we leave to the reader.
We further have a _contraction_ operation every time one of the arguments $\scr{A}_i$ is equal to one of the arguments $\scr{B}_j$:

\oldpage{149-23}

::: {.eqref #FGA-1-equation-8.4 title="" data-latex=""}
$$
  \begin{gathered}
    T_r^{s\bullet}(\scr{A}_1,\ldots,\scr{A}_{i-1},\scr{C},\scr{A}_{i+1},\ldots,\scr{A}_r;\scr{B}_1,\ldots,\scr{B}_{j-1},\scr{C},\scr{B}_{j+1},\ldots,\scr{B}_s)
  \\\to -T_{r-1}^{(s-1)\bullet}(\scr{A}_1,\ldots,\widehat{\scr{A}_i},\ldots,\scr{A}_r;\scr{B}_1,\ldots,\widehat{\scr{B}_j},\ldots,\scr{B}_s).
  \end{gathered}
\tag{8.4}
$$
:::

Furthermore, if some argument $\scr{A}_i$ is a locally-free sheaf, then we can suppress it by replacing one of the $\scr{A}_j$ (for $j\neq i$) by $\scr{A}_j\otimes\scr{A}_i$, or one of the $\scr{B}_k$ by $\scr{B}_k\otimes\scr{A}'_i$ (where $\scr{A}'_i=\shHom_{\scr{O}_X}(\scr{A}_i,\scr{O}_X$);
we have an analogous rule for the case where one of the arguments $\scr{B}_j$ is locally free.
In particular, we can always suppress any argument that is equal to $\scr{O}_X$.
If all the arguments are locally free, except for at most one of the arguments $\scr{B}_i$, then the rule that we have just stated gives a functorial isomorphism
$$
  T_r^{s\bullet}(\scr{A}_1,\ldots,\scr{A}_r;\scr{B}_1,\ldots,\scr{B}_s)
  = \HH^\bullet(X,\scr{A}'_1\otimes\ldots\otimes\scr{A}'_{r}\otimes\scr{B}_1\otimes\scr{B}_s)
\tag{8.5}
$$
(since we can restrict to the case where $r=0$ and $s=1$, and there it is immediate;
we can also directly use the spectral sequence whose initial term is [(8.2)](#FGA-1-equation-8.2)).
The corresponding operations of all the above can also be defined for the $\underline{T}_r^s$.
The relations between the various operations thus introduced are the same as for the analogous relations in tensor calculus.

Now let $n$ be the dimension of $X$.
By successively applying a tensor composition [(8.3)](#FGA-1-equation-8.3) and contractions [(8.4)](#FGA-1-equation-8.4) on repeated arguments, we obtain a pairing

::: {.eqref #FGA-1-equation-8.6 title="" data-latex=""}
$$
  \begin{gathered}
    (T_r^s)^p(\scr{A}_1,\ldots;\scr{B}_1,\ldots)
    \times (T_r^s)^{n-p}(\scr{B}_1,\ldots;\scr{A}_1,\ldots,\scr{A}_r\otimes\Omega_X^n)
  \\\longrightarrow\HH^n(X,\Omega_X^n).
  \end{gathered}
\tag{8.6}
$$
:::

::: {.itenv #FGA-1-theorem-6 title="Theorem 6" data-latex="{Theorem 6}"}
If $X$ is a non-singular projective variety, then the pairings in [(8.6)](#FGA-1-equation-8.6) are dualities.
:::

::: {.proof}
This follows in a purely formal way from the [corollary of Theorem 3](#FGA-1-theorem-3-corollary).
In fact, it easily follows from this corollary that, if $\scr{K}$ is a complex of _locally-free_ coherent algebraic sheaves, then the hypercohomology of $X$ with respect to $\scr{K}$ is in duality with the hypercohomology of $X$ with respect to $\scr{K}'\otimes\Omega_X^n$ via the natural pairings
$$
  \underline{\RR}^p\Gamma(\scr{K})
  \times \underline{\RR}^{n-p}\Gamma(\scr{K}'\otimes\Omega_X^n)
  \to \underline{\RR}^n\Gamma(\Omega_X^n)
  = \HH^n(X,\Omega_X^n).
\tag{8.7}
$$
We can see this by using the spectral sequence with initial page $\HH^p(\HH^q(X,\scr{K}))$ and the analogous spectral sequence for $\scr{K}'\otimes\Omega_X^n$.
From the above result, [Theorem 6](#FGA-1-theorem-6) can be deduced from the definition [(8.1)](#FGA-1-equation-8.1).
:::

\oldpage{149-24}

::: {.rmenv title="Remarks" data-latex="{Remarks}"}
—

1. For the definitions preceding [Theorem 6](#FGA-1-theorem-6), it was not necessary for $X$ to be non-singular, since it was not necessary to work with only _finite_ resolutions.
    But, if $X$ is singular, then we can no long be sure, a priori, that the $(\underline{T}_r^s)^p(\scr{A}_1,\ldots;\scr{B}_1,\ldots)$ are _coherent_ sheaves, since, in the complex of sheaves
    $$
      \shHom_{\scr{O}_X}(\underline{L}(\scr{A}_1)\otimes\ldots,\underline{L}(\scr{B}_1)\otimes\ldots)
    $$
    there will be an infinite number of components of any given total degree.

2. We can easily verify that, in the formulas in [(8.1)](#FGA-1-equation-8.1), we can replace _one_ of the $\underline{L}(\scr{B}_i)$ with $\scr{B}_i$.
    Taking [Proposition 3](#FGA-1-proposition-3) into account, this shows that we have
    $$
      \begin{aligned}
        \underline{T}_1^{1\bullet}(\scr{A};\scr{B})
        &= \shExt_{\scr{O}_X}^\bullet(\scr{A},\scr{B})
      \\T_1^{1\bullet}(\scr{A};\scr{B})
        &= \Ext_{\scr{O}_X}^\bullet(X;\scr{A},\scr{B}).
      \end{aligned}
    \tag{8.8}
    $$
    In particular, taking $r=s=1$ and $\scr{A}_1=\scr{O}_X$ in [(8.6)](#FGA-1-equation-8.6), we recover [Theorem 3](#FGA-1-theorem-3).
    Equation (8.8) also implies that $T_0^{1\bullet}(\scr{B})=\HH^\bullet(X,\scr{B})$, and that $T_1^{0\bullet}(\scr{A})=\Ext_{\scr{O}_X}^\bullet(X;\scr{A},\scr{O}_X)$.

3. We see, in [(8.1)](#FGA-1-equation-8.1), that the functors $\underline{T}_r^{s\bullet}$ and $T_r^{s\bullet}$ have, in general, components in positive _and_ negative degrees.
    Using the above remark, we see that, if the dimension of $X$ is $n$, then the non-zero components of $\underline{T}_r^{s\bullet}$ are concentrated between degrees $-(s-1)n$ and $rn$ if $s>0$, and between degrees $0$ and $rn$ if $s=0$; the non-zero components of $T_r^{s\bullet}$ are concentrated between degrees $-(s-1)n$ and $(r+1)n$ if $s>0$, and between degrees $0$ and $(r+1)n$ if $s=0$ (and, unless I am mistaken, if $r>0$, between degrees $-(s-1)n$ and $rn$, resp. $0$ and $rn$).
:::
