# Hilbert schemes {#fga-3.iv}

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\Tor}{\operatorname{Tor}}
\providecommand{\shTor}{\mathscr{T}\kern -.5pt or}
\providecommand{\Ext}{\operatorname{Ext}}
\providecommand{\shExt}{\mathscr{E}\kern -.5pt xt}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\shHom}{\mathscr{H}\kern -.5pt om}
\providecommand{\repHom}{\underline{\Hom}}
\providecommand{\supp}{\operatorname{supp}}
\providecommand{\red}{{\mathrm{red}}}
\providecommand{\OO}{\scr{O}}
\providecommand{\PP}{\mathbb{P}}
\providecommand{\Quot}{\operatorname{Quot}}
\providecommand{\shQuot}{\mathscr{Q}\kern -.5pt out}
\providecommand{\repQuot}{\underline{\Quot}}
\providecommand{\Grass}{\operatorname{Grass}}
\providecommand{\shGrass}{\mathscr{G}\kern -.5pt rass}
\providecommand{\repGrass}{\underline{\Grass}}
\providecommand{\Hilb}{\operatorname{Hilb}}
\providecommand{\shHilb}{\mathscr{H}\kern -.5pt ilb}
\providecommand{\repHilb}{\underline{\Hilb}}
\providecommand{\repPic}{\underline{\Pic}}
\providecommand{\repIsom}{\underline{\operatorname{Isom}}}
\providecommand{\repImm}{\underline{\operatorname{Imm}}}
\providecommand{\FXS}{{\scr{F}/X/S}}
\providecommand{\FXSp}{{\scr{F}'/X'/S'}}
\providecommand{\RR}{\operatorname{R}}
\providecommand{\rank}{\operatorname{rank}}
\providecommand{\Spec}{\operatorname{Spec}}
\providecommand{\Symm}{\operatorname{Symm}}

<!-- Content -->

::: {.original-citation}
[FGA 3.IV]
Grothendieck, A.
"Technique de descente et théorèmes d'existence en géométrie algébrique, IV: Les schémas de Hilbert".
_Séminaire Bourbaki_ **13** (1960--61), Talk no. 221.
:::

## Introduction {-}

\oldpage{221-01}

The techniques described in [@Gro1959, I and II] were, for the most part, independent of any projective hypotheses on the schemes in question.
Unfortunately, they have not as of yet allowed us to solve the existence problems posed in [FGA 3.II](FGA-3-II.html).
In the current article, and the following, we will solve these problems by imposing projective hypotheses.
The techniques used are typically projective, and practically make no use of any results from [@Gro1959, I and II].
Here we will construct "Hilbert schemes", which are meant to replace the use of Chow coordinates, as was mentioned in [@Gro1959, II, §2].
In the next article, the theory of passing to the quotient in schemes, developed in [FGA 3.III](FGA-3-III.html), combined with the theory of Hilbert schemes, will allow us, for example, to construct Picard schemes (defined in [@Gro1959, II, §3]) under rather general conditions.

In summary, we can say that we now have a more or less satisfying technique of projective constructions, apart from the fact that we are still missing^[See the addendum at the end of this article.] a theory of passing to the quotient by groups such as the projective group, acting "without fixed points" (cf. [@Gro1959, III, §8]).
The situation even seems slightly better in analytic geometry (if we restrict to the study of "projective" analytic spaces over a given analytic space), since, for analytic spaces, the difficulty of passing to the quotient by a group that acts nicely disappears.
Either way, in algebraic geometry, as well as in analytic geometry, it remains to develop a construction technique that works without any projective hypotheses.


## Bounded sets of sheaves: invariance properties {#fga-3-iv-section-1}

Let $k$ be a field, and $X$ a $k$-prescheme (which we take to be of finite type, for simplicity).
For every extension $K/k$, we obtain a $K$-prescheme $X_K=X\otimes_k K$.
If $\scr{F}$ is a coherent sheaf on $X_K$, and if $K'$ is an extension of $K$, then $\scr{F}\otimes_K K'=\scr{F}_{K'}$ is a quasi-coherent sheaf on $X_K\otimes_KK'=X_{K'}$.
\oldpage{221-02}So, if $K$ and $K'$ are arbitrary extensions of $k$, and $\scr{F}$ a quasi-coherent sheaf on $X_K$ and $\scr{F}'$ a quasi-coherent sheaf on $X_{K'}$, then we say that $\scr{F}$ and $\scr{F}'$ are _equivalent_ if there exists an extension $K''/k$ as well as $k$-homomorphisms $K\to K''$ and $K'\to K''$ such that $\scr{F}_{K''}$ and $\scr{F}'_{K''}$ are isomorphic over $X_{K''}$.
This defines an equivalence relation, and we are interested in the equivalence classes of sheaves under this relation, and of sets of such equivalence classes.
Note that, if $X_0$ is of finite type over $k$, then every class of coherent sheaves can be defined by a coherent sheaf on $X_K$, where $K$ is some extension of $k$ _of finite type_.
We can thus, in the definition of classes of coherent sheaves, restrict ourselves to _algebraically closed_ extensions of $k$, and we can also restrict ourselves to a fixed algebraically closed extension $\Omega$ of $k$, of infinite transcendence degree;
two coherent sheaves $\scr{F}$ and $\scr{F}'$ on $X_\Omega$ are then equivalent if and only if there exists a $K$-automorphism $\sigma$ of $\Omega$ such that $\scr{F}\otimes_K(\Omega,\sigma)$ is isomorphic to $\scr{F}'$.
Note that there is a bijective correspondence between classes of coherent sheaves under the first definition and under the second.

Let $E$ and $E'$ be two sets of classes of coherent sheaves on $X$.
Consider the classes of all sheaves of the form $\scr{F}\otimes\scr{F}'$, where $\scr{F}$ and $\scr{F}'$ are coherent sheaves on the _same_ $X_K$, with the class of $\scr{F}$ being in $E$ and the class of $\scr{F}'$ being in $E'$.
We thus define a set of classes of coherent sheaves that we denote by $E\otimes E'$.
We can similarly define $\shTor_i(E,E')$, etc.
Generally, to every function $\scr{U}$ that sends each sequence $\scr{F}_1,\ldots,scr{F}_n$ of $n$ coherent sheaves on one single $X_K$ to a set $\scr{U}(\scr{F}_1,\ldots,\scr{F}_n)$ of coherent sheaves on $X_K$, and that has the evident property of compatibility with isomorphisms of sheaves and inverse images under change of base, we associate a function, denoted by the same notation $\scr{U}$, that sends each sequence $E_1,\ldots,E_n$ of $n$ sets of classes of coherent sheaves to a set $\scr{U}(E_1,\ldots,E_n)$ of classes of coherent sheaves.

Our aim in this section is to give a definition of certain sets of classes of sheaves, said to be _bounded_, and to show that the most standard operations $\scr{U}$, applied to bounded sets, give sets that are again bounded.

Let $X$ be a prescheme of finite type over $S$, with $S$ _Noetherian_.
For all $s\in S$, the fibre $X_s$ is a prescheme of finite type over $k(s)$, and we will consider the classes of coherent sheaves on $X_s$, in the above sense.
This gives meaning to the phrase "class of coherent sheaves on a fibre of $X/S$", as well as to analogous phrases.
Similarly, proceeding separately on each fibre, we can again consider operations such as $E\otimes E'$ etc. that send systems of sets of classes of coherent sheaves on the fibres of $X/S$ to sets of classes of coherent sheaves on the fibres of $X/S$.
\oldpage{221-03}

::: {.rmenv #fga-3-iv-definition-1.1 title="Definition 1.1" latex="{Definition 1.1}"}
Let $E$ be a set of classes of coherent sheaves on the fibres of $X/S$.
We say that $E$ is _bounded_ if there exists a prescheme $S'$ of finite type over $S$, along with a coherent sheaf $\scr{F}'$ on $X'=X\times_S S'$, such that $E$ is contained in the set of classes of sheaves on the fibres of $X/S$ defined by $\scr{F}'$.
:::

This construction, by definition, sends $s\in S$ to the classes of sheaves $\scr{F}'\otimes_{S'}k(s')$, where $s'$ runs over the points of $S'$ over $s$ (so that $k(s')$ is an extension of $k(s)$, and $X\otimes (X_s)_{k(s')}$ can be identified with the fibre $X'\otimes_{S'}k(s')=X'_{s'}$ of $X'$ at $s'$).
We can say that the bounded sets are those that are contained in an _algebraic family_ of coherent sheaves, parametrised by some $S'$ of finite type over $S$.

A finite union of bounded sets is bounded (take the prescheme given by the sum of the parametrising preschemes $S_i$ defining the bounding algebraic families).
A base change $T\to S$ sends a family which is bounded with respect to $X/S$ to a family which is bounded with respect to $X_T/T$, and the converse is true if $T\to S$ is surjective (or, more generally, if its image contains the $s$ which appear in the given family $E$ for $X/S$).
This theoretically leads us to determine the bounded families only in the case where $S$ is the spectrum of an algebra of finite type over the ring of integers $\mathbb{Z}$.

If $E$ and $E'$ are bounded families of classes of sheaves with respect to $X/S$, then $E\otimes E'$ is also bounded:
indeed, if $E$ (resp. $E'$) is bounded by the algebraic families defined by $T\to S$ and $\scr{F}$ on $X_T$ (resp. $T'\to S$ and $\scr{F}'$ on $X_{T'}$), then $E\otimes E'$ is bounded by the algebraic family defined by $T''=T\times_S T'\to S$ and the sheaf $\scr{F}''$ on $X_{T''}$ given by the tensor product of the inverse images of $\scr{F}$ and $\scr{F}'$ on $X_{T''}$.
This argument is correct only because the functor $\scr{F}\otimes\scr{F}'$ is right exact in both $\scr{F}$ and $\scr{F}'$, and thus commutates with base extension (and, in particular, with passing to the fibres).
It is not applicable as-is to local operations, such as $\shTor_i(E,E')$, $\shHom(E,E')$, $\shExt^i(E,E')$.
We can, however, show that these operations also send bounded sets to bounded sets, by proceeding as for $E\otimes E'$, but by also using results of the following type (all contained in [@Gro1960b, IV 6.11]):
a bounded family $E$ is always bounded by an algebraic family defined by a coherent sheaf $\scr{F}$ on some $X_T$ (with $T$ of finite type over $S$) that is _flat_ with respect to $T$.
(We "cut into bits" the initial space of parameters).
\oldpage{221-04}
Such flatness properties on suitable sheaves indeed ensure the commutativity of operations such as $\shTor_i(\scr{F},\scr{F}')$ with arbitrary base change.
The same method applies to operations of a global nature:
direct images and derived direct images of coherent sheaves under proper morphisms, global $\Ext$ with respect to proper morphisms (cf. [@GD1960, III §6]), etc.;
all these operations send bounded families of sheaves to bounded families of sheaves (N.B. here the preschemes over which we are taking the various sheaves can change under the operations in question).

The two claims that follow can be proven by _essentially_ the same flatness technique;
for the primary decomposition on the fibres of a morphisms of finite type, see, in particular, [@GD1960, IV].

::: {.itenv #fga-3-iv-proposition-1.2 title="Proposition 1.2" latex="{Proposition 1.2}"}
Let $E$ and $E'$ be bounded sets of classes of sheaves on the fibres of $X/S$, with $X$ assumed to be proper over $S$.
Then

i. the family of kernels, cokernels, and images of homomorphisms $\scr{F}\to\scr{F}'$ (where the class of $\scr{F}$ is in $E$ and the class of $\scr{F}'$ is in $E'$) is bounded;
ii. the family of extensions $\scr{F}''$ of $\scr{F}$ by $\scr{F}'$ (where the class of $\scr{F}$ is in $E$ and the class of $\scr{F}'$ is in $E'$) is bounded.
:::

::: {.proof}
After potentially applying a suitable base change, we can suppose that $E$ and $E'$ are defined by coherent sheaves $\scr{G}$ and $\scr{G}'$ (respectively) on some $X_T/T$, with $T$ of finite type over $S$.
Further, we can suppose that certain flatness hypotheses are satisfied, implying that constructing the sheaves $f_T(\shHom_{\cal{O}_{X_T}}(\scr{G},\scr{G}'))$ and $\shExt_{f_T}^1(\scr{G},\scr{G}')$ commutes with base change by an arbitrary morphism $T'\to T$.
Further, we can suppose that the coherent sheaves above are locally free on $T$.
So let $T_0$ and $T_1$ be the vector bundles on $T$ whose sheaves of germs of sections are (respectively) the above sheaves.
We can then canonically define a homomorphism $\scr{G}_{T_0}\to\scr{G}'_{T_0}$ of coherent sheaves on $X_{T_0}$, along with an extension
$$
  0 \to \scr{G}_{T_1} \to \scr{G}'' \to \scr{G}'_{T_1} \to 0
$$
of coherent sheaves on $X_{T_1}$ that has the evident universal property.
This second sheaf defines an algebraic family that bounds the family in question in (ii).
\oldpage{221-05}
This is also true for the kernel, cokernel, and image of the above homomorphism, and the consideration of this proves (i) (provided that we assume the cokernel to be flat with respect to $T_0$, in which case we can again reduce to cutting $T_0$ into pieces...).
:::

::: {.itenv #fga-3-iv-proposition-1.3 title="Proposition 1.3" latex="{Proposition 1.3}"}
Let $E$ be a bounded family of classes of sheaves on the fibres of $X/S$.
Then the classes of the structure sheaves of the $(\supp\scr{F})_\red$, where $\scr{F}$ is a coherent sheaf on some $X_K$, with $K$ algebraically closed, and whose class is in $E$, form a bounded family.
:::

Here, $(\supp\scr{F})_\red$ denotes the support of $\scr{F}$, endowed with the induced reduced structure, i.e. its structure sheaf is the quotient of $\cal{O}_{X_K}$ by the largest sheaf of ideals that defines $\supp\scr{F}$.
We can prove the analogous result to [(1.3)](#fga-3-iv-proposition-1.3) for the sheaves canonically induced from $\scr{F}$ by the theory of primary decomposition;
for example, the $\scr{F}/\scr{F}_i$, where the $\scr{F}_i$ are the primary subsheaves of $\scr{F}$ for the components of the support of $\scr{F}$, and minimal with respect to this property;
or the $\cal{O}_{X_K}/\frak{p}$, where $\frak{p}$ is a prime sheaf of ideals associated to $\scr{F}$, or the $\cal{O}_{X_K}/\frak{q}$, where the $\scr{q}$ is a primary sheaf of ideals associated to a component of the support of $\scr{F}$ (the reference field being algebraically closed).

## Bounded families and the Hilbert polynomial {#fga-3-iv-section-2}

In the following, we assume that $X$ is projective over $S$, and endowed with a very ample sheaf, denoted by $\cal{O}_X(1)$.
For every extension $K$ of a residue extension $k(s)$ of a point $s$ of $S$, we consider the corresponding sheaf $\cal{O}_{X_K}(1)$ on $X_K$, which will again be very ample.

To each coherent sheaf $\scr{F}$ on $X_K$, we associate the function
$$
  P_\scr{F}(n) = \text{the Euler--Poincaré characteristic of }\scr{F}(n)\text{ on }X_k
$$
which is a polynomial in the integer $n$, and called the _Hilbert polynomial_ of $\scr{F}$.
For large values of $n$, $P(n)$ is exactly the dimension of $\HH^0(X_k,\scr{F}(n))$ over $K$, since the $\HH^i(X_k,\scr{F}(n))$ are zero for $i>0$ and large enough $n$.

Now, if $\scr{F}$ is a coherent sheaf on $X$ which is _flat_ with respect to $S$, then the Hilbert polynomials of the sheaves $\scr{F}_S$ induced on the fibres $X_S$ (with respect to one single connected component of $S$) are all equal [@GD1960, III, §7].
It thus follows (without any flatness hypothesis) that the set of Hilbert polynomials of the sheaves $\scr{F}_s$, for $s\in S$, is finite for every coherent sheaf $\scr{F}$ on $X$.

\oldpage{221-06}

Recall also that, if $\scr{F}$ is a coherent sheaf on $X$, then it is isomorphic to a quotient sheaf of a sheaf of the form $\OO_X(-n)^N$, for some large enough $n,N$.
So the sheaves $\scr{F}_s$ induced on the fibres are also quotients of the sheaf $\OO(-n)$ on the fibre.

From these two remarks, we reduce the "necessary" part of the following theorem:

::: {.itenv #fga-3-iv-theorem-2.1 title="Theorem 2.1" latex="{Theorem 2.1}"}
Let $X$ be projective over $S$, with $S$ Noetherian, and $\OO_X(1)$ very ample over $X$ with respect to $S$.
Let $E$ be a set of classes of sheaves on the fibres of $X/S$.
For $E$ to be bounded, it is necessary and sufficient that it satisfy the following conditions:

a. There exists a coherent sheaf $\scr{L}$ on $X$ (which we can suppose to be of the form $\OO_X(-n)^N$) such that $E$ is contained in the family of classes of coherent sheaves given by quotients of sheaves of the form $\scr{L}_K$;
b. The Hilbert polynomials $P_\scr{F}$ of the sheaves $\scr{F}$ whose class is in $E$ are elements of a single _finite_ set of polynomials.
:::

It remains to prove the "sufficient" part, which will be a particular case of a more precise result.
For every coherent module $\scr{F}$ on a prescheme of finite type over a field $K$, and for every integer $r$, let $N_r$ be the submodule of $\scr{F}$ whose sections over an open subset are the sections of $\scr{F}$ over the same subset whose support is of dimension $<r$.
We thus have that $N_r=\scr{F}$ for $r>\dim\supp\scr{F}$, and $N_r=0$ for $r\leq0$, and we thus obtain a finite increasing filtration of $\scr{F}$ whose factors $N_r/N_{r+1}$ are such that their associated prime cycles are exactly the associated prime cycles of $\scr{F}$ that are of dimension $r$.
We set
$$
  \scr{F}_{(r)} = \scr{F}/N_r
$$
so that the associated prime cycles of $\scr{F}_{(r)}$ are exactly the associated prime cycles of $\scr{F}$ that are of dimension $\geq r$, and, in particular, $\scr{F}_{(r)}$ is equal to $\scr{F}$ if and only if the associated prime cycles of $\scr{F}$ are of dimension $\geq r$.
With this, we have:

::: {.itenv #fga-3-iv-theorem-2.2 title="Theorem 2.2" latex="{Theorem 2.2}"}
Under the conditions of [Theorem 2.1](#fga-3-iv-theorem-2.1), let $s$ be an integer, and suppose that $E$ satisfies condition (a), as well as the following weakened form of (b):

- (b<sub>s</sub>) The Poincaré polynomials $P_\scr{F}$ of the sheaves $\scr{F}$ whose class is in $E$ have coefficients _in degrees $\leq (s-1)$_ that are bounded.

Under these conditions, the sheaves $\scr{F}_{(s)}$ (for the $\scr{F}$ whose class is in $E$) form a bounded family.
Furthermore, the coefficients in degree $(s-2)$ of the $P_\scr{F}$ are bounded below.
:::

\oldpage{221-07}

Thus:

::: {.itenv #fga-3-iv-corollary-2.3 title="Corollary 2.3" latex="{Corollary 2.3}"}
Suppose that the sheaves $\scr{F}$ whose class is in $E$ are such that all their associated prime cycles are of dimension $d$, with $s\leq d\leq r$.
Then, in condition (b) of [Theorem 2.1](#fga-3-iv-theorem-2.1), we can restrict to the coefficients of $P_\scr{F}$ between degree $(s-1)$ and $r$, inclusive.
:::

The end of this section is dedicated to a sketch proof of [Theorem 2.2](#fga-3-iv-theorem-2.2).
The key lemmas are the two following lemmas, of which the first is well known (and summarises the useful mathematical content of Chow coordinates):

::: {.itenv #fga-3-iv-lemma-2.4 title="Lemma 2.4 (Chow)" latex="{Lemma 2.4 (Chow)}"}
Consider the structure sheaves of the subschemes $Y$ with fibre $X_K$ (where $K$ is an algebraically closed extension of the residue field of $S$), where $Y$ is reduced, and all its components are of the same dimension $r$ (and with $\OO_Y$ being thought of as a quotient sheaf of $\OO_X$).
If the degrees of $Y$ are bounded, then the $Y$ form a bounded family.
:::

Here, the degree $a$ of $Y$ can be most conveniently defined as the coefficient of the dominant term of $P_{\OO_Y}=an^r/r!+\ldots$.

::: {.itenv #fga-3-iv-lemma-2.5 title="Lemma 2.5" latex="{Lemma 2.5}"}
Let $\scr{L}$ be a coherent sheaf on $X$, and $E$ a set of classes of the quotient sheaves $\scr{F}$ of the sheaf $\scr{L}_K$ (where $K$ is a residue extension of $S$).
Suppose that the fibres of $X$ over $S$ are of dimension $\leq r$, and set
$$
  P_\scr{F}(n) = a_\scr{F}n^r/r! + b_\scr{F}n^{r-1}/(r-1)! + \text{terms of degree }<r-1.
$$
Then the coefficient $a_\scr{F}$ is bounded (above), and $b_\scr{F}$ is bounded below.
If $b_\scr{F}$ is bounded, then the family $\scr{F}_{(r)}$ is bounded.
:::

::: {.proof}
By replacing $S$ by a union of subschemes of $S$ that cover $S$, we can suppose that there exists a *finite* morphism $f\colon X\to\PP_S^r$ such that $\OO_X(1)$ is isomorphic to the inverse image of $\OO_{\PP_S^r}(1)$, and thus, for every coherent sheaf $\scr{F}$ on $X$, we have that $P_\scr{F}=P_{f_*(\scr{F})}$.
We can also easily show (by the technique of the previous section) that a set of sheaves $\scr{F}$ on $X$ is bounded if and only if the set of $f_*(\scr{F})$ is bounded.
Finally, we have that
$$
  f_*(\scr{F})_{(r)} = f_*(\scr{F}_{(r)}).
$$
\oldpage{221-08}
This thus allows us to reduce to the case where $X=\PP_S^r$.
Furthermore, we can suppose that $\scr{L}=\OO_{\PP_S^r}(k)^s$, for some suitable $k$ and $s$.
The coefficient $a_\scr{F}$ satisfies
$$
  0\leq a_\scr{F} \leq s
$$
and is thus bounded.
With this in mind, saying that the $n^{r-1}$ coefficient $P_\scr{F}(n)$ is bounded below (resp. bounded) is equivalent to saying the same thing for the $P_\scr{F}(n-k)=P_{\scr{F}(-k)}(n)$.
This leads us to the case where
$$
  \scr{L} = \OO_{\PP_S^r}^s.
$$

Consider the exact sequence
$$
  0 \to N_r \to \scr{F} \to \scr{F}_{(r)} \to 0
$$
whence
$$
  P_\scr{F} = P_{\scr{F}_{(r)}} + P_{N_r}
$$
and, since the $n^{r-1}$ coefficient of $P_{N_r}$ is positive (since $\dim\supp N_r\leq r-1$), we have that
$$
  b_{\scr{F}_{(r)}} \leq b_\scr{F}.
$$
This allows us, in proving the lemma, to replace $\scr{F}$ by $\scr{F}_{(r)}$, i.e. to suppose that the quotients $\scr{F}$ of $\scr{L}$ in question are torsion free.

Since $\PP_K^r$ is normal, it follows that $\scr{F}$ is locally free of rank $a=a_\scr{F}$ on an open $U=\PP_K^r\setminus Y$, where $Y$ is of codimension $\geq2$.
Thus $\bigwedge^a\scr{F}$ is a sheaf on $\PP_K^r$ whose restriction to $U$ is invertible, and thus (since $\PP_K^r$ is regular, and $Y$ is of codimension $\geq2$) isomorphism to the restriction of an invertible sheaf on $\PP_K^r$, defined up to isomorphism.
This latter sheaf is of the form $\OO_{\PP_K^r}(d)$ for some well defined integer $d$.
Since $\bigwedge^a\scr{F}$ is a quotient of $\bigwedge^a\OO_{\PP_K^r}^n\simeq\OO_{\PP_K^r}^N$ with $N=\binom{n}{a}$, it admits $N$ canonical sections, which thus define sections of $\OO_{\PP_K^r}(d)$ over $U$, which are restrictions of sections $s_i$ (for $1\leq i\leq N$) of $\OO_{\PP_K^r}(d)$ (since $\PP_K^r$ is normal, and $Y$ is of codimension $\geq2$).
\oldpage{221-09}
These $s_i$ generate $\OO_{\PP_K^r}(d)$ at the points of $U$, and are thus not all zero, which implies that $d\geq0$.
An easy calculation also shows that
$$
  b_\scr{F} = a_\scr{F}(r+1)/2 + d.
$$
This shows, in particular, that $b_\scr{F}\geq0$, and so $b_\scr{F}$ is bounded below.
It is bounded if and only if $d$ is bounded;
we will show that $\scr{F}$ then remains in a bounded family.
We can fix $a_\scr{F}$ and $b_\scr{F}$, as well as $a$ and $b$ (and thus $d$).
The data of the $N$ sections $s_i$ of $\OO_{\PP_K^r}(d)$, i.e. of a homomorphism $s\colon\bigwedge^a\scr{L}_K\to\OO_{\PP_K^r}(d)$, allows us to recover $\scr{F}$ as the co-image of the corresponding composite homomorphism:
$$
  \scr{L}_K
  \to \shHom\left( \bigwedge^{a-1}\scr{L}_{K'}, \bigwedge^a\scr{L}_K \right)
  \to \shHom\left( \bigwedge^{a-1}\scr{L}_{K'}, \OO_{\PP_K^r}(d) \right)
$$
where the first arrow is the canonical homomorphism coming from the exterior product, and the second comes from $s$.
We then conclude by part (i) of [(1.2)](#fga-3-iv-proposition-1.2).
:::

The combination of the two lemmas above allows us to prove the following:

::: {.itenv #fga-3-iv-lemma-2.6 title="Lemma 2.6" latex="{Lemma 2.6}"}
Suppose, under the preliminary conditions of [(2.1)](#fga-3-iv-theorem-2.1), that, for all $\scr{F}$, we have
$$
  P_\scr{F}(n) = a_\scr{F} n^r/r! + b_\scr{F} n^{r-1}/(r-1)! + \text{terms of degree }<r-1
$$
and that the coefficients $a_\scr{F}$ are bounded.
Then the coefficients $b_\scr{F}$ are bounded below..
Furthermore, if the $b_\scr{F}$ are bounded, then the $\scr{F}_{(r)}$ are bounded.
:::

::: {.proof}
We can suppose that the base field $K$ of the sheaves $\scr{F}$ is algebraically closed.
We endow each $\supp\scr{F}_{(r)}$(the union of the components of degree $r$) with the induced reduced structure.
Then the degrees of the $\supp\scr{F}_{(r)}$ are bounded above by $a$, and so, by [(2.4)](#fga-3-iv-lemma-2.4), the $\supp\scr{F}_{(r)}$ form a bounded set.
Furthermore, for each component of $\supp\scr{F}_{(r)}$, the length of $\scr{F}_{(r)}$ for this component is $\leq a$, and so, if $\scr{I}_\scr{F}$ is the ideal that defines $\supp\scr{F}_{(r)}$, then $\scr{F}_{(r)}$ can be considered as a module on the subscheme $Y_\scr{F}$ of $X$ defined by $\scr{I}_\scr{F}^a$.
\oldpage{221-10}
As in the previous lemma, we can also reduce to the case where $\scr{F}=\scr{F}_{(r)}$, so that $\scr{F}$ comes from a module on $Y_\scr{F}$.
The $Y_\scr{F}$ correspond to a bounded family of quotient modules of the $\OO_{X_K}$, and thus come from a closed subscheme $Y$ of some scheme $X\times_S T$.
We can then apply [(2.5)](#fga-3-iv-lemma-2.5) to $Y/T$ and $\scr{L}\otimes_X Y$, whence the conclusion.
:::

::: {.proof}
We can now prove [(2.2)](#fga-3-iv-theorem-2.2) by induction on the upper bound $r$ of the $\dim\supp\scr{F}$.
The statement is trivial for $r<0$, so suppose that $r\geq0$ and that the statement has been proven for $r'<r$.
By [(2.6)](#fga-3-iv-lemma-2.6), the $\scr{F}_{(r)}$ form a bounded family, and so too, by part (i) of [(1.2)], do the kernels of the homomorphisms $\scr{L}_K\to\scr{F}_{(r)}$;
there thus exists a coherent module $\scr{L}'$ on $X$ such that kernels in question, and thus also the $N_r(\scr{F})=\Ker(\scr{F}\to\scr{F}_{(r)})$, are quotients of modules $\scr{L}'_K$.
Since the $\scr{F}_{(r)}$ are bounded, the $P_{\scr{F}_{(r)}}$ are bounded, and the formula
$$
  P_\scr{F} = P_{\scr{F}_{(r)}} + P_{N_r}
$$
then shows that the $P_{N_r}$ satisfy the same condition (b<sub>s</sub>) as the $P_\scr{F}$.
Thus the $N_r$ satisfy conditions (a) and (b<sub>s</sub>), and so, by the induction hypothesis, the $(N_r)_{(s)}$ are bounded.
But $\scr{F}_{(s)}$ is an extension of $\scr{F}_{(r)}$ by $(N_r)_{(s)}$, and so, by part (ii) of [(1.2)](#fga-3-iv-proposition-1.2), the $\scr{F}_{(s)}$ are bounded.
For the last claim of [(2.2)](#fga-3-iv-theorem-2.2), we note that the kernels $N_s$ of $\scr{F}\to\scr{F}_{(s)}$ are bounded, by part (i) of [(1.2)](#fga-3-iv-proposition-1.2), and that the coefficient of the $n^{s-1}$ term in $P_{N_s}$ is bounded;
then [(2.6)](#fga-3-iv-lemma-2.6) proves that the coefficient of the following term is bounded below.
This finishes the proof
:::


## Hilbert schemes: definition, existence theorem {#fga-3-iv-section-3}

Let $X$ be a prescheme over another prescheme $S$, and $\scr{F}$ a quasi-coherent module on $X$.
We denote by
$$
  \Quot(\FXS)
$$
the set of quasi-coherent modules given by quotients of $\scr{F}$ that are flat over $S$.
Now let $S'\to S$ be a base change morphisms, and set $X'=X\times_S S'$, and $\scr{F}'=\scr{F}\otimes_{\OO_S}\OO_{S'}$, so that $X'$ is a prescheme over $S'$ endowed with a quasi coherent module $\scr{F}'$, and we can consider $\Quot(\FXSp)$.
\oldpage{221-11}
We set
$$
  \shQuot_{\FXS}(S') = \Quot(\FXSp)
$$
(where $X'=X\times_S S'$, as above).

Now, if $S''\to S'$ is an $S$-morphism, then $X''=X\times_S S''$ is isomorphic to $X'\times_{S'}S''$, and $\scr{F}''$ is isomorphic to $\scr{F}'\otimes_{\OO_{S'}}\OO_{S''}$, and, since the inverse image functor $\scr{G}'\mapsto\scr{G}'\otimes_{\OO_{S'}}\OO_{S''}$ from the category of quasi-coherent modules on $X''$ is right exact, and sends $S'$-flat modules to $S''$-flat modules, we obtain a natural map
$$
  \Quot(\FXSp) \to \Quot(\scr{F}''/X''/S'')
$$
and so $\shQuot_{\FXS}(S')$ is a *contravariant functor in $S'$* (where $S'$ is a prescheme over $S$), with values in the categories of sets.
In what follows, we suppose that $X$ is *projective* over a *Noetherian* $S$, with $\scr{F}$ *coherent*;
for simplicity, we will limit ourselves to considering those $S'$ which are *locally Noetherian* over $S$.

::: {.itenv #fga-3-iv-theorem-3.1 title="Theorem 3.1" latex="{Theorem 3.1}"}
Under these conditions, the contravariant functor $\shQuot_{\FXS}$ on the category of locally Noetherian $S$-preschemes is *representable* by an $S$-prescheme $\repQuot_{\FXS}$, given by the sum of a sequence of projective $S$-schemes (and a fortiori $\repQuot_{\FXS}$ is locally of finite type over $S$).
:::

We will obtain such a decomposition in the following way.
Let $\OO_X(1)$ be an invertible sheaf on $X$ that is very ample with respect to $S$.
For every polynomial $P(n)$ with rational coefficients, let $\Quot^P(\FXS)$ be the subset of $\Quot(\FXS)$ consisting of coherent quotients $\scr{G}$ of $\scr{F}$ that are flat over $S$ and whose Hilbert polynomial at each $s\in S$ is equal to $P$.
We then set
$$
  \shQuot_\FXS^P(S') = \Quot^P(\FXSp)
$$
and thus obtain a subfunctor of $\shQuot_\FXS$.
The invariance property of Hilbert polynomials (recalled in [§2](#fga-3-iv-section-2)) implies the following:
*For $\shQuot_\FXS$ to be representable, it is necessary and sufficient that the $\shQuot_\FXS^P$ be representable, and then the $S$-prescheme $\repQuot_{\FXS}$ which represents it is isomorphic to the prescheme given by the sum of the $\repQuot_{\FXS}^P$ that represent the functors $\shQuot_\FXS^P$*.
With this, [Theorem 3.1](#fga-3-iv-theorem-3.1) will be a consequence of the following theorem:

\oldpage{221-12}

::: {.itenv #fga-3-iv-theorem-3.2 title="Theorem 3.2" latex="{Theorem 3.2}"}
With the above notation, the functor $\shQuot_\FXS^P$ is representable by a projective $S$-prescheme $\Quot_\FXS^P$.
:::

The rest of this section is dedicated to the proof of [Theorem 3.2](#fga-3-iv-theorem-3.2).

Let $\nu$ be an integer.
For every $S'$ over $S$, we denote by $A_\nu(S')$ the set of quotients $\scr{G}=\scr{F}'/\scr{H}$ of $\scr{F}'=\scr{F}\otimes_{\OO_S}\OO_{S'}$ that are coherent, flat over $S'$, and satisfy the following conditions:

a. $\RR^i f'_*(\scr{G}(n))=0$ for $i>0$ and $n\geq\nu$;
b. $\RR^i f'_*(\scr{H}(n))=0$ for $i>0$ and $n\geq\nu$;
c. $f'_*(\scr{H}(\nu+k))=\cal{S}'_k f'_*(\scr{H}(\nu))$ for $k\geq0$.

For this last condition, we suppose that $X$ is written as the homogeneous prime spectrum of a quasi-coherent positively-graded algebra $\cal{S}_\bullet$ over $S$ that is generated by $\cal{S}_1$, and we set $\cal{S}'=\cal{S}\otimes_{\OO_S}\OO_{S'}$, so that $X'$ is the homogeneous prime spectrum of $\cal{S}'$.
To prove [Theorem 3.2](#fga-3-iv-theorem-3.2), we can easily reduce to the case where $X=\PP_S^r$ (since $S$ is a union of open subsets $U$ such that $X|U$ is a closed subscheme of $\PP_U^r$, and $\OO_X(1)$ is induced by $\OO_{\PP_U^r}(1)$), and where $\scr{F}$ is of the form $(\OO_{\PP_S^r})^N$, and thus flat over $S$.
Then, in the above, the sheaves $\scr{H}$ are also flat over $S'$.
It then follows from the Künneth relations [@GD1960, III, §7] and from (b) that the conditions (a) and (b) are stable under base change, and imply that, for $n\geq\nu$, forming $f'_*(\scr{G}(n))$ and $F'_*(\scr{H}(n))$ commutes with extension of the base (*loc. cit.*).
In other words, *$A_\nu(S')$ is a contravariant functor in $S'$, and in a precise sense a subfunctor of $A(S')=\shQuot_{\FXS}^P(S')$*.
For varying $\nu$, we thus obtain an increasing sequence of subsets $A_\nu(S')$ of $A(S')$, whose union is $A(S')$ by a well known theorem of Serre [@GD1960, III, §2].
Note now that, if $\scr{G}$ is a coherent quotient of $\scr{F}'$ which is flat over $S$, and $s$ an element of $S$ such that the base change $\Spec(k(s))\to S$ gives rise to a quotient $\scr{G}_s$ of $\scr{F}_s$ satisfying conditions (a), (b), and (c), i.e. is in $A_\nu\Spec(k(s))$, then there exists an open neighbourhood $U$ of $s$ such that these same conditions are satisfied by $\scr{G}|(f')^{-1}(U)$, i.e. this quotient is in $A_\nu(U)$;
for (a) and (b), this follows in fact from the "Theorem of holomorphic functions" [@GD1960, III, §7], and (c) follows from the Nakayama lemma and the fact that we know that $f'_*(\scr{H}(n+k))=S'_kf'_*(\scr{H}(n))$ anyway for $n$ large enough and $k\geq0$ [@GD1960, III,§2].
\oldpage{221-13}
From these remarks, we conclude the following (compare with [@Gro1960a, IV]).
*For the functor $A$ to be representable, it is necessary and sufficient that the functors $A_\nu$ be representable, and then the $S$-prescheme $Q$ that represents $A$ is the increasing union of the opens $Q_\nu$ that represent the $A_\nu$.*

Let
$$
  M_\bullet
  = \sum_{n\geq0} f_*(\scr{F}(n))
  = \cal{S}_\bullet^N
$$
so that we have
$$
  M'_\bullet
  = M_\bullet\otimes_{\OO_S}\OO_{S'}
  = \sum_{n\geq0} f'_*(\scr{F}(n))
  = {\cal{S}'_\bullet}^N.
$$

It follows from (a) that we have

a'. $f'_*(\scr{G}(n))$ is locally free of rank $P(n)$ for $n\geq\nu$ [@GD1960, III, §7]

and it follows from (b),for $i=1$, that we have

a''. $f'_*(\scr{G}(n))$ is a quotient module of $M'_n$.

Also, the knowledge of this quotient module, for $n=\nu$, implies, by (c), that the knowledge of the submodules $f'_*(\scr{H}(n))$ of $M_n$ for $n\geq\nu$, and thus the knowledge of $\scr{H}$ and consequently of $\scr{G}$.
We thus obtain an *injective map*
$$
  A_\nu(S') \to \shGrass_{P(\nu)}(M'_\nu)
$$
from $A_\nu(S')$ to the set of locally free quotient modules of $M'$ of rank $P(\nu)$, whence a *functorial* homomorphism
$$
  i_\nu\colon A_\nu(S') \to \shGrass_{P(\nu)}(M_\nu)(S')
$$
where the functor on the right hand side is representable by the Grassmannian scheme $\Grass_{P(\nu)}(M_\nu)$ (compare with [@Gro1960a, V]), which is projective over $S$.
Then

::: {.itenv #fga-3-iv-lemma-3.3 title="Lemma 3.3" latex="{Lemma 3.3}"}
  $A_\nu(S')$ is a representable functor, and the morphism $Q_\nu\to\Grass_{P(\nu)}(M_\nu)$ that represents the homomorphism $i_\nu$ is an immersion (which implies that $Q_\nu$ is quasi-projective over $S$).
:::

This claim is equivalent to the following (compare with [@Gro1960a, IV]):
If we have a quotient module $N$ of $M'_\nu$ that is locally free of rank $P(\nu)$, then there exists a subprescheme $Z$ of $S'$ such that, for every locally Noetherian prescheme $T'$ over $S'$, the inverse image of $N$ over $T'$ is in $\Im A_\nu(T')$ if and only if $T'\to S'$ is bounded by the subprescheme $Z$.
\oldpage{221-14}
Changing notation, we can suppose that $S'=S$, i.e. we have a quotient $N_\nu$ of $M_\nu$ by a submodule $R_\nu$.
For it to come from an element of $A(s)$, it is necessary and sufficient that it satisfy the following two conditions:

i. $M_{\nu+k}/\cal{S}_k R_\nu$ is locally free of rank $P(\nu+k)$ for $k\geq0$.
ii. Both the subsheaf $\scr{H}$ of $\scr{F}$ defined by the graded submodule $R_\bullet=\sum_{k\geq0}\scr{S}_kR_\nu$ of $M_\bullet$ (cf. [@GD1960, II, §3]) and the quotient $\scr{G}=\scr{F}/\scr{H}$ satisfy conditions (a) and (b) above.

These conditions are clearly necessary, and if they are satisfied then the sheaf $\scr{G}$ defined in (ii) above, being isomorphic to the sheaf associated to the graded $\scr{S}_\bullet$-module $N_\bullet$ given by the sum of the $M_{n+k}/\scr{S}_kR$ is *flat* over $S$ (since its fibres are direct factors of localisations of $N$ for homogeneous prime ideals of $\cal{S}_\bullet$), and correspond to the Hilbert polynomial $P$ by virtue of (i).
Taking (ii) into account, we then see that (a') and (a'') are satisfied, and thus, for $n\geq\nu$, the natural homomorphism $N_n\to f_*(\scr{G}(n))$ is a *surjective* homomorphism of locally free modules of equal rank, and thus an isomorphism, and thus $f_*(\scr{H}(\nu+k))=\cal{S}_kR_\nu$ for all $k\geq0$, which proves that $\scr{G}\in A_\nu(S)$ and that $R_\nu$ is the element of $\Grass_{P(\nu)}(M_\nu)$ defined by $\scr{G}$.

Criteria (i) and (ii) above apply equally to the situation obtained after a change of base $S'\to S$.
We will prove first of all the fact that condition (i) is satisfied after the change of base $S'\to S$ can be expressed by saying that $S'\to S$ is bounded by a certain subprescheme $Z$ of $S$;
once we have shown this result, we are led (replacing $S$ with $Z$) to the case where condition (i) is already satisfied on $S$, and since it is stable under change of base, it remains to express condition (ii).
But then, if $U$ denotes the set of $s\in S$ such that the cohomology of the sheaves induced on the fibre $X_s$ by $\scr{G}(n)$ and $\scr{H}(n)$ is zero in dimension $>0$ for $n\geq\nu$, then we have already shown that $U$ is open, and condition (ii) will be satisfied after a change of base $S'\to S$ if and only if $S'\to S$ is bounded by $U$, which proves [Lemma 3.3](#fga-3-iv-lemma-3.3).
It thus remains to prove the following lemma:

::: {.itenv #fga-3-iv-lemma-3.4 title="Lemma 3.4" latex="Lemma 3.4"}
Let $S$ be a locally Noetherian prescheme, endowed with a quasi-coherent positively-graded algebra $\cal{S}_\bullet$ generated by $\cal{S}_1$, and let $M_\bullet$ be a quasi-coherent graded $\cal{S}$-module of finite type, $P$ a polynomial with rational coefficients, and $\nu$ and integer.
Then there exists a (clearly uniquet) subprescheme $Z$ of $S$ that has the following property:
for every prescheme $S'$ over $S$, for $M_n\otimes_{\OO_S}\OO_{S'}$ to be locally free of rank $P(n)$ for all $n\geq\nu$, it is necessary and sufficient that $S'\to S$ be bounded by $Z$.
:::

\oldpage{221-15}
We can evidently suppose that $S$ is affine, and thus Noetherian.
Then:

::: {.itenv #fga-3-iv-lemma-3.5 title="Lemma 3.5" latex="{Lemma 3.5}"}
For every integer $N\geq\nu$, let $U_N$ be the open subset of $S$ consisting of $s\in S$ such that $\rank_{k(s)}M_{ns}\otimes_{\OO_{S,s}}k(s)\leq P(n)$ for all $\nu\leq n\leq N$.
Then the decreasing sequence of open subsets $U_N$ stabilises.
:::

::: {.proof}
We know [@Gro1960b, IV] that $S$ admits a finite partition into reduced subschemes $S_i$ such that each $M\otimes_{\OO_S}\OO_{S_i}$ is *flat* over $S$.
We can thus suppose that $M$ is flat, and thus that the $M_n$ are flat.
Finally, we can evidently suppose that $S$ is connected.
But then [@GD1960, III, §7] there exists an integer $n_0$ and a polynomial $Q$ such that
$$
  \rank_{k(s)}M_{ns}\otimes_{\OO_{S,s}}k(s) = Q(n)
  \qquad\text{for }n\geq n_0.
$$
Suppose first of all that $P<Q$, and so $P(n)\neq Q(n)$ for large $n$.
Then we evidently have $U_N=\varnothing$ for large enough $N$, and thus a fortiori the sequence of $U_N$ stabilises.
In the contrary case, we have $P(n)\geq Q(n)$ for large $n$, and so $U_N=U_{n_0}$ for $N\geq n_0$, and the sequence of the $U_N$ again stabilises.
:::

In particular, the set $U_\infty$ of $s\in S$ such that

::: {.eqref #fga-3-iv-equation-asterisk title="" latex=""}
$$
  \rank_{k(s)}M_{ns}\otimes_{\OO_{S,s}}k(s) \leq P(n)
  \qquad\text{for all }n\geq\nu
\tag{$*$}
$$
:::

is open, since it is the intersection of the $U_N$.
We can then, for the proof of [Lemma 3.4](#fga-3-iv-lemma-3.4) replace $S$ with the open subset $U$, which leads us to the case where the inequality in [($*$)](#fga-3-iv-equation-asterisk) is satisfied at all $s\in S$.

::: {.itenv #fga-3-iv-lemma-3.6 title="Lemma 3.6" latex="{Lemma 3.6}"}
Let $M$ be a module on a locally Noetherian prescheme $S$, and $r$ an integer.
Then there exists a (clearly unique) subprescheme $Z$ of $S$ that has the following property:
for all $S'$ over $S$, for $M\otimes_{\OO_S}\OO_{S'}$ to be locally free of rank $r$, it is necessary and sufficient that $S'\to S$ be bounded by $Z$.
If $\rank_{k(s)}M_s\otimes_{\OO_{S,s}}k(s)\leq r$ for all $s$, then $Z$ is a closed subprescheme of $S$ (supposing that $M$ is coherent).
:::

\oldpage{221-16}
::: {.proof}
Indeed, the above reasoning leads us to the case where we have the inequality ($*$) for all $s\in S$ (by replacing, if necessary, $S$ with the open subset consisting of the $s$ where the inequality is satisfied).
We can then suppose that $M$ fits into an exact sequence
$$
  \OO_S^q \to \OO_S^r \to M \to 0
$$
and the condition in question on the $S'$ over $S$ also implies that, in the corresponding exact sequence $\OO_{S'}^q\to\OO_{S'}^r\to M'\to 0$, the second arrow is an isomorphism, i.e. the first is zero.
We then see that the closed subprescheme $Z$ of $S$ defined by the ideal generated by the coefficients of the matrix defining the homomorphism $\OO_S^q\to\OO_S^r$ satisfies the desired condition.
:::

::: {.proof}
Returning to the proof of [(3.4)](#fga-3-iv-lemma-3.4) where we left off, we denote by $Z_n$ the _closed_ subprescheme of $S$ associated, by [(3.6)](#fga-3-iv-lemma-3.6), to the module $M_n$ and the integer $r=P(n)$, and by $Z'_N$ the infimum of the $Z_n$ for $\nu\leq n\leq N$.
Then the $Z_N$ form a decreasing sequence of closed subpreschemes of $Z$, which is thus necessarily stationary.
Let $Z$ be the constant value of the $Z_W$ for large $N$.
This is the desired $Z$ in [(3.4)](#fga-3-iv-lemma-3.4).
This finishes the proof of [(3.4)](#fga-3-iv-lemma-3.4), and thus also of [(3.3)](#fga-3-iv-lemma-3.3)
:::

We have thus proven that _$\shQuot_{\FXS}^P$ is representable by an $S$-prescheme $Q$ that is an increasing union of open quasi-projective subpreschemes $Q_\nu$ over $S$._
To go further, we need to invoke [Theorem 2.1](#fga-3-iv-theorem-2.1), whence we easily conclude that $Q$ is _quasi-compact_ (since it is the image of a prescheme $S'$ of finite type over $S$ that parametrises the family of quotient sheaves of the $\scr{F}_K$ whose Hilbert polynomial is $P$).
Thus $Q$ is equal to one of the $Q_\nu$, and thus quasi-projective over $S$.
To prove that it is projective over $S$, it thus remains to prove that it is _proper_ over $S$, and for this it suffices to invoke the valuative criteria of properness in the form given in [@GD1960, II, 7.3.8].
It suffices to verify the following:

::: {.itenv #fga-3-iv-lemma-3.7 title="Lemma 3.7" latex="{Lemma 3.7}"}
Let $S$ be the spectrum of a discrete valuation ring, $s$ its generic point, $X$ a prescheme over $S$, $\scr{F}$ a quasi-coherent module over $X$, and $\scr{G}_s$ a quasi-coherent quotient module of $\scr{F}_s=\scr{F}\otimes_{\OO_S}k(s)$ over $X_s$.
Then there exists a unique quasi-coherent quotient module $\scr{G}$ of $\scr{F}$ that is flat over $S$ and whose restriction to $X_s$ is $\scr{G}_s$.
:::

\oldpage{221-17}

::: {.proof}
Indeed, if $\scr{G}_s=\scr{F}_s/\scr{H}_s$, it suffices to consider the largest subsheaf $\scr{H}$ of $\scr{F}$ that induces $\scr{H}_s$ ([@GD1960, I, 9.4.2]) and to take $\scr{G}=\scr{F}/\scr{H}$.
We easily verify that this sheaf works.
:::

[Theorem 3.2](#fga-3-iv-theorem-3.2), and thus [Theorem 3.1](#fga-3-iv-theorem-3.1), is now completely proven.

The proof also shows, at the same time, the following:

::: {.itenv #fga-3-iv-proposition-3.8 title="Proposition 3.8" latex="{Proposition 3.8}"}
Under the conditions of [(3.2)](#fga-3-iv-theorem-3.2), let $Q=\repQuot_{\FXS}^P$, $X_Q=X\times_s Q$, $\scr{F}_Q=\scr{F}\otimes_{\OO_S}\OO_Q$, and let $\scr{G}$ be the coherent quotient of $\scr{F}_Q$, which is flat over $Q$, that has $P$ as its relative Hilbert polynomial, so that $(Q,\scr{G})$ represents the functor $\shQuot_{\FXS}^P$.
Then there exists an integer $\nu$ such that, for $n\geq\nu$, $(f_Q)_*(\scr{G}(n))$ is a locally free module over $Q$ of rank $P(n)$, and is very ample with respect to $S$, i.e. it defines an immersion of $Q$ into a Grassmannian scheme $\repGrass_{P(n)}(M)$ over $S$.
A fortiori, for $n\geq\nu$, the sheaf $\bigwedge^{P(n)}(f_Q)_*(\scr{G}(n))$ over $Q$ is invertible and very ample with respect to $S$.
:::

::: {.proof}
Indeed, we can reduce, as in [(3.2)](#fga-3-iv-theorem-3.2), to the case where $\scr{F}$ is flat over $S$, and then it suffices to take an integer $\nu$ such that $A_\nu=A$ (with the notation above).
:::

The most important application of [(3.2)](#fga-3-iv-theorem-3.2) is in the case where $\scr{F}=\OO_X$.
We then write
$$
  \begin{aligned}
    \repQuot_{\OO_X/X/S}
    &= \repHilb_{X/S}
  \\\repQuot_{\OO_X/X/S}^P
    &= \repHilb_{X/S}^P
  \end{aligned}
$$
and so we have a decomposition
$$
  \repHilb_{X/S} = \coprod_P \repHilb_{X/S}^P.
$$
By definition, $\repHilb_{X/S}$ represents the functor $\shHilb_{X/S}(S')$ which is given by the set of closed subpreschemes of $X'=X\times_S S'$ that are flat over $S$;
and $\repHilb_{X/S}^P$ represents the subfunctor corresponding to the closed subpreschemes that admit a given Hilbert polynomial $P$.
These preschemes are also called the _Hilbert prescheme_ of $X$ over $S$ and the _Hilbert prescheme of index $P$_, respectively.
The terminology is justified by the role played in the theory by the Hilbert polynomials.
Their difference in nature with the classical Chow varieties (meant to parametrise cycles, not varieties) is analogous to that between _the Chow ring_ of classes of cycles of a variety and _the ring of classes of sheaves_ of the variety (as is introduced in the Riemann--Roch theorem [@BS1958]);
\oldpage{221-18}
we note that, when $X=\PP_S^r$, with $S$ the spectrum of a field, the knowledge of the Hilbert polynomial of a coherent module $\scr{F}$ over $X$ is equivalent to that of the Chern classes of $\scr{F}$, or even of the class of $\scr{F}$ in the ring of classes of coherent sheaves on $X$.

::: {.rmenv #fga-3-iv-remarks-3.9 title="Remarks 3.9" latex="{Remarks 3.9}"}
We also note that the construction of $\repQuot_{\FXS}$ and $\repQuot_{\FXS}^P$ was reduced to the case where $X=\PP_S^r$ and $\scr{F}=\OO_X^N$, with $\OO_X(1)$ being the usual very ample sheaf;
more precisely, the general $\repQuot_{\FXS}$ arise as closed subpreschemes of the above.
Since forming the $\repQuot_{\FXS}^P$ is evidently compatible with base change $S'\to S$, we see that we can reduce to the case where further $S=\Spec(\mathbb{Z})$:
$$
  \scr{Q}_{r,N}^P = \repQuot_{(\OO_{\PP_{\mathbb{Z}}^r})^N/\PP_{\mathbb{Z}}^r/\Spec(\mathbb{Z})}
$$
and, more particularly, the absolute Hilbert schemes:
$$
  \repHilb_r^P = \scr{Q}_{r,1}^P.
$$
A more detailed study of these schemes, starting with determining their connected components (are they connected?), and their irreducible components (by Serre [@Ser1961], there can exist irreducible components that exist entirely over a prime number $p\neq0$), would be very interesting.
Recall the question of Weil, asking if the irreducible components of the fibres of $\repHilb_r^P$ over the $s\in\Spec(\mathbb{Z})$ correspond to "regular" extensions of the prime field, i.e. if they are "relatively connected".
It could be the case that these questions are more accessible for Hilbert schemes than for "Chow varieties".

*[Comp.]*
The study of connected components of Hilbert schemes over an algebraically closed field was done by Hartshorne, who proves that the $\repHilb_r^P$ are connected, and determines the pairs $(r,P)$ for which $\repHilb_r^P\neq\varnothing$ [@Har1966].
:::


## Variants {#fga-3-iv-section-4}

a. Under the conditions of [(3.1)](#fga-3-iv-theorem-3.1), let $U$ be open in $X$, and denote by $A'$ the subfunctor of $A=\shQuot_{\FXS}$ such that $A'(S')$ is the set of quotient modules $\scr{G}$ of $\scr{F}'$ that are flat over $S'$ and whose support is contained inside $U'$.
    We immediately see that $A'$ is representable by an open subset of the prescheme $\repQuot_{\FXS}$ that represents $A$.
    \oldpage{221-19}
    It follows that Theorems [(3.1)](#fga-3-iv-theorem-3.1) and [(3.2)](#fga-3-iv-theorem-3.2) remain true if we suppose that $X$ is _quasi-projective_ over $S$ instead of projective over $S$, as long as we also replace in the conclusions the word "projective" by "quasi-projective", and use $\shQuot_{\FXS}(S')$ to mean the set of coherent quotients $\scr{G}$ of $\scr{F}'$ that are flat over $S'$ and _whose support is proper over $S'$._

b. Generally we can impose all sorts of supplementary natural conditions on the quotients $\scr{G}$ of $\scr{F}'=\scr{F}\otimes_{\OO_S}\OO_{S'}$ that are flat over $S'$ and stable under base change, thus obtaining as many subfunctors of $\shQuot_{\FXS}$ as we want to represent.
    The usual criteria allow us, in many cases, to prove that we again obtain functors that are representable by open subsets of $\repQuot_{\FXS}$.
    This is, in particular, the case if we impose one of the following additional properties:

    1. The dimensions of the prime cycles associated to the modules $\scr{G}_{s'}$ (for $s'\in S'$) that are induced on the fibres $X'_{s'}$ belong to a given set of integers.
    2. (In the case where $\scr{F}=\OO_X$, and thus $\scr{G}$ corresponds to a closed subprescheme $Y$ of $X'$); $Y$ is a _simple_ prescheme [@Gro1960b, IV] over $S$, resp. _normal_ over $S$ (i.e. the fibres $Y_{s'}$ are normal "over $k(s)$", i.e. are normal under any extension of base field), resp. (if $X$ is flat over $S$) are local complete $k$-intersections in $X$ with respect to $S$ (i.e. the fibres $Y_{s'}$ are local complete intersections in the $X_{s'}$)

    Other conditions would involve properties of a cohomological nature on the modules $\scr{G}_{s'}$ induced on the $X'_{s'}$, etc.
    Of course, the conjunction of conditions where each is represented by an open $U_i$ of $\repQuot_{\FXS}$ is represented by the open intersection.
    For example, considering, for all $S'$ over $S$, the set of closed subpreschemes $Y$ of $X'=X\times_S S'$ that are étale covers [@Gro1960b, I] of a given rank $r$ over $S'$, we obtain a representable contravariant functor in $S'$.

c. The preschemes $\repHom_S(X,Y)$, $\prod_{X/S}Z/S$, and $\repIsom_S(X,Y)$, defined in [@Gro1959, II, C, §2] exist thanks to suitable projective hypotheses, and can be realised as opens in suitable Hilbert preschemes.
    Since we have $\repHom_S(X,Y)=\prod_{X/S}((X\times Y)/X)$, the case of $\Hom_S(X,Y)$ reduces to that of $\prod_{X/S}(Z/X)$.
    We then note that, for all $S'$ over $S$, the set of sections of $Z'=Z\times_S S'$ over $X'=X\times_S S'$ is in bijective correspondence with the set of subpreschemes $\Gamma$ of $Z$ (necessarily closed if $Z$ is separated over $X$) such that the morphism $\Gamma\to X'$ induced by $Z'\to X'$ is an isomorphism.
  \oldpage{221-20}
    In this way, _if $X$ is flat and proper over $S$, and $Z$ quasi-projective over $S$, then $\prod_{X/S}(Z/X)$ exists and is realised as an open subprescheme of $\repHilb_{Z/S}$._
    Thus _if $X$ is projective and flat over $S$, and $Y$ quasi-projective over $S$, then $\repHom_S(X,Y)$ exists and is realised as an open subprescheme of $\repHilb_{(X\times_S Y)/S}$._
    If $X$ and $Y$ are both projective over $S$, then it immediately follows that $\repIsom_S(X,Y)$ also exists, and is represented by an open subset of $\repHom_S(X,Y)$.
    Similarly, if $X$ is flat and projective over $S$, and $Y$ quasi-projective over $S$, then the $S$-prescheme $\repImm_S(X/Y)$ that corresponds to the subfunctor of the functor represented by $\repHom_S(X,Y)$ that corresponds to $S'$-homomorphisms $X'\to Y'$ that are immersions is also representable by an open subset of $\repHom_S(X,Y)$.

    Let $\scr{L}$ (resp. $\scr{M}$) be an invertible sheaf on $X$ (resp. $Y$) that is very ample with respect to $S$, whence we obtain a sheaf $\scr{L}\otimes_{\OO_S}\scr{M}$ on $X\times_S Y$ that is very ample with respect to $S$.
    Then, for any polynomial $P$ with rational coefficients, $\repHilb_{(X\times_S Y)/S}^P$ is defined and is a quasi-projective prescheme over $S$.
    It thus induces, on $\repHom_S(X,Y)$, a subset that is both open and closed, and quasi-projective over $S$, which we denote by $\Hom_S(X,Y)^P$.
    Thus the sections of $\repHom_S(X,Y)^P$ over $S$ are the $S$-morphisms $g\colon X\to Y$ such that, for any integer $n$, we have
    $$
      \chi\Big((\scr{L}\otimes_{\OO_X}g^*(\scr{M}))^{\otimes n}\Big)
      = P(n).
    $$
    In this way we obtain generalisations of Matsusaka's theorem, affirming that the automorphisms of a "polarised" projective variety form an algebraic group, a claim that here has an evidently more precise meaning, since we have a definition of this group as the solution to a universal problem.
    We note also that, over an algebraically closed field, the group of automorphisms considered in the past is that which is induced by the "true" one defined here, by dividing by the nilpotent elements;
    this explains why there is little chance that the historical constructions could be done over a non-perfect base field, since the ideal of nilpotent elements that appears after an extension of the base field is not necessarily "defined over $k$".
    This same remark applies equally to the majority of historical constructions.


## Differential study of Hilbert schemes {#fga-3-iv-section-5}

\oldpage{221-21}

We have the following result:

::: {.itenv #fga-3-iv-proposition-5.1 title="Proposition 5.1" latex="{Proposition 5.1}"}
Let $S$ be a prescheme, $S_0$ a subprescheme defined by a square-zero quasi-coherent ideal $\scr{I}$, $X$ an $S$-prescheme, and $\scr{F}$ a quasi-coherent module on $X$.
Let $X_0=\scr{F}\times_S S_0$ and $\scr{F}_0=\scr{F}\otimes_{\OO_S}\OO_{S_0}$.
Finally, let $\scr{G}_0=\scr{F}_0/\scr{H}_0$ be a quasi-coherent quotient module of $\scr{F}_0$ that is flat over $S_0$.
For every open $U$ of $X$, let $\scr{E}(U)$ be the set of quasi-coherent quotient modules $\scr{G}$ of $\scr{F}|U$ that are flat over $S$ and are such that $\scr{G}\otimes_{\OO_S}\OO_{S_0}=\scr{G}_0$;
as $U$ varies, the $\scr{E}(U)$ are the sections of a sheaf $\scr{E}$ on $U$.
With this, the sheaf of groups
$$
  \scr{A} = \repHom_{\OO_{X_0}}(\scr{H}_0,\scr{G}_0\otimes_{\OO_{S_0}}\scr{I})
$$
acts naturally on $\scr{E}$, which thus becomes a "formally $\mathscr{A}$-principal homogeneous" sheaf (i.e. for every open $U$ in $X$, $\scr{E}(U)$ is either empty or an $\scr{A}(U)$-principal homogeneous set).
:::

We thus conclude:

::: {.itenv #fga-3-iv-corollary-5.2 title="Corollary 5.2"}
Suppose that there exists locally on $X$ an extension $\scr{G}$ of $\scr{G}_0$ to a quotient of $\scr{F}$ that is flat over $S$ (i.e. that the fibres of the sheaf $\scr{E}$ are non-empty).
Then there exists a canonical obstruction class
$$
  c(\scr{G}_0) \in \HH^1(X,\scr{A})
$$
whose vanishing is necessary and sufficient for the existence of a global extension $\scr{G}$ of $\scr{G}_0$ to a quotient of $\scr{F}$ that is flat over $S$.
If this class is zero, then the set $\scr{E}(X)$ of all possible extensions is a principal homogenous set for $\scr{A}(X)=\Hom_{\OO_X}(\scr{H}_0,\scr{G}_0\otimes_{\OO_{S_0}}\scr{I})$.
:::

The existence of a global extension is thus guaranteed, in particular, if $\HH^1(X,\scr{A})=0$.

::: {.itenv #fga-3-iv-corollary-5.3 title="Corollary 5.3"}
Suppose that $Q=\repQuot_\FXS$ exists (cf. [§4.a](#fga-3-iv-section-4)) --- for example, suppose that $X$ is quasi-projective over some locally Noetherian $S$, and $\scr{F}$ is coherent.
Let $x\in Q$, corresponding to a residue extension $K=k(x)$ of some $k(s)$ (where $s\in S$).
Then $x$ is defined by a coherent quotient module $\scr{G}_0=\scr{F}_0/\scr{H}_0$ of the module $\scr{F}_0=F_K$ on the $K$-prescheme $X_K$.
Let $\scr{A}$ be the coherent sheaf on $X_K$ defined by
$$
  \scr{A} = \repHom_{\OO_{X_0}}(\scr{H}_0,\scr{G}_0).
$$

Then the Zariski tangent space of the fibre $Q_s$ at the point $x$ (given by the dual over $K$ of $\frak{m}/\frak{m}^2$, where $\frak{m}$ is the maximal ideal of $\OO_{Q_k,x}$) is canonically isomorphic to $\HH^0(X_k,\scr{A})$.
:::

The result giving the Zariski tangent space can be generalised, and gives a characterisation, for a given $S$-morphism $g\colon S'\to Q$, i.e. a section $g'$ of $Q'=Q\times_S S'$ over $S'$, of the module
$$
  \Omega
  = g^*(\Omega_{Q/S}^1)
  = {g'}^*(\scr{J}/\scr{J}^2)
$$
(where $\scr{J}$ is the ideal on $Q'$ defined by the section $g'$ of $Q'$ over $S'$) by the formula
$$
  \Hom_{\OO_{S'}}(\Omega,\scr{M})
  \simeq \HH^0(X',\scr{A})
$$
which is functorial in the coherent module $\scr{M}$ over $S'$, and where $\scr{A}$ is again the module on $X'=X\times_S S'$ defined by
$$
  \scr{A} = \repHom_{\OO_{X'}}(\scr{H},\scr{G}\otimes_{\OO_S}\scr{M})
$$
($\scr{G}=\scr{F}'/\scr{H}$ being the quotient module of $\scr{F}'=\scr{F}\otimes_{\OO_S}\OO_{S'}$ that corresponds to $g$).
It suffices to apply [(5.1)](#fga-3-iv-proposition-5.1) by replacing $S_0$ with $S'$, and $S$ with the prescheme $D(\scr{M})=(S',\OO_{S'}+\scr{M})$, where $\scr{M}$ is considered as a square-zero ideal.

If, in [(5.1)](#fga-3-iv-proposition-5.1), we have $\scr{F}=\OO_X$, then the data of $\scr{G}_0$ corresponds to the data of a closed subprescheme $Y_0$ of $X_0$ that is flat over $S_0$, defined by the ideal $\scr{J}_0=\scr{M}_0$, and then [($*$)](#fga-3-iv-equation-asterisk) gives
$$
  \scr{A} = \repHom_{\OO_{X_0}}(\scr{J}_0/\scr{J}_0^2,\OO_{Y_0}\otimes_{\OO_{S_0}}\scr{J})
$$
where $\scr{J}/\scr{J}^2$ is thought of as the *conormal sheaf* of $Y_0$ in $X_0$, which we also denote by $\scr{N}_{Y_0/X_0}$;
\oldpage{221-23}
it is then interesting to consider $\scr{A}$ as a module over $Y_0$, and to calculate $\HH^0$ and $\HH^1$ on $Y$.
If $Y_0$ is locally a complete intersection in $X_0$, with $X$ flat over $S$, then, in [(5.1)](#fga-3-iv-proposition-5.1), the possibility of a local extension is guaranteed, and $\scr{J}/\scr{J}^2$ is locally free over $Y_0$ and we can write
$$
  \scr{A} = \check{\scr{N}}_{X_0/Y_0}\otimes_{\OO_{S_0}}\scr{J}
$$
where the first factor on the right-hand side is the normal cone of $Y_0$ inside $X_0$.
Using the fundamental criterion of simplicity [@Gro1960b, III, 3.1], we find, for example:

::: {.itenv #fga-3-iv-corollary-5.4 title="Corollary 5.4"}
Under the conditions of [(5.3)](#fga-3-iv-corollary-5.3), suppose that $\scr{F}=\OO_X$, with $X$ flat over $S$, and that the closed subprescheme $Y_0$ of $X_0$ that corresponds to $\scr{G}_0$ is locally a complete intersection.
Then the Zariski tangent space of $Q_s$ at $x$ is canonically isomorphic to $\HH^0(Y_0,\check{\scr{N}}_{X_0/Y_0})$.
If $\HH^1(Y_0,\check{\scr{N}_{X_0/Y_0}})=0$, then the Hilbert prescheme $X$ is simple over $S$ at the point $x$ (where $\check{\scr{N}}_{X_0/Y_0}$ is the normal sheaf of $Y_0$ inside $X_0$).
:::

::: {.rmenv #fga-3-iv-remark-5.5 title="Remark 5.5"}
This statement applies in particular when $Y_0$ is a complete intersection in $X_0$ defined by *one* single equation, i.e. is a positive "Cartier divisor".
Then $\check{\scr{N}}_{X_0/Y_0}$ is isomorphic to the sheaf on $Y_0$ induced by the invertible sheaf $\scr{J}^{-1}$ on $X_0$ defined by the divisor $Y_0$.
This is the situation that we find in particular in the study of families of positive divisors on a non-singular projective variety $X_0$.
The isomorphism between the Zariski tangent space at the point $x$ of $Q$ (or, if one prefers, of the open $D$ of $Q$ that corresponds to the divisors) and $\scr{H}^0(Y_0,\check{\scr{N}}_{X_0/Y_0})$ was known in classical algebraic geometry under the name of "*characteristic homomorphism*" (from the former to the latter).
It was not defined when $x$ was a simple point of the variety of parameters $T$ of a "complete continuous family" of divisors, i.e. from our point of view, of an irreducible component of the scheme $D$, endowed with the induced *reduced* structure.
The tangent space of $T$ at $x$ is then a *subspace* of the tangent space of $D$ at $x$, and so the characteristic homomorphic of yore is indeed injective, but it is not surjective except for under supplementary conditions, for example if $D$ is integral at $x$.
\oldpage{221-24}
In fact, Zappa [@Zap1945] constructed an example (with $X$ a non-singular projective surface over the *field of complex numbers*) where even at the generic point of $T$ the characteristic homomorphism is not surjective.
*This thus implies that $D$ is not integral even at the generic point of the irreducible component in question.*
This shows in a particularly striking manner how varieties with nilpotent elements are necessary for understanding the most classical phenomena of the theory of surfaces.

*[Comp.]*
Concerning the example of Zappa, we note that Mumford has even constructed an irreducible component of the Hilbert scheme for $\PP_\mathbb{C}^3$ (whose general points represent non-singular curves of degree $14$ and genus $24$), which is non-reduced at its generic points.
Blowing up the curves obtained, he also obtains a regular projective scheme of dimension $3$ over $\mathbb{C}$, whose formal scheme of modules is non-reduced at its generic point, or, equivalently, such that its local variety of modules, in the sense of analytic geometry, over $\mathbb{C}$ (see *Séminaire Cartan **13**, 1960/61*) is non-reduced at all its points.
:::

::: {.rmenv #fga-3-iv-remark-5.6 title="Remark 5.6"}
We have given, in [(5.4)](#fga-3-iv-remark-5.4), a criterion for simplicity, which applies in particular to schemes of divisors.
Kodaira gave a different criterion in [@Kod1956], given by the vanishing of $\HH^1(X_0,\scr{L})$, where $\scr{L}=\scr{J}_0^{-1}$ is the invertible sheaf on $X_0$ defined by the divisor $Y_0$;
this criterion holds whenever $S$ is the spectrum of a field of characteristic $0$, and is proved in [@Kod1956] by transcendental methods in the case where the base field is $\mathbb{C}$.
We note here that, in general, $S$ now arbitrary, Kodaira's condition is a sufficient condition for the canonical morphism $D\to\repPic_{X/S}$ from the prescheme of divisors to the Picard prescheme of $X/S$ to be simple at the point $x$ in question (as we easily verify by the usual criterion for simplicity, once we have the existence of $\repPic_{X/S}$).
Then if, further, $\repPic_{X/S}$ is simple over $S$ at the point given by the image of $x$ (for example if $\repPic_{X/S}$ is simple over $S$), then $D$ is simple over $S$ at $x$.
On the other hand, Cartier has shown that every group prescheme locally of finite type over *a field $k$ of characteristic $0$* is simple over $k$>
By combining these two results, we recover the result of Kodaira.
Note that it follows from these remarks that, over a field $K$ of characteristic $p>0$, if $\repPic_{X/S}$ is not simple over $k$ (which is the case whenever $X$ is the Igusa surface), then the condition $\HH^1(X_0,\scr{L})=0$ implies to the contrary that $D$ is not simple at $x$, and even not reduced at $x$ if $K$ is algebraically closed.
:::

To finish, we give the following result, which plays an important role in the differential study of fibred spaces:

::: {.itenv #fga-3-iv-proposition-5.7 title="Proposition 5.7"}
Let $X$ be a finite prescheme that is flat over $S$ and locally Noetherian, and let $Z$ be a prescheme over $S$ such that $\prod_{X/S}(Z/X)$ exists (which is the case if $Z$ is quasi-projective over $X$).
If $Z$ is simple over $X$, then $\prod_{X/S}(Z/X)$ is simple over $S$.
:::

::: {.proof}
This is an immediate consequence of the definition, and of the usual criterion of simplicity [@Gro1960b, III, §3.1].
:::

Note that if $X$ is finite and flat over $S$, then the question of the existence of $\prod_{X/S}(Z/X)$ can be dealt with in a very elementary manner, without using the theory of Hilbert schemes.
\oldpage{221-25}
We find, for example, that if $X$ is radicial over $S$, then $\prod_{X/S}(Z/X)$ exists without any restrictions on $Z$.
For example, let $T$ be an $S$-prescheme, and let $T_n$ be "the infinitesimal neighbourhood of order $n$" of the diagonal of $T\times_S T$ in $T\times_S T$, endowed with the morphisms $p_1,p_2\colon T_n\to T$ induced by the two projections.
We can consider $T_n$ as a finite prescheme over $T$ thanks to $p_1$, and we suppose further that $T_n$ is flat over $T$ (which is the case if $T$ is simple over $S$).
For every prescheme $X$ over $T$, set
$$
  (X/T/S)^{(n)} = \prod_{T_n/S}(p_2^*(X/T)/T_n)
$$
which is a prescheme over $T$ called the *bundle of germs of sections of order $n$ of $X$ over $T$* (with respect to $S$).
This depends functorially on $X$, and is simple over $T$ if $X$ is.


## Relation to the notion of norm and symmetric products {#fga-3-iv-section-6}

Let $S$ be a prescheme, let $X$ and $Y$ be $S$-preschemes, and let
$$
  u\colon(X/S)^n\to Y
$$
be a *symmetric* $S$-morphism from the $n$-th cartesian power of $X/S$ to $Y$.
Suppose, for simplicity, that $S$ is locally Noetherian, and that $X$ and $Y$ are of finite type over $S$.
We can then associate, to every coherent module $\scr{F}$ on $X$ with finite support on $S$ that is furthermore flat over $S$ and of rank equal to $n$ with respect to $S$ (i.e. such that $f_*(\scr{F})$ is a locally free module of rank $n$ on $S$), in a natural way a section of $Y$ over $S$:
$$
  \scr{N}_{X/S}^u(\scr{F}) \in \Gamma(Y/S).
$$
We will not give here the details of the definition, but instead content ourselves with noting that the formalism to which one arrives is a natural generalisation of the usual formalism of norms and traces.
When the symmetric $n$-th power of $X$ over $S$ exists (for example, if the orbits of the symmetric group $\sigma_n$ acting on $(X/S)^n$ are contained inside affine opens), we can take $Y$ to be this symmetric power $\Symm_S^n(X)$, and we obtain a canonical element
$$
  \scr{N}_{X/S}(\scr{F}) \in \Gamma(\Symm_S^n(X)/S)
$$
\oldpage{221-26}
which allows us to recover the $\scr{N}_{X/S}^u(\scr{F})$.
Another important case is that where $X$ is a commutative monoid over $S$, and $X=Y$, and the morphism $u$ comes from the composition law of $X$.
We then simply write $\scr{N}(\scr{F})$ for the section of $X$ over $S$ associated to the module $\scr{F}$ on $X$.

Now suppose that we have a coherent module $\scr{F}$ on $X$ such that $\repQuot_{\FXS}$ exists, or at least such that the functor $\shQuot_{\FXS}^n$, which associates to each $S'$ over $S$ the set of coherent quotient sheaves $\scr{M}$ of $\scr{F}'=\scr{F}\otimes_{\OO_S}\OO_{S'}$ that are flat over $S$ and of relative rank $n$, is representable by an $S$-prescheme $\repQuot_{\FXS}^n$.
(If $X$ is quasi-projective over $S$, then $\repQuot_{\FXS}^n$ indeed exists, and is exactly, with the notation of [§3](#fga-3-iv-section-3), $\repQuot_{\FXS}^P$, where $P$ is the polynomial consisting of the constant term $n$).
Since the formation of the $\scr{N}_{X/S}^u(\scr{M})$ is compatible with base change, we thus obtain a canonical morphism
$$
  \scr{N}_{X/S}^u\colon \repQuot_{\FXS}^n \to Y
$$
and, in particular, if the $n$-th symmetric power of $X$ over $S$ exists,
$$
  \scr{N}_{X/S}\colon \repQuot_{\FXS}^n \to \Symm_S^n(X).
$$
The most important case is that where $\scr{F}=\OO_X$, which gives a morphism
$$
  \scr{N}_{X/S}\colon \repHilb_{X/S}^n \to \Symm_S^n(X).
$$
This is evidently an isomorphism for $n=0$ and $n=1$.
But for $n\geq1$, even if $S$ is the spectrum of a field $k$, and $X$ is simple over $S$, it is not in general an isomorphism nor even an injective morphism, since a sub-scheme of dimension $0$ of $X$ (corresponding, for example, to a primary ideal $\scr{I}$ for the maximal ideal in a local ring $\OO_{X,x}$, for a closed point $x$ of $X$) is not known when we know only the cycle that it defines (to be precise, when we know the codimension over $k$ of $\scr{I}$ in $\OO_{X,x}$).
We can only say the following (where $S$ is once more arbitrary):

a. If $X$ is simple over $S$, then the norm morphism defines an isomorphism from the open of $\repHilb_{X/S}^n$ that corresponds to the classification of étale covers of rank $n$ contained inside $X$ (cf. [§4.b](#fga-3-iv-section-4)) to the open of $\Symm_S^n(X)$ that corresponds to the $n$-cycles without multiple components.
b. If furthermore $X$ is of relative dimension $1$ over $S$, then the norm morphism even defines an isomorphism from $\repHilb_{X/S}^n$ to $\Symm_{X/S}^n$.

\oldpage{221-27}
This second fact is due to the fact that a subscheme of dimension $0$ of a non-singular algebraic curve is known whenever we know the corresponding cycle.
The same remark also applies more generally to Cartier divisors that are positive over a non-singular algebraic scheme (and it is not excluded that, in this very particular case, the Chow variety gives the same thing as the Hilbert variety).


## Supplements and questions {#fga-3-iv-section-7}

As remarked by J.-P. Serre, it follows from a well-known example of Nagata that we can find a scheme $S$ that is the spectrum of a field $k$, an $S$-scheme $S'$ that is the spectrum of a quadratic extension $k'$ of $k$, and finally a simple and proper (but non-projective) $S'$-scheme $X$ of dimension $3$ such that $\prod_{S'/S}(X/S)$ does not exist.
This implies a fortiori that the Hilbert scheme $\repHilb_{X/S}^2$ does not exist (nor even the $k$-scheme that would represent the étale covers of rank $2$ of $S$ contained inside $X$, nor a fortiori the symmetric square of $X$, cf. [§6](#fga-3-iv-section-6)).
This thus imposes serious limitations on the possibilities of non-projective constructions in algebraic geometry.
(It is, however, plausible that such limitations do not present themselves in analytic geometry, just as they do not present themselves in formal geometry (cf. [FGA 3.II](FGA-3-II.html))).
However, if $X$ is a proper scheme over the spectrum $S$ of a field $k$, and if $Z$ is quasi-projective over $X$, then $\prod_{X/S}(Z/X)$ exists, and is a scheme, given by the sum of a sequence of quasi-projective schemes over $S$ (as in the projective case [(3.1)](#fga-3-iv-theorem-3.1)).
To see this, we can reduce to the case where $X$ is itself projective, by dominating $X$ by a projective $S$-scheme $X'$;
we will not give here the details of the proof, which also uses the result of factorisation of a finite morphism given in [@Gro1959, I, A, 2.b].
The success of the method is all in the fact that, with $S$ the spectrum of a field, the $X'$ that appears in Chow's lemma will automatically be flat over $S$.
I do not know if the result remains true without any hypotheses on $S$, supposing only that $X$ is proper and flat over $S$, and that $Z$ is quasi-projective over $X$.
An important case in the applications is that where $Z$ is a closed subscheme of $X$;
if then $\prod_{X/S}(Z/X)$ exists, it is necessarily a closed subscheme of $S$.
\oldpage{221-28}
We can construct it directly in a relatively simple manner whenever $X$ is projective over $S$, without using the theory of Hilbert schemes, and the method used shows more generally that, if $Z$ is affine over $X$, then $\prod_{X/S}(Z/X)$ exists and is affine over $S$.
It equally shows that, if $X$ is proper and flat over $S$ (but not necessarily projective over $S$), then, for every vector bundle $Z$ that is locally trivial on $X$, $\prod_{X/S}(Z/X)$ exists and is a vector bundle on $S$.
It would be desirable for these results to be studied again and unified.
