# (PART\*) Descent, and existence theorems in algebraic geometry {-}

# Generalities, and descent by faithfully flat morphisms {#fga-3.i}

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\ourrar}[2]{\overset{#1}{\underset{#2}{\rightrightarrows}}}
\providecommand{\oullar}[2]{\overset{#1}{\underset{#2}{\leftleftarrows}}}
\providecommand{\id}{\operatorname{id}}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\shHom}{\mathscr{H}\kern -.5pt om}
\providecommand{\Aut}{\operatorname{Aut}}
\providecommand{\HH}{\operatorname{H}}
\providecommand{\RR}{\operatorname{R}}
\providecommand{\GL}{\operatorname{GL}}
\providecommand{\Ga}{\operatorname{G_a}}
\providecommand{\Gm}{\operatorname{G_m}}
\providecommand{\SL}{\operatorname{SL}}
\providecommand{\Sp}{\operatorname{Sp}}
\providecommand{\Spec}{\operatorname{Spec}}

<!-- Content -->

::: {.original-citation}
Grothendieck, A.
"Technique de descente et théorèmes d'existence en géométrie algébrique, I: Généralités. Descente par morphismes fidèlement plats".
_Séminaire Bourbaki_ **12** (1959--60), Talk no. 190.
:::

(_[Trans.]_
Sections 3.1 to 3.4 were numbered A.1 to A.4 in the original;
sections 3.5 to 3.9 were numbered B.1 to B.5.)

::: {.rmenv title="Remark" latex="{Remark}"}
_[Comp.]_
For various details concerning the theory of descent, see also SGA VI, VII, and VIII.
:::

\oldpage{190-01}

From a technical point of view, the current article, and those that will follow, can be considered as variations on Hilbert's celebrated "Theorem 90".
The introduction of the method of descent in algebraic geometry seems to be due to A. Weil, under the name of "descent of the base field".
Weil considered only the case of separable finite field extensions.
The case of radicial extensions of height $1$ was then studied by P. Cartier.
Lacking the language of schemes, and, more particularly, lacking nilpotent elements in the rings that were under consideration, the essential identity between these two cases could not have been formulated by Cartier.

Currently, it seems that the general technique of descent that will be explained (combined with, when necessary, the fundamental theorems of "formal geometry", cf. [@Gro1958a]) is at the base of the majority of existence theorems in algebraic geometry.^[_[Comp.]_ It now seems excessive to say that the technique of descent is "at the base of the majority of existence theorems in algebraic geometry". This is true to a large extent for the non-projective techniques that are the object of study of the first two articles of this current series (i.e. "Techniques of descent and existence theorems in algebraic geometry"), but not for the projective techniques (articles IV, V, and VI).]
It is worth noting as well that this aforementioned technique of descent can certainly be transported to "analytic geometry", and we can hope that, in the not-too-distant future, the specialists will know how to prove the "analytic" analogues of the existence theorems in formal geometry that will be given in article II.
In any case, the recent work of Kodaira--Spencer, whose methods seem unfit for defining and studying "varieties of modules" in the neighbourhood of their singular points, show reasonably clearly the necessity of methods that are closer to the theory of schemes (which should naturally complement transcendental techniques).

In the present article (namely article I) we will discuss the most elementary case of descent (the one indicated in the title).
The applications of [Theorem 1](#fga-3-i-theorem-1), [Theorem 2](#fga-3-i-theorem-2), and [Theorem 3](#fga-3-i-theorem-3) below (in [§B.1](#fga-3-i-section-B.1)) are, however, already vast in number. 
We will restrict ourselves to giving only some of them as examples, without aiming for the maximum generality possible.

We will freely use the language of schemes, for which we refer to the already cited article, as well as [@GR1958].
We make clear to point out, however, that the preschemes considered in this current article are not necessarily Noetherian, and that the morphisms are not necessarily of finite type.
\oldpage{190-02}
So, if $A$ is a local Noetherian ring, with completion $\overline{A}$, then we will need to consider the non-Noetherian ring $\overline{\overline{A}}\otimes_A\overline{A}$, as well as the morphisms of affine schemes that correspond to the inclusions between the rings in question.

## **A.** Preliminaries on categories {-}


## Fibred categories, descent data, $\cal{F}$-descent morphisms {#fga-3-i-section-A.1}


### (a) {#fga-3-i-section-A.1.a}

::: {.rmenv #fga-3-i-section-A.1-definition-1.1 title="Definition 1.1" latex="{Definition 1.1}"}
A _fibred category $\cal{F}$ with base $\cal{C}$_ (or _over $\cal{C}$_) consists of

- a category $\cal{C}$

- for every $X\in\cal{C}$, a category $\cal{F}_X$

- for every $\cal{C}$-morphism $f\colon X\to Y$, a functor $f^*\colon\cal{F}_Y\to\cal{F}_X$, which we also write as
    $$
      f^*(\xi) = \xi \times_Y X
    $$
    for $\xi\in\cal{F}_Y$ (with $X$ being thought of as an "object of $\cal{C}$ over $Y$", i.e. as being endowed with the morphism $f$)

- for any two composible morphisms $X\xrightarrow{f}Y\xrightarrow{g}Z$, an isomorphism of functors
    $$
      c_{f,g}\colon (gf)^* \to f^*g^*
    $$

with the above data being subject to the conditions that

i. $\id^*=\id$

ii. $c_{f,g}$ is the identity isomorphism if $f$ or $g$ is an identity isomorphism

iii. for any three composible morphisms $X\xrightarrow{f}Y\xrightarrow{g}Z\xrightarrow{h}T$, the following diagram, given by using the isomorphisms of the form $c_{u,v}$, commutes:
    $$
      \begin{CD}
        (h(gf))^* @= ((hg)f)^*
      \\@VVV @VVV
      \\(gf)^*h^* @. f^*(hg)^*
      \\@VVV @VVV
      \\(f^*g^*)h^* @= f^*(g^*h^*)
      \end{CD}
    $$
:::

::: {.rmenv #fga-3-i-section-A.1-example-1 title="Example 1" latex="{Example 1}"}
Let $\cal{C}$ be a category where all fibre products exist.
We then define a fibred category $\cal{F}$ with base $\cal{C}$ by setting $\cal{F}_X$ to be the category of objects of $\cal{C}$ over $X$, and the functor $f^*\colon\cal{F}_Y\to\cal{F}_X$ corresponding to a morphism $f\colon X\to Y$ being defined by the _fibre product_ $Z\rightsquigarrow Z\times_Y X$.
:::

::: {.rmenv #fga-3-i-section-A.1-example-2 title="Example 2" latex="{Example 2}"}
Let $\cal{C}$ be the category of preschemes, and, for $X\in\cal{C}$, let $\cal{F}_X$ be the category of quasi-coherent sheaves of modules on $X$.
If $f\colon X\to Y$ is a morphism of preschemes, then $f^*\colon\cal{F}_Y\to\cal{F}_X$ is the _inverse image of sheaves of modules_ functor.
\oldpage{190-03}
We thus obtain a category fibred over $\cal{C}$.
:::


### (b) {#fga-3-i-section-A.1.b}

::: {.rmenv #fga-3-i-section-A.1-definition-1.2 title="Definition 1.2" latex="{Definition 1.2}"}
A diagram of maps of sets
$$
  E \xrightarrow{u}
  E' \ourrar{v_1}{v_2}
  E''
$$
is said to be _exact_ if $u$ is a bijection from $E$ to the subset of $E'$ consisting of the $x'\in E'$ such that $v_1(x')=v_2(x')$.
:::

:::: {.rmenv #fga-3-i-section-A.1-definition-1.3 title="Definition 1.3" latex="{Definition 1.3}"}
Let $\cal{F}$ be a fibred category with base $\cal{C}$, and consider a diagram of morphisms in $\cal{C}$
$$
  S \xleftarrow{\alpha}
  S' \oullar{\beta_1}{\beta_2}
  S''
$$
such that $\alpha\beta_1=\alpha\beta_2$;
this diagram is said to be _$\cal{F}$-exact_ if, for every pair $(\xi,\eta)$ of elements of $\cal{F}_S$, the diagram of sets

::: {.eqref #fga-3-i-section-A.1-definition-1.3-equation}
$$
  \Hom(\xi,\eta) \xrightarrow{\alpha^*}
  \Hom(\alpha^*(\xi),\alpha^*(\eta)) \ourrar{\beta_1^*}{\beta_2^*}
  \Hom(\gamma^*(\xi),\gamma^*(\eta))
\tag{+}
$$
:::

(where $\gamma=\alpha\beta_1=\alpha\beta_2$) is exact.

In this above diagram, for simplicity, we have identified $\beta_i^*\alpha^*$ with $(\alpha\beta_i)^*=\gamma^*$, using $c_{\beta_i,\alpha}$.
::::

::: {.rmenv #fga-3-i-section-A.1-definition-1.4 title="Definition 1.4" latex="{Definition 1.4}"}
Let $\cal{F}$ be a fibred category with base $\cal{C}$, and consider morphisms $\beta_1,\beta_2\colon S''\to S'$ in $\cal{C}$.
Let $\xi'\in\cal{F}_{S'}$.
We define a _gluing data_ on $\xi'$ (with respect to the pair $(\beta_1,\beta_2)$) to be an isomorphism from $\beta_1^*(\xi')$ to $\beta_2^*(\xi')$.
If $\xi',\eta'\in\cal{F}_{S'}$ are both endowed with gluing data, then a morphism $u\colon\xi'\to\eta'$ in $\cal{F}_{S'}$ is said to be _compatible with the gluing data_ if the following diagram commutes:
$$
  \begin{CD}
    \beta_1^*(\xi') @>>> \beta_2^*(\xi')
  \\@VVV @VVV
  \\\beta_1^*(\eta') @>>> \beta_2^*(\eta').
  \end{CD}
$$
:::

With this definition, the objects of $\cal{F}_{S'}$ that are endowed with gluing data (with respect to $\beta_1$ and $\beta_2$) then form a _category_.
If $\alpha\colon S'\to S$ is a morphism such that $\alpha\beta_1=\alpha\beta_2$, then, for every $\xi\in\cal{F}_{S'}$, the object $\xi'=\alpha^*(\xi)$ of $\cal{F}_{S'}$ is endowed with a canonical gluing data, since
\oldpage{190-04}
$$
  \beta_i^*\alpha^*(\xi)
  \simeq (\alpha\beta_i)^*(\xi)
  = \gamma^*(\xi),
$$
where we again set $\gamma=\alpha\beta_1=\alpha\beta_2$;
furthermore, if $u\colon\xi\to\eta$ is a morphism in $\cal{F}_s$, then
$$
  \alpha^*(u)\colon \alpha^*(\xi) \to \alpha^*(\eta)
$$
is a morphism in $\cal{F}_{S'}$ that is compatible with the canonical gluing data.
We thus obtain a _canonical functor_ from the category $\cal{F}_S$ to the category of objects of $\cal{F}_{S'}$ endowed with gluing data with respect to the pair $(\beta_1,\beta_2)$.
With this, we can also rephrase [Definition 1.3](#fga-3-i-section-A.1-definition-1.3) by saying that the diagram [(+)](#fga-3-i-section-A.1-definition-1.3-equation) is _$\cal{F}$-exact_ if the above functor is _fully faithful_, i.e. if the above functor defines an equivalence between the category $\cal{F}_S$ and a subcategory of the category of objects of $\cal{F}_S$ endowed with gluing data with respect to $(\beta_1,\beta_2)$.

::: {.rmenv #fga-3-i-section-A.1-definition-1.5 title="Definition 1.5" latex="{Definition 1.5}"}
We say that a gluing data on $\xi'\in\cal{F}_{S'}$ is _effective_ (with respect to $\alpha$) if $\xi'$, endowed with this data, is isomorphic to $\alpha^*(\xi)$ for some $\xi\in\cal{F}_S$.
:::

In the case where the diagram [(+)](#fga-3-i-section-A.1-definition-1.3-equation) is $\cal{F}$-exact, the object $\xi$ in [Definition 1.5](#fga-3-i-section-A.1-definition-1.5) is then determined up to unique isomorphism, and _the category $\cal{F}_S$ is equivalent to the category of objects of $\cal{F}_{S'}$ endowed with effective gluing data_.


### (c) {#fga-3-i-section-A.1.c}

The most important case is that where
$$
  S'' = S' \times_S S',
$$
with the $\beta_i$ being the two projections $p_1$ and $p_2$ from $S'\times_S S'$ to its two factors (where we now suppose that $\cal{C}$ has all fibre products).
We then have two immediate necessary conditions for a gluing data $\varphi\colon p_1^*(\xi')\to p_2^*(\xi')$ on some $\xi'\in\cal{F}_S$ to be effective:

i. $\Delta^*(\varphi) = \id_\xi$, where $\Delta\colon S'\to S'\times_S S'$ denotes the diagonal morphism, and where we identify $\Delta^* p_i^*(\xi')$ with $(p_i\Delta)^*(\xi')=\xi'$.

ii. $p_{31}^*(\varphi) = p_{32}^*(\varphi)p_{21}^*(\varphi)$, where $p_{ij}$ denotes the canonical projection from $S'\times_S S'\times_S S'$ to the partial product of its $i$th and $j$th factors.

\oldpage{190-05}

::: {.rmenv #fga-3-i-section-A.1-definition-1.6 title="Definition 1.6" latex="{Definition 1.6}"}
We define _descent data_ on $\xi'\in\cal{F}_{S'}$, with respect to the morphism $\alpha\colon S'\to S$, to be a gluing data on $\xi'$ with respect to the pair $(p_1,p_2)$ of canonical projections $S'\times_S S'\to S'$ that satisfies conditions (i) and (ii) above.
:::

::: {.rmenv #fga-3-i-section-A.1-definition-1.7 title="Definition 1.7" latex="{Definition 1.7}"}
A morphism $\alpha\colon S'\to S$ is said to be an _$\cal{F}$-descent morphism_ if the diagram of morphisms
$$
  S \xleftarrow{\alpha}
  S' \oullar{p_1}{p_2}
  S'\times_S S'
$$
is $\cal{F}$-exact ([Definition 1.3](#fga-3-i-section-A.1-definition-1.3));
we say that $\alpha$ is a _strict $\cal{F}$-descent morphism_ if, further, every descent data ([Definition 1.6](#fga-3-i-section-A.1-definition-1.6)) on any object of $\cal{F}_{S'}$ is effective.

This latter condition (of strictness) can also be stated in a more evocative way:
"giving an object of $\cal{F}_S$ is equivalent to giving an object of $\cal{F}_{S'}$ endowed with a descent data".
:::

Note that, if an $\cal{F}$-descent morphism^[_[Comp.]_ It is useless to assume here that $\alpha$ is an $\cal{F}$-descent morphism.] $\alpha\colon S'\to S$ admits a _section_ $s\colon S\to S'$ (i.e. a morphism $s$ such that $\alpha s=\id_S$), then it is a strict $\cal{F}$-descent morphism:
if $\xi'\in\cal{F}_{S'}$ is endowed with descent data with respect to $\alpha$, then "it comes from" $\xi=s^*(\xi')$.


### (d) {#fga-3-i-section-A.1.d}

We can present the above notions in a more intuitive manner, by introducing, for an object $T$ of $\cal{C}$ over $S$, the set
$$
  \Hom_S(T,S') = S'(T),
$$
where elements will be denoted by $t$, $t'$, etc.
Given an object $\xi'\in\cal{F}_{S'}$, there then corresponds, to every $t\in S'(T)$, an object $t^*(\xi')$ of $\cal{F}_T$, which will also be denoted by $\xi'_t$.
A gluing data on $\xi'$ (with respect to $(p_1,p_2)$) is then defined by the data, for every $T$ over $S$, and every pair of points $t,t'\in S'(T)$, of an isomorphism
$$
  \varphi_{t',t}\colon \xi'_t \to \xi'_{t'}
$$
(satisfying the evident conditions of functoriality in $T$).
Conditions (i) and (ii) of [§A.1.c](#fga-3-i-section-A.1.c) can then be written as

i bis. $\varphi_{t,t}=\id_{\xi'_t}$, for all $T$ and all $t\in S'(T)$.
\oldpage{190-06}

ii bis. $\varphi_{t,t''}=\varphi_{t,t'}\varphi_{t',t''}$, for all $T$ and all $t,t',t''\in S'(T)$.

We can show that (ii bis) implies that $\varphi_{t,t}^2=\varphi_{t,t}$, by taking $t=t'=t''$, and thus, since $\varphi_{t,t}$ is an isomorphism by hypothesis, implies (i bis), which is thus a consequence of (ii bis) (and so (i) is also a consequence of (ii)).
But if we no longer suppose a priori that the $\varphi_{t,t}$ are isomorphisms (i.e. that $\varphi\colon p_1^*(\xi')\to p_2^*(\xi')$ is an isomorphism), then (ii bis) no longer necessarily implies (i bis);
the combination of (ii bis) and (i bis), however, does imply that the $\varphi_{t,t'}$ are isomorphisms (since we then have $\varphi_{t,t'}\varphi_{t',t}=\varphi_{t,t}=\id_{\xi'_t}$).


## Exact diagrams and strict epimorphisms, descent morphisms, and examples {#fga-3-i-section-A.2}


### (a) {#fga-3-i-section-A.2.a}

::: {.rmenv #fga-3-i-section-A.2-definition-2.1 title="Definition 2.1" latex="{Definition 2.1}"}
Let $\cal{C}$ be a category.
A diagram of morphisms
$$
  T \xrightarrow{\alpha}
  T' \ourrar{\beta_1}{\beta_2}
  T''
$$
is said to be _exact_ if, for all $Z\in\cal{C}$, the corresponding diagram of sets
$$
  \Hom(Z,T) \to
  \Hom(Z,T') \rightrightarrows
  \Hom(Z,T'')
$$
is exact ([Definition 1.2](#fga-3-i-section-A.1-definition-1.2)).
We then say that $(T,\alpha)$ (or, by an abuse of language, $T$) is a _kernel_ of the pair $(\beta_1,\beta_2)$ of morphisms.
:::

This kernel is evidently determined up to unique isomorphism.
If $\cal{C}$ is the category of sets, then the above definition is compatible with [Definition 1.2](#fga-3-i-section-A.1-definition-1.2).
Dually, we define the exactness of a diagram of morphisms in $\cal{C}$
$$
  S \xleftarrow{\alpha}
  S' \oullar{\beta_1}{\beta_2}
  S''
$$
and then say that $(S,\alpha)$ is a _cokernel_ of the pair $(\beta_1,\beta_2)$ morphisms.

::: {.rmenv #fga-3-i-section-A.2-definition-2.2 title="Definition 2.2" latex="{Definition 2.2}"}
A morphism $\alpha\colon S'\to S$ is said to be a _strict epimorphism_ if it is an epimorphism and, for every morphism $u\colon S'\to Z$, the following necessary condition is also sufficient for $u$ to factor as $S'\to S\to Z$:
for every $S''\in\cal{C}$ and every pair $\beta_1,\beta_2\colon S''\to S$ of morphisms such that $\alpha\beta_1=\alpha\beta_2$, we also have that $u\beta_1=u\beta_2$.
:::

If the fibre product $S'\times_S S'$ exists, then it is equivalent to say that the diagram
$$
  S \xleftarrow{\alpha}
  S' \oullar{p_1}{p_2}
  S'\times_S S'
$$
\oldpage{190-07}
is exact, i.e. that $S$ is a cokernel of the pair $(p_1,p_2)$.
In any case, a cokernel morphism is a strict epimorphism.
Note also that, if a strict epimorphism is also a monomorphism, then it is an isomorphism.
We leave to the reader the task of developing the dual notion of a _strict monomorphism_.

To make the relation between the ideas of $\cal{F}$-descent morphisms and strict epimorphisms more precise, we introduce the following definitions:

::: {.rmenv #fga-3-i-section-A.2-definition-2.3 title="Definition 2.3" latex="{Definition 2.3}"}
A morphism $\alpha\colon S'\to S$ is said to be a _universal epimorphism_ (resp. a _strict universal epimorphism_) if, for every $T$ over $S$, the fibre product $T'=S'\times_S T$ exists, and the projection $T'\to T$ is an epimorphism (resp. a strict epimorphism).
:::

In very nice categories (such as the category of sets, the category of sets over a topological space, abelian categories, etc.), the four notions of "epijectivity" introduced above all coincide;
they are, however, all distinct in a category such as the category of preschemes, or the category of preschemes over a given non-empty prescheme $S$, even if we restrict to $S$-schemes that are finite over $S$.

::: {.rmenv #fga-3-i-section-A.2-definition-2.4 title="Definition 2.4" latex="{Definition 2.4}"}
A morphism $\alpha\colon S'\to S$ is said to be a _descent morphism_ (resp. a _strict descent morphism_) if it is an $\cal{F}$-descent morphism (resp. a strict $\cal{F}$-descent morphism) (cf. [Definition 1.7](#fga-3-i-section-A.1-definition-1.7)), where $\cal{F}$ denotes the fibred category over $\cal{C}$ of objects of $\cal{C}$ over objects of $\cal{C}$ (cf. [Example 1](#fga-3-i-section-A.1-example-1)).
:::

::: {.rmenv #fga-3-i-section-A.2-proposition-2.1 title="Proposition 2.1" latex="{Proposition 2.1}"}
If $\cal{C}$ has all finite products and (finite) fibre products, then there is an identity between descent morphisms in $\cal{C}$ and strict universal epimorphisms in $\cal{C}$.
:::


### (b) {#fga-3-i-section-A.2.b}

:::: {.rmenv title="Example" latex="{Example}"}
Let $\cal{C}$ be the category of preschemes.
Let $S\in\cal{C}$, and let $S'$ and $S''$ be preschemes that are _finite_ over $S$, i.e. that correspond to sheaves of algebras $\scr{A}'$ and $\scr{A}''$ over $S$ that are quasi-coherent (as sheaves of modules) and of finite type (i.e. coherent if $S$ is locally Noetherian).
Let $\alpha\colon S'\to S$ be the structure morphism of $S'$, and let $\beta_1$ and $\beta_2$ be $S$-morphisms from $S''$ to $S'$, defined by algebra homomorphisms $\scr{A}'\to\scr{A}''$, which we also denote by $\beta_1$ and $\beta_2$.
Using the fact that a finite morphism is closed (the first Cohen--Seidenberg theorem), we can easily prove that the diagram in $\cal{C}$

::: {.eqref #fga-3-i-section-A.2.b-equation}
$$
  S \xleftarrow{\alpha}
  S' \oullar{\beta_1}{\beta_2}
  S''
\tag{+}
$$
:::

is exact if and only if the diagram of sheaves on $S$
\oldpage{190-08}
$$
  \scr{O}_S = \scr{A} \xrightarrow{\alpha}
  \scr{A}' \ourrar{\beta_1}{\beta_2}
  \scr{A}''
$$
is exact.
In particular, if $\alpha\colon S'\to S$ is a finite morphism corresponding to a sheaf $\scr{A}'$ of algebras on $S$, then $\alpha$ is a strict epimorphism if and only if the diagram of sheaves
$$
  \scr{O}_S = \scr{A} \to
  \scr{A}' \ourrar{p_1}{p_2}
  \scr{A}'\otimes_{\scr{A}}\scr{A}'
$$
is exact (it is an epimorphism if and only if $\scr{A}\to\scr{A}'$ is injective).
If $S$ is affine of ring $A$, then $S'$ is affine of ring $A'$, with $A'$ finite over $A$, and so $S'\to S$ is a strict epimorphism if and only if $A\to A'$ is an isomorphism from $A$ to the subring of $A'$ consisting of the $x'\in A'$ such that
$$
  1_{A'}\otimes_A x' - x'\otimes_A 1_{A'} = 0
$$
(it is an epimorphism if and only if $A\to A'$ is injective).
As we have already mentioned, even if $S$ is the scheme of a local Artinian ring, then a finite morphism $S'\to S$ that is an epimorphism is not necessarily a strict epimorphism.
However, we can prove that, _if $S$ is a Noetherian prescheme, then every finite morphism $S'\to S$ that is an epimorphism is the composition of a finite sequence of strict epimorphisms_ (also finite).
This also shows that the composition of two strict epimorphisms is not necessarily a strict epimorphism.
::::


### (c) {#fga-3-i-section-A.2.c}

If [(+)](#fga-3-i-section-A.2.b-equation) is an exact diagram of finite morphisms, then, for every _flat_ morphism $T\to S$ of prescheme, the diagram induced from [(+)](#fga-3-i-section-A.2.b-equation) by a change of base $T\to S$ is again exact.
It thus follows that, if $X$ and $Y$ are $S$-preschemes, with $X$ _flat_ over $S$, then the following diagram of maps (where $X'$ and $Y'$ are the inverse images of $X$ and $Y$ over $S'$, and $X''$ and $Y''$ are their inverse images over $S''$) is exact:
$$
  \Hom_S(X,Y) \to
  \Hom_{S'}(X',Y') \rightrightarrows
  \Hom_{S''}(X'',Y'').
$$
In particular, if $\cal{F}$ denotes the fibred category (over the category $\cal{C}$ of preschemes) such that, for $X\in\cal{C}$, $\cal{F}_X$ is the category of _flat_ $X$-preschemes, then the diagram [(+)](#fga-3-i-section-A.2.b-equation) is $\cal{F}$-exact.
(This result becomes false if we do not impose the flatness hypothesis; in particular, a finite strict epimorphism is not necessarily a descent morphism).
We similarly see that [(+)](#fga-3-i-section-A.2.b-equation) is $\cal{F}$-exact if $\cal{F}$ denotes the fibred category for which $\cal{F}_X$ is the category of _flat_ quasi-coherent sheaves on the prescheme $X$ (here, again, the flatness hypothesis is essential).
\oldpage{190-09}
In either case, the question of _effectiveness_ of a gluing data (and, more specifically, of a descent data, when $S''=S'\times_S S'$) on a flat object over $S'$ is delicate (and its answer in many particular cases in one of the principal objects of these current articles).
The speaker does not know if, for every finite strict epimorphism $S'\to S$, every descent data on a flat quasi-coherent sheaf on $S'$ is effective (even if we suppose that $S$ is the spectrum of a local Artinian ring, and we restrict to locally free sheaves of rank $1$).
More generally, let $A$ be a ring, and $A'$ an $A$-algebra (where everything is commutative) such that the diagram
$$
  A \to
  A' \rightrightarrows
  A'\otimes_A A'
$$
is exact, which is equivalent to saying that the corresponding morphism $S'\to S$ between the spectra of $A'$ and $A$ is an $\cal{F}$-descent morphism, where $\cal{F}$ is the fibred category of flat quasi-coherent sheaves.
Let $M'$ be a flat $A'$-module endowed with a descent data to $A$, i.e. with an isomorphism
$$
  \varphi\colon M'\otimes_A A' \xrightarrow{\sim} A'\otimes_A M'
$$
of $(A'\otimes_A A')$-modules that satisfies conditions (i) and (ii) of [§A.1.c](#fga-3-i-section-A.1.c) (which we leave to the reader to write out in terms of modules).
Is this data effective (relative to the fibred category of flat quasi-coherent sheaves)?
Let $M$ be the subset of $M'$ consisting of the $x'\in M'$ such that
$$
  \varphi(x'\otimes_A 1_{A'}) = 1_{A'}\otimes_A x',
$$
which is a sub-$A$-module of $M'$.
The canonical injection $M\to M'$ defines a homomorphism of $A'$-modules $M\otimes_A A'\to M'$.
_The effectiveness of $\varphi$ then implies the following: $M$ is a flat $A$-module, and the above homomorphism is an isomorphism._

::: {.rmenv title="Remark" latex="{Remark}"}
In the above, we have imposed no flatness hypotheses on the morphisms of the diagram [(+)](#fga-3-i-section-A.2.b-equation), and this obliges us, in order to have a technique of descent, to impose flatness hypotheses on the objects over $S$ and $S'$ that we consider.
In [§B.2](#fga-3-i-section-B.2), we will impose a flatness hypothesis on $\alpha\colon S'\to S$, which will allow us to have a technique of descent for objects over $S$ and $S'$ that are no longer under any flatness hypotheses.
In any case, there is a flatness hypothesis involved somewhere.
This is one of the main reasons for the importance of the notion of flatness in algebraic geometry (whose role could not be visible when we restricted to base _fields_, over which everything, in fact, is flat!).
:::


## Application to étalements {#fga-3-i-section-A.3}

Let $A$ be a local ring, and $B$ a local algebra over $A$ whose maximal ideal induces that of $A$.
\oldpage{190-10}
We say that $B$ is _étalé_ over $A$ (instead of "unramified", as used elsewhere) if it satisfies the following conditions:

i. $B$ is flat over $A$; and
ii. $B/\frak{m}B$ is a separable finite extension of $A/\frak{m}=k$ (where $\frak{m}$ denotes the maximal ideal of $A$).

If $A$ and $B$ are Noetherian, and $k$ is algebraically closed, then this implies that the homomorphism $\overline{A}\to\overline{B}$ between the completions that extends $A\to B$ is an isomorphism.
A morphism $f\colon T\to S$ of finite type is said to be _étale at $x\in T$_, or $T$ is said to be _étalé over $S$ at $x$_, if $\scr{O}_x$ is étalé over $\scr{O}_{f(x)}$;
$f$ is said to be _étale_, or an _étalement_, or $T$ is said to be _étalé over $S$_, if $f$ is étale at all $x\in T$.
Note that, if $S$ is locally Noetherian, then the set of points of $T$ where $f$ is étale is open, and Zariski's "main theorem" allows us to precisely state the structure of $T/S$ in a neighbourhood around such a point (by an equation of well-known type).

If $S$ is a scheme of finite type over the field of complex numbers, then there exists a corresponding analytic space $\overline{S}$ (in the sense of Serre [@Ser1956]), except for the fact that $\overline{S}$ can have nilpotent elements in its structure sheaf, which changes nothing essential in [@Ser1956].
We then easily see that $f$ is an étalement if and only if $\overline{f}\colon\overline{T}\to\overline{S}$ is an étalement, i.e. if every point of $\overline{T}$ admits a neighbourhood on which $\overline{f}$ induces an isomorphism onto an open subset of $\overline{S}$.
In particular, to every _étale covering_ $T$ of $S$ (i.e. every finite étale morphism $f\colon T\to S$), there is a corresponding étale covering $\overline{T}$ of $\overline{S}$, which is connected if and only if $T$ is connected [@Ser1956].
We can also easily see that, if $T$ and $T'$ are étale schemes over $S$, then the natural map
$$
  \Hom_S(T,T') \to \Hom_{\overline{S}}(\overline{T},\overline{T}'')
$$
is bijective, i.e. the functor $T\mapsto\overline{T}$ from the category of étale schemes over $S$ to the category of analytic spaces over $S$ is "fully faithful", and thus defines an equivalence between the first category and a subcategory of the second.
A theorem of Grauert--Remmert [@GR1958] implies that, if $S$ is normal, then we thus obtain an equivalence between the category of _étale coverings_ of $S$ and the category of (_finite_) étale coverings of $S$, i.e. every étale covering $\scr{C}$ of $\overline{S}$ is $\overline{S}$-isomorphic to some $\overline{T}$, where $T$ is an étale covering of $S$.
We will show that _the Grauert--Remmert theorem remains true without any normality hypotheses on $S$_.
\oldpage{190-11}
First let $S'\to S$ be a finite strict epimorphism, and suppose that the theorem has been proven for $S'$; we will show that it holds for $S$.
Let $\scr{C}$ be an étale covering of $\overline{S}$, and consider its inverse image $\scr{C}'$ over $S'$, which corresponds to a coherent analytic sheaf $\frak{A}'$ of algebras on $S'$ that is the inverse image of a sheaf of algebras $\frak{A}$ on $\overline{S}$ defining $\scr{C}$.
By hypothesis, on $S'$, $\scr{C}'$ comes from an étale covering $T'$ of $S'$, i.e. $\frak{A}'$ comes from a coherent sheaf of algebras $\scr{A}'$ on $S'$.
Also, $\frak{A}'$ is endowed with a canonical descent data with respect to $\overline{S}'\to\overline{S}$, i.e. with an isomorphism between its two inverse images on $\overline{S}'\times_{\overline{S}}\overline{S}'=\overline{S'\times_SS'}$ (satisfying conditions (i) and (ii)), and this isomorphism comes from, by what has already been said, an isomorphism between the corresponding algebraic sheaves, i.e. from a descent data on $\scr{A}'$ with respect to $S'\to S$.
We can easily show that the latter is effective (since it is effective on $\frak{A}'$, and the effectiveness of a descent data, as described explicitly in the previous section, is something that can be checked locally on the _completions_ of the modules that are involved).
From this, we obtain a coherent sheaf of algebras $\scr{A}$ on $S$ that defines a covering $T$ of $S$, and this is the desired covering.
The above result then obviously holds true if $S'\to S$ is just a composition of a finite number of finite strict epimorphisms, i.e. is just an arbitrary finite epimorphism (by the factorisation result stated in [§A.2](#fga-3-i-section-A.2).
It thus follows that the Grauert--Remmert theorem holds true if $S$ is a _reduced_ scheme, i.e. such that $\scr{O}_S$ has no nilpotent elements, as we can see by introducing its normalisation $S'$.
We can easily pass to the general case.

A completely analogous argument, again using the factorisation result for finite strict epimorphisms, and the "formal" nature of the effectiveness of descent data, allows us to prove the following result:
let $S$ be a locally Noetherian prescheme, and let $S'\to S$ be a finite, surjective, and radicial morphism (or, equivalently, a morphism of finite type such that, for every $T$ over $S$, the morphism $T'=S'\times_S T\to T$ is a homeomorphism, which we can also express by saying that $S'\to S$ is a _universal homeomorphism_).
For every $T$ étalé over $S$, consider its inverse image $T'=T\times_S S'$, which is étalé over $S'$.
_Then the functor $T\mapsto T'$ is an equivalence between the category of preschemes $T$ that are étalé over $S$ and the category of preschemes $T'$ that are étalé over $S'$._
(We use the bijectivity of
$$
  \Hom_S(T_1,T_2) \to \Hom_{S'}(T'_1,T'_2)
$$
for preschemes $T_1$ and $T_2$ that are étalé over $S$, which can be proven directly without difficulty. We also use the fact that the stated theorem is true if $S'=(S,\scr{O}_S/\scr{J})$, where $\scr{J}$ is a nilpotent coherent sheaf of ideals of $\scr{O}_S$, cf. [@Mur1958, Lemma 6]).
\oldpage{190-12}
Note also that we do not suppose here that the $T$ in question are finite over $S$.
This result implies, in particular, that the morphism $S'\to S$ induces an isomorphism between the fundamental group of $S'$ and the fundamental group of $S$ ("_topological invariance of the fundamental group of a prescheme_").


## Relations to $1$-cohomology {#fga-3-i-section-A.4}


### (a) {#fga-3-i-section-A.4.a}

Let $\cal{C}$ be a category such that the product of any two objects always exists, and let $T\in\cal{C}$.
For every finite set $I\neq\varnothing$, we can consider $T^I$, and so we obtain a covariant functor from the category of non-empty finite sets to the category $\cal{C}$, i.e. what we can call a _simplicial object_ of $\cal{C}$, denoted by $K_T$.
This object depends covariantly on $T$;
also, _if $u$ and $v$ are morphisms $T\to T'$, then the corresponding morphisms $K_T\to K_{T}$ are homotopic_.
We say that $T$ _dominates_ $T'$ if $\Hom(T,T')\neq\varnothing$, and this gives an (upward) directed preorder on $\cal{C}$.
It follows from the above that, if $T$ dominates $T'$, then there exists a canonical class (up to homotopy) of homomorphisms of simplicial objects $K_T\to K_{T'}$;
in particular, if $K_T$ and $K_{T'}$ are such that $T$ and $T'$ dominate one another, then $K_T$ and $K_{T'}$ are homotopically equivalent.
Now let $F$ be a (contravariant, to be clear) functor from $\cal{C}$ to an _abelian_ category $\cal{C}'$.
Then
$$
  C^\bullet(T,F) = F(K_T)
$$
is a cosimplicial object of $\cal{C}'$, and thus defines, in a well-known way, a (cochain) complex in $\cal{C}'$, of which we can take the cohomology:
$$
  \HH^\bullet(T,F)
  = \HH^\bullet(C^\bullet(T,F))
  = \HH^\bullet(F(K_T))
$$
(we may write a subscript "$\cal{C}$" on the $\HH^\bullet$ if there is any possibility for confusion).
This is a cohomological functor in $F$, of which the variance for $T$ varying follows from what has already been said about the $K_T$;
more precisely, for fixed $F$ and varying $T$ in $\cal{C}$ (preordered by the domination relation), the $\HH^\bullet(T,F)$ form an inductive system of graded objects of $\cal{C}'$;
in particular, if $T$ and $T'$ are such that each one dominates the other, then $\HH^\bullet(T,F)$ and $\HH^\bullet(T',F)$ are canonically isomorphic.

Suppose that $\cal{C}$ has all fibre products.
Then we can, for fixed $S\in\cal{C}$, apply the above to the category $\cal{C}_S$ of objects of $\cal{C}$ over $S$;
we then write $C^\bullet(T/S,F)$ and $\HH^\bullet(T/S,F)$ instead of $C^\bullet(T,F)$ and $\HH^\bullet(T,F)$ if we wish to make clear that we are working in the category $\cal{C}_S$;
\oldpage{190-13}
then $C^\bullet(T/S,F)$ is a cochain complex in $\cal{C}'$ that, in degree $n$, is equal to $F(T\times_S T\times_S\ldots\times_S T)$ (where there are $n+1$ factors $T$).

Note that, as per usual, we can define $\HH^0(T/S,F)$ without assuming the category $\cal{C}'$ to be abelian:
it is the kernel ([Definition 2.1](#fga-3-i-section-A.2-definition-2.1)), if it exists, of the pair $(F(p_1),F(p_2))$ of morphisms
$$
  F(T) \to F(T\times_S T)
$$
corresponding to the two projections $p_1,p_2\colon T\times_S T\to T$.
In particular, we then have the natural morphism (called the _augmentation_)
$$
  F(S) \to \HH^0(T/S,F)
$$
which is an isomorphism in nice cases (in particular, in the case where $T\to S$ is a strict epimorphism and $F$ is "left exact").
Similarly, if $F$ takes values in the category of groups in a category $\cal{C}''$, then we can also define $\HH^1(T/S,F)$;
in the case where $\cal{C}''$ is the category of sets (i.e. when $F$ takes values in the category of non-necessarily-commutative groups), $\HH^1(T,F)$ is the quotient of the subgroup $Z^1(T/S,F)$ of $C^1(T/S,F) = F(T\times_S T)$ consisting of the $g$ such that
$$
  F(p_{31})(g) = F(p_{32})(g) F(p_{21})(g)
$$
by the group with operators $F(T)$ acting on $C^1(T/S,F)$, and thus, in particular, on the subset $Z^1(T/S,F)$, by
$$
  \rho(g')\cdot g = F(p_2)(g') g F(p_1)(g')^{-1}.
$$


### (b) {#fga-3-i-section-A.4.b}

For example, let $\cal{F}$ be a fibred category with base $\cal{C}$.
Let $\xi,\eta\in\cal{F}_S$, and, for all $S'$ over $S$, let
$$
  F_{\xi,\eta}(S') = \Hom(\xi\times_S S', \eta\times_S S').
$$
Then $F_{\xi,\eta}$ is a contravariant functor from $\cal{C}_S$ to the category of sets.
With this setup, _saying that the augmentation morphism_
$$
  F_{\xi,\eta}(S) \to \HH^0(S'/S,F_{\xi,\eta})
$$
_is an isomorphism for every pair of elements $\xi,\eta\in\cal{F}_S$ implies that $\alpha\colon S'\to S$ is an $\cal{F}$-descent morphism_ ([Definition 1.7](#fga-3-i-section-A.1-definition-1.7)).


### (c) {#fga-3-i-section-A.4.c}

Similarly, for $\xi\in\cal{F}_S$ and any object $S'$ of $\cal{C}$ over
$$
  G_\xi(S') = \Aut(\xi\times_S S'),
$$
we thus define a contravariant functor $G_\xi$ from $\cal{C}_S$ to the category of groups.
\oldpage{190-14}
With this setup, we claim that _$Z^1(S'/S,G)$ is canonically identified with the set of descent data on $\xi'=\xi\times_S S'$ with respect to $S'\to S$_ ([Definition 1.6](#fga-3-i-section-A.1-definition-1.6)), and that _$\HH^1(S'/S,G)$ can be identified with the set of isomorphism classes of objects of $\cal{F}_{S'}$ endowed with a descent data relative to $\alpha\colon S'\to S$ that are isomorphic, as objects of $\cal{F}_{S'}$, to $\xi'=\xi\times_S S'$_.
Then, _if $\alpha\colon S'\to S$ is an $\cal{F}$-descent morphism_ (cf. [§A.4.b](#fga-3-i-section-A.4.b)), _then $\HH^1(S'/S,G)$ contains as a subset the set of isomorphism classes of objects $\eta$ of $\cal{F}_S$ such that $\eta\times_S S'$ is isomorphic (in $\cal{F}_{S'}$) to $\xi\times_S S'$_;
further, _this inclusion is the identity if and only if every descent data on $\xi'=\xi\times_S S'$ with respect to $\alpha\colon S'\to S$ is effective_.
(This will be the case, in particular, if $\alpha\colon S'\to S$ is a strict $S$-descent morphism).

::: {.rmenv title="Remark" latex="{Remark}"}
The cochain complexes of the form $C^\bullet(T/S,F)$ contain, as particular cases, the majority of standard known complexes (that of Čech cohomology, of group cohomology, etc.), and play an important role in algebraic geometry (notably in the "Weil cohomology" of preschemes).
:::


### (d) {#fga-3-i-section-A.4.d}

::: {.rmenv #fga-3-i-section-A.4-example-1 title="Example 1" latex="{Example 1}"}
Let $S'$ be an object over $S\in\cal{C}$, and let $\Gamma$ be a group of automorphisms of $S'$ such that $S'$ is "formally $\Gamma$-principal over $S$", i.e. such that the natural morphism
$$
  \Gamma\times S' \to S'\times_S S'
$$
(where $\Gamma\times S'$ denotes the direct sum of $\Gamma$ copies of $S'$) is an isomorphism.
(We suppose that all the necessary direct sums exist in $\cal{C}$).
Let $F$ be a contravariant functor from $\cal{C}$ to the category of abelian groups.
Then _$C^\bullet(S'/S,F)$ is canonically isomorphic to the simplicial group $C^\bullet(\Gamma,F(S'))$ of standard homogeneous cochains, and so $\HH^\bullet(S'/S,F)$ is canonically isomorphic to $\HH^\bullet(\Gamma,F(S')$_.
:::


### (e) {#fga-3-i-section-A.4.e}

::: {.rmenv #fga-3-i-section-A.4-example-2 title="Example 2" latex="{Example 2}"}
Let $\cal{C}$ be the category of preschemes.
We denote by $\Ga$ (for "additive group") the contravariant functor from $\cal{C}$ to the category of abelian groups, defined by
$$
  \Ga(X) = \HH^0(X,\scr{O}_X).
$$
We similarly define the functor $\Gm$ (for "multiplicative group") by
$$
  \Gm(X) = \HH^0(X,\scr{O}_X)^\times
$$
(i.e. the group of invertible elements of the ring $\HH^0(X,\scr{O}_X)$), and, more generally, the functor $\GL(n)$ (for "linear group of order $n$") by
\oldpage{190-15}
$$
  \GL(n)(X) = \GL(n,\HH^0(X,\scr{O}_X)),
$$
which is a functor from $\cal{C}$ to the category of (not-necessary-commutative, if $n>1$) groups;
for $n=1$ we recover $\Gm$.
We can also think of $\GL(n)$ as an automorphism functor (cf. [§A.4.c](#fga-3-i-section-A.4.c)) by considering the fibred category $\cal{F}$ with base $\cal{C}$ such that $\cal{F}_X$ is the category of locally free sheaves on $X$, for $X\in\cal{C}$, since then $\GL(n)(X)=\Aut_{\cal{F}_X}(\scr{O}_X^n)$.
By [§A.4.b](#fga-3-i-section-A.4.b), it follows that, if $\alpha\colon S'\to S$ is an $\cal{F}$-descent morphism (cf. [§A.2.c](#fga-3-i-section-A.2.c)), then $\HH^1(S'/S,\GL(n))$ contains the set of isomorphism classes of locally free sheaves on $S$ whose inverse image on $S'$ is isomorphic to $\scr{O}_{S'}^n$, and this inclusion is an equality if and only if every descent data on $\scr{O}_{S'}^n$ (with respect to $\alpha\colon S'\to S$) is effective.
If $S$ is the spectrum of a local ring, then this implies that $\HH^1(S'/S,\GL(n))=(e)$, since every locally free sheaf on $S$ is then trivial.

We note that the following conditions concerning a morphism $\alpha\colon S'\to S$ are equivalent:
  
i. The augmentation homomorphism $\HH^0(S,\scr{O}_S) = \Ga(S)\to\HH^0(S'/S,\Ga)$ is an isomorphism.
ii. $\alpha\colon S'\to S$ is an $\cal{F}$-descent morphism (where $\cal{F}$ is the fibred category over $\cal{C}$ described above).
iii. $\alpha\colon S'\to S$ is a strict epimorphism (cf. [§A.2.c](#fga-3-i-section-A.2.c)).

Now suppose that $S=\Spec(A)$ and $S'=\Spec(A')$;
then
$$
  C^n(S'/S,\Ga)
  = C^n(A'/A,\Ga)
  = \underbrace{A'\otimes_A A'\otimes_A\ldots\otimes_A A'}_{n+1\text{ copies of }A'}
$$
with the coboundary operator $C^n(A'/A,\Ga)\to C^{n+1}(A'/A,\Ga)$ being the alternating sum of the face operators
$$
  \partial_i(x_0\otimes x_1\otimes\ldots\otimes x_n)
  = x_0\otimes\ldots\otimes x_{i-1}\otimes1_{A'}\otimes x_i\otimes\ldots\otimes x_n.
$$
Similarly, $C^n(S'/S,\Gm)=C^n(A'/A,\Gm)$ can be identified with $(\bigotimes_A^{n+1}A')^\times$, with the simplicial operations for $C^\bullet(A'/A,\Gm)$ being induced by those in $C^\bullet(S'/S,\Ga)$.
We can write down the simplicial operations for $C^\bullet(A'/A,\GL(n))$ in the same explicit manner.
_In all the cases known to the speaker, $\HH^i(A'/A,\Ga)=0$ for $i>0$, and, if $A$ is local, then $\HH^1(A'/A,\Gm)=0$, and, more generally, $\HH^1(A'/A,\GL(n))=(e)$_ (if $S'\to S$ is an $\cal{F}$-descent morphisms, i.e. if the diagram $A\to A'\rightrightarrows A'\otimes_A A'$ is exact, then compare this with [§A.2.c](#fga-3-i-section-A.2.c)).
\oldpage{190-16}
We note that _Hilbert's "Theorem 90" is exactly the fact that $\HH^1(S'/S,\Gm)=0$ if $A$ is a field and $A'$ is a finite Galois extension of $A$_ (cf. [Example 1](#fga-3-i-section-A.4-example-1)), _and we can also express it by saying that, in the case in question, $S'\to S$ is a strict descent morphisms for the fibred category of locally free sheaves of rank $1$._
This latter statement is the one that is most suitable to generalise Hilbert's theorem, by varying the hypotheses both on the morphism $S'\to S$ and on the quasi-coherent sheaves in question.

Finally, we note that, for a local _Artinian_ $A$ with maximal ideal $\frak{m}$, and an $A$-algebra $A'$ (where we denote, for any integer $k>0$, the ring $A/\frak{m}^{k+1}$ (resp. $A'/\frak{m}^{k+1}A'$) by $A_k$ (resp. $A'_k$)), the following properties are equivalent:

i. $\HH^1(A'_k/A_k,\Ga)=0$ for all $k$.
ii. $\HH^1(A'_k/A_k,\Gm)=0$ for all $k$.
iii. $\HH^1(A'_k/A_k,\GL(n))=(e)$ for all $k$ and all $n$.

If $S'\to S$ is a strict epimorphism, then the above conditions imply that it is a _strict_ descent morphism for free modules (not necessarily of finite type) over $A'$.
:::

::: {.rmenv title="Remark" latex="{Remark}"}
The definition of the groups $\HH^i(S'/S,\Gm)$ in the case where $S$ (resp. $S'$) is a scheme over the field $A$ (resp. $A'$) is due to Amitsur.
The group $\HH^2(S'/S,\Gm)$ is particularly interesting as a "global" variant of the Brauer group, for which we can refer to [@GD1960, chap. VII].
:::


## **B.** Descent by faithfully flat morphisms {-}


## Statement of the descent theorems {#fga-3-i-section-B.1}

::: {.rmenv #fga-3-i-section-B.1-definition-1.1 title="Definition 1.1" latex="{Definition 1.1}"}
A morphism $\alpha\colon S'\to S$ of prescheme is said to be _flat_ if $\scr{O}_{x'}$ is a flat module over the ring $\scr{O}_{\alpha(x')}$ for all $x'\in S'$ (i.e. if $\scr{O}_{x'}\otimes_{\scr{O}_{\alpha(x')}}M$ is an exact functor in the $\scr{O}_{\alpha(x')}$-module $M$).
A morphism is said to be _faithfully flat_ if it is flat and surjective.
:::

For example, if $S=\Spec(A)$ and $S'=\Spec(A')$, then $S'$ is flat over $S$ if and only if $A'$ is a flat $A$-module, and $S'$ is faithfully flat over $S$ if and only if $A'$ is a faithfully flat $A$-module (i.e. if and only if $A'\otimes_A M$ is an _exact_ and _faithful_ functor in the $A$-module $M$);
this also implies, in the terminology of Serre [@Ser1956], that the pair $(A,A')$ is flat.
If $S'$ is faithfully flat over $S$, then the inverse image functor of quasi-coherent sheaves on $S$ is exact and faithful;
\oldpage{190-17}
in other words, for a sequence of homomorphisms of quasi-coherent sheaves on $S$ to be exact, it is necessary and sufficient that its inverse image on $S'$ be exact (in particular, for a homomorphism of quasi-coherent sheaves on $S$ to be a monomorphism (resp. an epimorphism, resp. an isomorphism), it is necessary and sufficient that its inverse image on $S'$ be a monomorphism (resp. an epimorphism, resp. an isomorphism)).
This property holds true if we restrict to an arbitrary open subset of $S'$, and then characterise faithfully flat morphisms in this form.

::: {.rmenv #fga-3-i-section-B.1-definition-1.2 title="Definition 1.2" latex="{Definition 1.2}"}
A morphism $\alpha\colon S'\to S$ is said to be _quasi-compact_ if the inverse image of every quasi-compact open subset $U$ of $S$ is quasi-compact (i.e. a _finite_ union of affine open subsets).
:::

It evidently suffices to verify this property for the _affine_ open subsets of $S$.
For example, an affine morphism (i.e. a morphism such that the inverse image of an affine open subset is affine) is quasi-compact.

The class of flat (resp. faithfully flat, resp. quasi-compact) morphisms is stable under composition and by "base extension", and of course contains all isomorphisms.

::: {.itenv #fga-3-i-section-B.1-theorem-1 title="Theorem 1" latex="{Theorem 1}"}
Let $\alpha\colon S'\to S$ be a morphism of preschemes that is _faithfully flat_ and _quasi-compact_.
Then $\alpha$ is a _strict descent morphism_ (cf. [Definition 1.7](#fga-3-i-section-A.1-definition-1.7) for the fibred category $\cal{F}$ of quasi-coherent sheaves (cf. [§A, Example 2](#fga-3-i-section-A.1-example-2)).
:::

This statement implies two things:

i. If $\cal{F}$ and $\scr{G}$ are quasi-coherent sheaves on $S$, and $\cal{F}'$ and $\scr{G}'$ their inverse images on $S'$, then the natural homomorphism
    $$
      \Hom(\cal{F},\scr{G}) \to \Hom(\cal{F}',\scr{G}')
    $$
    is a bijection from the left-hand side to the subgroup of the right-hand side consisting of homomorphisms $\cal{F}'\to\scr{G}'$ that are compatible with the canonical descent data on these sheaves, i.e. whose inverse images under the two projections of $S''=S'\times_S S'$ to $S'$ give the same homomorphism $\cal{F}''\to\scr{G}''$.

ii. Every quasi-coherent sheaf $\cal{F}'$ on $S'$ endowed with a descent data with respect to the morphism $\alpha\colon S'\to S$ (cf. [Definition 1.6](#fga-3-i-section-A.1-definition-1.6) is isomorphic (endowed with this data) to the inverse image of a quasi-coherent sheaf $\cal{F}$ on $S$.

Setting $\cal{F}=\scr{O}_S$ in (i), we obtain:

::: {.rmenv #fga-3-i-section-B.1-corollary-1 title="Corollary 1" latex="{Corollary 1}"}
Let $\scr{G}$ be a quasi-coherent sheaf on $S$, with $\scr{G}'$ and $\scr{G}''$ denoting its inverse images on $S'$ and $S''=S'\times_S S'$ (respectively), and let $p_1$ and $p_2$ be the two projections from $S''$ to $S$.
Then the diagram of maps of sets
\oldpage{190-18}
$$
  \Gamma(\scr{G}) \xrightarrow{\alpha^*}
  \Gamma(\scr{G}') \ourrar{p_1^*}{p_2^*}
  \Gamma(\scr{G}'')
$$
is _exact_ (cf. [Definition 1.1](#fga-3-i-section-A.1-definition-1.1).
:::

Also, the combination of (i) and (ii) with [Definition 1.1](#fga-3-i-section-A.1-definition-1.1) gives:

::: {.rmenv #fga-3-i-section-B.1-corollary-2 title="Corollary 2" latex="{Corollary 2}"}
Let $\scr{G}$ be as in [Corollary 1](#fga-3-i-section-B.1-corollary-1).
Then there is a bijective correspondence between quasi-coherent subsheaves of $\scr{G}$ and quasi-coherent subsheaves of $\scr{G}'$ whose inverse images on $S''$ under the two projections $p_1$ and $p_2$ give the same subsheaf of $\scr{G}$.
:::

Of course, we have an equivalent statement in terms of quotient sheaves.
As we have already seen in [§A.4.e](#fga-3-i-section-A.4.e), [Theorem 1](#fga-3-i-theorem-1) should be thought of as a generalisation of Hilbert's "Theorem 90", and implies, as particular cases, various formulations in terms of $1$-cohomology.
For the proof, we can easily reduce to the case where $S=\Spec(A)$ and $S'=\Spec(A')$, and, for (i), we can easily restrict to proving [Corollary 1](#fga-3-i-section-B.1-corollary-1), i.e. the exactness of the diagram
$$
  M = A\otimes_A M \to
  A'\otimes_A M \rightrightarrows
  A'\otimes_A A'\otimes_A M
$$
for every $A$-module $M$, which follows from the more general lemma:

::: {.itenv #fga-3-i-section-B.1-lemma-1.1 title="Lemma 1.1" latex="{Lemma 1.1}"}
Let $A'$ be a faithfully flat $A$-algebra.
Then, for every $A$-module $M$, the $M$-augmented complex $C^\bullet(A'/A,\Ga)\otimes_A M$ (cf. [§A.4.e](#fga-3-i-section-A.4.e)) is a _resolution_ of $M$.
:::

::: {.proof}
It suffices to prove that the augmented complex induced from the above by extension of the base $A$ to $A'$ satisfies the same conclusions.
This leads to proving the statement when we replace $A$ by $A'$, and $A'$ by $A'\otimes_A A'$, and so we can restrict to the case where there exists an $A$-algebra homomorphism $A'\to A$ (or, in geometric terms, the case where $S'$ over $S$ admits a section).
In this case, the claim follows from the generalities of [§A.4.a](#fga-3-i-section-A.4.a).
:::

We note, in passing, the following corollary, which generalises a well-known statement in Galois cohomology (compare with [§A.4.e](#fga-3-i-section-A.4.e)):

::: {.itenv title="Corollary" latex="{Corollary}"}
If $A'$ is faithfully flat over $A$, then $\HH^0(A'/A,\Ga)=A$, and $\HH^i(A'/A,\Ga)=0$ for $i\geq1$.
:::

::: {.proof}
_Part (ii)._
To prove part (ii) of [Theorem 1](#fga-3-i-theorem-1), we proceed, as for (i), by restricting to the case where $S'$ over $S$ admits a section, where the result then follows from (i) (cf. [§A.1.c](#fga-3-i-section-A.1.c)).
:::

We can evidently vary [Theorem 1](#fga-3-i-theorem-1) and its corollaries _ad libitum_ by introducing various additional structures on the quasi-coherent sheaves (or systems of sheaves) in question.
\oldpage{190-19}
For example, the data on $S$ of a quasi-coherent sheaf of commutative algebras "is equivalent to" the data on $S'$ of such a sheaf endowed with a descent data relative to $\alpha\colon S'\to S$.
Taking into account the functorial correspondence between such quasi-coherent sheaves on $S$ and affine preschemes over $S$, we obtain the second claim of the following theorem:

::: {.itenv #fga-3-i-section-B.1-theorem-2 title="Theorem 2" latex="{Theorem 2}"}
Let $\alpha\colon S'\to S$ be as in [Theorem 1](#fga-3-i-theorem-1).
Then $\alpha$ is a (non-strict, in general) _descent morphism_ (cf. [§A, Definition 2.4](#fga-3-i-section-A-definition-2.4)), and it is a _strict descent morphism_ for the fibred category of affine schemes over preschemes (cf. [§A, Definition 1.7](#fga-3-i-section-A.1-definition-1.7).
:::

The first claim of the theorem implies this:
let $X$ and $Y$ be preschemes over $S$, with $X'$ and $Y'$ their inverse images over $S$, and $X''$ and $Y''$ their inverse images over $S''=S'\times_S S'$;
then the diagram of natural maps
$$
  \Hom_S(X,Y) \xrightarrow{\alpha^*}
  \Hom_{S'}(X',Y') \ourrar{p_1^*}{p_2^*}
  \Hom_{S''}(X'',Y'')
$$
is _exact_, i.e. $\alpha^*$ is a bijection from $\Hom_S(X,Y)$ to the subset of $\Hom_{S'}(X',Y')$ consisting of homomorphisms that are compatible with the canonical descent data on $X'$ and $Y'$ (i.e. whose inverse images under the two projections from $S''$ to $S'$ are equal).
This follows easily from [Theorem 1](#fga-3-i-theorem-1) and [Corollary 1](#fga-3-i-section-B.1-corollary-1), if we restrict to $Y$ being affine over $S$;
in the general case, we need to combine [Theorem 1](#fga-3-i-theorem-1) with the following result:

::: {.itenv #fga-3-i-section-B.1-lemma-1.2 title="Lemma 1.2" latex="{Lemma 1.2}"}
Let $\alpha\colon S'\to S$ be a faithfully flat and quasi-compact morphism.
Then $S$ can be identified with a _topological quotient space of $S'$_, i.e. every subset $U$ of $S$ such that $\alpha^{-1}(U)$ is open, is open.
:::

To complete [Theorem 2](#fga-3-i-theorem-2), we must give effectiveness criteria for a descent data on an $S'$-prescheme $X'$ (in the case where $X'$ is not assumed to be affine over $S'$).
Note first of all that _such a descent data is not necessarily effective_, even if $S$ is the spectrum of a field $k$, $S'$ the spectrum of a quadratic extension $k'$ of $k$, and $S''$ a proper algebraic scheme of dimension $2$ over $S'$ (as we can see, due to Serre, by using the non-projective surface of Nagata).
_For a descent data on $X'/S'$ with respect to $\alpha\colon S'\to S$ (assumed to be faithfully flat and quasi-compact) to be effective, it is necessary and sufficient that $X'$ be a union of open subsets $X'_i$ that are affine over $S'$ and "stable" under the descent data on $X'$._
This is certainly the case (for any $X'/S'$ and any descent data on $X'$) if the morphism $\alpha\colon S'\to S$ is _radicial_ (i.e. injective, and with radicial residual extensions).
\oldpage{190-20}
We can also show that this is the case if $\alpha\colon S'\to S$ is _finite_, and every finite subset of $X'$ that is contained in a fibre of $X'$ over $S$ is also contained in an open subset of $X'$ that is affine over $S$ (this is the _Weil criterion_).
It is, in particular, the case if $X'/S'$ is quasi-projective, and, in this case, we can show that the "descended" prescheme $X/S$ is also quasi-projective (and projective if $X'/S'$ is projective).
In summary:

::: {.itenv #fga-3-i-section-B.1-theorem-3 title="Theorem 3" latex="{Theorem 3}"}
Let $\alpha\colon S'\to S$ be faithfully flat and quasi-compact morphism of preschemes.
If $\alpha$ is _radicial_, then it is a _strict descent morphism_.
If $\alpha$ is finite, then it is a strict descent morphism with respect to the fibred category of quasi-projective (or projective) preschemes over preschemes.
:::

::: {.rmenv title="Remark" latex="{Remark}"}
I do not know if, in the second claim above, the hypothesis that $\alpha$ be _finite_ is indeed necessary;
we can prove that, in any case, we can "formally" replace it by the following, seemingly weaker, hypothesis:
_for every point of $S$ there exists an open neighbourhood $U$, a finite and faithfully flat $U'$ over $U$, and an $S$-morphism from $U'$ to $S'$_.
A type of case that is not covered by the above is that where $S=\Spec(A)$ and $S'=\Spec(\overline{A})$, with $A$ a local Noetherian ring and $\overline{A}$ its completion;
or even that where $S'$ is quasi-finite over $S$ (i.e. locally isomorphic to an open subset of a finite $S$-scheme) but not finite.
In these two cases, the speaker also does not know the answer to the following question:
let $X$ be an $S$-scheme such that $X'=X\times_S S'$ is projective over $S'$;
is it then true that $X$ is projective over $S$?

_[Comp.]_
A morphism $S'\to S$ that is quasi-finite, étale, surjective, or a morphism of the form $\Spec(\overline{A})\to\Spec(A)$, is not always a strict descent morphism, even if $A$ is the local ring of an algebraic curve over an algebraically closed field $k$ and $S=\Spec(A)$.
We can thus find a proper simple morphism $f\colon X\to S$ that makes $X$ into a principal $E$-bundle over $S$, with $E$ an elliptic curve, such that $f'\colon X'\to S'$ is projective, but $f$ is not projective.
So this is also an example of a homogeneous principal bundle that is _non-isotrivial_ under an abelian scheme.
:::


## Application to the descent of certain properties of morphisms {#fga-3-i-section-B.2}

Let $P$ be a class of morphisms of preschemes.
Let $\alpha\colon S\to S'$ be a morphism of preschemes, and let $f\colon X\to Y$ be a morphism of $S$-preschemes, with $f'\colon X'\to Y'$ the inverse image of $f$ under $\alpha$.
We can then ask if the relation "$f'\in P$" implies that "$f\in P$".
It appears that the answer is affirmative in many important cases, if we suppose that $\alpha$ is _faithfully flat_ and _quasi-compact_ (this latter hypothesis being sometimes overly strong).
We can see this directly without difficulty if $P$ is the class of surjective (resp. radicial) morphisms (with these two cases following from the surjectivity of $\alpha$), or flat (resp. faithfully flat, resp. simple) morphisms (with these three cases following from the faithful flatness of $\alpha$), or morphisms of finite type.
Using [Theorem 1](#fga-3-i-theorem-1), [Theorem 2](#fga-3-i-theorem-2), and [Lemma 1.2](#fga-3-i-section-B.1-lemma-1.2), we see that it is also true if $P$ is one of the following classes:
isomorphisms, open immersions, closed immersions, immersions (if $f$ is of finite type, and $Y$ is locally Noetherian), affine morphisms, finite morphisms, quasi-finite morphisms, open morphisms, closed morphisms, homeomorphisms, separated morphisms, or proper morphisms.
\oldpage{190-21}
The only important case not covered here is that of projective or quasi-projective morphisms, which has already been discussed in the remark in [§B.1](#fga-3-i-section-B.1).


## Decent by finite faithfully flat morphisms {#fga-3-i-section-B.3}

Let $\alpha\colon S'\to S$ be a _finite_ morphism, corresponding to a sheaf of algebras $\scr{A}'$ on $S$ that is _locally free_ and of finite type as a sheaf of modules, and everywhere non-zero.
Then $\alpha$ is a faithfully flat and quasi-compact morphism, to which we can thus apply the above results.
The data of a quasi-coherent sheaf $\cal{F}'$ on $S'$ is equivalent to the data of the quasi-coherent sheaf $\alpha_*(\cal{F}')$ on $S$ endowed with its $\scr{A}'$-modules structure (noting that $\scr{A}'=\alpha_*(\scr{O}_{S'})$).
For simplicity, we also denote this sheaf on $S$ by $\cal{F}'$.
The two inverse images $p_i^*(\cal{F}')$ of $\cal{F}'$ on $S'\times_S S'$ similarly correspond to the quasi-coherent sheaves of $(\scr{A}'\otimes_{\scr{O}_S}\scr{A}')$-modules $\cal{F}'\otimes_{\scr{O}_S}\scr{A}'$ and $\scr{A}'\otimes_{\scr{O}_S}\cal{F}'$.
The data of an $(S'\times_S S')$-homomorphism from the former to the latter is equivalent to the data of a homomorphism of $(\scr{A}'\otimes\scr{A}')$-modules, and, taking into account the fact that $\scr{A}'$ is locally free, this is equivalent to the data of a homomorphism of $(\scr{A}'\otimes\scr{A}')$-modules:
$$
  \scr{U}
  = \shHom_{\scr{O}_S}(\scr{A}',\scr{A}')
  = \scr{A}'\otimes\check{\scr{A}}'
  \to \shHom_{\scr{O}_S}(\cal{F}',\cal{F}')
$$
i.e. to the data, for every section $\xi$ of $\scr{U}$ over an open subset $V$, of a homomorphism of $\scr{O}_S$-modules $T_\xi\colon\cal{F}'|V\to\cal{F}'|V$ that satisfies the conditions

::: {.eqref #fga-3-i-section-B.3-equation-3.1}
$$
  \begin{aligned}
    T_{f\xi}(x) &= fT_\xi(x),
  \\T_{\xi f}(x) &= T_\xi(fx),
  \end{aligned}
\tag{3.1}
$$
:::

where $f$ and $x$ are (respectively) sections of $\scr{A}'$ and $\cal{F}'$ over an open subset of $S$ that is contained inside $V$.
Conditions (i) and (ii) of a descent data (cf. [§A.1.c](#fga-3-i-section-A.1.c)) can then be written (respectively) as

::: {.eqref #fga-3-i-section-B.3-equation-3.2}
$$
  T_{1_U}(x) = x,
  \qquad\text{i.e. }T_{1_U}=\id_{\cal{F}'}
\tag{3.2}
$$
:::

::: {.eqref #fga-3-i-section-B.3-equation-3.3}
$$
  T_{\xi\eta} = T_\xi T_\eta.
\tag{3.3}
$$
:::

In other words, _a descent data on $\cal{F}'$ is equivalent to a representation of the sheaf $\scr{U}=\shHom_{\scr{O}_S}(\scr{A}',\scr{A}')$ of $\scr{O}_S$-algebras in the sheaf $\shHom_{\scr{O}_S}(\cal{F}',\cal{F}')$ of $\scr{O}_S$-algebras that satisfies the two linearity conditions [(3.1)](#fga-3-i-section-B.3-equation-3.1)_.
If we have a pairing of quasi-coherent sheaves on $S'$:
$$
  \cal{F}'_1\times\cal{F}'_2 \to \cal{F}'_3
$$
\oldpage{190-22}
(that we can think of as a pairing of sheaves of $\scr{A}'$-modules on $S$), and gluing data on the $\cal{F}'_i$ defined by homomorphisms $T_i\colon\scr{U}\to\shHom_{\scr{O}_S}(\cal{F}'_i,\cal{F}'_i)$ (for $i=1,2,3$), then these data are _equivalent to the given pairing_, in the evident meaning of the phrase, if and only if the following condition is satisfied:

For every section $\xi$ of $\scr{U}$ over an open subset, and denoting by $\Delta\xi=\sum\xi'_i\otimes_{\scr{A}'}\xi''_i$ the section of $\scr{U}\otimes_{\scr{A}'}\scr{U}$ (where $\scr{U}$ is considered as an $\scr{A}'$-module with its left structure) defined by the formula
$$
  \xi\cdot(fg) = \sum_i\xi'_i(f)\xi''_i(g)
$$
(where $f$ and $g$ are sections of $\scr{A}'$ over a smaller open subset), we have the formula

::: {.eqref #fga-3-i-section-B.3-equation-3.4}
$$
  T_\xi^{(3)}(x\cdot y) = \sum_i T_{\xi'_i}^{(1)}x\cdot T_{\xi''_i}^{(2)}y
\tag{3.4}
$$
:::

for every pair $(x,y)$ of sections of $\scr{A}'$ over a smaller subset.
(We can express this property by saying that the homomorphisms $T^{(i)}$ are _compatible with the diagonal map of $\scr{U}$_, with respect to the given pair).
In particular, equations [(3.1)](#fga-3-i-section-B.3-equation-3.1) to [(3.4)](#fga-3-i-section-B.3-equation-3.4) allow us to understand, in terms of representations of algebras via diagonal maps, the descent data on a quasi-coherent sheaf of _algebras_ on $S'$, and thus also (by restricting to commutative algebras) the descent data on an affine $S'$-scheme.

From here, we obtain an analogous interpretation of descent data on an arbitrary $S'$-prescheme $X'$:
the data of such an $X'$ is equivalent to the data of a prescheme $X'$ _over $S$_ endowed with a homomorphism of $\scr{O}_S$-algebras
$$
  \scr{A}'\to\scr{O}_{X'},
$$
and a descent data on $X'$ is equivalent to the data of a sheaf homomorphism
$$
  \scr{U}
  \to \shHom_{h^{-1}(\scr{O}_S)}(\scr{O}_{X'},\scr{O}_{X'})
$$
that is compatible with the morphism $h\colon X'\to S'$ and that satisfies the conditions analogous to equations [(3.1)](#fga-3-i-section-B.3-equation-3.1) to [(3.4)](#fga-3-i-section-B.3-equation-3.4) above.

::: {.rmenv #fga-3-i-section-B.3-example-1 title="Example 1" latex="{Example 1}"}
(_Weil_).
Suppose that $S'/S$ is a _Galois étale covering_ with Galois group $\Gamma$ (cf. [§A.3](#fga-3-i-section-A.3) and [§A.4.d](#fga-3-i-section-A.4).
Then a descent data on a quasi-coherent sheaf $\cal{F}'$ on $S'$ (resp. on an $S'$-prescheme $X'$) is equivalent to the data of a representation of $\Gamma$ by automorphisms of $(S',\cal{F}')$ (resp. of $(S',X')$) that is compatible with the action of $\Gamma$ on $S'$.
\oldpage{190-23}
This result is "formal", i.e. it can be proven in terms of categories, but, from the point of view of this section, we also obtain the explicit structure of $\scr{U}$ (endowed with its ring structure, the ring homomorphism $\scr{A}'\to\scr{U}$, and the diagonal map), which is completely known thanks to the following result:
_$\scr{U}$ admits, as a left $A'$-module, a basis given by the sections of $\scr{U}$ that correspond to elements of $\Gamma$_.
:::

:::: {.rmenv #fga-3-i-section-B.3-example-2 title="Example 2" latex="{Example 2}"}
(_Cartier_).
Let $p$ be a prime number, and suppose that $p\scr{O}_S=0$ (i.e. that $\scr{O}_S$ is of _characteristic $p$_), that $(\scr{A}')^p\subset\scr{O}_S=\scr{A}$ (i.e. that $S'/S$ is _radicial of height $1$_), and that the sheaf of algebras $\scr{A}'$ over $\scr{A}$ _locally admits a $p$-basis_ (i.e. a family $(x_i)$ of sections such that $\scr{A}'$ is generated as an algebra by the $x_i$ under the sole condition that $x_i^p=0$).
We suppose that the set of the $i$ is finite, of cardinality $n$.
Let $\frak{C}$ be the sheaf of $A$-derivations of $A'$, which is a locally free sheaf of rank $n$ of $A'$-modules, and, furthermore, a sheaf of Lie $p$-algebras over $\scr{A}$ (but not over $\scr{A}'$) that satisfies the following condition:

::: {.eqref #fga-3-i-section-B.3-equation-3.5}
$$
  [X,fY] = X(f)Y + f[X,Y].
\tag{3.5}
$$
:::
::::

:::: {.itenv title="Lemma" latex="{Lemma}"}
$\scr{U}=\shHom_{\scr{O}_S}(\scr{A}',\scr{A}')$ is generated, as an $\scr{O}_S$-algebra endowed with an algebra homomorphism $\scr{A}'\to\scr{U}$, by the sub-left-$A'$-module $\frak{C}$, with the following additional relations:

::: {.eqref #fga-3-i-section-B.3-equation-3.6}
$$
  \begin{cases}
    Xf-fX &= X(f)
  \\XY-YX &= [X,Y]
  \\X^p &= X^{(p)}.
  \end{cases}
\tag{3.6}
$$
:::
::::

It follows from the above lemma that a descent data on the quasi-coherent sheaf $\cal{F}'$ on $S'$ is equivalent to the data, for all $X\in\frak{C}$, of an $\scr{O}_S$-endomorphism $\overline{X}$ of $\cal{F}'$ that satisfies the following conditions:

::: {.eqref #fga-3-i-section-B.3-equation-3.7}
$$
  \overline{fX} = f\overline{X}
\tag{3.7}
$$
:::

::: {.eqref #fga-3-i-section-B.3-equation-3.8}
$$
  \overline{X}(fx) = X(f)x + f\overline{X}(x)
\tag{3.8}
$$
:::

::: {.eqref #fga-3-i-section-B.3-equation-3.9}
$$
  \overline{[X,Y]} = [\overline{X},\overline{Y}]
\tag{3.9}
$$
:::

::: {.eqref #fga-3-i-section-B.3-equation-3.10}
$$
  \overline{X^{(p)}} = \overline{X}^p.
\tag{3.10}
$$
:::

(This is what we may call a _linear connection on $\cal{F}$_, which is further _flat_ and _compatible with the $p$-th powers_).
We can similarly write down the notion of a descent data on an $S'$-prescheme $X'$, with equation [(3.4)](#fga-3-i-section-B.3-equation-3.4) being replaced by the condition that the $\overline{X}$ are _derivations_ of $\scr{O}_{X'}$.
Since the morphism $S'\to S$ is radicial, [Theorem 3](#fga-3-i-theorem-3) ensures that every such descent data is effective, and thus defines an $S$-prescheme $X$.
\oldpage{190-24}

Note that we have not needed to impose any flatness, non-singular, or finiteness hypotheses on $\cal{F}'$ or $X'$.




## Application to rationality criteria {#fga-3-i-section-B.4}

Let $X$ be an $S$-prescheme such that the direct image of $\scr{O}_X$ on $S$ is $\scr{O}_S$;
this property remains true for any flat base extension $S'\to S$.
If $\cal{F}$ is an _invertible sheaf_ (i.e. locally free of rank $1$) on $X$, then there is a bijective correspondence between automorphisms of $\cal{F}$ (identified with the invertible sections of $\scr{O}_X$) and invertible sections of $\scr{O}_S$.
So let $s$ be a section of $X$ over $S$;
we define a _section of $\cal{F}$ over $s$_ to be a section of the invertible sheaf $s^*(\cal{F})$ on $S$.
It follows from the above that, if $\cal{F}_i$ (for $i=1,2$) are invertible sheaves on $X$, each endowed with a section over $s$, and _if $\cal{F}_1$ and $\cal{F}_2$ are isomorphic, then there exists exactly one isomorphism from $\cal{F}_1$ to $\cal{F}_2$ that is compatible with the sections in question_ (i.e. sending the first to the second).
We also, independently of the section $s$, regard two invertible sheaves $\cal{F}_1$ and $\cal{F}_2$ on $X$ as _equivalent_ if every point of $S$ has an open neighbourhood $U$ such that the restrictions of $\cal{F}_1$ and $\cal{F}_2$ to $X|U$ are isomorphic.
Then _every invertible sheaf $\cal{F}$ on $X$ is equivalent to an invertible sheaf $\cal{F}_1$ endowed with a marked section over $s$_ (we take $\cal{F}_1=Fs^*(\cal{F})^{-1}$), _and $\cal{F}_1$ is determined up to isomorphism_.
In other words, the classification _up to equivalence_ of invertible sheaves on $X$ is the same as the classification _up to isomorphism_ of invertible sheaves endowed with a marked section.

Since these properties remain true under flat extensions $\alpha\colon S'\to S$ of the base (by replacing the section $s$ with its inverse image $s'$ under $\alpha$), we thus conclude, taking [Theorem 1](#fga-3-i-theorem-1) into account:

_With the prescheme $X/S$ being as above, and admitting a section $s$, let $\alpha\colon S'\to S$ be a faithfully flat and quasi-compact morphism; let $\cal{F}'$ be an invertible sheaf on $X'=X\times_S S'$._
_For $\cal{F}'$ to be equivalent to the inverse image on $X'$ of an invertible sheaf $\cal{F}'$ on $X$, it is necessary and sufficient for its inverse images $p_1^*(\cal{F}')$ and $p_2^*(\cal{F}')$ on $X'\times_X X'=X\times_S(S'\times_S S')$ to be equivalent._
_If this is the case, then $\cal{F}$ is determined up to equivalence._
(We then say that $\cal{F}'$ is _rational_ on $S$).

Considering this principle in the case where $\alpha\colon S'\to S$ is as in [Example 1](#fga-3-i-section-B.3-example-1) and [Example 2](#fga-3-i-section-B.3-example-2) in the previous section, we recover the _rationality criteria of Weil and of Cartier_.
\oldpage{190-25}
(We note that the authors restrict to the case where $S$ and $S'$ are spectra of fields;
a fortiori, $S$ is then the spectrum of a local ring, and the equivalence relation introduced above is exactly the relation of being isomorphic).
The the first case, $\cal{F}'$ is rational on $S$ if and only if its images under $\Gamma$ are all equivalent to $\cal{F}'$.
To express the rationality criterion in the second case, we consider, more generally, the diagonal morphism $X'\to X''=X'\times_X X'$ of $X'/X$, with the corresponding sheaf of ideals $\scr{I}$ on $X'\times_X X'$, and the sheaf $\scr{I}/\scr{I}^2$, which can be identified with its inverse image $\Omega_{X'/X}^1$ on $X$ (the _sheaf of $1$-differentials of $X'$ with respect to $X$_).
Since the restrictions of the $\cal{F}''_i=p_i(\cal{F}')$ (for $i=1,2$) to the diagonal are isomorphic (since they are both isomorphic to $\cal{F}'$), i.e. $\cal{F}''_1(\cal{F}''_2)^{-1}=\cal{F}''$ has a restriction to the diagonal which is trivial, it follows that the restriction of $\cal{F}''$ to $(X'',\scr{O}_{X''}/\scr{I}^2)$ is given, up to isomorphism, by a well-defined element $\xi$ of
$$
  \HH^1(X'',\scr{I}/\scr{I}^2) = \HH^1(X',\Omega_{X'/X}^1).
$$
Also, being precise, we have $\Omega_{X'/X}^1=\Omega_{S'/S}^1\otimes_{\scr{O}_S}\scr{O}_X$, and thus, _if $\Omega_{S'/S}^1$ is locally free on $S$_ (as in the Cartier case), _then $\xi$ defines a section of $\RR^1f'(\scr{O}_{X'})\otimes\Omega_{S'/S}^1$ on $S'$_ (called the _Atiyah--Cartier class of the invertible sheaf $\cal{F}$ on $X'/S$_) _whose vanishing is necessary and sufficient for the inverse images of $\cal{F}'$ under the two projections of_
$$
  (X'',\scr{O}_{X''}/\scr{I}^2) = X\times_S(S'',\scr{O}_{S''}/\scr{J}^2)
$$
_to $X'$ to be equivalent_ (where $\scr{J}$ is the sheaf of ideals on $S''=S'\times_S S'$ defined by the diagonal morphism $S'\to S'\times_S S'$).
This vanishing is thus trivially _necessary_ for the inverse images of $\cal{F}'$ on $X''=X\times_S S''$ itself to be equivalent, and thus also for $\cal{F}$ to be equivalent to the inverse image of an invertible sheaf $\cal{F}$ on $X$.
The Atiyah--Cartier class can also be understood as the obstruction to the existence, locally over $S'$, of a _connection_ of $\cal{F}'$ relative to the derivations of $X'/X$, with such a connection further being determined when we know the derivations of $\cal{F}'$ corresponding to the natural extensions of derivations of $S'/S$ to $X'$.
From this, and the results of the previous section, we easily conclude that, in the case of the aforementioned [Example 2](#fga-3-i-section-B.3-example-1), and when $X/S$ admits a section, the vanishing of the Atiyah--Cartier class is also sufficient for $\cal{F}'$ to be rational on $S$.


## Application to the restriction of the base scheme to an abelian scheme {#fga-3-i-section-B.5}

Let $S$ be a prescheme.
\oldpage{190-26}
Well define an _abelian scheme_ over $S$ to be a simple proper scheme $X$ over $S$ whose fibres at the points $x\in S$ are schemes of abelian varieties over the $\kres(x)$.
Suppose that $S$ is Noetherian and _regular_ (i.e. that its local rings are regular), then we can show, using the _connection theorem_ of Murre [@Mur1958]
(at least in the case "of equal characteristics", where the cited theorem is currently proven) that _every rational section of $X$ over $S$ is everywhere defined_ (i.e. is a section) (which generalises a classical theorem of Weil).
It then follows, more generally, that, if $X'$ is a simple scheme over $S$, then every rational $S$-map from $X'$ to $X$ is everywhere defined.
From this, we obtain the following, which generalises a result of Chow--Lang:
_with $S$ Noetherian and regular, and $K$ denoting its ring of rational functions_ (a direct sum of fields), _let $X$ be an abelian scheme over $K$; if $X$ is isomorphic to a $K$-scheme of the form $X_0\times_S\Spec(K)$, where $X_0$ is an abelian scheme over $S$, then $X_0$ is determined up to unique isomorphism._

Using the above uniqueness result, we see that the question of restriction of the base to $X$ is local on $S$ (and thus that it suffices to know how to do the restriction to $\Spec(\scr{O}_x)$, where $x\in S$).
In the same way, we see that, if $S'\to S$ is a _simple_ morphism of finite type, if $Y'$ is the ring of rational functions of $S'$, and if $X\otimes_K K'$ is of the form $X'_0\times_{S'}\Spec(K')$, _then $X'_0$ is endowed with a canonical descent data with respect to $\alpha$_.
Taking [Theorem 3](#fga-3-i-theorem-3) into account, we thus conclude:

::: {.itenv #fga-3-i-section-B.5-proposition-5.1 title="Proposition 5.1" latex="{Proposition 5.1}"}
Let $S$ be an irreducible regular Noetherian prescheme, with field of rational functions $Y$, let $K'$ be a finite extension of $K$ that is _unramified over $S$_, let $S'$ be the normalisation of $S$ in $K'$ (which is thus an étale cover of $S$), and let $X$ be an abelian scheme over $K$ such that $X\otimes_K K'$ is of the form $X'_0\times_{S'}\Spec(K')$, where $X'_0$ is a projective abelian scheme over $S'$.
Then $X$ is of the form $X_0\times_S\Spec(K)$, where $X_0$ is a projective abelian scheme over $S$.
:::

::: {.rmenv title="Remark" latex="{Remark}"}
The speaker does not know if we can replace the hypothesis that $S'\to S$ be a surjective étale cover (which allows us to apply [Theorem 3](#fga-3-i-theorem-3)) with the hypothesis that it is instead a _simple_ and _surjective_ morphism of finite type (not even if we suppose that it is an étalement), or if the proposition still holds true without supposing that $X'_0$ is projective over $S'$ (a condition which could be automatically satisfied).
:::


## Application to local triviality and isotriviality criteria {#fga-3-i-section-B.6}

Let $S$ be a prescheme, $G$ a "_prescheme of groups_" over $S$, $P$ a prescheme over $S$ on which "_$G$ acts_" (on the right).
We say that $P$ is _formally principal homogeneous_ under $G$ if the well-known morphism
$$
  G\times_S P \to P\times_S P
$$
\oldpage{190-27}
(induced from the actions of $G$ on $P$) is an _isomorphism_.
From now on, we assume $G$ to be _flat_ over $S$ (and thus faithfully flat over $S$), and we reserve the name of _principal homogeneous bundle_ under $G$ for a formally principal homogeneous bundle $P$ that is _faithfully flat_ and _quasi-compact_ over $S$.
It is immediate that this is equivalent to being able to find a _faithfully flat_ and _quasi-compact extension_ $S'\to S$ of the base $S$ such that the formally principal homogeneous bundle $P'=P\times_S S'$ under $G'=G\times_S S'$ is _trivial_, i.e. isomorphic to $G'$ (i.e. admitting a section);
we can take, in particular, $S'=P$.
Note also that, if $S$ is locally Noetherian, then the faithfully-flat hypothesis on $P$ is equivalent to the hypothesis that $\overline{P}_S=P\times_S\Spec(\overline{\scr{O}}_s)$ be faithfully flat over $\overline{\scr{O}}_s$ for all $s\in S$ (where $\overline{\scr{O}}_s$ denotes the completion of the local ring $\scr{O}_s$), as follows from the fact that $\overline{\scr{O}}_s$ is faithfully flat over $\scr{O}_s$.
Also, if $P$ is of finite type over $S$, and $S$ is locally Noetherian, then the set of points $s$ satisfying the above condition is constructible, and so, if $S$ is a "Jacobson prescheme" (for example, a scheme of finite type over a field, or, more generally, over a Jacobson ring), then it suffices to verify the condition in question for the _closed_ points of $S$.
This leads us to the case where the base is the spectrum of a complete local ring $A$.
If $S=\Spec(A)$ (with $A$ a complete Noetherian local ring), and if $P$ is of finite type over $S$, then the faithful flatness of $P/S$ is also equivalent to the existence of an $S'$ that is _finite and flat_ over $S$ such that $P'$ is trivial, and, if, further, $G$ is _simple_ over $S$, then we can suppose $S'$ to be _étale_ over $S$.
Then, if, further, the residue field of $A$ is algebraically closed (the "_geometric case_"), then $P$ is faithfully flat over $A$ if and only if it is trivial.
Thus, if $S$ is an algebraic prescheme over an algebraically closed field, and if $G$ is simple and of finite type over $S$, then we see that the faithfully-flat condition on $S$ is equivalent to the condition of being analytically trivial (SLF) of Serre [@Ser1958a, pp. 1--12].

We can consider other, stronger, types of conditions on $P$, that have a "local triviality" nature.
In particular, we say that $P$ is _isotrivial_ (resp. _strictly isotrivial_) if, for all $s\in S$, there exists an open neighbourhood $U$ of $S$, and a _finite and faithfully flat_ morphism (resp. a _surjective étale covering_) $U'\to U$ such that $P'=P\times_S U'$ is trivial.
(We stray from the terminology of Serre [@GD1960], which uses "locally isotrivial" for what we call "strictly isotrivial").
Strict isotriviality is mainly useful if $G$ is simple over $S$, but is, however, an inadequate notion in other cases.

If $G$ is _affine_ over $S$, then every principal homogeneous bundle $P$ under $G$ is affine, by [§B.2](#fga-3-i-section-B.2), whence the possibility, thanks to [Theorem 2](#fga-3-i-theorem-2), to "descend" from such bundles by faithfully flat and quasi-compact morphisms.
\oldpage{190-28}
Taking, in particular, $G=\GL(n)_S$, defined by the condition that the functor $S'\mapsto\Hom(S',G)$ of $S$-preschemes (with values in the category of groups) can be identified with the functor $\GL(n)(S')=\GL(n,\HH^0(S',\scr{O}_{S'}))$ described in [§A.4.e](#fga-3-i-section-A.4).
Using the facts

i. that every principal homogeneous bundle under $G$ (resp. every locally free sheaf of rank $n$ on $S$) becomes isomorphic to the "trivial" object $G$ (resp. $\scr{O}_S^n$) under a suitable faithfully flat and quasi-compact extension of $S$;

ii. that we can descend the type of objects in question (principal homogeneous bundles under $G$, resp. locally free sheaves of rank $n$) by such morphisms; and, finally

iii. that the automorphism group of the trivial bundle on any $S'/S$ is functorially isomorphic to the automorphism group of the trivial locally free sheaf of rank $n$ on $S'$,

we "formally" conclude that it is "equivalent" to give, on $S$ (or on some $S'/S$) a principal homogeneous bundle of group $G$, or to give a locally free sheaf of rank $n$.
(More precisely, we have an _equivalence of fibred categories_).
We thus conclude, in particular:

::: {.itenv #fga-3-i-section-B.6-proposition-6.1 title="Proposition 6.1" latex="{Proposition 6.1}"}
Every principal homogeneous bundle under the group $\GL(n)_S$ is locally trivial.
:::

By known arguments, we thus conclude the same result for others structure groups such as $\SL(n)_S$, $\Sp(n)_S$, and products of such groups.
We thus also conclude that, if $F$ is a closed subgroup of $G=\GL(n)_S$ that is flat over $S$, and such that the quotient $G/F$ exists, and such that $G$ is an isotrivial (resp. strictly isotrivial) principal homogeneous bundle on $G/F$, of structure group $F\times_S(G/F)$, then _every_ principal homogeneous bundle of structure group $F$ is isotrivial (resp. strictly isotrivial).
This applies to all the "linear groups" on $S$ that have been used up until now, and, in particular, to the case where $G=S\times_k\Gamma$, with $S$ a prescheme over the field $k$, and $\Gamma$ a linear group (in the classical sense) over $k$ (and thus in particular simple).
This thus answers, for such groups, a question of Serre (loc. cit.).

We also point out that, for most groups (linear or not) that are simple over $S$ that we know of, and certainly for all those of the form $S\times_k\Gamma$ as above, we can show that every isotrivial principal homogeneous bundle is strictly isotrivial, which answers, in particular, another question of Serre (loc. cit. 1--14), taking into account the fact that a homogeneous principal bundle obtained by a descent _à la_ Cartier (cf.[Example 2](#fga-3-i-section-B.3-example-2)) is obviously isotrivial.

::: {.rmenv title="Remark" latex="{Remark}"}
One of the essential difficulties in these questions (setting aside the question of the existence of quotient schemes) is the lack of effectiveness criteria for a descent data along a faithfully flat _non-finite_ morphism.
:::
