# The existence theorem and the formal theory of modules {#fga-3.ii}

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\kres}{\mathfrak{K}}
\providecommand{\simto}{\xrightarrow{\sim}}
\providecommand{\simfrom}{\xleftarrow{\sim}}
\providecommand{\Set}{\mathtt{Set}}

\providecommand{\id}{\operatorname{id}}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\repHom}{\underline{\Hom}}
\providecommand{\Aut}{\operatorname{Aut}}
\providecommand{\repAut}{\underline{\Aut}}
\providecommand{\HH}{\operatorname{H}}
\providecommand{\RR}{\operatorname{R}}
\providecommand{\GL}{\operatorname{GL}}
\providecommand{\Ga}{\operatorname{G_a}}
\providecommand{\Gm}{\operatorname{G_m}}
\providecommand{\SL}{\operatorname{SL}}
\providecommand{\Sp}{\operatorname{Sp}}
\providecommand{\Spec}{\operatorname{Spec}}
\providecommand{\Pro}{\operatorname{Pro}}
\providecommand{\Ext}{\operatorname{Ext}}
\providecommand{\op}{\circ}

<!-- Content -->

::: {.original-citation}
Grothendieck, A.
"Technique de descente et théorèmes d'existence en géométrie algébrique, II: Le théorème d'existence et théorie formelle des modules".
_Séminaire Bourbaki_ **12** (1959--60), Talk no. 195.
:::

(_[Trans.]_
Sections 4.1 to 4.5 were numbered A.1 to A.5 in the original;
sections 4.6 to 4.10 were numbered C.1 to C.5.)


## **A.** Representable and pro-representable functors {-}


## Representable functors {#fga-3-ii-section-A.1}

Let $\cal{C}$ be a category.
\oldpage{195-01}
For all $X\in\cal{C}$, let $h_X$ be the contravariant functor from $\cal{C}$ to the category $\Set$ of sets given by
$$
  \begin{aligned}
    h_X\colon \cal{C} &\to \Set
  \\Y&\mapsto \Hom(Y,X).
  \end{aligned}
$$
If we have a morphism $X\to X'$ in $\cal{C}$, then this evidently induces a morphism $h_X\to h_{X'}$ of functors;
$h_X$ is a covariant functor in $X$, i.e. we have defined a _canonical covariant functor_
$$
  h\colon \cal{C} \to \Hom(\cal{C}^\op,\Set)
$$
from $\cal{C}$ to the category of covariant functors from the dual $\cal{C}^\op$ of $\cal{C}$ to the category of sets.
We then recall:

::: {.itenv #fga-3-ii-section-A.1-proposition-1.1 title="Proposition 1.1" latex="{Proposition 1.1}"}
This functor $h$ is _faithfully flat_;
in other words, for every pair $X,X'$ of objects of $\cal{C}$, the natural map
$$
\Hom(X,X') \to \Hom(h_X,h_{X'})
$$
is _bijective_.
:::

In particular, if a functor $F\in\Hom(\cal{C}^\op,\Set)$ is isomorphic to a functor of the form $h_X$, then _$X$ is determined up to unique isomorphism_.
We then say that the functor $F$ is _representable_.
The above proposition then implies that the canonical functor $h$ defines an _equivalence_ between the category $\cal{C}$ and the full subcategory of $\Hom(\cal{C}^\op,\Set)$ consisting of representable functors.
This fact is the basis of _the idea of a "solution of a universal problem"_, with such a problem always consisting of examining if a given (contravariant, as here, or covariant, in the dual case) functor from $\cal{C}$ to $\Set$ is representable.
\oldpage{195-02}
Note further that, even by the definition of products in a category [@Gro1957], the functor $h\colon X\mapsto h_X$ commutes with products whenever they exist (and, more generally, with finite or infinite projective limits, and, in particular, with fibred products, taking "kernels" [@Gro1958a], etc., whenever such things exist): we have an isomorphism of functors
$$
  h_{X\times X'} \simto h_X\times h_{X'}
$$
whenever $X\times X'$ exists, i.e. we have functorial (in $Y$) bijections
$$
  h_{X\times X'} \simto h_X(Y)\times h_{X'}(Y).
$$
In particular, the data of a morphism
$$
  X\times X' \to X''
$$
in $\cal{C}$ (i.e. of a "_composition law_" in $\cal{C}$ between $X$, $X'$, and $X''$) is equivalent to the data of a morphism $h_{X\times X'}=h_X\times h_{X'}\to h_{X''}$, i.e. to the data, for all $Y\in\cal{C}$, of a composition law of _sets_
$$
  h_X(Y)\times h_{X'}(Y) \to h_{X''}(Y)
$$
such that, for every morphism $Y\to Y'$ in $\cal{C}$, the system of set maps
$$
  h_{X^{(i)}}(Y) \to h_{X^{(i)}}(Y')
  \qquad\text{(for }i=0,1,2\text{)}
$$
is a morphism for the two composition laws, with respect to $Y$ and $Y'$.
In this way, we see that the idea of a "$\cal{C}-group$" structure, or a "$\cal{C}$-ring" structure, etc. on an object $X$ of $\cal{C}$ can be expressed in the most manageable way (in theory as much as in practice) by saying that, for every $Y\in\cal{C}$, we have a group law (resp. ring law, etc.) in the usual sense on the set $h_X(Y)$, with the maps $h_X(Y)\to h_X(Y')$ corresponding to morphisms $Y\to Y'$ that should be group homomorphisms (resp. ring homomorphisms, etc.).
This is the most intuitive and manageable way of defining, for example, the various classical groups $\Ga$, $\Gm$, $\GL(n)$, etc. on a prescheme $S$ over an arbitrary base, and of writing the classical relations between these groups, or of placing a "vector bundle" structure on the affine scheme $V(\scr{F})$ over $S$ defined by a quasi-coherent sheaf $\scr{F}$, and of defining and studying the many associated flag varieties (Grassmannians, projective bundles), etc.;
_the general yoga is purely and simply identifying, using the canonical functor $h$, the objects of $\cal{C}$ with particular contravariant functors (namely, representable functors) from $\cal{C}$ to the category of sets_.

\oldpage{195-03}

The usual procedure of reversing the arrows that is necessary, for example, in the case of affine schemes in order to pass from the geometric language to the language of commutative algebra, leads us to dualise the above considerations, and, in particular, to also introduce _covariant representable functors $\cal{C}\to\Set$_, i.e. those of the form $Y\mapsto\Hom(X,Y)=h'_X(Y)$.


## Pro-representable functors, pro-objects {#fga-3-ii-section-A.2}

Let $\cal{X}=(X_i)_{i\in I}$ be a projective system of objects of $\cal{C}$;
there is a corresponding covariant functor
$$
  h'_{\cal{X}} = \varinjlim_i h'_{X_i}
$$
which can be written more explicitly as
$$
  h'_{\cal{X}}(Y) = \varinjlim_i h'_{X_i}(Y) = \varinjlim_i\Hom(X_i,Y)
$$
which is a functor from $\cal{C}$ to $\Set$.
A functor from $\cal{C}$ to $\Set$ that is isomorphic to a functor of this type _with $I$ filtered_ is said to be _pro-representable_.
By the previous section, these are exactly the functors that are isomorphic to _filtered inductive limits of representable functors_.
Let $\cal{X}'=(X_j)_{j\in J}$ be another filtered projective system in $\cal{C}$ (indexed by another filtered preordered set of indices $J$).
Then we can easily show that we have a canonical bijection
$$
  \Hom(h_{\cal{X}'},h_{\cal{X}}) = \varprojlim_j\varinjlim_i\Hom(X_i,X'_j)
$$
(generalising [§A, Proposition 1.1](#fga-3-ii-section-A.1-proposition-1.1)).
This leads to introducing the _category $\Pro(\cal{C})$ of pro-objects of $\cal{C}$_, whose objects are projective systems of objects of $\cal{C}$ (indexed by arbitrary filtered preordered sets of indices), and whose morphisms between objects $\cal{X}=(X_i)_{i\in I}$ and $\cal{X}'=(X_j)_{j\in J}$ are given by
$$
  \Pro\Hom(\cal{X},\cal{X}') = \varprojlim_j\varinjlim_i\Hom(X_i,X'_j),
$$
with the composition of pro-homomorphisms being evident.
By the very construction itself, $\cal{X}\mapsto h'_{\cal{X}}$ can be considered as a contravariant functor in $\cal{X}$, establishing an _equivalence between the dual category of the category $\Pro(\cal{C})$ of pro-objects of $\cal{C}$ and the category of pro-representable covariant functors from $\cal{C}$ to $\Set$_.
\oldpage{195-04}
Of course, an object $X$ of $\cal{C}$ canonically defines a pro-object, denoted again by $X$, so that _$\cal{C}$ is equivalent to a full subcategory of $\Pro(\cal{C})$_.
Then, if $\cal{X}=(X_i)_{i\in I}$ is an arbitrary pro-object of $\cal{C}$, then (with the above identification) we have that
$$
  \cal{X} = \varprojlim_i X_i
$$
with the projective limit being _taken in $\Pro(\cal{C})$_ (since $h_{\cal{X}}=\varinjlim_i h_{X_i}$).

We draw attention to the fact that, even if the projective limit of the $X_i$ _exists in $\cal{C}$_, it will generally _not_ be isomorphic to the projective limit $\cal{X}$ in $\Pro(\cal{C})$, as is already evident in the case where $\cal{C}$ is the category of sets.
We note that, by the definition itself, $\varprojlim{}_{\cal{C}}X_i=L$ is defined by the condition that the functor
$$
  \varprojlim_i\Hom_{\cal{C}}(Y,X_i)=\Hom_{\Pro(\cal{C})}(Y,\cal{X})
$$
in $Y\in\cal{C}$ and with values in $\Set$ be representable via $\cal{L}$, i.e. that it be isomorphic to $\Hom_{\cal{C}}(Y,\cal{L})$;
then _$\lim{}_{\cal{C}}X_i$ is already defined in terms of the *pro-object* $\cal{X}$_, and, in a precise way, depends functorially on the pro-object $\cal{X}$ whenever it is defined;
there is therefore no problem with denoting it by $\lim{}_{\cal{C}}(\cal{X})$.
If projective limits in $\cal{C}$ always exist, then $\lim{}_{\cal{C}}(\cal{X})$ is a functor from $\Pro(\cal{C})$ to $\cal{C}$, and there is a canonical homomorphism of functors $\lim_\cal{C}(\cal{X})\to\cal{X}$.
Since every (covariant, say, for simplicity) functor
$$
  F\colon \cal{C} \to \cal{C}'
$$
can be extended in an obvious way to a functor
$$
  \Pro(F)\colon \Pro(\cal{C}) \to \Pro(\cal{C}'),
$$
it follows that, if projective limits always exist in $\cal{C}'$, then $F$ also canonically defines a composite functor
$$
  \overline{F} = \varprojlim{}_{\cal{C}'}\colon \Pro(\cal{C}) \to \cal{C}'
$$
sending $\cal{X}=(X_i)_{i\in I}$ to $\varprojlim{}_{\cal{C}'}F(X_i)$.

A pro-object $\cal{X}$ is said to be a _strict pro-object_ if it is isomorphic to a pro-object $(X_i)_{i\in I}$, where the transition morphisms $X_i\to X_j$ are _epimorphisms_;
a functor defined by such an object is said to be _strictly pro-representable_.
We can thus further demand that $I$ be a filtered _ordered_ set, and that every epimorphism $X_i\to X'$ be equivalent to an epimorphism $X_i\to X_j$ for some suitable $j\in I$ (uniquely determined by this condition).
\oldpage{195-05}
Under these conditions, the projective system $(X_i)_{i\in I}$ is determined _up to unique isomorphism_ (in the usual sense of isomorphisms of projective systems).
It thus follows that _the projective limit of a projective system $\cal{X}^{(\alpha)}$ of strict pro-objects always exists in $\Pro(\cal{C})$_, and that, with the above notation of $F$ and $\overline{F}$, we have that
$$
  \overline{F}\varprojlim_\alpha\cal{X}^{(\alpha)} = \varprojlim_\alpha{}_{\cal{C}'}F(X^{(\alpha)}).
$$
In particular, if every pro-object of $\cal{C}$ is strict (cf. the previous section), then the extended functor $\overline{F}$ commutes with projective limits.


## Characterisation of pro-representable functors {#fga-3-ii-section-A.3}

Let $\cal{C}$ and $\cal{C}'$ be categories in which all finite projective limits (i.e. limits over finite, not necessarily filtered, preordered sets) exist, or, equivalently, in which finite products and finite fibred products exist (which implies, in particular, the exists of a "right-unit object" $e$ such that $\Hom(X,e)$ consists of only on element for all $X$).
Let $F$ be a covariant functor from $\cal{C}$ to $\cal{C}'$.
Then the following conditions are equivalent:

i. $F$ commutes with finite projective limits;
ii. $F$ commutes with finite products and with finite fibred products;
iii. $F$ commutes with finite products, and, for every exact diagram
    $$
      X\to X'\rightrightarrows X''
    $$
    in $\cal{C}$ (cf. [@Gro1959, I, A, Definition 2.1]), the image of the diagram under $F$
    $$
      F(X)\to F(X')\rightrightarrows F(X'')
    $$
    is exact.

We then say that $F$ is _left exact_.

In what follows, we assume that finite projective limits always exist in $\cal{C}$.
It is then immediate from the definitions that a representable functor is left exact, and, by taking the limit, that _a pro-representable functor is left exact_.

To obtain a converse, let
$$
  F\colon \cal{C} \to \Set
$$
be a covariant functor, and let $X\in\cal{C}$ and $\xi\in F(X)$.
\oldpage{195-06}
We say that $\xi$ (or the pair $(X,\xi)$) is _minimal_ if, for all $X'\in\cal{C}$ and all $\xi'\in F(X')$, and for every strict monomorphism (cf. [@Gro1959, I, A, §2]) $u\colon X'\to X$ such that $\xi=F(u)(\xi')$, $u$ is an isomorphism.
We also say that a pair $(X,\xi)$ _dominates_ $(X'',\xi'')$ (where $xi\in F(X)$ and $\xi''\in F(X'')$) if there exists a morphism $v\colon X\to X''$ such that $\xi''=F(v)(\xi)$;
_if $\xi$ is minimal, and if $F$ is left exact, then this morphism $v$ is unique_;
_if $\xi''$ is minimal, then $v$ is surjective_.
From this we easily deduce the following proposition:

::: {.itenv #fga-3-ii-section-A.3-proposition-3.1 title="Proposition 3.1" latex="{Proposition 3.1}"}
For $F$ to be strictly pro-representable, it is necessary and sufficient for it to satisfy the following two conditions:

i. $F$ is left exact; and
ii. every pair $(X,\xi)$, with $\xi\in F(X)$, is dominated by some _minimal_ pair.
:::

This second condition is trivial if every object of $\cal{C}$ is Artinian (by taking a sub-object $X'$ of $X$ that is minimal amongst those for which there exists some $\xi'\in F(X')$ such that $\xi$ is the image of $\xi'$).
Whence:

::: {.itenv title="Corollary" latex="{Corollary}"}
Let $\cal{C}$ be a category whose objects are all Artinian and in which all finite projective limits exist.
Then the pro-representable functors from $\cal{C}$ to $\Set$ are exactly the left exact functors, and they are in fact strictly pro-representable.
:::

This last fact also implies that _every pro-object of $\cal{C}$ is then strict_.


## Example: groups of Galois type, pro-algebraic groups {#fga-3-ii-section-A.4}

If $\cal{C}$ is the category of ordinary finite groups, then $\Pro(\cal{C})$ is equivalent to the category of totally disconnected compact topological^[_[Trans.]_ Here the word "Hausdorff" is implicit.] groups.
It is groups of this type, and their generalisations, obtained by replacing ordinary finite groups with schemes of finite groups over a given base prescheme (for example, finite algebraic groups over a field $k$), that serve as fundamental groups, homotopy groups, and absolute and relative homology groups for preschemes.
In all these examples, the corollary to [Proposition 3.1](#fga-3-ii-section-A.3-proposition-3.1) applies, and it is indeed by the associated functor that the $\pi_1$ should be defined [@Gro1958a].
It is the same if we start with the category of algebraic or quasi-algebraic groups over a field (or, more generally, over a Noetherian prescheme): we recover the "_pro-algebraic groups_" of Serre [@Ser1958].


## Example: "formal varieties" {#fga-3-ii-section-A.5}

Let $\Lambda$ be a Noetherian ring, $\cal{C}$ the category of $\Lambda$-algebras that are Artinian modules of finite type over $\Lambda$ (or, more concisely, _Artinian $\Lambda$-algebras_).
\oldpage{195-07}
The conditions of the corollary to [Proposition 3.1](#fga-3-ii-section-A.3-proposition-3.1) are then satisfied.
Here, the category $\Pro(\cal{C})$ is equivalent to the category of _topological algebras_ $O$ over $\Lambda$ that are isomorphic to topological projective limits
$$
  O = \varprojlim O_i
$$
of algebras $O_i\in\cal{C}$, i.e. those whose topology is _linear_, _separated_, and _complete_, and such that, for every open ideal $\frak{J}_i$ of $O$, the algebra $O/\frak{J}_i$ is an _Artinian_ algebra over $\Lambda$.
The functor $\cal{C}\to\Set$ associated to such an algebra is exactly
$$
  \begin{aligned}
    F(A)
    &= h'_{O}(A)
  \\&= \{\text{continuous homomorphisms of topological }\Lambda\text{-algebras }O\to A\}
  \\&= \varinjlim_i \Hom_{\Lambda\text{-algebras}}(O_i,A).
  \end{aligned}
$$
Note also that the category $\cal{C}$ is essentially the product of analogous categories, corresponding to the local rings that are the completions of the $\Lambda_{\frak{m}}$ for the maximal ideals $\frak{m}$ of $\Lambda$;
we can thus, if so desired, restrict to the case where $A$ is such a complete local ring.
In any case, $O$ decomposes canonically as the topological product of its _local components_, which correspond to the "points" of the _formal scheme_ [@Gro1958a] defined by $O$.
Such a point is defined by an object $\xi$ of some $F(K)$, where $K\in\cal{C}$ is a _field_ (for example, the residue field of the local component in question), and where two pairs $(\xi,K)$ and $(\xi',K')$ define the same point if and only if they are both dominated by the same $(\xi'',K'')$, or if they both dominate the same $(\xi''',K''')$.
(If the $\Lambda/\frak{m}$ are algebraically closed, then it suffices to take the set given by the sum of the $F(\Lambda/\frak{m})$).

It is important to give conditions that ensure that the local component $O_\xi$ of $O$ corresponding to some $\xi\in F(K)$ be a _Noetherian_ ring.
If $\Lambda$ is a complete local ring (Noetherian, we recall), then it is equivalent to say that $O_\xi$ is isomorphic to a _quotient ring of a formal series ring $\Lambda[[t_1,\ldots,t_n]]$_.
To give such a criteria, we introduce (for every ring $A$) the $A$-algebra $I_A$ of "dual numbers" of $A$, defined by
$$
  I_A = A[t]/t^2A[t].
$$
Let $\varepsilon\colon I_A\to A$ be the augmentation homomorphism, which defines (if $A\in\cal{C}$) a map
$$
  F(\varepsilon)\colon F(I_A) \to F(A).
$$
\oldpage{195-08}
Using the fact that $F$ is left exact, we intrinsically define the structure of an $A$-module on the subset
$$
  F(I_A,\xi) = F(\xi)^{-1}(\xi) \subset F(I_A)
$$
consisting of the $\xi'\in F(I_A)$ that are "reducible along $\xi$";
using the explicit form of $F$ in terms of $O$, we find that this $K$-module can be identified with $\Hom_\Lambda(\frak{m}_\xi/\frak{m}_\xi^2,A$, where $m_\xi$ is the kernel of the homomorphism $\xi\colon O\to A$, i.e. if $A$ is a field, then the maximal ideal of the local component $O_\xi$ of $O$.
From this, we immediately deduce the following proposition:

::: {.itenv #fga-3-ii-section-A.5-proposition-5.1 title="Proposition 5.1" latex="{Proposition 5.1}"}
Let $\xi\in F(K)$, where $K\in\cal{C}$ is a field.
For the corresponding local component $O_\xi$ of $O$ to be a _Noetherian_ ring, it is necessary and sufficient for the set $F(I_K,\xi)$ of elements of $F(I_K)$ that are reducible along $\xi$ to be a vector space of _finite dimension_ over $K$.
Under these conditions, we have a canonical isomorphism
$$
  F(I_K,\xi) = \Hom(\frak{m}_\xi/\frak{m}_\xi^2+\frak{n}_\xi\scr{O}_\xi, K)
$$
(where $\frak{n}_\xi$ is the maximal ideal of $\Lambda$ given by the kernel of the homomorphism $\Lambda\to K$), and so, in particular, the dimension of the $K$-vector space $F(I_K,\xi)$ is equal to the dimension of the vector space $\frak{m}_\xi/\frak{m}_\xi^2$ over the field $O_\xi/\frak{m}_\xi=K(\xi)$.

_[Comp.]_ The formula given above is only correct when $\Lambda$ is a field; in the general case, we must replace $\frak{m}_\xi/\frak{m}_\xi^2$ with the quotient of this space by the image of $\frak{n}_\xi/\frak{n}_\xi^2$, where $\frak{n}$ is the maximal ideal of $\Lambda$.
:::

Suppose that $O_\xi$ is Noetherian, and suppose, for notational simplicity, that $\Lambda$ is complete and local, and that $O=O_\xi$.
(_[Comp.]_ The following definition is correct only when the residue extension $k'/k$ is _separable_; for the general case, see SGA III, 1.1.)
We say that _$O$ is simple over $\Lambda$_ if $O$ is a finite and étale algebra over the completion algebra of the localisation of $\Lambda[t_1,\ldots,t_n]$ at one of its maximal ideals that induces the maximal ideal of $\Lambda$;
if the residue extension of $O$ over $\Lambda$ is trivial (for example, if the residue field of $\Lambda$ is algebraically closed), then this is equivalent to saying that $O$ itself is isomorphic to such a formal series algebra.
Finally, if we no longer necessarily suppose that $O$ is Noetherian, then we again say that _$O$ is simple over $\Lambda$_ if $O$ is isomorphic to a topological projective limit of quotient $\Lambda$-algebras that are Noetherian and $\Lambda$-simple in the above sense.
We can immediately generalise to the case where $\Lambda$ and $O$ are no longer assumed to be local.
With this, we have the following proposition:

::: {.itenv #fga-3-ii-section-A.5-proposition-5.2 title="Proposition 5.2" latex="{Proposition 5.2}"}
For $O$ to be simple over $\Lambda$, it is necessary and sufficient for the associated functor $F$ to send epimorphisms to epimorphisms.
:::

If this is the case, then this implies that, for every _surjective_ homomorphism $A\to A'$ in $\cal{C}$, the morphism $F(A)\to F(A')$ is also _surjective_.
Of course, it suffices to verify this condition in the case where $A$ is _local_, and (proceeding step-by-step) where the ideal of $A$ given by the kernel of $A\to A'$ is annihilated by the maximal ideal of $A$.
This leads, in practice, to verifying that a certain obstruction, linked to _infinitesimal_ invariants of the situation that give us a functor $F$, is null;
this is a problem of a _cohomological_ nature.

\oldpage{195-09}

To finish, we say some words, in the above context, about _rings of definition_.
Let $F$ still be a functor from $\cal{C}$ to $\Set$, assumed to be pro-representable via a topological $\Lambda$-algebra $O$.
Then, for every $A\in\cal{C}$ and every $\xi\in F(A)$, there exists a _smallest_ subring $A'$ of $A$ such that $\xi$ is the image of an element $\xi'$ of $F(A')$ (which is then uniquely determined):
indeed, it suffices to think of $\xi$ as a homomorphism from $O$ to $A$, and to take $A'$ to be the image of $O$ under this $\xi$.
We then say that $A'$ is the _ring of definition of the object $\xi\in F(A)$_.
If $u\colon A\to B$ is an algebra homomorphism, and if $\eta=F(u)(\xi)$, then the ring of definition of $\eta$ is the image under $u$ of the ring of definition of $\xi$.
If we start with a functor $F$ from $\cal{C}$ to $\Set$, then the existence of rings of definition, along with their properties that we have just discussed, is more or less _equivalent_ to the condition that $F$ be pro-representable;
that is, they are usually far from being trivial.


## **B.** The two existence theorems {.unnumbered #fga-3-ii-section-B}

Keeping the notation of [§A.5](#fga-3-ii-section-A.5), and, given a covariant functor
$$
  F\colon \cal{C} \to \Set,
$$
we wish to find manageable criteria for $F$ to be pro-representable, i.e. expressible via a $\Lambda$-algebra $O$ as above.
By the corollary of [Proposition 3.1](#fga-3-ii-section-A.3-proposition-3.1), to ensure this, it is necessary and sufficient for $F$ to be _left exact_.
In the current state of the technique of descent (cf. the questions asked in [@Gro1959, I, p. 9]), this criterion is not directly verifiable, in this form, in the most important cases, and we need criteria that seem less demanding.

::: {.itenv #fga-3-ii-section-B-theorem-1 title="Theorem 1" latex="{Theorem 1}"}
For the functor $F$ to be pro-representable, it is necessary and sufficient for it to satisfy the two followings conditions:

i. $F$ commutes with finite products;
ii. for every algebra $A\in\cal{C}$ and every homomorphism $A\to A'$ in $\cal{C}$ such that the diagram
    $$
      A \to A' \rightrightarrows A'\otimes_A A'
    $$
    is exact (cf. [@Gro1959, I, A, Definition 1.2]), the diagram
    $$
      F(A) \to F(A') \rightrightarrows F(A'\otimes_A A')
    $$
    is also exact.

\oldpage{195-10}

Furthermore, it suffices to verify condition (ii) in the case where $A$ is local, and when, further, we are in one of the two following cases:

a. $A$ is a _free_ module over $A$;
b. the quotient module $A'/A$ is an $A$-module _of length $1$_.
:::

The proof of this theorem is rather delicate, and cannot be sketched here.
We content ourselves with pointing out that it relies essentially on a study of _equivalence relations_ (in the sense of categories) in _the spectrum of an Artinian algebra_ (the study of which poses even more problems, whose solutions seems essential for the further development of the theory).

In applications, the verification of condition (i) is always trivial.
The verification of condition (ii) splits into two cases: case (a), where $A'$ is a free $A$-module, can be dealt with using the _technique of descent by flat morphisms_ (cf. [@Gro1959, I, Theorems 1, 2, and 3]), which offers no difficulty;
to deal with case (b), we will use the following result:

::: {.itenv #fga-3-ii-section-B-theorem-2 title="Theorem 2" latex="{Theorem 2}"}
Let $A$ be a local Artinian ring with maximal ideal $\frak{m}$, and let $A'$ be an $A$-algebra containing $A$, and such that $\frak{m}A'\subset A$, and $A\to A'\rightrightarrows A'\otimes_A A'$ is _exact_ (which is the case, in particular, if $A'/A$ is an $A$-module of length $1$).
Let $\cal{F}$ be the fibred category (cf. [@Gro1959, I, A, Definition 1.1]) of quasi-coherent sheaves that are flat over varying preschemes.
Then the morphism $\Spec(A')\to\Spec(A)$ is a _strict $\cal{F}$-descent morphism_ (cf. [@Gro1959, I, A, Definition 1.7]).
:::

In other words, the data of a flat $A$-module $M$ is completely equivalent to the data of a flat $A'$-module $M'$ endowed with an $(A'\otimes_A A')$-isomorphism from $M'\otimes_A A'$ to $A'\otimes_A M'$ satisfying the usual transitivity condition for a descent data (loc. cit.).

We prove [Theorem 2](#fga-3-ii-section-B-theorem-2) by first proving that
$$
  \HH^i(A'/A,\Ga) = 0
  \qquad\text{(for }i\geq1\text{)}
$$
(cf. [@Gro1959, I, A.4.e]), with the hypothesis that $\frak{m}A'\subset A$ allowing us to easily reduce to the case where $A$ is a field (namely $A/\frak{m}$).
We can then apply the equivalences described in [@Gro1959, I, p. 16].


## **C.** Applications to some particular cases {-}


## General remarks on functors represented by preschemes {#fga-3-ii-section-C.1}

Let $S$ be a locally Noetherian prescheme.
\oldpage{195-11}
A prescheme $X$ over $S$ is said to be _locally of finite type_ over $S$ if, for all $x\in X$ that project to $y\in Y$, there exists an affine neighbourhood of $y$ of ring $A$, and an affine neighbourhood of $x$ (over the aforementioned affine neighbourhood of $y$) of ring $B$, such that $B$ is an $A$-algebra of finite type.
There are many important examples of preschemes locally of finite type over $S$, that are not of finite type over $S$, given by solutions of classical universal problems;
thus it is important to be able to consider the Picard scheme of a curve as a union of infinitely-many connected components (that we must avoid confusing with the connected component of the identity element, i.e. the "Picard variety").
It is thus sometimes useful to place ourselves in the category $\cal{C}$ of preschemes locally of finite type over $S$, in order to study the question of representability of a contravariant functor $F$.
_The main goal of these articles is to develop a general technique that allows us to recognise when such a functor $F$ is representable, and to study the properties of the corresponding $S$-prescheme $X$ by means of the properties of $F$._
We note in passing that, in this study, we find non-pathological examples of preschemes over $S$ that are not separated over $S$, notably as "Picard preschemes" of excellent $S$-schemes;
we must thus refrain from banishing preschemes that are not schemes from algebraic geometry.

Let $X$ be a prescheme locally of finite type over $S$, and let
$$
  F\colon Y \mapsto \Hom_S(Y,X)
$$
be the associated contravariant functor.
We can consider the restriction $F_0$ of $F$ to the subcategory $\cal{C}_0$ of $\cal{C}$ consisting of preschemes $Y$ over $S$ that are Artinian and finite over $S$:
if $S=\Spec(\Lambda)$, then $\cal{C}_0$ is the category dual to the category of Artinian $\Gamma$-algebras considered in [§B](#fga-3-ii-section-B).
If $Y=\Spec(A)$, where $A$ is a _local_ Artinian ring, then $Y$ consists of a single point $y$ living above a closed point $s$ of $S$, and an $S$-homomorphism from $Y$ to $X$ (i.e. an element of $F(Y)$) is defined by the data of a point $x\in X$ over $s$, along with an $\scr{O}_s$-homomorphism from $\scr{O}_x$ to $A$.
If there exists such a homomorphism, then $x$ is necessarily a closed point of $X$ (since its residue field is algebraic over the residue field of $s$).
This thus shows that _the restriction $F_0$ of $F$ to "Artinian $Y$-algebras" is pro-representable, and is represented by the topological $Y$-algebra whose local components are the completions $\widehat{\scr{O}_x}$ of the local rings of $X$ at the points $x$ of $X$ that are closed and live above closed points of $Y$_.
This shows that only knowing $F_0$ gives precise information about the structure of $X$ (that is, the structure of the completions of its local rings at the aforementioned points).
\oldpage{195-12}
We note that, even in the case where $S$ is the spectrum of an algebraically closed field, it is only thanks to the systematic consideration of "varieties" $Y$ such that $\scr{O}_Y$ may admit nilpotent elements (and, in particular, working with the spectra of local Artinian rings) that we can arrive at the "good formulation" of classical universal problems, and understand the "infinitesimal" aspect.

If we start with a given functor $F$, and we want to know whether or not it is representable, then studying the functor $F_0$ (using [Theorem 1](#fga-3-ii-section-B-theorem-1) and [Theorem 2](#fga-3-ii-section-B-theorem-2)) will give quasi-complete hints;
either, as is often the case (by simply testing, for example, the nature of the sets $F(I_K,\xi)$ and their functorial behaviour, cf. [§A](#fga-3-ii-section-A)), $F_0$ is already not pro-representable (which explains the failure of attempts made up until now to define varieties of modules in a reasonably natural way for the classification of vector bundles of rank $>1$);
or we might be able to show that $F_0$ is indeed representable, but that that vector spaces $F(I_K,\xi)$ are not of finite dimension, in which case we must be content with the "formal" solution;
or it could be the case that $F_0$ is indeed representable by a product of complete Noetherian local rings, which gives very strong assumptions for $F$ itself to be representable, and, combined with the analogous properties (but of a more global nature) that we will later develop, will in all likelihood suffice to imply that it is indeed so.
Finally, we come across interesting geometric problems (see sections [§C.4](#fga-3-ii-section-C.4) and [§C.5](#fga-3-ii-section-C.5) below) where we have only the functor $F_0$ (not coming from any "global" functor $F$), and where we will consider ourselves content if we can associate to it a "formal scheme of modules".

To finish these generalities, we note how the theory of schemes explains some apparent anomalies, such as the Igusa surface $V$ whose "Picard variety" $P$ consists of a single point, and for which, however, $\HH^1(V,\scr{O}_V)\neq0$;
in this case, $P$ is a non-trivial "purely infinitesimal" group, i.e. defined by a local algebra $\scr{O}$ of finite rank over the base field $k$ and endowed with a diagonal map corresponding to the multiplicative structure of $P$;
if $\frak{m}$ is the maximal ideal of $\scr{O}$, then the dual of $\frak{m}/\frak{m}^2$ is canonically isomorphic to $\HH^1(V,\scr{O}_V)$ (cf. section [§C.3](#fga-3-ii-section-C.3) below).
It is only when the Picard group is an algebraic group in the classical sense (i.e. simple over the base field $k$) that the dimension of $\HH^1(V,\scr{O}_V)$ (which is always equal to that of $\frak{m}/\frak{m}^2$) is equal to that of the Picard group.


## The schemes $\repHom_S(X,Y)$, $\prod_{X/S}Z$, $\repAut(X)$, etc. {#fga-3-ii-section-C.2}

Let $X$ and $Y$ be preschemes over $S$;
\oldpage{195-13}
for every prescheme $T$ over $S$, let $X_T=X\times_S T$ and $Y_T=Y\times_S T$, and consider the set
$$
  F(T)
  = \Hom_T(X_T,Y_T)
  = \Hom_S(X_T,Y)
  = \Hom_S(X\times_S T,Y)
$$
as a contravariant functor in $T$.
If it is representable, then we denote by $\repHom_S(X,Y)$ the prescheme over $S$ that represents it, and we then have a functorial isomorphism
$$
  \Hom_S(T,\repHom_S(X,Y)) \simto \Hom_S(T\times_S X,Y).
$$
There are variants of this universal problem, the solutions to which can be summarised as follows: a prescheme of _$S$-automorphisms of_ an $S$-prescheme $X$ (which will be a prescheme in _groups_), a prescheme of _$S$-homomorphisms_ from an $S$-prescheme in _groups_ to another (which will be a prescheme in commutative groups if the latter scheme in groups is commutative), etc.
We can also generalise the definition of $\repHom_S(X,Y)$ by considering a prescheme $Z$ over the prescheme $X$ over $S$, and the functor
$$
  F(T) = \Hom_{X_T}(X_T,Z_T)
$$
(the set of "sections" of $Z_T$ over $X_T$);
if this functor is representable, then the $S$-prescheme that represents it will be denoted by $\Pi_{X/S}Z$, and we will thus have, by definition, a functorial isomorphism
$$
  \Hom_S(T,\Pi_{X/S}Z) = \Hom_{X_T}(X_T,Z_T).
$$
Setting $Z=Y\times_S X$, we recover $\repHom_S(X,Y)$.
From these definitions follows a formula for the new preschemes thus introduced that is as trivial as it is useful, that we will not give here (given that it holds in every category where products and fibred products exist).
More serious is the question of _existence_ of schemes of the type $\repHom_S(X,Y)$.
We note first of all that, for fixed $X$, $\repHom_S(X,Y)$ (resp. $\Pi_{X/S}Z$) can only exist for all $Y$ over $S$ (resp. for all $Z$ over $X$) if $X$ is _flat_ over $S$.
Furthermore, we can convince ourselves that it is not reasonable to expect the existence of a solution, for general enough $Y$, except in the case where $X$ is further _proper_ over $S$.
It seems, however, that these conditions are sufficient for the existence of $\repHom_S(X,Y)$ and $\Pi_{X/S}Z$, with the condition that, if necessary, we make some sort of "quasi-projective" hypothesis on $Y/S$ (resp. $Z/X$);
this is what we can verify anyway in numerous cases (for example, when $Y$ is _affine_ over $S$, or, by direct elementary constructions, when $X$ is _finite_ over $S$).
Here is what [Theorem 1](#fga-3-ii-section-B-theorem-1) and [Theorem 2](#fga-3-ii-section-B-theorem-2) give:

\oldpage{195-14}

::: {.itenv #fga-3-ii-section-C.2-proposition-2.1 title="Proposition 2.1" latex="{Proposition 2.1}"}
Let $\Lambda$ be a Noetherian ring, and $X$ and $Y$ arbitrary preschemes over $\Lambda$.
Consider the functor
$$
  F(A) = \Hom_A(X_A,Y_A)
$$
on the category $\cal{C}_0$ of Artinian $\Lambda$-algebras.
If $X$ is flat over $\Lambda$, then this functor is pro-representable.
:::

Furthermore, we can show that, for all $A\in\cal{C}_0$ and all $\xi\in F(A)$, we have a canonical isomorphism
$$
  F(I_A,\xi) = \HH^1\Big(X_A,\repHom_{\scr{O}_{X_A}}\big(\xi^*(\Omega_{Y_A/A}^1),\scr{O}_{X_A}\big)\Big)
$$
where $\Omega_{Y_A/A}^1$ is the sheaf of Kähler $1$-differentials of $Y_A$ with respect to $A$.
Taking $A$ to be a field, we find, using [§A, Proposition 5.1](#fga-3-ii-section-A.5-proposition-5.1) and the finiteness theorem from [@Gro1958a], the following corollary:

::: {.itenv title="Corollary" latex="{Corollary}"}
Suppose that $X$ is flat and proper over $S$, and that $Y$ is of finite type over $S$.
Then $F$ is pro-representable, and the local components of the corresponding topological $\Lambda$-algebra are _Noetherian_ rings.
:::

::: {.rmenv title="Remarks" latex="{Remarks}"}
The problems considered in this section, and many others, having been generally studied, in the framework of classical algebraic geometry, via the "Chow coordinates" of cycles in projective space, allow us to consider these cycles as points of suitable projective varieties.
This procedure, and, more generally, the use of Chow coordinates, seems irredeemably insufficient from the point of view of schemes, since it destroys the nilpotent elements in the parameterised varieties, and, in particular, do not lend themselves to a satisfying study of infinitesimal variations of cycles (without taking its non-intrinsic nature, linked to the projective space, into account).
The language of Chow coordinates has sadly been the only one used by many algebraic geometers for the study of families of varieties or families of cycles, which seems to have been a serious obstacle to the understanding of these notions, despite its certain technical interest (probably temporary).
If we wish to obtain the analogue of Chow varieties in the theory of schemes, we are led to the following universal problem:
let $X$ be a prescheme over $S$, and, for every prescheme $T$ over $S$, consider the set $F(T)$ of closed sub-preschemes of $X_T=X\times_S T$ that are _flat_ over $T$; we want to represent this functor in $T$ via some prescheme over $S$.
\oldpage{195-15}
More generally, we can start with a quasi-coherent sheaf $\scr{G}$ on $X$, and take $F(T)$ to be the set of quotient sheaves of $\scr{G}_T$ that are flat over $T$.
It seems that there exists a solution to this problem, with a scheme $C$ that is locally of finite type over $S$, if $X$ is proper over $S$, if $S$ is locally Noetherian, and if $F$ is furthermore coherent.
In any case, supposing only that $S$ is locally Noetherian, the restriction of $F$ to "Artinian $S$-algebras" is pro-representable, and, if, furthermore, $X$ is proper over $S$, and $F$ is coherent, then the local components of the corresponding topological ring $\scr{O}$ are Noetherian.
Of course, even after having proven the existence of the "Chow scheme" of $X$ over $S$, it remains to find a decomposition of it into disjoint open subsets $C_i$ (corresponding to fixing continuous invariants, such as degree and dimension of the cycles that we vary) over $S$, as well as to make precise the relations between this scheme with the classical Chow varieties, and to make precise when a $C_i$ is _projective_ (or at least quasi-projective) over $S$.
:::

::: {.rmenv title="Remark" latex="{Remark}"}
_[Comp.]_
The problems described here are completely resolved in the projective case by "Hilbert schemes" (cf. [FGA 3.IV](FGA-3-IV.html)).
Examples by Nagata and Hironaka show, however, that the functors described are not necessarily representable if we do not make the projective hypothesis, even if we restrict to the classification of subvarieties of dimension $0$ of a complete non-singular variety of dimension $3$;
this is linked to the fact that the symmetric square of such a variety does not necessarily exist.
:::


## Picard schemes {#fga-3-ii-section-C.3}

_[Comp.]_ For a more complete study, see [FGA 3.V](FGA-3-V.html).

Let $f\colon X\to S$ be an $S$-prescheme, and consider the multiplicative sheaf $\scr{O}_X^\times$ of units of the structure sheaf of $X$, along with the group
$$
  P(X/S) = \HH^0(S,\RR^1f_*(\scr{O}_X^\times)),
$$
called the _relative Picard group_ of $X/S$.
An element of this group is thus defined by giving an open cover $(U_i)$ of $S$, along with an invertible sheaf $\scr{L}_i$ on each $f^{-1}(U_i)$, such that $\scr{L}_i|f^{-1}(U_i\cap U_j)$ is isomorphic to $\scr{L}_j|f^{-1}(U_i\cap U_j)$ for all $i,j$, or, at least locally over $U_i\cap U_j$ (i.e. these two sheaves are "equivalent" in the sense of [@Gro1959, I, B.4]).
If $X/S$ admits a section, then $P(X/S)$ is exactly the set of classes of invertible sheaves on $X/S$ up to "equivalence" (loc. cit.).
We now set, for all $T$ over $S$,
$$
  F(T) = P(X_T/T)
$$
which gives a covariant functor in $T$, that we call the _Picard functor_ of $X/S$;
if this functor is representable, then the prescheme over $S$ that represents it is called the _Picard prescheme_ of $X/S$, and denoted by $\scr{P}(X/S)$.
In this case, we then have an isomorphism of functors:
$$
  \Hom_S(T,\scr{P}(X/S)) \simto P(X_T/T).
$$
Taking the Picard prescheme is compatible with extension of the base, and, in particular, the Picard preschemes of the fibres of $X$ over $S$ (which are preschemes over the residue fields $K(s)$ of the $s\in S$) are the fibres of $\scr{P}(X/S)$.
\oldpage{195-16}
Of course, since $P(X_T/T)=F(T)$ is a commutative group, the Picard preschemes are preschemes in groups.
Note as well that the _generalised Jacobians_ of Rosenlicht are exactly the connected components of the identity in the Picard schemes of complete curves (possibly with singularities), which should make most of their properties clear (once their existence has been proven).

::: {.rmenv title="Remark" latex="{Remark}"}
The definition adopted here is only reasonable when every point of $Y$ admits an open neighbourhood $U$ over which $X$ admits a section.
In the general case, it is necessary to slightly modify the definition of the Picard functor in order to still obtain an existence theorem.

Here, the plausible existence conditions for a Picard prescheme are the following: $X$ is _proper_ and _flat_ over $S$; $f_*(\scr{O}_X)=\scr{O}_S$; and $X$ locally admits a section over $S$.
This condition naturally arises in the application of the technique of descent, _in eliminating the automorphisms of an invertible sheaf $\scr{L}$ on $X$ by endowing them with a marked section over the section $s$_ ([@Gro1959, I, B.4]).
Notably, we find the following:
:::

::: {.itenv #fga-3-ii-section-C.3-proposition-3.1 title="Proposition 3.1" latex="{Proposition 3.1}"}
Suppose that $X$ is flat over $S=\Spec(\Lambda)$, where $\Lambda$ is Noetherian, and suppose that, for all $T$ of finite type over $S$, we have ${f_T}_*(\scr{O}_{X_T})=\scr{O}_T$ (if $f$ is proper and separable and has separable fibres, or if $S$ is the spectrum of a field, then it follows from Künneth that the latter condition is equivalent to $f_*(\scr{O}_X)=\scr{O}_S$).
Then the Picard functor of $X/S$ on the category of Artinian $\Lambda$-algebras is pro-representable.

Furthermore, we then have
$$
  F(I_A,\xi) = \HH^1(X_A,\scr{O}_{X_A}),
$$
and, in particular:
:::

::: {.itenv title="Corollary" latex="{Corollary}"}
If $X$ is proper over $S$, then the local components of the topological $\Lambda$-algebra corresponding to the Picard functor are Noetherian.
:::

::: {.rmenv title="Remarks" latex="{Remarks}"}
We can generalise the definitions and results from this section to the classification of principal bundles on $X$, with structure group $G$ being a scheme in groups over $S$ that is _affine_ and _flat over $S$_, and also _commutative_.
In the case where $G$ would not be commutative, and thus where the adjoint bundle in groups of a principal bundle (whose sections of the automorphisms of the principal bundle) would no longer be trivial, [Proposition 3.1](#fga-3-ii-section-C.3-proposition-3.1) no longer holds true as it is stated.
We can, however, modify the universal problem in such a way that we again obtain a solution (at least, for now, in formal geometry).
\oldpage{195-17}
_The golden rule to remember, in the context of the current_
_section and in the following, and every time we are looking for "schemes of modules" for classes of objects that are only defined up to isomorphism, is always the following:_
_eliminate the possible automorphisms of the objects that we want to classify, by introducing, if necessary, auxiliary structures_ (points or elements of marked sections, fixing differential forms, etc.) that we take to be insignificant enough that we do not substantially modify the initial problem.
:::

::: {.rmenv title="Remarks" latex="{Remarks}"}
_[Comp.]_
I have recently shown that the formal scheme of modules for an abelian variety over a field is indeed simple over the Witt ring, or, in other words, that every abelian scheme $X$ over a local Artinian ring that is the quotient of another such scheme $Y$ comes, by reduction, from an abelian scheme over $Y$.
The proof simply uses the variance properties of the obstruction class of the covering, introduced in [FGA II, p. 12](FGA-2.html#fga-2-section-6).
Recall also that the schemes of modules for curves of genus $g$ or for polarised abelian schemes have been constructed by Mumford (cf. _Séminaire Mumford--Tate_, Harvard University (1961--62)).
:::


## Formal modules of a variety {#fga-3-ii-section-C.4}

Let $\Lambda$ be a _local_ Noetherian ring of residue field $k$ (more often than not, $\Lambda$ will be equal to $k$, or to a Cohen $p$-ring), and let $X_0$ be a prescheme over $k$.
For every local Artinian $\Lambda$-algebra $A$, consider the set $F(A)$ of isomorphism classes of $A$-preschemes $X$ that are _flat_ over $A$, endowed with an isomorphism

::: {.eqref #fga-3-ii-section-C.4-equation-asterisk}
$$
  X\otimes_A\kres(A) \simfrom X_0\otimes_k\kres(A)
\tag{$*$}
$$
:::

where $\kres(A)$ is the residue field of $A$;
of course, the isomorphisms between such flat $A$-preschemes should respect the above isomorphism given in the structure.
If $A$ is a (not necessary local) Artinian $\Lambda$-algebra, with local components $A_i$, then we take $F(A)$ to be the product of the $F(A_i)$.
Then $F$ becomes a multiplicative functor in $A$, and we call it the _functor of modules_ for $X_0$ (and $\Lambda$).
If this functor is representable, then it has a corresponding local topological $\Lambda$-algebra $O$, of residue field $k$, and the formal spectrum of $O$ is called the _formal scheme of modules_ for $X_0$ (and $\Lambda$) (cf. [@Gro1958a] for some details on this).

Here, if we wish to apply the technique of descent, the "finite" automorphisms of $X_0$ are inoffensive, since they have no influence on the existence of automorphisms (in the precise sense above) of $A$-preschemes $X$;
the necessary and sufficient condition, if $A$ is not simply a field, for $X$ to not have any non-trivial $A$-automorphisms is that
$$
  \HH^0(X_0,\frak{G}_{X_0/k}) = 0
$$
where $\frak{G}_{X_0/k}$ denotes the sheaf of $k$-derivations (i.e. the tangent sheaf) of $X_0$.
We can easily show (at least, if $X_0$ is simple over $k$) that
$$
  F(I_A,\xi) = \HH^1(X_A,\frak{G}_{X_A/A}).
$$
We thus conclude, as per usual:

::: {.itenv #fga-3-ii-section-C.4-proposition-4.1 title="Proposition 4.1" latex="{Proposition 4.1}"}
Suppose that $\HH^0(X_0,\frak{G}_{X_0/k})=0$.
\oldpage{195-18}
Then the formal scheme of modules for $X_0$ exists.
If, furthermore, $X_0$ is proper over $k$, then the formal scheme of modules is Noetherian.
:::

::: {.rmenv title="Remarks" latex="{Remarks}"}
—

1. If $X_0$ is not assumed to be simple over $k$, then $F(I_A,\xi)$ can be identified with a sub-$A$-module of
    $$
      \Ext_{\scr{O}_{P_A}}^1(P_A;\scr{I}_{X_A},\scr{O}_{X_A})
    $$
    where we set $P_A=X_A\times_A X_A$, where $\scr{O}_{X_A}$ is considered as a coherent sheaf on $P_A$ via the diagonal morphism $X_A\to P_A$, and where $\scr{I}_{X_A}$ denotes the coherent sheaf of ideals on $P_A$ defined by the diagonal morphism.
    More precisely, an easy globalisation of Hochschild theory shows that the $\Ext^1$ above can be identified with the set of classes, up to isomorphism, of sheaves of $I_A$-algebras $\scr{O}$ that are flat over $X_A$, and endowed with an augmentation isomorphism $\scr{O}\otimes_{I_A}A\to\scr{O}_{X_A}$ (recall that we set $I_A=At/(t^2)$).
    The submodule $F(I_A,\xi)$ is that which corresponds to the sheaves of _commutative_ algebras.
    The simplicity hypotheses are thus not essential in the theory of modules, as [@Gro1958a] implies.

2. Recall (loc. cit.) that, in particular, every _simple_ and _proper algebraic curve_ $X_0$ over $k$ admits a formal scheme of modules that is simple over $\Lambda$, and of relative dimension equal to $3g-3$ if the genus $g$ is $\geq2$, and to $g$ if $g=0,1$.
    These two latter cases no longer figure directly in [Proposition 4.1](#fga-3-ii-section-C.4-proposition-4).
    We can, however, recover them in the case of elliptic curves ($g=1$) thanks to the remarks that will follow.
:::

We can, of course, vary [Proposition 4.1](#fga-3-ii-section-C.4-proposition-4) _ad libitum_ by considering systems of schemes over $k$ endowed with various structures.
Suppose, for example, that $X_0$ is an _abelian scheme_ over $k$, with a marked origin (i.e. $X_0$ is considered as a scheme in _groups_ over $k$), and let $F(A)$ be the set of isomorphism classes of _abelian_ schemes over $A$ (i.e. of schemes in groups that are proper and simple over $A$) endowed with an isomorphism [($*$)](#fga-3-ii-section-C.4-equation-asterisk) of abelian schemes.
We can show that imposing a multiplicative structure (or even only a "unit section") eliminates the infinitesimal automorphisms, and that there thus exists a formal scheme of modules that corresponds to a complete local Noetherian ring $O$.
We can also show that, if $X$ is a proper and simple scheme with "absolutely connected" fibres over a locally Noetherian prescheme $S$, then every multiplicative structure on $X$ that admits a unit section is necessarily associative and commutative (provided that it is associative and commutative on _one_ fibre, and provided that $S$ is connected), and is furthermore uniquely determined by the knowledge of the unit section.
\oldpage{195-19}
Further, supposing that $S$ is the spectrum of a local Artinian ring $A$ of residue field $k$, that $X$ is proper over $A$ and endowed with a section $s$, and finally that $X\otimes_A k$ is endowed with the structure of an abelian scheme over $k$, admitting the point of $X\otimes_A k$ corresponding to $s$ as the zero element, an easy calculation of obstructions, combined with an argument due to Serre, allows us to prove that there exists on $X$ a multiplicative structure admitting the section $s$ as the unit section.
(From here, using the "existence theorem" of [@Gro1958a] to pass to the case where $A$ is complete local Noetherian, and then the technique of descent from [@Gro1959, I] for the general case, we can prove the analogous claim for all locally Noetherian connected $S$).
This proves that the functor $F(A)$ considered here is isomorphic to the analogous functor defined at the start of this section by abstracting the multiplicative structure on $X_0$.
It then follows that, in particular, if $\frak{m}$ is the maximal ideal of $O$, then $\frak{m}/\frak{m}^2$ is canonically isomorphic to the dual of $\HH^1(X_0,\frak{G}_{X_0/k})$, and is thus of dimension $n^2$, where $n=\dim X_0$.
It would be very interesting to determine if $O$ is indeed _simple_ over $\Lambda$, i.e. isomorphic to an algebra of formal series in $n^2$ variables over $\Lambda$.
Now [§A, Proposition 5.2](#fga-3-ii-section-A.5-proposition-5.2) allows us to give an equivalent formulation of this problem as an _existence problem of abelian schemes that are reducible along a given abelian scheme_.
In any case, we see, by a transcendental way, that the answer is affirmative if $k$ is of characteristic $0$.
In characteristic $p\neq0$, it evidently suffices to restrict to the case where $\Lambda$ is the ring of Witt vectors constructed over an algebraically closed field $k$.
This could be the moment for the "_Greenberg functor_" to prove its worth...


## Extension of coverings {#fga-3-ii-section-C.5}

Let $\frak{X}$ be a _formal_ Noetherian prescheme [@Gro1958a], $U$ an open subset of $\frak{X}$ defined locally by the "non-vanishing" of a section of $\scr{O}_\frak{X}$ that is not a zero divisor (and thus large enough that every section of $\scr{O}_\frak{X}$ over an open subset $V$ that is zero on $U\cap V$ is zero).
(_[Comp.]_ It is also necessary to assume that the section defining $U$ is not a zero divisor not only on $\frak{X}$, but also on every $X_n$.)
Let $\frak{J}$ be an "ideal of definition" for $\frak{X}$, and let $X_n=(\frak{X},\scr{O}_\frak{X}/\frak{J}^{n+1})$, which is thus a ordinary Noetherian prescheme.
Then, if $\frak{X}'$ and $\frak{X}''$ are _flat coverings_ of $\frak{X}$ (i.e. preschemes over $\frak{X}$ defined by sheaves of algebras that are coherent and locally free as sheaves of modules) that are _unramified over $U$_, the evident map
$$
  \Hom_\frak{X}(\frak{X}',\frak{X}'') \to \Hom_{X_0}(X'_0,X''_0)
$$
is _injective_;
in particular, _an automorphism of $\frak{X}'$ that induces the identity on $X'_0$ is the identity_.
This allows us to apply the technique of descent to the situation.
\oldpage{195-20}
We start, in particular, with a flat covering $X'_0$ of $X_0$, unramified over $U_0$, and let $G(\frak{X})$ be the set of classes, up to isomorphism (inducing the identity on $X'_0$), of flat coverings $\frak{X}'$ of $\frak{X}$ that induce $X'_0$ on $X_0$ (and that are thus necessarily unramified over $U$).
We similarly define $G(V)$ for every open subset $V$ of $\frak{X}$, and, more generally, $G(\frak{Y})$ for every formal prescheme $\frak{Y}$ over $\frak{X}$.
With this, the results of [@Gro1958a] and [@Gro1959, I] imply, first of all, the following results:

a. If $V$ varies amongst open subset of $\frak{X}$, then the $G(V)$ form a _sheaf_ on $\frak{X}$, say $\scr{G}_\frak{X}=\scr{G}$.
    The restriction of this sheaf to $U$ is the _constant_ sheaf whose fibres consist of a single element.

    More generally, describing the fibres of $\scr{G}_\frak{X}$ is a question of complete local rings, in a precise way:

b. For all $x\in\frak{X}$, we have
    $$
      \scr{G}_x = G(\Spec(\scr{O}_{\frak{X},x})) \subset G(\Spec(\widehat{\scr{O}}_{\frak{X},x}))
    $$
    (i.e. isomorphism classes of finite free algebras $B$ over $\widehat{\scr{O}}_{\frak{X},x}$ endowed with an isomorphism from $B\otimes_{\widehat{\scr{O}}_{\frak{X},x}}\scr{O}_{X_0,x}$ to $(\widehat{\scr{O}}'_0)_x$, where $\scr{O}'_0$ is the sheaf of algebras on $X_0$ that defines $X'_0$).

c. We have a canonical isomorphism $\scr{G}_\frak{X}=\varprojlim\scr{G}_{\frak{X}_n}$; in other words, for every open subset $V$ of $\frak{X}$, we have $G(V)=\varprojlim G(V_n)$.

d. Suppose that $\frak{X}$ comes from an ordinary _proper_ scheme $X$ over a complete local Noetherian ring $\Lambda$ that has ideal of definition $\frak{m}$ by taking the $\scr{J}$-adic completion of $\scr{O}_X$, where $\scr{J}=\frak{m}\cdot\scr{O}_X$.
    Then $G(\frak{X})$ is canonically isomorphic to the set of classes of flat coverings of the _ordinary_ scheme $X$ that are "reducible along $X'_0$".

Figuratively speaking, we can say that (a) and (b) establish the fundamental relations between the local and global aspects of the problem; (c) gives the relations between the "finite" and "infinitesimal" aspects; and finally (d) remembers (under precise conditions) the identity between the "formal" and "algebraic" aspects.

Now suppose that $\frak{X}$ is defined by a local complete Noetherian ring $\Lambda$, with $\scr{J}=\frak{m}\cdot\scr{O}_X$ (and so $X_0$ is a prescheme over $\Lambda/\frak{m}$).
For every algebra $A$ that is finite over $\Lambda$, we set
$$
  F(A) = G(\frak{X}\times_\Lambda A).
$$
This is a covariant functor in $A$, with values in the category of sets, and, by (c), this functor is completely determined by how it acts on Artinian algebras $A$;
it is equivalent to say either that this functor is pro-representable, i.e. of the form
$$
  F(A) = \Hom_{\text{top. }\Lambda\text{-algebras}}(\scr{O},A)
$$
\oldpage{195-21}
where $\scr{O}$ is a topological $\Lambda$ algebra of the type described in [§A.5](#fga-3-ii-section-A.5), or that this is true when we restrict to only Artinian algebras $A$.
The combination of [Theorem 1](#fga-3-ii-section-B-theorem-1) and [Theorem 2](#fga-3-ii-section-B-theorem-2) then effectively implies:

::: {.itenv #fga-3-ii-section-C.5-proposition-5.1 title="Proposition 5.1" latex="{Proposition 5.1}"}
The above functor is pro-representable.
:::

Of course, by (a), if $U=\frak{X}$, then $G(\frak{Y})$ consists of a single element for all $\frak{Y}$ over $\frak{X}$, and the functor $F$ is then not very interesting (we will have $\scr{O}=\Lambda$).
It seems that, in practically every other case, the topological local ring $\scr{O}$ _is not Noetherian_.
Its existence, however, shows, in a striking manner, the _"continuous" nature_ of the set $G(\frak{X})$ of solutions (corresponding intuitively to the fact that there is a "continuous" choice in the way in which the ramification spreads when we take an extension of $X'_0$).
We will compare this result with the point of view of J.-P. Serre [@Ser1958] via local class field theory, drawing attention as well to the _continuous_ character of the topological Galois group of the maximal abelian extension of a "geometric" local field, with the dual group (in the sense of Pontrjagin) appearing as an inductive limit of algebraic (or at least quasi-algebraic) groups;
here as well, the classification of extensions is given by infinite-dimensional "varieties".
We can also take, in the above, $\frak{X}$ to be the formal spectrum of a complete local ring (of which $\Lambda$ will be, for example, a Cohen subring), and we might hope that the results of this section can be used in the study of extensions of a local complete ring of dimension $>1$.
Just as much in the local case as in the global case, they might allow us to formulate precise relations between the phenomena of higher ramification and phenomena in characteristic $0$ (approachable via a transcendental way).
In any case, it is the preliminary analysis of [Proposition 5.1](#fga-3-ii-section-C.5-proposition-5.1) that allows us to extend the methods described in [@Gro1958a] for the study of the fundamental group to the "tamely ramified" case, and to resolve, by a transcendental way, the "problem of three points".

To finish, we note that the situation simplifies if $X_0$ is of dimension $1$;
then, by (a) and (b), $G(\frak{X})$ can be identified with $\prod_i G(\Spec(\scr{O}_{\frak{X},x_i}))$, where the $x_i$ are the points of $X_0\setminus U$:
_we can take arbitrary "local" extensions at the ramification points_.
Further, if $X_0$ is normal, then we note that the formal scheme of modules guaranteed by [Proposition 5.1](#fga-3-ii-section-C.5-proposition-5.1) is _simple_ over $\Spec(\Lambda)$.
