# Formal geometry and algebraic geometry {#fga-2}

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\PP}{\mathbb{P}}
\providecommand{\ZZ}{\mathbb{Z}}
\providecommand{\kres}{\mathfrak{K}}
\providecommand{\red}{\mathrm{red}}

\providecommand{\Spec}{\operatorname{Spec}}
\providecommand{\supp}{\operatorname{supp}}
\providecommand{\RR}{\operatorname{R}}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\shHom}{\mathscr{H}\kern -.5pt om}
\providecommand{\Aut}{\operatorname{Aut}}
\providecommand{\shAut}{\mathscr{A}\kern -.5pt ut}
\providecommand{\gr}{\operatorname{gr}}

<!-- Content -->

::: {.original-citation}
Grothendieck, A.
"Géométrie formelle et géométrie algébrique".
_Séminaire Bourbaki_ **11** (1958--59), Talk no. 182.
:::

\oldpage{C-03}

The substance of [§1](#fga-2-section-1) to [§5](#fga-2-section-5) is contained in the published part of EGA III; that of [§6](#fga-2-section-6) and [§7](#fga-2-section-7) is contained in SGA III.
For the study of the fundamental group, see SGA V, IX, X, and XI, as well as SGA 1962 (talks X, XII, and XIII) for the Lefschetz-type theorems and numerous open questions.
Only the theory of moderately ramified coverings (cf. [Theorem 14](#fga-2-theorem-14)) has not yet been the subject of a dedicated talk.
The [corollary to Theorem 14](#fga-2-theorem-14-corollary-1), which completely determines Galois coverings of order coprime to the characteristic of an algebraic curve over an algebraically closed field, has been used in an essential manner on three separate occasions:

1. in the proof by Igusa of the Picard inequality for non-singular projective surfaces in arbitrary characteristic;

2. in the study (developed independently by Ogg and Šafarevič) of the group of homogeneous principal bundles over an abelian variety defined over a function field in one variable, in arbitrary characteristic; and

3. in the recent proof, by Artin, of certain key theorems concerning the "Weil cohomology" of algebraic varieties.


## Schemes {#fga-2-section-1}

\oldpage{182-01}

We know that an affine algebraic space defined over a field $k$ is essentially determined by its affine algebra $A$ (the ring of regular functions defined over $k$), and the morphisms $X\to Y$ of algebraic spaces correspond bijectively to homomorphisms $A(Y)\to A(X)$ of $k$-algebras.
The affine algebra corresponding to an algebraic space is a $k$-algebra of finite type, and, from the "classical" point of view, it has no nilpotent elements;
conversely, every such algebra is obtained as the affine algebra of an algebraic space defined over $k$.
There is thus a known dictionary that allows us to interpret situations concerning affine algebraic spaces in terms of commutative algebra.
We have long since noted that we thus obtain more general statements, since it was not generally necessary to suppose that the rings in play were of the form just described, with the Noetherian hypothesis being sufficient the most of the time.
In particular, whether or not a base field were given, it was not necessary to exclude the case where these rings contained nilpotent elements.
Up until now, geometers had refused to take into account this information, and were obstinate in restricting to the consideration of affine algebra without nilpotent elements, i.e. algebraic spaces in whose structure sheaves there are no nilpotent elements (and even, most of the time, "absolutely irreducible" algebraic spaces).
The speaker thinks that this state of mind has been a serious obstacle to the development of truly natural methods in algebraic geometry.

Let $A$ be a commutative ring.
It is well known that the set $X=\Spec(A)$ of prime ideals of $A$ is endowed with a natural topology: the "_Zariski topology_", or the spectral topology.
Also, there is a sheaf of commutative rings $\scr{O}_X$ on $X$, whose fibre at $\frak{p}\in X$ is the localised ring $A_\frak{p}$, and whose ring of sections can be identified with $A$.
Thus $X$ becomes a _ringed space_, and is called the _prime spectrum_ of $A$.
A ring homomorphism $f\colon A\to B$ defines a morphism $f'\colon\Spec(B)\to\Spec(A)$ of ringed spaces, with the underlying map of sets being exactly $\frak{p}\mapsto f^{-1}(\frak{p})$.
The homomorphisms $\Spec(B)\to\Spec(A)$ of ringed spaces obtained in this manner are exactly those for which the homomorphisms $\scr{O}_x\to\scr{O}_y$ (where $x=f'(y)$) are local (i.e. the inverse image of a maximal ideal is a maximal ideal).

\oldpage{182-02}

We define an _affine scheme_ to be a ringed space that is isomorphic to some $\Spec(A)$, and a _prescheme_ to be a locally-affine ringed space, i.e. such that every point has an open neighbourhood that is an affine scheme for the induced structure.
We define, in an evident way, _morphisms_ of preschemes;
locally, they correspond to ring homomorphisms.

When we fix a prescheme $S$, and we look at morphisms $X\to S$ of preschemes, then $S$ plays the role of a base field or base ring (or, even better, of a base space in a fibration).
We then say that $X$ is an _$S$-prescheme_;
if $S=\Spec(A)$, then this also implies that $\scr{O}_X$ is a sheaf of _$A$-algebras_.
So every prescheme can be regarded in a unique way as a $\mathbb{Z}$-prescheme.
Of course, $S$-preschemes form a category, and we can further show that, in this category, the product of two objects $X$ and $Y$ always exists;
it is denoted by $X\times_S Y$.
This notion of product allows us to define the _change of base_ of an $S$-prescheme, corresponding to a morphism $S'\to S$, since $X\times_S S'$ can be considered as an $S'$-prescheme.

We say that $X$ is _separated_ over $S$ if the diagonal of $X\times_S X$ is closed.
We define a _scheme_ to be a prescheme that is separated over $\mathbb{Z}$;
it is then separated over anything.
For simplicity, we will now only speak of schemes, which we will further suppose to be _Noetherian_, i.e. finite unions of affine opens that are spectra of Noetherian rings.
We say that $X$ is _of finite type_ over $S$ if, for every affine open subset $U$ of $S$, its inverse image in $X$ is a finite union of affine opens whose rings are algebras of finite type over the ring of $U$.
It is such $S$-schemes that lend themselves to a properly geometry study.
In particular, for every $s\in S$, the fibre $f^{-1}(s)$ of $X$ over $s$ is an algebraic scheme over the residue field $k(s)$ of the local ring $\scr{O}_s$ of $s$ in $S$.
Thus $X$ can be, to a certain extent, considered as a family of "algebraic spaces" $f^{-1}(s)$, with the parameter $s$ running over $S$ (i.e., from the local point of view, the set of prime ideals of a given ring).
Of course, the $k(s)$ can have different characteristics.
If $S=\Spec(k)$, where $k$ is a field, then we essentially recover the usual notion of "algebraic space", with the only difference being that now the structure sheaf can have nilpotent elements.

\oldpage{182-03}

Inspired by well-known ideas, we can define the notion of a _projective morphism_, and, more generally, of a _proper morphism_.
Such a morphism is of finite type, and further sends closed subsets to closed subsets, and retains this property under an arbitrary change of base.

With $X$ being a (Noetherian, as always) scheme, the sheaf $\scr{O}_X$ is a _coherent sheaf of rings_ in the sense of [@2-2].
The coherent sheaves of modules on $X$ are thus also the sheaves which are locally isomorphic to a cokernel of some morphism $\scr{O}_X^m\to\scr{O}_X^n$.


## Formal schemes {#fga-2-section-2}

Let $X$ be a scheme, and $X'$ a closed subset of $X$.
Then there exists a coherent subsheaf $\scr{J}$ of $\scr{O}_X$ such that $X'=\supp\scr{O}_X/\scr{J}$ (and there even exists a largest such one).
Endowing $X'$ with the sheaf $\scr{O}_X/\scr{J}$ makes $X'$ a scheme, denoted $X_0$;
such a scheme is called a _closed subscheme of $X$_.
We can also, for any $n$, consider $X'$ endowed with $\scr{O}_X/\scr{J}^{n+1}$, denoted $X_n$, which is a closed subprescheme of $X$ whose underlying set is again $X'$, but with a different structure sheaf, namely $\scr{O}_{X_n}=\scr{O}_X/\scr{J}^{n+1}$.
Clearly the $\scr{O}_{X_n}$ form a projective system of sheaves of rings on $X$, whose projective limit $\overline{\scr{O}_X}$ is called the _formal completion of $\scr{O}_X$ along $X'$_.
Endowed with this sheaf of rings, $X'$ is called the _formal completion of $X$ along $X'$_, and is thus a ringed space, but not a scheme in general.
For every coherent sheaf $\scr{F}$ on $X$, we can similarly consider the formal completion $\overline{\scr{F}}=\varprojlim_n\scr{F}_n$ of $\scr{F}$ along $X'$ (where $\scr{F}_n=\scr{F}\otimes_{\scr{O}_X}\scr{O}_X/\scr{J}^{n+1}$), which is a sheaf of modules on $\overline{X}$.
Its sections are called _formal sections of $\scr{F}$ along $X$_, and can be identified with elements of $\varprojlim_n\Gamma(X',\scr{F}_n)$.
For $\scr{F}=\scr{O}_X$, we recover the "holomorphic functions" of $X$ along $X'$, in the sense of Zariski (whose terminology we will not follow, due to its interferences with classical terminology).

We define a _formal scheme_ (implicitly assumed to be Noetherian) to be a topological space $\frak{X}$ endowed with a sheaf of topological rings $\scr{O}_{\frak{X}}$ satisfying the following condition:
there is an isomorphism of sheaves of topological rings $\scr{O}_{\frak{X}}=\varprojlim_n\scr{O}_n$, where the $\scr{O}_n$ form a projective system of sheaves of rings on $\frak{X}$, with each one making $\frak{X}$ into a scheme $\frak{X}_n$, and such that, for $m\geq n$, the homomorphism $\scr{O}_m\to\scr{O}_n$ is surjective and has $\scr{J}_m^{n+1}$ as its kernel, where $\scr{J}_m$ is the kernel of $\scr{O}_m\to\scr{O}_0$.
We will show that $\scr{O}_{\frak{X}}$ is a _coherent_ sheaf of _local Noetherian_ rings.

\oldpage{182-04}

By the definitions, a formal completion $\overline{X}$ as above is a formal scheme, and, conversely, every formal scheme is _locally_ of this type.
In fact, the data of a formal _affine_ scheme (i.e. such that $\frak{X}_0$ is affine, which implies that all the $\frak{X}_n$ are affine) is equivalent to the data of a separated complete $\scr{J}$-adic Noetherian topological ring.

The usual definitions (morphism, morphism of finite type, proper morphism, etc.) for ordinary schemes generalise without problem to formal schemes.


## The three fundamental theorems {#fga-2-section-3}

Let $f\colon X\to Y$ be a proper morphism of schemes (Noetherian, as always), and let $Y'$ be a closed subset of $Y'$, with $X'$ its inverse image in $X$, and consider the corresponding formal completions $\overline{Y}$ and $\overline{X}$.
Then $f$ induces a morphism $\overline{f}\colon\overline{X}\to\overline{Y}$ of formal schemes, which is also proper.
Let $\scr{F}$ be a coherent sheaf on $X$, then $\overline{\scr{F}}$ is a coherent sheaf on $\overline{X}$.
In [Theorem 1](#fga-2-theorem-1), we forget $X$, $Y$, and $\scr{F}$, and consider only the proper morphism $\overline{f}$ of formal schemes, along with the coherent sheaf $\overline{\scr{F}}$ on $\overline{X}$.
(However, the speaker has only written the complete proof in the case where we start with some $X$, $Y$, $f$, and $F$).

::: {.itenv #fga-2-theorem-1 title="Theorem 1" latex="{Theorem 1}"}
_Finiteness theorem._ ---

i. The $\RR^q\overline{f}_*(\overline{\scr{F}})$ are coherent sheaves on $\overline{Y}$.

ii. The natural homomorphisms
    $$
        \RR^q\overline{f}_*(\overline{\scr{F}}) \to \varprojlim_n\RR^q (f_n)_*(\scr{F}_n)
    $$
    are isomorphisms.
:::

In this statement, we suppose that we already have some coherent subsheaf $\scr{J}$ of $\scr{O}_Y$ that defines $Y'$, whence, by taking the inverse image, a coherent subsheaf of $\scr{O}_X$ that defines $X'$, whence, by definition, $\scr{F}_n$, $X_n$, $Y_n$, and $f_n\colon X_n\to Y_n$ as in [§2](#fga-2-section-2).
The minor changes that need to be made to the notation in the explanation if we started with an arbitrary proper morphism between two formal schemes are evident.

[Theorem 1](#fga-2-theorem-1) deals only with "formal cohomology";
the following theorem relates it with "algebraic cohomology", and resembles a well-known theorem of Serre [@2-4] on the comparison between algebraic cohomology and analytic cohomology.

\oldpage{182-05}

::: {.itenv #fga-2-theorem-2 title="Theorem 2" latex="{Theorem 2}"}
_First comparison theorem._ ---
The $\RR^q f_*(\scr{F})$ are coherent sheaves on $Y$ (which is a particular case of [Theorem 1](#fga-2-theorem-1)), and the natural homomorphisms
$$
  \overline{\RR^q f_*(\scr{F})} \to \varprojlim_n \RR^q (f_n)_*(\scr{F}_n)
$$
are isomorphisms.
:::

::: {.itenv #fga-2-theorem-2-corollary-1 title="Corollary 1" latex="{Corollary 1}"}
There are canonical isomorphisms $\overline{\RR^q f_*(\scr{F})} = \RR^q\overline{f}_*(\overline{\scr{F}})$.
:::

This corollary is, for $q=0$, a generalisation of Zariski's "fundamental theorem of holomorphic functions", from which we will deduce a generalisation of Zariski's "connection theorem".
We also note that, while [Theorem 1](#fga-2-theorem-1) (ii) is trivial for $q=0$, this is not at all the case for [Theorem 2](#fga-2-theorem-2) nor for its equivalent formulation ([Corollary 1](#fga-2-theorem-2-corollary-1)).
In fact, the proof proceeds by decreasing induction on $q$ (being trivial for large $q$, since then both sides of the equation are zero), and the case $q=0$ thus appears as the last induction step, and so could be called the "most difficult" case.

::: {.itenv #fga-2-theorem-2-corollary-2 title="Corollary 2" latex="{Corollary 2}"}
Let $Y=\Spec(A)$, and let $Y'$ be defined by an ideal $\scr{J}$ of $A$.
Then, for every coherent sheaf $\scr{F}$ on $X$, the $H^q(X,\scr{F})$ are $A$-modules of finite type, whose $\scr{J}$-adic completions are the $H^q(\overline{X},\overline{\scr{F}})$.
:::

Finally, applying this corollary to $H=\shHom_{\scr{O}_X}(\scr{F},\scr{G})$, we obtain:

::: {.itenv #fga-2-theorem-2-corollary-3 title="Corollary 3" latex="{Corollary 3}"}
Let $Y=\Spec(A)$, and let $Y'$ be defined by an ideal $\scr{J}$ of $A$.
Let $\scr{F}$ and $\scr{G}$ be coherent sheaves on $X$.
Then $\Hom(\scr{F},\scr{G})$ is an $A$-module of finite type, whose $\scr{J}$-adic completion can be identified with $\Hom(\overline{\scr{F}},\overline{\scr{G}})$.
:::

Of course, the natural map $\Hom(\scr{F},\scr{G})\to\Hom(\overline{\scr{F}},\overline{\scr{G}})$ is that which sends a homomorphism $u\colon\scr{F}\to\scr{G}$ to its extension "by continuity" $\overline{u}\colon\overline{\scr{F}}\to\overline{\scr{G}}$ (so that $\overline{\scr{F}}$ becomes a functor in $\scr{F}$).

Now suppose that $A$ is separated and complete for its $\scr{J}$-adic topology.
Then [Corollary 2](#fga-2-theorem-2-corollary-2) and [Corollary 3](#fga-2-theorem-2-corollary-3) above give:
$$
  \begin{aligned}
    H^q(X,\scr{F}) &= H^q(\overline{X},\overline{\scr{F}}),
  \\\Hom(\scr{F},\scr{G}) &= \Hom(\overline{\scr{F}},\overline{\scr{G}}).
  \end{aligned}
$$

\oldpage{182-06}

The latter identity shows that the category of coherent sheaves on $X$ can be identified with a _subcategory_ (with morphisms being the induced morphisms) of the category of coherent sheaves on $\overline{X}$.
In fact, we even have:

::: {.itenv #fga-2-theorem-3 title="Theorem 3" latex="{Theorem 3}"}
For a sheaf of modules on $\overline{X}$ to be coherent, it is necessary and sufficient for it to be isomorphic to a sheaf of the form $\overline{\scr{F}}$, where $\scr{F}$ is a coherent sheaf on $X$ (determined up to canonical isomorphism, by [Corollary 3 of Theorem 2](#fga-2-theorem-2-corollary-3)).
[We recall that now $Y=\Spec(A)$, with $A$ being a complete and separated $\scr{J}$-adic Noetherian topological ring].
:::

::: {.itenv #fga-2-theorem-3-corollary-1 title="Corollary 1" latex="{Corollary 1}"}
The closed subschemes of $X$ are in bijective correspondence with the closed formal subschemes of $\overline{X}$.
:::

Indeed, they correspond to coherent subsheaves of $\scr{O}_X$ (resp. of $\scr{O}_{\overline{X}}$).
Considering the graphs of morphisms as closed subschemes, [Corollary 1](#fga-2-theorem-3-corollary-1) implies:

::: {.itenv #fga-2-theorem-3-corollary-2 title="Corollary 2" latex="{Corollary 2}"}
Let $X$ and $Z$ be proper schemes over $A$ (which is a separated complete $\scr{J}$-adic Noetherian ring).
Then the map $g\mapsto\overline{g}$ defines a bijective correspondence between $Y$-morphism from $X$ to $Z$ and $\overline{Y}$-morphisms from $\overline{X}$ to $\overline{Z}$.
:::

In other words, proper algebraic schemes over $A$ give a subcategory (with the morphisms being the induced morphisms) of the category of proper formal schemes over $\overline{Y}$.
We note, however, that _there exist proper formal schemes over $\overline{Y}$ that are not "algebraisable"_, i.e. isomorphic to some $\overline{X}$, where $X$ is proper over $A$ (just as there exist compact complex-analytic varieties that do not come from algebraic varieties defined over the field of complex numbers).
Such formal schemes naturally appear in "module theory".
We note, however, an interesting case where a formal scheme is algebraisable:

::: {.itenv #fga-2-theorem-4 title="Theorem 4" latex="{Theorem 4}"}
Let $A$ be a complete local Noetherian ring, with residue field $k$, and let $\frak{X}$ be a proper formal scheme over $A$ (endowed with its $\frak{r}(A)$-adic topology).
We suppose that

i. the local rings of $\scr{O}_{\frak{X}}$ are _flat_ $A$-modules, or, equivalently, that, if we endow $\scr{O}_{\frak{X}}$ and $A$ with the filtration given by powers of the maximal ideal of $A$, then the associated graded algebras satisfy
    $$
      \gr(\scr{O}_{\frak{X}}) \simeq \gr^0(\scr{O}_{\frak{X}})\otimes_k\gr(A);
    $$

ii. $H^2(\frak{X}_0,\scr{O}_{\frak{X}_0})=0$, where we consider $\frak{X}_0=\frak{X}\otimes_Ak$ as an algebraic scheme over $k$;

iii.  $\frak{X}_0$ is projective.

\oldpage{182-07}

Then, under these conditions, $\frak{X}$ is algebraisable, and, more precisely, is isomorphic to $\overline{X}$, where $X$ is some projective $A$-scheme.
:::

Conditions (ii) and (iii) will be satisfied if, in particular, $\frak{X}_0$ is a _simple curve_ over $k$, and [Theorem 4](#fga-2-theorem-4) can be applied, in particular, in the "module theory" of curves of a given genus...
We will give here a hint on how to prove [Theorem 4](#fga-2-theorem-4):
we can show (cf. [Proposition 3](#fga-2-proposition-3) below) that (i) and (ii) imply that every coherent sheaf on $\frak{X}_0$ that is locally isomorphic to a fundamental sheaf can be obtained by reduction starting from a sheaf of the same nature on $\frak{X}$.
So, starting with an "ample" sheaf on $\frak{X}_0$ (which, by (iii), exists), we lift it to obtain an invertible sheaf on $\frak{X}$, and, using [Theorem 1](#fga-2-theorem-1), we prove that a multiple of this invertible sheaf defined an immersion of $X$ into the formal completion of a scheme $\PP_A^r$ ("projective type" of dimension $r$ over $A$).

For the proof of [Theorem 1](#fga-2-theorem-1), [Theorem 2](#fga-2-theorem-2), and [Theorem 3](#fga-2-theorem-3), we refer the reader to [@2-1].


## Applications to Zariski's connection theorem and "main theorem" {#fga-2-section-4}

Let $f\colon X\to Y$ be a proper morphism of schemes.
Then, by the finiteness theorem ([Theorem 1](#fga-2-theorem-1)), $f_*(\scr{O}_X)=\underline{A}$ is a coherent sheaf on $Y$, and is also a sheaf of commutative algebras, and thus corresponds to a $Y$-scheme $g\colon Y'\to Y$ that is finite over $Y$ (defined by the condition of being affine over $Y$, i.e. the inverse image of an affine open is affine, and $g_*(\scr{O}_{Y'})=\underline{A}$).
It is immediate that $f$ then canonically factors as $f=gf'$, where $f'\colon X\to Y'$ is a morphism from $X$ to $Y$ that is now such that $f'_*(\scr{O}_X)=\scr{O}_{Y'}$.
This factorisation of $f$ is called _the Stein factorisation_ of $f$.
Applying the first comparison theorem ([Theorem 2](#fga-2-theorem-2)) and its [Corollary 1](#fga-2-theorem-2-corollary-1) to $f'$ and the subset $Y'$ consisting of a single point $y'$, we see that $(f')^{-1}(y')=X'$ is connected (or, in other words, the formal sections of $X$ along $X'$ do not form a local ring, but the completion $f'_*(\scr{O}_X)_{y'}=\scr{O}_{y'}$ is local!)
We have proven:

::: {.itenv #fga-2-theorem-5 title="Theorem 5" latex="{Theorem 5}"}
_Zariski's "connection theorem"_ ---
Let $f\colon X\to Y$ be a proper morphism.
Then $f$ factors uniquely (up to isomorphism) as $f=gf'$, where $g\colon Y'\to Y$ is finite, and $f'\colon X\to Y'$ is such that $f'_*(\scr{O}_X)=\scr{O}_{Y'}$ (whence $g_*(\scr{O}_{Y'})=f_*(\scr{O}_X)$).
Also, the fibres of $f'$ are connected, i.e. the set of connected components of a fibre $f^{-1}(y)$ of $f$ is in bijective correspondence with the set of points of $Y'$ over $y$, i.e. the set of maximal ideals in $f_*(\scr{O}_X)_y$.
:::

\oldpage{182-06}

From this, we immediately deduce the usual variants of the connection theorem.
We state here only the following:

::: {.itenv #fga-2-theorem-5-corollary-1 title="Corollary 1" latex="{Corollary 1}"}
For a point $x$ of $X$ to be isolated in its fibre $f^{-1}(y)$, it is necessary and sufficient for the fibre $(f')^{-1}(y')$ (where $y'=f'(x)$) to consist of a single point $x$, or for $f'$ to induce an isomorphism from a neighbourhood of $x$ to a neighbourhood of $y'$.
The set of these points is an open subset $U$, and $f'$ induces an isomorphism from $U$ to an open subset of $Y'$.
:::

To show that $f'$ is a local isomorphism at $x$, we note that $f'$ induces an _isomorphism_ $\scr{O}_{y'}\to\scr{O}_x$, as we see thanks to $f'(\scr{O}_X)=\scr{O}_{Y'}$;
we also note that the $(f')^{-1}(V)$ give a fundamental system of neighbourhoods of $x$ when $V$ runs over a fundamental system of neighbourhoods of $y'$ (since $f'$ is a closed map whose fibre at $y'$ consists of the single point $x$).
We thus immediately deduce the following result, due to Chevalley in the "geometric" case:

::: {.itenv #fga-2-theorem-5-corollary-2 title="Corollary 2" latex="{Corollary 2}"}
For $f$ to be a finite morphism, it is necessary and sufficient for it to be proper with finite fibres.
:::

If this is so, then $f'$ is effectively an isomorphism, by the above.

Let $f\colon X\to Y$ be a morphism that is not necessarily proper, but suppose that $X$ is contained in some proper $Y$-scheme $\overline{f}\colon\overline{X}\to Y$ as an open subset (which is the case if, in particular, $\overline{f}$ is quasi-projective).
Applying [Corollary 1](#fga-2-theorem-5-corollary-1), we see that $\overline{f'}$ induces an isomorphism from the set $U$ of points of $X$ that are isolated in their fibre to an open subset of $Y'$ (and that $U$ is indeed an open subset).
We thus deduce the following global version of Zariski's "main theorem":

::: {.itenv #fga-2-theorem-6 title="Theorem 6" latex="{Theorem 6}"}
Let $f\colon X\to Y$ be a morphism of finite type.
Then the set $U$ of points of $X$ that are isolated in their fibre is open, and, if $f$ is quasi-projective^[_[Comp.]_ This hypothesis can be replaced by the weaker hypothesis "if $f$ is separated", by means of the following result (see SGA VIII, 6.2): every morphism $f\colon X\to Y$ which is quasi-finite and separated is also projective.], then $U$ is $Y$-isomorphic to an open subset of some scheme $Y'$ that is finite over $Y$.
:::

Since a morphism of finite type is locally affine, and _a fortiori_ locally quasi-projective, we immediately deduce from [Theorem 6](#fga-2-theorem-6) the usual local variants of the main theorem.


## Application to the cohomological study of proper and flat morphisms {#fga-2-section-5}

Let $f\colon X\to Y$ be a proper morphism, and $\scr{F}$ a coherent sheaf on $X$, with $\scr{F}$ assumed to be $Y$-flat, i.e. the $\scr{F}_x$ are flat modules over the rings $\scr{O}_y$ (where $y=f(x)$).
\oldpage{182-09}
This also implies that, for every $y\in Y$, if we filter $\scr{F}$ along the fibre $f^{-1}(y)$ by the $\frak{m}_y^n\scr{F}$ (where $\frak{m}_y$ is the maximal ideal of $\scr{O}_y$), then the associated graded algebra is isomorphic to $(\scr{F}/\frak{m}_y\scr{F})\otimes_{\kres(y)}\gr(\scr{O}_y)$;
in other words, we have that
$$
  \frak{m}_y^n\scr{F}/\frak{m}_y^{n+1}
  = \scr{F}_y\otimes_{\kres(y)}(\frak{m}_y^n/\frak{m}_y^{n+1})
$$
for every integer $n$, where $\scr{F}_y$ denotes the sheaf $\scr{F}/\frak{m}_y\scr{F}$ induced by $\scr{F}$ on $X_y$ (with $X_y$ denoting the fibre $f^{-1}(y)$ considered as a proper scheme over the residue field $\kres(y)$ of $y$).
Taking this isomorphism, as well as [Theorem 2](#fga-2-theorem-2), into account, we obtain augmentations, and sometimes computations, of the $\RR^q f_*(\scr{F})$ in a neighbourhood of $y$, knowing the cohomology of $X_y$ with coefficients in $\scr{F}_y$.
Here [Theorem 2](#fga-2-theorem-2) takes the form
$$
  \overline{\RR^q f_*(\scr{F})} = \varprojlim_n H^q(\scr{F}_y,\scr{F}/\frak{m}_y^n\scr{F}).
$$
We will mention here only the following consequence:

::: {.itenv #fga-2-proposition-1 title="Proposition 1" latex="{Proposition 1}"}
Let $f\colon X\to Y$ be a proper morphism, and $\scr{F}$ a coherent $Y$-flat sheaf on $X$.
Let $y\in Y$, let $q$ be an integer, and suppose that $H^q(X_y,\scr{F}_y)=0$.
Then $\RR^q f_*(\scr{F})$ is zero on a a neighbourhood of $y$, and, for every $n$, the natural homomorphism
$$
  \RR^{q-1}f_*(\scr{F})_y \to H^{q-1}(X_y,\scr{F}_y/\frak{m}_y^n\scr{F}_y)
$$
is surjective.
:::

In particular, if $f$ is a flat morphism (i.e. if $\scr{O}_X$ is $Y$-flat), then every locally free coherent sheaf $\scr{F}$ on $X$ is $Y$-flat.
Let $\scr{F}$ and $\scr{G}$ be two such sheaves, and apply [Proposition 1](#fga-2-proposition-1) to $\shHom_{\scr{O}_X}(\scr{F},\scr{G})$ and $q=1$ to obtain:

::: {.itenv #fga-2-theorem-7 title="Theorem 7" latex="{Theorem 7}"}
Let $f$ be a flat proper morphism, $\scr{F}$ and $\scr{G}$ locally free coherent sheaves on $X$, and $y\in Y$;
suppose that $H^1(X_y,\shHom_{\scr{O}_X}(\scr{F}_y,\scr{G}))=0$.
Then every homomorphism $u_0\colon\scr{F}_y\to\scr{G}_y$ is induced by a homomorphism $u\colon\scr{F}|V\to\scr{G}|V$, where $V=f^{-1}(U)$ is the inverse image of a neighbourhood $U$ of $y$.
:::

::: {.itenv #fga-2-theorem-7-corollary-1 title="Corollary 1" latex="{Corollary 1}"}
If $u_0$ is an isomorphism (resp. a monomorphism, resp. an epimorphism), then so too is $u$, for small enough $U$.
:::

In particular:

\oldpage{182-10}
::: {.itenv #fga-2-theorem-7-corollary-2 title="Corollary 2" latex="{Corollary 2}"}
Let $E_0$ be a locally free coherent sheaf on $X_y$ such that $H^1(X_y;\shHom_{\scr{O}_X}(E_0,E_0))=0$.
Then any two locally free sheaves whose restrictions to $X_y$ are isomorphic to $E_0$ are themselves isomorphic to one another in a neighbourhood of $X_y$.
:::

Thus:

::: {.itenv #fga-2-theorem-7-corollary-3 title="Corollary 3" latex="{Corollary 3}"}
Suppose that $H^1(X_y,\scr{O}_{X_y})=0$.
Then any two invertible sheaves on $X$ (i.e. locally isomorphic to $\scr{O}_X$) whose restrictions to $X_y$ are isomorphic are themselves isomorphic to one another.
:::

It thus follows that:

::: {.itenv #fga-2-proposition-2 title="Proposition 2" latex="{Proposition 2}"}
Let $Y$ be a connected scheme, and $E$ a locally free coherent sheaf on $Y$.
Consider the bundle of projective spaces $X=\PP(E)$ associated to $E$, endowed with its well-known invertible sheaf $\scr{O}_X(1)$.
Then every invertible sheaf $\scr{L}$ on $X$ is isomorphic to a sheaf of the form $f^*(\scr{L}')\otimes\scr{O}_X(n)$, where $\scr{L}'$ is an invertible sheaf on $Y$, and $n$ is an integer.
Further, $n$ is uniquely determined, and $\scr{L}'$ is determined up to isomorphism.
:::

[Corollary 3](#fga-2-theorem-7-corollary-3) above proves that $\scr{L}$ is isomorphic to an $\scr{O}_X(n)$-module on a neighbourhood of each fibre.
The rest is more or less formal.

[Proposition 2](#fga-2-proposition-2) allows us to determine the $Y$-morphisms from $X=\PP(E)$ to another projective bundle.
We see, in particular:

::: {.itenv #fga-2-proposition-2-corollary-1 title="Corollary 1" latex="{Corollary 1}"}
Let $u$ be an automorphism of $X=\PP(E)$.
Then there exists an invertible sheaf $\scr{L}'$ on $Y$, and an isomorphism $v$ from $E$ to $E\otimes\scr{L}'$ such that $u$ is the isomorphism corresponding to $\PP(E)\xrightarrow{\sim}\PP(E\otimes\scr{L}')=\PP(E)$;
the pair $(v,\scr{L}')$ is determined up to isomorphism.
:::

Let $\Gamma$ be the set of classes of invertible bundles $\scr{L}'$ on $Y$ such that $E\otimes\scr{L}'$ is isomorphic to $E$.
Its elements are torsion, since, if $n$ is the rank of $E$, then (by taking $n$-th exterior powers) we must have that $(\scr{L}')^{\otimes n}\xrightarrow{\sim}\scr{O}_Y$.
The above corollary can then be expressed by saying that we have an exact sequence of groups:
$$
  e \to \Aut(E)/\Gamma(Y,\scr{O}_Y^*) \to \Aut_Y(X) \to \Gamma \to e
$$
(which can also be deduced from the exact sequence in cohomology induced by the exact sequence of _sheaves_ of groups
\oldpage{182-11}
$$
  e \to \scr{O}_X^* \to \shAut \to \shAut_Y(X) \to e,
$$
where $\scr{O}_X^*$ is the sheaf of "units" of $\scr{O}_X$, identified with the centre of $\shAut(E)$.)


## Application to existence and uniqueness theorems for sheaves and schemes over a complete $\mathscr{J}$-adic ring {#fga-2-section-6}

[Theorem 7](#fga-2-theorem-7) gave a uniqueness result for locally free coherent sheaves, by using [Theorem 1](#fga-2-theorem-1) and [Theorem 2](#fga-2-theorem-2).
Using [Theorem 3](#fga-2-theorem-3), we now obtain _existence_ theorems for sheaves, for morphisms of schemes, or for schemes.
In the following, $A$ denotes a local Noetherian ring, assumed to be separated and _complete_.
The general method still consists of making _formal_ construction, which consists essentially of doing _algebraic geometry over an Artinian ring_, and deducing conclusions from this that are "algebraic" in nature, by using the three fundamental theorems.

::: {.itenv #fga-2-proposition-3 title="Proposition 3" latex="{Proposition 3}"}
Let $\frak{X}$ be a proper formal scheme that is flat over $A$, and let $\scr{F}_0$ be a locally free sheaf on $X_0$ such that $H^2(X_0,\shHom_{\scr{O}_{X_0}}(\scr{F}_0,\scr{F}_0))=0$.
Then there exists a locally free sheaf $\scr{F}$ on $\frak{X}$ that induces, on $X_0$, a sheaf isomorphic to $\scr{F}_0$.
(This $\scr{F}$ is also unique up to isomorphism if $H^1(X_0,\shHom_{\scr{O}_{X_0}}(\scr{F}_0,\scr{F}_0))=0$).
:::

We construct, step by step, locally free sheaves $\scr{F}_n$ on the $X_n$ that induce one another.
The construction of $\scr{F}_0$ is met with an obstruction living in $H^2(X_0,\shHom_{\scr{O}_{X_0}}(\scr{F}_0,\scr{F}_0))\otimes_{A/\scr{J}}(\scr{J}^n/\scr{J}^{n+1})$, but this is zero, by hypothesis.
Now, using [Theorem 3](#fga-2-theorem-3), we obtain:

::: {.itenv #fga-2-proposition-3-corollary-1 title="Corollary 1" latex="{Corollary 1}"}
Let $X$ be a proper scheme that is flat over $A$, and let $\scr{F}_0$ be as above.
Then there exists a locally free sheaf $\scr{F}$ on $X$ that induces, on $X_0$, a sheaf that is isomorphic to $\scr{F}_0$.
This $\scr{F}$ is also unique up to isomorphism if $H^1(X_0,\shHom_{\scr{O}_{X_0}}(\scr{F}_0,\scr{F}_0))=0$.
:::

Let $X_0$ be a scheme of finite type over the field $k$, and suppose that $X_0$ is _simple_ (by which we mean _absolutely_ simple) over $k$, but not necessarily proper over $k$.
Let $A$ be a local Artinian ring with residue field $k$.
We are interested in finding schemes $X$ that are flat over $A$, and such that $X\otimes_A k=X_0$ (this is the starting point of the "_theory of modules_", or of "structure variations" of $X_0$).
\oldpage{182-12}
It is equivalent to give either such an $X$ or, on the topological space $X_0$, a sheaf $\scr{O}_X$ endowed with the following structures:

i. $\scr{O}_X$ is a sheaf of $A$-algebras;

ii. $\scr{O}_X$ is endowed with an augmentation homomorphism $\scr{O}_X\to\scr{O}_{X_0}$ (that is compatible with the $A$-algebra structures);

and with the above data being subject to the following conditions: the augmentation induces an isomorphism $\scr{O}_X\otimes_A k\xrightarrow{\sim}\scr{O}_{X_0}$;
$\scr{O}_X$ is flat over $A$, i.e. the graded algebra associated to $\scr{O}_X$ filtered by the powers of the maximal ideal $\frak{m}$ of $A$ is isomorphic to $\gr^0(\scr{O}_X)\otimes_k\gr(A)$, i.e. we have isomorphisms $\frak{m}^n\scr{O}_X/\frak{m}^{n+1}\scr{O}_X = \scr{O}_{X_0}\otimes_k(\frak{m}^n/\frak{m}^{n+1})$.
The fundamental fact is the following:

::: {.itenv #fga-2-theorem-8 title="Theorem 8" latex="{Theorem 8}"}
Let $X_0$ be a simple scheme of finite type over the field $k$, and assume $X_0$ to be affine.
Let $A$ be a local Artinian ring of residue field $k$.
Then there exists an $A$-scheme $X$ that is flat over $A$ and such that $X\otimes_A k=X_0$.
Further, any two such schemes are necessarily isomorphic.
:::

Note that the isomorphic in question is not canonical, since $X$ will have, in general, non-trivial $A$-automorphisms that induce the identity on $X_0$.
Furthermore, there is not, in general, a "canonical" choice of $X$ satisfying the given conditions, except in the case where $A$ is a $k$-algebra (the case of _equal characteristics_), where we can take $X=X_0\otimes_k A$, i.e. $\scr{O}_X=\scr{O}_{X_0}\otimes_k A$ (whether or not $X_0$ is affine, in fact).
In the case of unequal characteristics, I do not know in general, when $X_0$ is not affine, if we can "lift" $X_0$ to an $X$ defined over $A$.
However, for any integer $n>0$, let $A_{n-1}=A/\frak{m}^n$, and suppose that we have lifted $X_0$ to a flat $A_{n-1}$-scheme $X_{n-1}$;
we intend to lift $X_{n-1}$ to a flat $A_n$-scheme $X_n$.
We already know, by [Theorem 8](#fga-2-theorem-8), that this is possible locally;
we can also easily verify that, if $U_n$ lifts an open subset $U_{n-1}$ of $X_{n-1}$, then the sheaf of groups of automorphisms of $U_n$ (that induce the identity on $U_{n-1}$) is canonically isomorphic to $\frak{G}_{X_0/k}\otimes_k\frak{m}^n/\frak{m}^{n+1}$ restricted to $U_{n-1}$, and thus, in particular, commutative (where $\frak{G}_{X_0/k}$ denotes the sheaf of germs of $k$-derivations on $X_0$).
It follows easily that we have an _obstruction of constructing $X_n$ lifting $X_{n-1}$_, which lives in $H^2(X_0,\frak{G}_{X_0/k})\otimes\frak{m}^n/\frak{m}^{n+1}$.
Then:

::: {.itenv #fga-2-theorem-8-corollary-1 title="Corollary 1" latex="{Corollary 1}"}
Let $X_0$ be a simple scheme of finite type over $k$, and suppose that
$$H^2(X_0,\frak{G}_{X_0/k})=0.$$
\oldpage{182-13}
Then, for every local Artinian ring $A$ with residue field $k$, there exists a flat $A$-scheme $X$ such that $X\otimes_A k=X_0$.
:::

Also, if we can find _one_ $X$ that is flat over $A$ and that lifts $X_0$, then, by [Theorem 8](#fga-2-theorem-8), the set of classes (up to isomorphism) of flat $A$-schemes that lift $X_0$ can be identified with $H^1(X_0,\shAut(X))$, where $\shAut(X)$ denotes the sheaf of germs of automorphisms of the sheaf $\scr{O_X}$ of $A$-algebras _that are compatible with the augmentation_.
The filtration of $\scr{O}_X$ defines a filtration of $\shAut(X)$, with the quotient of this sheaf by the $n$-th subgroup of the filtration being $\shAut(X_n)$;
the graded algebra associated to this filtration is commutative, and can be identified with $\frak{G}_{X_0/k}\otimes_k\gr(A)$.
In particular, if $\frak{m}^{n+1}$ is the first power of $\frak{m}$ that is not zero, then $F^n(\shAut(X))$ (the last stage of the filtration) is in the centre of $\shAut(X)$, and is isomorphic to $\frak{G}_{X_0/k}\otimes_k\frak{m}^n$;
it is also the sheaf of germs of automorphisms of $X$ that induce the identity on $X_{n-1}=X\otimes_A A/\frak{m}^n$.
Using these results, we immediately obtain the following statements:

::: {.itenv #fga-2-theorem-8-corollary-2 title="Corollary 2" latex="{Corollary 2}"}
Let $X_0$ be a simple scheme of finite type over $k$, and let $A$ be a local Artinian ring with residue field $k$ and maximal ideal $\frak{m}$.
Suppose that $\frak{m}^{n+1}=0$.
Let $A_{n-1}=A/\frak{m}^n$, and let $X_{n-1}$ be a flat $A_{n-1}$-scheme such that $X_{n-1}\otimes_Ak=X_0$.
Then the set of classes (up to an isomorphism that induces the identity on $X_{n-1}$) of flat $A$-schemes $X_n$ such that $X\otimes_AA_{n-1}=X_{n-1}$ is either empty, or a homogeneous principal space under $H^1(X_0,\frak{G}_{X_0/k})\otimes_k\frak{m}^n$.
:::

(Note that, in general, there is no privileged choice of origin in the latter homogeneous principal space, since there is no privileged way of lifting $X_{n-1}$ to $X_n$).

::: {.itenv #fga-2-theorem-8-corollary-3 title="Corollary 3" latex="{Corollary 3}"}
Let $X_0$ be a simple scheme of finite type over $k$, and suppose that $H^1(X_0,\frak{G}_{X_0/k})=0$.
Then, for every local Artinian ring $A$ with residue field $k$, _there exists at most one flat $A$-scheme $X$_ (up to isomorphism) such that $X\otimes_Ak=X_0$.
:::

[Corollary 1](#fga-2-theorem-8-corollary-1) and [Corollary 3](#fga-2-theorem-8-corollary-3) immediately imply the claims, which seem more general, obtained by supposing only that $A$ is a _complete local Noetherian ring with residue field $k$_, provided that we introduce $X$ as a formal scheme over $A$:

::: {.itenv #fga-2-theorem-9 title="Theorem 9" latex="{Theorem 9}"}
Let $k$ be a field, and $X_0$ a _simple_ scheme of finite type over $k$.
For every complete locally Noetherian ring $A$ with residue field $k$, let $F(A)$ be the set of classes (up to an isomorphism that induces the identity on $X_0$) of formal schemes $\frak{X}$ over $A$, of finite type, and flat over $A$, such that $X\otimes_Ak=X_0$.
\oldpage{182-14}
With this notation:
for all $A$,

i. if $H^1(X_0,\frak{G}_{X_0/k})=0$ then $F(A)$ has at most one element;
ii. if $H^2(X_0,\frak{G}_{X_0/k})=0$ then $F(A)$ has at least one element.
:::

::: {.itenv #fga-2-theorem-9-corollary-1 title="Corollary 1" latex="{Corollary 1}"}
Suppose that $X_0$ is proper over $k$.
Under condition (i) of [Theorem 9](#fga-2-theorem-9), for all $A$, there exists at most (up to an isomorphism that induces the identity on $X_0$) one scheme $X$ that is proper, flat over $A$, and such that $X\otimes_Ak=X_0$.
:::

We can use [Corollary 2 of Theorem 3](#fga-2-theorem-3-corollary-2).
For example:

::: {.itenv #fga-2-theorem-9-corollary-2 title="Corollary 2" latex="{Corollary 2}"}
If $X$ is a proper flat $A$-scheme such that $X\otimes_Ak$ is isomorphic to the projective-type scheme $\frak{P}_k^r$ of dimension $r$ over $k$, then $X$ is isomorphic to $\frak{P}_k^r$.
:::

(We can also deduce this result from [Corollary 1 of Proposition 3](#fga-2-proposition-3-corollary-1)).

::: {.itenv #fga-2-theorem-9-corollary-3 title="Corollary 3" latex="{Corollary 3}"}
Let $X_0$ be a simple projective scheme over $k$, and suppose that
$$
  H^2(X_0,\scr{O}_{X_0}) = H^2(X_0,\frak{G}_{X_0/k}) = 0.
$$
Then, for all $A$, there exists a flat projective $A$-scheme such that $X\otimes_Ak=X_0$.
:::

We can combine [Theorem 9](#fga-2-theorem-9) (ii) with [Theorem 4](#fga-2-theorem-4).
In particular:

::: {.itenv #fga-2-theorem-9-corollary-4 title="Corollary 4" latex="{Corollary 4}"}
Let $X_0$ be the scheme of a complete simple algebraic curve over $k$.
Then, for every complete local Noetherian ring $A$ with residue field $k$, there exists a "simple curve scheme" $X$ over $A$, such that $X\otimes_Ak=X_0$.
:::

::: {.rmenv title="Remarks" latex="{Remarks}"}
—

1. [Corollary 3](#fga-2-theorem-9-corollary-3) and [Corollary 4](#fga-2-theorem-9-corollary-4) are above all interesting if $k$ is of characteristic $p\neq0$, taking $A$ to be a discrete valuation ring _of characteristic $0$_, with residue field $k$;
    for example, the "smallest possible $A$", i.e. that for which $p$ generates the maximal ideal.
    (In fact, by theorems of Cohen, it suffices to have [Corollary 3](#fga-2-theorem-9-corollary-3) and [Corollary 4](#fga-2-theorem-9-corollary-4) for such a ring $A$).
    We note that, concerning this point, according to the specialists, we do not know if there exist schemes over a field $k$ that are not reductions $\mod p$ of a flat scheme defined over such a ring $A$.
    At the least, the results of this section give a way of systematically investigating this question.
    We must start by seeing if the first obstruction that we have, in $H^2(X_0,\frak{G}_{X_0/k})$, is necessarily zero.

\oldpage{182-15}

2. We note that [Theorem 3](#fga-2-theorem-3), and the corresponding technique, only works for a _complete_ (local, for simplicity) base ring.

    In order to go from known results concerning the completion of a local ring to the corresponding results for the local ring itself, we would need a fourth "fundamental theorem", whose precise statement still needs to be found.

3. We will compare the results from this section (mainly the above [Corollary 1](#fga-2-theorem-9-corollary-1) and [Corollary 2](#fga-2-theorem-9-corollary-2)), as well as those from the following, with the results of Kodaira--Spencer on the variation of complex structures.
    Using the conjectural theorem to which we have just alluded, we should be able to conclude, under the conditions of [Corollary 1](#fga-2-theorem-9-corollary-1), but where $A$ is no longer assumed to be complete, that there exists a ring $A'$ that contains $A$, and that is finite and unramified over $A$, such that $X\otimes_AA'$ and $X'\otimes_AA'$ are $A'$-isomorphic (where $X$ and $X'$ are given, and are proper flat $A$-schemes such that $X\otimes_Ak=X'\otimes_Ak=X_0$).
    This is what we can prove, at least, when $X_0=\frak{P}_k^r$, by using [Corollary 1 of Proposition 2](#fga-2-proposition-2-corollary-1).
    In any case, if $H^1(X_0,\frak{G}_{X_0/k})=0$, then we can prove that the fibres of $X$ and $X'$ over any point $y$ of $Y=\Spec(A)$ are isomorphic, or at least when we pass to the algebraic closure of the residue field $\kres(y)$.
    (We have a local result, seemingly stronger, when we don't suppose that $A$ is necessarily local).
    As for "structure variations" of the projective space, we again point out the following question, suggested by a corresponding problem of Kodaira--Spencer.
    Let $X$ be a proper flat scheme, over a local integral ring $A$ with field of fractions $K$ and residue field $k$, and suppose that $X\otimes_AK$ is isomorphic to $\frak{P}_K^r$.
    Is it then true that $X\otimes_Ak=X_0$ is isomorphic to $\frak{P}_k^R$ (or at least, over the algebraic closure of $k$)?
    In this question, we can assume that $A$ is a complete discrete valuation ring.
    There is an analogous question when $X_0$ is an abelian variety.
:::

::: {.rmenv title="Remark" latex="{Remark}"}
_[Comp.]_
_(Concerning Remark 1 above)._
We note that J.-P. Serre has constructed a non-singular projective variety, of dimension $3$, over an algebraically closed field $k$, of characteristic $p>0$, which does not come from reduction of a proper scheme over a local integral ring with residue field $k$, and having a field of fractions of characteristic $0$.^[Serre, J.-P. "Exemples des variétés projectives en caractéristique $p$ non relevables en caractéristique zéro". _Proc. Nat. Acad. Sc. U.S.A._ **47** (1961), 108--109.]
Mumford would have found an analogous result, with a non-singular projective _surface_.
:::

::: {.rmenv title="Remark" latex="{Remark}"}
_[Comp.]_
_(Concerning Remarks 2 and 3 above.)_
I am now less optimistic concerning the results conjectured here.
However, the question concerning structure variations for projective space, mentioned at the end of Remark 3 above, has been positively resolved by Hironaka, and the analogous question for abelian varieties has been resolved by Koizumi.
:::


## Application to the "theory of modules" {#fga-2-section-7}

Since the speaker has only recently encountered this theory himself, we will be obliged to limit ourselves to just cursory remarks.
For simplicity, we work over a _field_ $k$, i.e. we work in _equal characteristic_, even though [Theorem 8](#fga-2-theorem-8) allows us to also discuss the more general case, without any fundamental changes, so it seems.
We have not yet gotten past the "formal" stage, but the speaker still hopes to be able to construct true schemes of modules in certain cases from this, and, in particular, construct, for every integer $g$, a scheme over the integers that plays the role of universal scheme of modules for the simple curves of genus $g$.

\oldpage{182-16}

::: {.rmenv title="Remark" latex="{Remark}"}
_[Comp.]_
We note that Mumford has recently constructed schemes of modules for the curves of genus $g$ (cf. _Mumford--Tate seminar_, Harvard University, 1961--62).
[Theorem 10](#fga-2-theorem-10) also proves that the "level $n$ Jacobi schemes" from the theory of modules are non-singular (and even simple over $\underline{\ZZ}$).
:::

We continue to use the setting and notation of [Theorem 9](#fga-2-theorem-9), and now suppose that $A$ is a local algebra of finite rank over $k$, which is assumed to be algebraically closed, for simplicity.
Then $F(A)$ can be thought of as a covariant functor in $A$, with values in the category of sets, with a homomorphism $A\to B$ of $k$-algebras defining a map $F(A)\to F(B)$, since every flat $A$-scheme $X$ with $X\otimes_Ak=X_0$ gives rise to a $B$-scheme $X\otimes_AB$ with the same properties.
_Suppose_ that we can find a complete local Noetherian $k$-algebra $\cal{O}$, as well as a functorial isomorphism
$$
  \Hom(\cal{O},A) \xrightarrow{\sim} F(A)
  \tag{$*$}
$$
(where the left-hand side denotes homomorphisms of $k$-algebras).
We can easily see that such an $\cal{O}$ is determined up to canonical isomorphism, and so we call the formal spectrum $\frak{Y}$ of $\cal{O}$ (i.e. the topological space consisting of a single point, endowed with a sheaf of topological rings consisting of just $\cal{O}$) the _formal scheme of modules for $X_0$_.
(Note that it does not necessarily exist).
Let $\frak{r}$ be the maximal ideal of $\cal{O}$, and, for all $n$, let $\scr{O}_n=\cal{O}/\frak{r}^{n+1}$ (so that $\scr{O}_0=k$).
Then the canonical homomorphism $\cal{O}\to\scr{O}_n$ is an element of $\Hom(\cal{O},\scr{O}_n)$, and thus defines an element of $F(\scr{O}_n)$, i.e. a flat $\scr{O}_n$-scheme $X_n$ whose restriction $\mod\frak{r}$ is $X_0$.
These $X_n$ are induced from one another by extension of scalars (i.e. here by reductions), whence it follows that they come from a formal scheme $\frak{X}$ that is well determined by the formal scheme of modules $\frak{Y}$;
further, $\frak{X}$ is flat over $\frak{Y}$, and $\frak{X}_0=X_0$.
The isomorphism ($*$) is then given, as we can immediately see, by associating to each homomorphism $\cal{O}\to A$ of $k$-algebras the class of the $A$-scheme $\frak{X}\otimes_{\cal{O}} A$ (i.e. to every morphism $\frak{Y}'=\Spec(A)\to\frak{Y}$ of $k$-schemes, we associate the $\frak{Y}'$-scheme $\frak{X}\otimes_{\frak{Y}}\frak{Y}'$ given by base change).
Furthermore, we see that the isomorphism ($*$) and its above description still hold even if we only suppose that $A$ is a complete local Noetherian $k$-algebra (not necessarily Artinian).
Of course, as always, $\cal{O}$ can indeed _a priori_ have nilpotent elements, and it seems likely that there should exist cases where $\cal{O}$ is itself Artinian, without being identical to $k$.
This tells us at which point the point of view of Kodaira--Spencer (restricting to considering the $A$ that are _regular_ rings) is _a priori_ inadequate in the general case.

\oldpage{182-17}
It remains to give sufficient conditions for there to exist a formal scheme of modules for $X_0$, assumed to be proper over $k$.
Generally, it is easy to give simple necessary and sufficient conditions on a functor $A\to F(A)$ (from local $k$-algebras of finite rank to sets) in order for it to be of the form $\Hom(\cal{O},A)$ for some suitable $\cal{O}$.
We do not give the details here.
We point out only that, in the case which we are studying, these conditions impose non-trivial conditions of a cohomological nature on $X_0$, and it seems unlikely that they will always be satisfied, even though the speaker has not constructed any counterexamples.
It seems plausible, however, that the condition $H^0(X,\frak{G}_{X_0/k})=0$ is _sufficient_ (even if not at all necessary) in order to guarantee the existence of a formal scheme of modules.
We restrict ourselves to stating here a theorem that deals with a particularly simple case (whose analogue in the theory of analytic spaces is well known, cf. Kodaira--Spencer), which can easily be proven using the results from the previous section:

::: {.itenv #fga-2-theorem-10 title="Theorem 10" latex="{Theorem 10}"}
Let $X_0$ be a simple proper scheme over the field $k$ such that
$$
  H^0(X_0,\frak{G}_{X_0/k}) = H^2(X_0,\frak{G}_{X_0/k}) = 0.
$$
Then there exists a formal scheme of modules for $X_0$, corresponding to a local regular ring $\cal{O}$ (i.e. an algebra of formal series over $k$).
:::

As we have already pointed out, it is not true in general that the formal scheme $\frak{X}$ over $\cal{O}$ is algebraisable;
but we know that this is true, however, when $X_0$ is projective and $H^2(X_0,\scr{O}_{X_0})=0$ ([Theorem 4](#fga-2-theorem-4)), such as when $X_0$ is of dimension $1$.
This is what gives some hope of constructing a scheme of modules over the integers for curves of a given genus...

Note also that methods such as those described in this section can be applied in the construction and study of Picard varieties, as well as in many other constructions.
We will return to this soon.


## Application to the fundamental group {#fga-2-section-8}

The techniques described allows us to tackle the system study of the fundamental group, using the example of topological theory.
The first two theorems stated in this section are generalisations of results in a recent work by Lang--Serre.

Let $X$ be a scheme.
Then an $X$-scheme $X'$ is said to be an _unramified covering of $X$_ if
\oldpage{182-18}

i. $X'$ is finite over $X$, i.e. it is defined by a coherent sheaf of algebras $\scr{A}=\scr{A}(X')$ on $X$;

ii. $\scr{A}$ is a locally free sheaf on $X$;

iii. for all $x\in X$, the quotient $\scr{A}_x/\frak{m}_x\scr{A}_x = \scr{A}_x\otimes_{\scr{O}_X}\pi(x)$ is a separable algebra over $\kres(x)$.

This notion of unramified covering (due to Serre and the speaker) posses all the elementary properties for which we can reasonably hope, and which we will not list.
We restrict ourselves to saying that it gives rise to a _Galois theory_ modelled on classical Galois theory (and containing it; the proofs being overall simpler than the proofs generally seen for the latter) and the Galois theory of topological coverings.
More precisely, we define a _geometric point_ of a scheme $X$ to be a morphism $a$ from the spectrum $\xi$ of an algebraically closed field $\Omega$ to $X$, i.e. the data of an algebraically closed extension of the residue field $\kres(x)$ of a point $x=|a|$ of $X$ (called the _locality_ of the geometric point $a$).
If $X'$ is an unramified covering of $X$, then we can associate to it the set $E_a(X')$ of "geometric points of $X'$ over $a$", i.e. the set of pairs consisting of an $x'\in X'$ over $x$ and a $\kres(x)$-homomorphism to $\Omega$.
We thus obtain (for fixed $(X,a)$) a functor $F(X,a)$ from the category $R(X)$ of unramified coverings $X'$ of $X$ to the category of finite sets.
If $X$ is connected, then the pair given by $R(X)$ and $F(X,a)$ has all the formal properties necessary in order to be isomorphic to the analogous pair defined by a suitable totally disconnected compact topological group $\pi$ (i.e. a projective limit of finite groups): we take the category $\cal{C}(\pi)$ of finite sets on which $\pi$ acts continuously, and the identity functor $F(\pi)(E)=E$ from this category to the category of finite sets.
The group $\pi$ is also determined up to canonical isomorphic by the condition that $(\cal{C}(\pi),F(\pi))$ is isomorphic to a given pair.
To be precise, $\pi$ is called the _fundamental group of the connected scheme $X$ at the geometric point $a$_, and we denote it by $\pi_1(X,a)$.
If $X$ is not connected, then we can replace it by the connected component containing $x=|a|$.
If, however, $X$ is connected, then the groups $\pi_1(X,a')$ and $\pi_1(X,a')$ are isomorphic for any two geometric points $a'$ and $a''$ of $X$ (with the isomorphism being determined up to inner automorphism), and thus we can, as per usual, choose the most suitable $a$ for our purposes, such as the generic point of $X$ that is assumed to be irreducible.
\oldpage{182-19}
Of course, $\pi_1(X,a)$ is a _covariant functor in the pointed scheme $(X,a)$_.
Every statement concerning the classification of inseparable coverings can then be translated into the language of group theory, following the well-known dictionary (except that we must take into account the fact that here we have _topological groups_).

Our goal is to develop an analogue of the homotopy exact sequence of fibre bundles, relative to a proper morphism $f\colon X\to Y$.
Clearly, since we don't know what the higher homotopy groups are, we will only have necessarily incomplete results.
In order to be able to apply the fundamental theorems from [§3](#fga-2-section-3), we must first explain certain elementary lemmas concerning schemes over Artinian rings or fields (following the general procedure!).

::: {.itenv #fga-2-lemma-1 title="Lemma 1" latex="{Lemma 1}"}
Let $(X',a')$ be a pointed unramified covering associated to a pointed representation of $\pi_1(X,a)$ in a finite set $E$ (endowed with a marked point $e$),
Then the canonical morphism $\pi_1(X',a')\to\pi_1(X,a)$ identifies the domain with the stabiliser of $e$ in $\pi_1(X,a)$ (and is thus injective).
:::

::: {.itenv #fga-2-lemma-2 title="Lemma 2" latex="{Lemma 2}"}
Let $X$ be an algebraic scheme over the field $k$, and let $k'$ be a radicial extension of $k$.
Then every unramified covering of $X\otimes_kk'$ is given by the inverse image (i.e. extension of scalars) of an unramified covering of $X$, determined up to isomorphism.
:::

It follows, in particular, from these two lemmas that, for _every_ algebraic extension $K$ of $k$, and every geometric point $a'$ of $X'=X\otimes_kK$ that projects to the geometric point $a$ of $X$, that the functorial homomorphism $\pi_1(X',a')\to\pi_1(X,a)$ is injective.

::: {.itenv #fga-2-lemma-3 title="Lemma 3" latex="{Lemma 3}"}
Let $X$ be a complete scheme over a local Artinian ring $A$, such that $H^0(X,\scr{O}_X)=A$.
Let $X'$ be an unramified covering of $X$, and let $A'=H^0(X',\scr{O}_{X'})$, which is thus a ring that is finite over $A$ (and which may a priori be ramified over $A$).
Let $X_0$ and $X'_0$ be the reduced subschemes associated to $X$ and $X'$, respectively (obtained by splitting by the sheaves of nilpotent elements in $\scr{O}_X$ and $\scr{O}_{X'}$, respectively).
Let $k$ be a subfield of $A/\frak{r}(A)$ over which $A/\frak{r}(A)$ is finite (so $X_0$ is a complete algebraic scheme over $k$, and $X'_0$ is an unramified covering).
Finally, let $\Omega$ be an algebraically closed extension of $k$, and consider the unramified covering $X'_0\otimes_k\Omega$ of $X_0\otimes_k\Omega$.
Then the following two conditions are equivalent:
\oldpage{182-20}

i. $X'_0\otimes_k\Omega$ is completely decomposed over $X_0\otimes_k\Omega$;
ii. the natural morphism $X'\to X\otimes_AA'$ is an isomorphism.

Under these conditions, $A'$ is an _unramified_ extension of $A$.
Finally, if $X'$ is connected, then condition (i) is equivalent to the following, seemingly weaker, condition:

i bis. $X'_0\otimes_k\Omega$ admits a regular section over $X_0\otimes_k\Omega$.
:::

When condition (ii) is satisfied, we say that the unramified covering $X'$ of $X$ is _geometrically trivial_.

::: {.itenv #fga-2-lemma-4 title="Lemma 4" latex="{Lemma 4}"}
Let $f\colon X\to Y$ be a proper morphism such that $f_*(\scr{O}_X)=\scr{O}_Y$.
Let $a$ be a geometric point of $X$, and $b$ its projection over $Y$.
Then $\pi_1(X,a)\to\pi_1(Y,b)$ is _surjective_.
:::

What we need to show is effectively the following: if an unramified covering $Y'$ of $Y$ (corresponding to a locally free sheaf of algebras $\scr{A}$) is such that $X\otimes_YY'$ is disconnected, then $Y'$ is also disconnected.
In fact, $\scr{A}$ is then the direct sum of two non-zero sheaves of rings, and thus so too is its direct image, which is exactly $\scr{A}\otimes f_*(\scr{O}_X)=\scr{A}$.

::: {.itenv #fga-2-lemma-5 title="Lemma 5" latex="{Lemma 5}"}
Let $X$ be a complete scheme over a field $k$, and suppose that $H^0(X,\scr{O}_X)$ is a local ring $A$, and that $A/\frak{r}(A)$ is radicial over $k$.
Let $\Omega$ be an algebraic closure of $k$, and let $\overline{X}=X\otimes_k\Omega$ (which is connected).
Pick a geometric point $\overline{a}$ of $\overline{X}$ that projects to the geometric point $a$ of $X$.
Then we have an exact sequence
$$
  e
  \to \pi_1(\overline{X},\overline{e})
  \to \pi_1(X,a)
  \to \pi_1(k,b)
  \to e
$$
(where $\pi_1(k,b)$ is the Galois group of $\Omega$ over $k$).
:::

The fact that the first homomorphism is injective has already been shown with [Lemma 1](#fga-2-lemma-1) and [Lemma 2](#fga-2-lemma-2);
the exactness in the middle follows from [Lemma 3](#fga-2-lemma-3);
finally, the surjectivity of the last homomorphism (which is the only thing to rely on the fact that $A/\frak{r}(A)$ is radicial) follows from [Lemma 4](#fga-2-lemma-4).

::: {.itenv #fga-2-proposition-4 title="Proposition 4" latex="{Proposition 4}"}
Let $f\colon X\to Y$ be a proper flat morphism such that, for all $y\in Y$, the algebra $H^0(f^{-1}(y),\scr{O}_{f^{-1}(y)})$ is separable over the residue field $\kres(y)$ (which is the case, for example, if $f^{-1}(y)$ is a _separable scheme_ over $\kres(y)$, i.e. reduced and such that the fields corresponding to its irreducible components are separable extensions of $\kres(y)$).
\oldpage{182-21}
Then the covering $Y'$ of $Y$ associated to $f_*(\scr{O}_X)$ is unramified.
:::

The proof is easy, thanks to [Theorem 2](#fga-2-theorem-2).

This proposition, combined with [Lemma 1](#fga-2-lemma-1), practically reduces the homotopical study of proper and flat morphisms (with separable fibres) to the case where $f_*(\scr{O}_X)=\scr{O}_Y$ (since, using Stein factorisation, we can replace $Y$ by $Y'$).

::: {.rmenv title="Remark" latex="{Remark}"}
A flat morphism of finite type whose fibres are separable (resp. simple) schemes is said to be _separable_ (resp. _simple_).
We show that, if $f$ is flat and if $f^{-1}(y)$ is separable (resp. simple) then there exists a neighbourhood of $f^{-1}(y)$ on which $f$ is separable (resp. simple).
The same result holds true for "absolutely normal" (this is _Bertini's theorem_).
:::

Let $f\colon X\to Y$ be a proper morphism such that

::: {.eqref #fga-2-equation-i}
$$
  f_*(\scr{O}_X) = \scr{O}_Y
\tag{i}
$$
:::

and let $X'$ be a finite scheme over $X$.
Let $Y'$ be the covering of $Y$ corresponding to the Stein factorisation of $X'\to Y$ (cf. [Theorem 5](#fga-2-theorem-5)).
Let $y\in Y$, so that the set of connected components of the fibre $F'$ of $X'$ over $y$ can be identified with the set of points $y'\in Y'$ over $y$ ([Theorem 5](#fga-2-theorem-5)).
Consider the evident morphism

::: {.eqref #fga-2-equation-asterisk}
$$
  X'\to X\times_Y Y'
\tag{$*$}
$$
:::

induced by the natural morphisms $X'\to X$ and $X\to Y'$;
this will be an isomorphism whenever $X'$ is of the form $X\times_Y Y''$, where $Y''$ is an unramified covering of $Y$, and then $Y'$ will be exactly $Y''$, and [Equation ($*$)](#fga-2-equation-asterisk) will be the identity.
We wish to precisely give the conditions for which $X'$ is of the form that we have just indicated, i.e. such that $Y'$ is unramified and [Equation ($*$)](#fga-2-equation-asterisk) is an isomorphism.
For this, we introduce the fibre $F$ of $X$ at $y$, which is a proper scheme over $\kres(y)$, for which $F'$ is a cover (an unramified one if $X$ is).
Let $F'_1$ be a connected component of $F'$ corresponding to a point $y'_1$ of $Y'$ over $y$.
Suppose further that

ii. $X'$ is unramified over $X$ at the points of $F'_1$ (and thus $F'_1$ is an unramified cover of $F$), and
iii. $F'_1$ is a geometrically trivial covering of $F$ (cf. [Lemma 3](#fga-2-lemma-3)).

::: {.itenv #fga-2-theorem-11 title="Theorem 11" latex="{Theorem 11}"}
Under these conditions, there exists an open neighbourhood $U'$ of $y'_1$ in $Y'$ such that [Equation ($*$)](#fga-2-equation-asterisk) is an isomorphism over $U'$.
\oldpage{182-22}
Furthermore, $Y'$ is unramified at $y'_1$ over $Y$ (but can be ramified at other points $y'$ of $Y'$ over $y$).
:::

Of course, conditions (ii) and (iii) are also necessary for the conclusion of the theorem.
The proof of the theorem is easy, thanks to [Lemma 3](#fga-2-lemma-3) and [Theorem 2](#fga-2-theorem-2).

::: {.itenv #fga-2-theorem-11-corollary-1 title="Corollary 1" latex="{Corollary 1}"}
Suppose that (i) is still satisfied.
For an unramified covering over $X$ to be isomorphic to the inverse image of an unramified covering $Y'$ of $Y$, it is necessary and sufficient for $X'$ to induce, on each fibre $f^{-1}(y)$, a geometrically trivial covering.
:::

By [Theorem 11](#fga-2-theorem-11), the set of points of $Y$ for which this condition is satisfied is open, and so it suffices to verify it at the points $y$ which are closed...
Note that the following statement is equivalent to [Corollary 1](#fga-2-theorem-11-corollary-1):

_The kernel of the homomorphism $\pi_1(X)\to\pi_1(Y)$ (which is surjective, by [Lemma 4](#fga-2-lemma-4)) is the closed invariant subgroup generated by the images in $\pi_1(X)$ of $\pi_1(f^{-1}(y))$, where $f^{-1}(y)$ denotes the scheme $f^{-1}(y)\otimes_{k(y)}\overline{\kres(y)}$ (where $\overline{\kres(y)}$ denotes an algebraic closure of $\kres(y)$)._

We note that, since we cannot _choose_ the same base point for all the fibres, the homomorphisms $\pi_1(f^{-1}(y))\to\pi_1(X)$ are determined (after having picked a base point for $X$, and then for $Y$) only up to composition with an inner automorphism of $\pi_1(X)$.

::: {.itenv #fga-2-theorem-11-corollary-2 title="Corollary 2" latex="{Corollary 2}"}
Under the general conditions of [Theorem 11](#fga-2-theorem-11), suppose further that $Y$, $X$, and $X'$ are integral, and let $K$, $L$, and $L'$ be their fields (respectively).
Then there exists a separable sub-extension $K'$ of $K$ in $L'$, linearly disjoint from $L$, such that $L'=LK'$ (whence $L'=L\otimes_KK'$).
:::

(We apply the last part of [Lemma 3](#fga-2-lemma-3) to the generic fibre of $X$).
The most interesting case in which we can apply [Theorem 11](#fga-2-theorem-11) is when $f$ is a _separable_ morphism.
Then $X'$ is also separable over $Y$, and so, by [Proposition 4](#fga-2-proposition-4), $Y'$ is unramified over $Y$, and so the right-hand side $X\times_YY'$ in [Equation ($*$)](#fga-2-equation-asterisk) is unramified over $X$.
From this, we easily conclude:

::: {.itenv #fga-2-theorem-11-corollary-3 title="Corollary 3" latex="{Corollary 3}"}
Suppose, in addition to (i), that $f$ is separable.
Let $X'$ be a connected unramified covering of $X$.
For $X$ to be the inverse image of an unramified covering $Y'$ of $Y$, it is necessary and sufficient for the induced covering $\overline{F}'$ of a geometric fibre $\overline{F}=\overline{f^{-1}(y)}$ to admit a regular section.
:::

Note that it was not necessary to suppose that $\overline{F}'$ be _geometrically_ trivial over $\overline{F}$ (which will be true _a posteriori_, even though _a priori_ this condition is a lot stronger).
\oldpage{182-23}
[Corollary 3](#fga-2-theorem-11-corollary-3) is equivalent to the following statement:

::: {.itenv #fga-2-theorem-11-corollary-4 title="Corollary 4" latex="{Corollary 4}"}
Let $f\colon X\to Y$ be a proper and separable morphism such that $f_*(\scr{O}_X)=\scr{O}_Y$.
Let $\overline{F}$ be the geometric fibre of a point $y\in Y$, and pick a geometric point in $\overline{F}$, which, by the morphisms $\overline{F}\to X\to Y$, gives geometric points in $X$ and $Y$; we take these three points as base points for the fundamental groups of $\overline{F}$, $X$, and $Y$, respectively.
Under these conditions, we have the exact sequence
$$
  \boxed{\pi_1(\overline{F}) \to \pi_1(X) \to \pi_1(Y) \to 0.}
$$
:::

From this, we easily deduce the two following statements of Serre--Lang, with all normality hypotheses removed:

::: {.itenv #fga-2-theorem-11-corollary-5 title="Corollary 5" latex="{Corollary 5}"}
Let $X$ and $Y$ be connected schemes over a field $k$, with $X$ or $Y$ proper over $k$, and suppose that the reduced scheme $X_\red$ is separable over $k$ (which is automatically true if $k$ is perfect) and complete.
Pick a geometric point $a$ (resp. $b$) in $X$ (resp. $Y$); this gives a geometric point $c=(a,b)$ in $X\times_kY$, and a natural morphism
$$
  \pi_1(X\times_kY,c) \to \pi_1(X,a)\times\pi_1(Y,b)
$$
(induced by the functorial morphisms from $\pi_1(X\times Y,c)$ to $\pi_1(X,a)$ and $\pi_1(Y,b)$).
This morphism is injective, and further bijective if $k$ is algebraically closed.
:::

(The surjectivity in the above claim is almost trivial).
We thus deduce, with Serre--Lang:

::: {.itenv #fga-2-theorem-11-corollary-6 title="Corollary 6" latex="{Corollary 6}"}
Let $X$ be a connected algebraic scheme over an algebraically closed field $k$, and let $K$ be an algebraically closed extension of $k$.
Then the fundamental groups of $X$ and $X\times_kK$ are the same, i.e. every unramified covering of the latter scheme is given by extension of scalars of an unramified covering (which is unique up to isomorphism) of $X$.
:::

::: {.rmenv title="Remarks" latex="{Remarks}"}
—

1. Using [Proposition 4](#fga-2-proposition-4), we see that the hypothesis that $f_*(\scr{O}_X)=\scr{O}_Y$ in [Corollary 4](#fga-2-theorem-11-corollary-4) is not essential.
    In the general case, instead of putting the trivial group $e$ after $\pi_1(Y)$, one must continue by $\pi_0(\overline{F})\to\pi_0(X)\to\pi_0(Y)\to e$,
    as in algebraic topology.

\oldpage{182-24}

2. In general, we cannot say anything at the moment about the kernel of $\pi_1(\overline{F})\to\pi_1(X)$, although it should involve a $\pi_2(Y)$.
    It seems, however, that we should be able to prove that $\pi_1(\overline{F})\to\pi_1(X)$ is _injective_ if $Y$ is the spectrum of a local ring $A$, by appealing to [Theorem 12](#fga-2-theorem-12) below (which shows that this is the case if $A$ is _complete_).
:::

[Theorem 11](#fga-2-theorem-11) used only [Theorem 1](#fga-2-theorem-1) and [Theorem 2](#fga-2-theorem-2);
we will now use [Theorem 3](#fga-2-theorem-3), along with the following elementary lemma:

::: {.itenv #fga-2-lemma-6 title="Lemma 6" latex="{Lemma 6}"}
Let $X$ be a scheme, and $X_0$ the corresponding reduced scheme (i.e. where we have killed all the nilpotent elements).
Then every unramified covering $X'_0$ of $X_0$ is induced by an unramified covering $X'$ of $X$, determined up to isomorphism.
:::

This lemma, which is of a purely local nature, plays a role analogous to that of [Theorem 8](#fga-2-theorem-8) here, in the theory of modules.
Combining it with the existence theorem ([Theorem 3](#fga-2-theorem-3)), we obtain:

::: {.itenv #fga-2-theorem-12 title="Theorem 12" latex="{Theorem 12}"}
Let $A$ be a complete local Noetherian ring with residue field $k$.
Let $X$ be a proper scheme over $A$.
Then every unramified covering $X'_0$ of $X_0=X\otimes_Ak$ is induced by an unramified covering $X'$ of $X$, unique up to isomorphism.
:::

In other words:

::: {.itenv #fga-2-theorem-12-corollary-1 title="Corollary 1" latex="{Corollary 1}"}
Pick a geometric point in $X_0$ as the base point for the fundamental groups of $X_0$ and $X$.
Then the canonical homomorphism $\pi_1(X_0)\to\pi_1(X)$ is an _isomorphism_.
:::

Applying [Lemma 5](#fga-2-lemma-5) to $X_0$ (supposing that $H^0(X_0,\scr{O}_{X_0})=k$, for simplicity), and noting that, since $A$ is complete, the unramified extensions of $A$ correspond to unramified extensions of its residue field, i.e. $\pi_1(Y)=\pi_1(k)$ (where $Y=\Spec(A)$).
We obtain the exact sequence:
$$
  e \to \pi_1(\overline{X_0}) \to \pi_1(X) \to \pi_1(Y) \to e.
$$

::: {.itenv #fga-2-theorem-12-corollary-2 title="Corollary 2" latex="{Corollary 2}"}
Let $f\colon X\to Y$ be a proper flat morphism, and let $y_1$ be a point of $Y$, and $y_0$ a specialisation of $y_1$.
Consider the corresponding "geometric" fibres $\overline{X_1}$ and $\overline{X_0}$, and suppose that $\overline{X_0}$ is separable and connected (which implies that $\overline{X_1}$ satisfies the same conditions).
Then we can find a group homomorphism $\pi_1(X_1)\to\pi_1(X_0)$, defined up to inner automorphism.
Further, this homomorphism is _surjective_.
:::

\oldpage{182-25}
We might hope that this homomorphism is always _bijective_.
Unfortunately, this is not the case in general if $\kres(y_0)$ is of characteristic $>0$.
We will, however, obtain below a group containing the kernel of this homomorphism (at least in the case where $\overline{X_0}$ is simple), implying that, if $\kres(y_0)$ is of characteristic $0$, then the above homomorphism is bijective (which is a result that we can also prove by transcendentality).
At the very least, we already have, in any case, a group containing $\pi_1$, given by a special fibre, using the one given by a generic fibre.
Using, for example, the fact that an algebraic curve in characteristic $p$ lifts to a curve in characteristic $0$ ([Corollary 4 of Theorem 9](#fga-2-theorem-9-corollary-4)), we obtain, by transcendentality:

::: {.itenv #fga-2-theorem-12-corollary-3 title="Corollary 3" latex="{Corollary 3}"}
Let $X_0$ be the scheme of complete simple curve over an algebraically closed field of arbitrary characteristic, and let $g$ be the genus of $X_0$.
Then $\pi_1(X_0)$ admits $2g$ topological generators, related by the well-known relation.
:::

We thus deduce, by a well-known technique using hyperplane sections:

::: {.itenv #fga-2-theorem-12-corollary-4 title="Corollary 4" latex="{Corollary 4}"}
Let $X$ be a simple projective scheme over an algebraically closed field of arbitrary characteristic.
Then $\pi_1(X)$ admits a finite number of topological generators.
:::

We wish to describe the kernel of the homomorphism $\pi_1(\overline{X_1})\to\pi_1(\overline{X_0})$.
For this, we can suppose that $Y$ is the spectrum of a discrete complete valuation ring $V=\scr{O}_y$ (where $y=y_0$).
The question is the equivalent to the following:
given an unramified covering $\overline{X'_1}$ of $\overline{X_1}$ (which as can suppose to be Galois, if we wish), under which conditions must it come from an unramified covering of $X_0$?
A priori, the given covering comes, by extension of scalars, from an unramified covering $X'_1$ of $X_1\otimes_KK'$, where $K'$ is a finite extension of the algebraic closure $\overline{K}$ of the field of fractions $K$ of $V$;
if $X'_1$ were Galois, of group $G$, then we could choose $X'_1$ to also be Galois of group $G$.
Thus: _for $X'_1\otimes_{K'}\overline{K}=\overline{X'_1}$ to come from an unramified covering of $X_0$, it is necessary and sufficient for there to exists a finite extension $K''$ of $K'$ in $\overline{K}$ such that $X''_1=X'_1\otimes_{K'}K''$ is of the form $X''\otimes_{V''}K''$, where $V''$ is the normal closure of $V$ in $K''$, and where $X''$ is an unramified covering of $X\otimes_V V''$._
Suppose, for example, that $X_0$ is absolutely normal, whence $X\otimes_V V''$ is normal (since it is flat over $V''$ and has normal special fibre), and its field of functions is identical to $K''(X_1)$, which is the field of functions of
$$
  X_1\otimes_K K'' = (X\otimes_VK)\otimes_KK'' = X\otimes_VK'' = (X\otimes_VV'')\otimes_{V''}K''.
$$
\oldpage{182-26}
Let $L''=K''(X'_1)$ be the field of functions of $X'_1\otimes_{K'}K''$, which is a separable finite extension of $K''(X_1)$, and the above condition also implies that _$L''$ is an unramified extension of the field of functions of $X\otimes_VV''$_ (i.e. the normalisation of $X\otimes_V V''$ in $L''$ is unramified over $X\otimes_VV''$).
It suffices to show that $L''$ is unramified at the points of the special fibre of $X\otimes_VV''$ (since it is unramified over the generic fibre $X_1\otimes_KK''$).
If $X_0$ is now _simple_, then it follows from the "_purity theorem_" of Nagata--Zariski that it even suffices to show that $L''$ is unramified over the local ring $\scr{O}''$ of the generic point of the normalisation of $X\otimes_VV''$, which is a discrete valuation ring, equal to the normalisation in $K''(X_1)$ of the local ring $\scr{O}\subset K(X_1)$ of the generic point of the special fibre of $X$.
We thus obtain:

::: {.itenv #fga-2-theorem-12-corollary-5 title="Corollary 5" latex="{Corollary 5}"}
Under the above conditions, and with the above notation, for the unramified covering $X'_1\otimes_{K'}\overline{K}$ of $\overline{X_1}=X_1\otimes_K\overline{K}$ to come from an unramified covering of $\overline{X_0}$, it is necessary and sufficient for there to exist a finite sub-extension $K''$ of $\overline{K}/K'$ such that $K''(X'_1)$ is unramified over the discrete valuation ring $\scr{O}''\subset K''(X_1)$.
:::

Now note that $\scr{O}''$ is the normalisation in $K''(X_1)$ of the discrete valuation ring $\scr{O}'\subset K'(X_1)$ (which is the normalisation of $\scr{O}$ in $K'(X_1)$), and that $\scr{O}'$ contains the normalisation $V'$ of $V$ in $K'$, with a uniformiser $u$ of $V'$ being also a uniformiser of $\scr{O}'$.
Suppose now that $X'_1$ is Galois, with Galois group $G$ _of order $n$, coprime to the characteristic $p$ of $\kres(y_0)$_ (which is also the characteristic of the residue field of $\scr{O}'$).
Then $K'(X_1')$ is "tamely ramified" over $\scr{O}'$, from which it easily follows (via "_Abhyankar's lemma_") that, if we adjoin an $n$-th root $v$ of a uniformiser of $\scr{O}'$, then it becomes unramified over the normalisation of $\scr{O}'$ in $K'(X_1)(v)$.
But we can take $v$ to be an $n$-th root of a uniformiser of $V'$, which shows that the condition of [Corollary 5](#fga-2-theorem-12-corollary-5) is satisfied.
(This idea of using Abhyankar's lemma and the purity theorem was given to me by Serre).
To express the result we thus obtain, we introduce, for every totally disconnected compact group $\pi$, the quotient $\overline{\pi}$ of $\pi$ by the closed subgroup generated by its Sylow $p$-sub-groups, i.e. the projective limit of the discrete quotient groups of $\pi$ that are of order coprime to $p$.
With this notation, we obtain:

::: {.itenv #fga-2-theorem-13 title="Theorem 13" latex="{Theorem 13}"}
Let $f\colon X\to Y$ be a proper flat morphism, $y_1$ a point of $Y$, and $y_0$ a specialisation of $y_1$.
Suppose that $\overline{X_0}$ is connected and simple.
\oldpage{182-27}
Then the homomorphism $\overline{\pi_1}(\overline{X_1})\to\overline{\pi_1}(\overline{X_0})$ induced by the
surjective homomorphism from [Corollary 2 of Theorem 12](#fga-2-theorem-12-corollary-2) is an _isomorphism_.
:::

In other words:

::: {.itenv #fga-2-theorem-13-corollary-1 title="Corollary 1" latex="{Corollary 1}"}
The classification of unramified Galois coverings, of Galois group of order coprime to the characteristic $p$ of $\kres(y_0)$, is the same for $\overline{X_0}$ and for $\overline{X_1}$.
:::

In particular, if $\kres(y_0)$ is of characteristic $0$, then we see, algebraically, that $\pi_1(\overline{X_1})\to\pi_1(\overline{X_0})$ is bijective.

We finally point out that the techniques utilised also give the following result, which is more general than [Theorem 13](#fga-2-theorem-13):

::: {.itenv #fga-2-theorem-14 title="Theorem 14" latex="{Theorem 14}"}
Let $f\colon X\to Y$ be a proper simple morphism, and let $D$ be a closed subscheme of $X$ that is simple over $Y$, and of codimension $1$ at all points.
Given a fibre $Z=f^{-1}(z)$ of $f$, let $Z'=Z\setminus Z\cap D$, and let $\pi_1^\mathrm{t}(\overline{Z'})$ be the quotient of the fundamental group $\pi_1(Z')$ that classifies the unramified coverings of $\overline{Z'}$ that are "tamely ramified" over $\overline{Z\cap D}$.
Let $y_0$ and $y_1$ be as in [Theorem 13](#fga-2-theorem-13).
Then there exists a _surjective_ homomorphism (defined up to inner automorphism) $\pi_1^\mathrm{t}(\overline{X'_1})\to\pi_1^\mathrm{t}(\overline{X'_0})$, and the corresponding homomorphism $\overline{\pi_1^\mathrm{t}}(\overline{X'_1})\to\overline{\pi_1^\mathrm{t}}(\overline{X'_0})$ is an isomorphism.
:::

From this we obtain corresponding variants of the corollaries of [Theorem 13](#fga-2-theorem-13), and of [Corollary 4 of Theorem 12](#fga-2-theorem-12-corollary-4).
Similarly, using [Corollary 3 of Theorem 9](#fga-2-theorem-9-corollary-3), we obtain, transcendentally:

::: {.itenv #fga-2-theorem-14-corollary-1 title="Corollary 1" latex="{Corollary 1}"}
Let $X_0$ be the scheme of a complete simple curve over an algebraically closed field of arbitrary characteristic, and let $S=(s_i)_{1\leq i\leq n}$ be a finite subset of $X_0$ with $n$ elements.
Then $\pi_1^\mathrm{t}(X_0\setminus S)$ admits $2g+n$ topological generators, $x_i,y_i,\sigma_j$ (for $1\leq i\leq g$ and $1\leq j\leq n$), satisfying the relation
$$
  \left(\prod_i x_iy_ix_i^{-1}y_i^{-1}\right)\sigma_1\ldots\sigma_n = 1,
$$
where the $\sigma_j$ are generators of the inertia groups corresponding to the $s_j$.
For every finite group $G$ _of order coprime to the characteristic_ that is generated by elements $\overline{x_i},\overline{y_i},\overline{\sigma_j}$ satisfying the above relation, there exists an unramified Galois covering of $X_0\setminus S$, of group $G$, with inertia groups at the points $s_j$ generated by the $\overline{\sigma_j}$.
:::

If $X_0$ is of genus $0$, and $n=3$, then we have a solution to the "_three point problem_", at least for Galois coverings of order coprime to the characteristic.
\oldpage{182-28}
(Here, [Theorem 9](#fga-2-theorem-9) is actually useless, and it seems that we can deduce the above corollary from the particular case in question in the three point problem).

::: {.rmenv title="Remarks" latex="{Remarks}"}
—

1. A more complete study, probably involving generalised Galois coverings of $X$, $X_0$, and $X_1$ (of eventually infinitesimal Galois group), should allow one to recover the kernel in [Corollary 2 of Theorem 12](#fga-2-theorem-12-corollary-2).
    However, a study of coverings admitting ramifications that are not "tame" seems much more difficult.

2. [Lemma 6](#fga-2-lemma-6), combined with a result of Grauert concerning the formal completion of a non-singular projective scheme along a hyperplane section (or with the theorem, as yet unproven, mentioned in Remark 2 after [Theorem 11](#fga-2-theorem-11)), would also allow us to prove, in "abstract" algebraic geometry, the classical _Lefschetz theorem_ on the fundamental group.
:::