# Picard schemes: Existence theorems {#fga-3.v}

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

\providecommand{\Pic}{\operatorname{Pic}}
\providecommand{\shPic}{\mathscr{P}\kern -.5pt ic}
\providecommand{\repPic}{\underline{\Pic}}
\providecommand{\OO}{\scr{O}}
\providecommand{\simto}{\xrightarrow{\sim}}
\providecommand{\HH}{\operatorname{H}}
\providecommand{\Sch}{\mathtt{Sch}}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\from}{\leftarrow}
\providecommand{\pr}{\mathrm{pr}}
\providecommand{\div}{\operatorname{div}}
\providecommand{\Div}{\operatorname{Div}}
\providecommand{\shDiv}{\mathscr{D}\kern -.5pt iv}
\providecommand{\Hilb}{\operatorname{Hilb}}
\providecommand{\shHilb}{\mathscr{H}\kern -.5pt ilb}
\providecommand{\repHilb}{\underline{\Hilb}}

<!-- Shortcuts -->

<!-- Content -->

::: {.original-citation}
Grothendieck, A.
"Technique de descente et théorèmes d'existence en géométrie algébrique, V: Les schémas de Picard: Théorèmes d'existence".
_Séminaire Bourbaki_ **14** (1961--62), Talk no. 232.
:::

**TO-DO:**

- **additif**
- **errata**


## Relative Picard groups and functors {#fga-3-v-section-1}

\oldpage{232-01}
For every prescheme (more generally, every ringed space) $X$, we define the (*absolute*) *Picard group* of $X$, denoted by $\Pic(X)$, to be the group of isomorphism classes of invertible (i.e. locally isomorphic to $\OO_X$) modules on $X$.
We thus have a canonical isomorphism

::: {.eqref #fga-3-v-equation-1.1 title="" latex=""}
$$
  \Pic(X)
  \simto \HH^1(X,\OO_X^\times)
\tag{1.1}
$$
:::

where $\OO_X^\times$ denotes the sheaf of units of $\OO_X$ (which can be identified with the sheaf of automorphisms of the invertible module **!!TO-DO: type?!!** $\OO_X$).
Note that $X\mapsto\Pic(X)$ is a contravariant functor in $X$ in the evident way, and that the isomorphism [(1.1)](#fga-3-v-equation-1.1) is functorial.

If $X$ is a prescheme over a prescheme $S$, then, for variable $S'$ in the category $\Sch_{/S}$ of preschemes over $S$, we have a contravariant functor $S'\mapsto\Pic(X\times_S S')$ thanks to the above.
This functor has no chance of being "representable" ([@Gro1959, II, A]) since, as a consequence of the existence of *non-trivial automorphisms* of invertible modules that we propose to classify, this functor is not of a *"local nature"* ([@Gro1960a, IV, 5.4]).
There is thus an opportunity to "make it local", by introducing, for every relative prescheme $X/S$, a group of a relative nature

::: {.eqref #fga-3-v-equation-1.2 title="" latex=""}
$$
  \Pic'(X/S)
  = \HH^0(S,\RR^1f_*(\OO_X^\times))
\tag{1.2}
$$
:::

(where $f\colon X\to S$ is the structure morphism) (cf. [@Gro1959, II, C.3]).
In *loco citato* this group is called the relative Picard group, but it will be preferable to call it here the *restricted relative Picard group* of $X/S$, for reasons that will be made clear.
As $S'$ varies over $\Sch_{/S}$, $S'\mapsto\Pic'(X\times_S S'/S')$ is a contravariant functor in $S'$, denote also by $\shPic'_{X/S}$, thus given essentially by the formula

::: {.eqref #fga-3-v-equation-1.3 title="" latex=""}
$$
  \shPic'_{X/S}(S')
  = \Pic(X\times_S S'/S').
\tag{1.3}
$$
:::

\oldpage{232-02}
This functor is now "of local nature", given that did what was necessary to make this happen.
Intuitively, the right-hand side of [(1.3)](#fga-3-v-equation-1.3) can be understood as the set of "algebraic families" of classes of invertible sheaves on (the fibres of) $X/S$, indexed by the parameter prescheme $S'/S$.
When the functor $\shPic'$ is representable, the prescheme over $S$ that represents it is denoted by $\repPic_{X/S}$, and is called the *Picard prescheme* of $X$ over $S$, and so we will then have

::: {.eqref #fga-3-v-equation-1.4 title="" latex=""}
$$
  \Hom_S(S',\repPic_{X/S})
  \cong \shPic'_{X/S}(S')
  = \Pic'(X\times_S S'/S').
\tag{1.4}
$$
:::

There are, however, important cases where $\shPic'_{X/S}$ is not representable (example: the "Brauer--Severi" variety over a field $k$, without a rational point over $k$), but where there nevertheless exists a natural definition of a relative Picard prescheme.
This is due to the fact that, in the definition of the functor $\shPic'$ from the absolute Picard groups $\Pic(X\times_S S'/S')$, we have not localised enough;
more precisely, $\shPic'$ is not in general "compatible with faithfully flat descent".
We now explain the details.

Let $(\scr{M})$ be the set of morphisms of preschemes that are *faithfully flat and quasi-compact*;
this set is stable under base change and composition.
Let $P$ be a contravariant functor from $\Sch_{/S}$ to the category of sets, and, for every $S$-morphism $u\colon T'\to T$ with $u\in(\scr{M})$, consider the diagram

::: {.eqref #fga-3-v-equation-1.5 title="" latex=""}
$$
  P(T)
  \to P(T')
  \rightrightarrows P(T'\times_T T')
\tag{1.5}
$$
:::

which is given by $P$ applied to the diagram
$$
  T
  \from T'
  \underset{\pr_2}{\overset{\pr_1}{\leftleftarrows}} T'\times_T T'.
$$
If $P$ is representable, it follows from the theory of descent ([@Gro1959, I, B, Theorem 2]) that the diagram [(1.5)](#fga-3-v-equation-1.5) is exact for all $u\in(\scr{M})$.
We express this fact by saying that $P$ is compatible with $(\scr{M})$, in the event that $P$ is "compatible with faithfully flat descent", or that the *"presheaf"* $P$ on $\Sch_{/S}$ is a *"sheaf"* for the notion of localisation given by the set $(\scr{M})$.
If $P$ is arbitrary, then a standard procedure, well known in the case of usual topological localisation, allows us to associate to it a "sheaf" $\scr{P}$ and a homomorphism of functors $P\to\scr{P}$ that is universal in an obvious sense.
The construction of $\scr{P}$ can be made explicit in the following way: to define $\scr{P}(T)$, we denote, for all $T'$ over $T$ such that the morphism $u\colon T'\to T$ is in $(\scr{M})$, by $\overline{\HH}^0(T'/T,P)$ the subset of $P(T')$ consisting of the elements $\xi$ such that their images $\xi_1,x_2$ in $P(T'\times_T T')$ are such that there exists a morphism $v\colon T''\to T'\times_T T'$ in $(\scr{M})$ such that $\xi_1$ and $\xi_2$ have the same image in $P(T'')$.

\oldpage{232-03}
(N.B. The set $\overline{\HH}^0$ thus defined is larger than the set $\HH^0(T'/T,P)$ introduced in [@Gro1959, I, A.4.a]).
As $T'$ varies over fixed $T$ (always with $u\in(\scr{M})$), the $\overline{\HH}^0(T'/T,P)$ form an inductive system (when the set of the $T'$ is endowed with a preorder defined by domination), and we set

::: {.eqref #fga-3-v-equation-1.6 title="" latex=""}
$$
  \scr{P}(T)
  = \varinjlim_{T'} \overline{\HH}^0(T'/T,P).
\tag{1.6}
$$
:::

The functoriality in $T$ of this expression is evident.

When
$$
  P(T)
  = \Pic(X\times_S T)
$$
the contravariant functor on $\Sch_{/S}$ defined by [(1.6)](#fga-3-v-equation-1.6) is called the *relative Picard functor* of $X$ over $S$, and denoted by $\shPic_{X/S}$, and we define the *relative Picard group* of $X$ over $S$, denoted by $\Pic(X/S)$, the group $\shPic_{X/S}(S)$.
We then have an evident bijection

::: {.eqref #fga-3-v-equation-1.7 title="" latex=""}
$$
  \shPic_{X/S}(T)
  \simto \Pic(X\times_S T/T).
\tag{1.7}
$$
:::

An element of $\Pic(X/S)$ is thus defined by means of an element $\xi'$ of a group $\Pic(X\times_S S')$ (where $S'\to S$ is faithfully flat and quasi-compact) such that we can find a faithfully flat quasi-compact morphism $S''\to S'\times_S S'$ such that the two inverse images of $\xi'$ in $\Pic(X\times_S S'')$ are the same.
An element $\xi'$ of $\Pic(X\times_S S')$ and an element $\xi_1$ of $\Pic(X\times_S S_1)$ (satisfying the conditions that we have just stated) define the same element of $\Pic(X/S)$ if and only if there exists a faithfully flat quasi-compact morphism $S'_1\to S'\times_S S_1$ such that the images of the two elements in question in $\Pic(X\times_S S'_1)$ are equal.
It is often convenient to work instead with the functor $P'=\shPic'_{X/S}$ introduced above, and we immediately note that the canonical morphism $P\to P'$ defines an *isomorphism*

::: {.eqref #fga-3-v-equation-1.8 title="" latex=""}
$$
  \scr{P}
  \simto \scr{P}'
\tag{1.8}
$$
:::

which gives a description of $\shPic_{X/S}$ in terms of $\shPic'_{X/S}=P'$ that is usually more convenient.
By [(2.3)](#fga-3-v-corollary-2.3) below, if we replace $P$ by $P'$ in the description of $\Pic(X/S)$ that we have just given then we can take $S''=S'\times_S S'$ and $S'_1=S'\times_S S_1$, at least under the conditions given in *loco citato*.

If the functor $\shPic_{X/S}$ is representable, we say that $X/S$ admits a Picard prescheme, and the prescheme over $S$ that represents the functor is called the *Picard prescheme* of $X$ over $S$, and denoted by $\repPic_{X/S}$.
For this, it evidently suffices that $P'=\shPic_{X/S}$ be representable, since then $P'$ is already a "sheaf", and equation [(1.8)](#fga-3-v-equation-1.8) proves that the morphism $P'\to\scr{P}'$ can be identified with the canonical morphism

::: {.eqref #fga-3-v-equation-1.9 title="" latex=""}
$$
  \shPic'_{X/S}
  \to \shPic_{X/S}
\tag{1.9}
$$
:::

which is then an isomorphism.
This means that our terminology is compatible with that introduced above with [(1.4)](#fga-3-v-equation-1.4).
In general, when $\repPic_{X/S}$ exists it is defined by the functorial isomorphism

::: {.eqref #fga-3-v-equation-1.10 title="" latex=""}
$$
  \Hom_S(S',\repPic_{X/S})
  \simto \Pic(X\times_S S'/S').
\tag{1.10}
$$
:::


## Relations between the various relative and absolute Picard groups {#fga-3-v-section-2}

::: {.itenv #fga-3-v-proposition-2.1 title="Proposition 2.1" latex="{Proposition 2.1}"}
Let $f\colon X\to S$ be a morphism such that $\OO_S\simto f_*(\OO_X)$.
Then we have an exact sequence
$$
  0
  \to \Pic(S)
  \to \Pic(X)
  \to \Pic'(X/S).
$$
If $X$ admits a section over $S$, then the last morphism is surjective, i.e. we have an isomorphism
$$
  \Pic'(X/S)
  \simto \Pic(X)/\Pic(S).
$$
:::

::: {.proof}
The exact sequence can be considered as the low degrees of the exact sequence that corresponds to the Leray spectral sequence for $f$ and $\OO_X$.
The second claim is equally formal.
:::

::: {.itenv #fga-3-v-proposition-2.2 title="Proposition 2.2" latex="{Proposition 2.2}"}
Let $f\colon X\to S$ be a quasi-compact separated morphism such that $\OO_S\simto f_*(\OO_X)$, and let $S'\to S$ be a faithfully flat quasi-compact morphism.
Then

i. $\Pic'(X/S)\to\Pic'(X\times_S S'/S')$ is injective;
ii. If $X$ locally admits a section over $S$ (i.e. every $s\in S$ has an open neighbourhood $U$ such that $X|U$ has a section over $U$), then the diagram
  $$
    \Pic'(X/S)
    \to \Pic'(X\times_S S'/S')
    \rightrightarrows \Pic'(X\times_S S''/S'')
  $$
  (where $S''=S'\times_S S'$) is exact.
:::

::: {.proof}
The first claim follows, thanks to the elementary properties of faithfully flat descent, from the following general remark.
\oldpage{232-05}
If $f\colon X\to S$ is a morphism such that $\OO_S\simto f_*(\OO_X)$, then the functor $\scr{F}\mapsto f^*(\scr{F})$, from the category of locally free modules of finite type on $S$ to the category of locally free modules of finite type on $X$, is fully faithful, and its essential image is given by the modules $\scr{G}$ on $X$ such that $f_*(\scr{G})$ is locally free and such that the canonical homomorphism
$$
  f^*f_*(\scr{G})
  \to \scr{G}
$$
is an isomorphism.
The second statement was proven by the theory of descent in [@Gro1959, I, B.4].
:::

The results of [(2.2)](#fga-3-v-proposition-2.2) can also be stated as follows:

::: {.itenv #fga-3-v-corollary-2.3 title="Corollary 2.3" latex="{Corollary 2.3}"}
Under the conditions of [(2.2)](#fga-3-v-proposition-2.2), the canonical homomorphism [(1.9)](#fga-3-v-equation-1.9) $\shPic'_{X/S}\to\shPic_{X/S}$ is injective, and even bijective if $X$ locally admits a section over $S$.
(In the latter case, the relative Picard group $\Pic(X/S)$ is identified with the restricted relative Picard group $\Pic'(X/S)$.)
:::

Combining this with [(2.1)](#fga-3-v-proposition-2.1), we thus obtain:

::: {.itenv #fga-3-v-corollary-2.4 title="Corollary 2.4" latex="{Corollary 2.4}"}
Under the conditions of  [(2.2)](#fga-3-v-proposition-2.2), we have an exact sequence
$$
  0
  \to \Pic(S)
  \to \Pic(X)
  \to \Pic(X/S).
$$
If $X$ admits a section over $S$, then the last homomorphism is surjective, i.e. we have an isomorphism
$$
  \Pic(X/S)
  \simto \Pic(X)/\Pic(S).
$$
:::

::: {.rmenv #fga-3-v-remark-2.5 title="Remark 2.5" latex="{Remark 2.5}"}
Let $f\colon X\to S$ be a morphism such that $\OO_S\simto f_*(\OO_X)$, and let $g$ be a section of $X$ over $S$.
Let $\scr{L}$ be an invertible module on $X$.
We define the *$g$-rigidification* of $\scr{L}$ to be an isomorphism $\OO_S\simto g^*(\scr{L})$, and a *$g$-rigidified invertible module* to be an invertible module $\scr{L}$ on $X$ endowed with a $g$-rigidification.
Every automorphism of such a structure is trivial, and $\Pic'(X/S)$ can be identified with the set of isomorphism classes of $g$-rigidified invertible modules on $S$.
(It is this fact that allows us to use the theory of descent to prove [(2.2), (ii)](#fga-3-v-proposition-2.2).)
This gives a new interpretation of $\Pic(X/S)$, at least when $f$ is further quasi-compact and separated, so that $\Pic(X/S)\simto\Pic'(X/S)$ by [(2.3)](#fga-3-v-corollary-2.3).
:::

::: {.rmenv #fga-3-v-remark-2.6 title="Remark 2.6" latex="{Remark 2.6}"}
Let $f\colon X\to S$ be a morphism as in [(2.2)](#fga-3-v-proposition-2.2), and let $S'\to S$ be a faithfully flat quasi-compact morphism such that there exists an $S$-morphism $S'\to X$, i.e. such that there exists a section of $X'=X\times_S S'$ over $S'$.
\oldpage{232-06}
Let $S''=S'\times_S S'$, and $X''=X\times_S S''$, and consider the exact sequence
$$
  \Pic(X/S)
  \to \Pic(X'/S')
  \rightrightarrows \Pic(X''/S'').
$$
Applying [(2.4)](#fga-3-v-corollary-2.4), we obtain the exact sequence
$$
  \Pic(X/S)
  \to \Pic(X')/\Pic(S')
  \rightrightarrows \Pic(X'')/\Pic(S'').
$$
In particular, every element of the relative Picard group already "comes from" an element of $\Pic(X')$.
This gives a substantial simplification of the description of the relative Picard group given in the previous section, and even of the Picard functor of $X$ over $S$, since, for all $T$ over $S$, we can apply the above to $X\times_S T/T$ and to the morphism $T'=S'\times_S T\to T$.
If, for example, $f$ itself is faithfully flat, then we can take $S'=X$, which allows us, whenever $f$ is further of finite type (resp. simple, etc.), to restrict, in the description of the relative Picard functor $T\mapsto\Pic(X\times_S T/T)$, to the base changes $T'\to T$ that are of finite type (resp. simple, etc.).
If $f$ is projective and flat, and $S$ locally Noetherian, then we can prove that we can take in the above a $S'\to S$ such that $S'$ is the direct sum of *flat covers* $S'_i$ of opens $S_i$ of $S$ that cover $S$;
if $f$ is further separable, then we can take $S'_i$ to be étale over $S_i$.
:::


## The principal existence theorem: statement {#fga-3-v-section-3}

We do not have, not even conjecturally, an existence statement for Picard preschemes that encompasses all known cases.
A "practically necessary" condition, if we can say that, is that $f\colon X\to S$ be *proper* (ensuring essential finiteness properties) and *flat*.
These conditions are not sufficient, even if $S$ is the spectrum of the algebra of dual numbers $k[t]/(t^2)$ over a field $k$ (say, the field $\mathbb{C}$ of complex numbers), and $X$ is of dimension $1$.
At the moment of writing this present talk, the most important existence theorems for the Picard prescheme follow from the following theorem:

::: {.itenv #fga-3-v-theorem-3.1 title="Theorem 3.1" latex="{Theorem 3.1}"}
Let $f\colon X\to S$ be a morphism of locally Noetherian preschemes.
Suppose that
\oldpage{232-07}

i. $f$ is projective
ii. $f$ is flat
iii. the geometric fibres of $f$ are integral.

Under these conditions, $\repPic_{X/S}$ exists.
:::

The proof, which will be sketched in the following two sections, will at the same time show the following:
Let $\xi$ be the section of $\repPic_{X/S}$ that corresponds to a very ample sheaf $\OO_X(1)$ over $X/S$ (i.e. induced by a projective embedding $X\to\mathbb{P}(\scr{E})$);
then there exists an open subset $U$ of $\repPic_{X/S}$, disjoint union of quasi-projective open subsets of $S$, such that $U$ is stable under translation by $\xi$, and such that $\repPic_{X/S}$ is the increasing union of opens $U\setminus n\xi$ (each isomorphic to $U$).
It thus follows, in particular, that, under the conditions of [(3.1)](#fga-3-v-theorem-3.1), that $\Pic_{X/S}$ is *separated* over $S$.

::: {.rmenv #remark-3.2 title="Remark 3.2" latex="{Remark 3.2}"}
We see from examples (with $S$ the spectrum of a discrete valuation ring, and $X$ of relative dimension $1$ over $S$, for example), that if we omit hypothesis (iii) in [(3.1)](#fga-3-v-theorem-3.1) and replace it with the weaker hypothesis that, for all $s\in S$, the homomorphism $k(s)\to\HH^0(X_s,\OO_{X_s})$ be an isomorphism, then $\repPic_{X/S}$ is not necessarily separated over $S$;
both in the case where the geometric fibres of $f$ are reduced, but where a generic integral geometric fibre "blows up" by specialisation into two irreducible components, and in the case where the geometric fibres of $f$ are irreducible, but where a generic integral geometric fibre specialises to a "multiple fibre".
The first case happens, for example, with a conic that degenerates into two concurrent lines; an example of the second was shown to me by D. Mumford, with an elliptic curve that degenerates to a double elliptic curve.
These examples work in any characteristic.
:::

::: {.rmenv #fga-3-v-remark-3.3 title="Remark 3.3" latex="{Remark 3.3}"}
Under the conditions of [(3.1)](#fga-3-v-theorem-3.1), I do not know if $\repPic_{X/S}$ is a disjoint union of opens that are of finite type, thus quasi-projective, over $S$.
We note that the study of the Hilbert polynomials $Q\in\mathbb{Q}[t]$ allows us, as in the case of Hilbert schemes ([@Gro1959, IV]), to give a decomposition of $\repPic_{X/S}$ as a disjoint sum of opens $\Pic_{X/S}^Q$, and it seems plausible that these opens are quasi-projective over $S$;
this is what we will see at least in the next talk when $f$ is a simple morphism.
We draw attention to the fact that if we replace hypothesis (i) by the hypothesis "$X$ is *locally* projective over $S$" (which is sufficient to prove [(3.1)](#fga-3-v-theorem-3.1), since the question of existence of $\repPic_{X/S}$ is clearly local on $S$) however, then it is easy to give examples where *$\repPic_{X/S}$ contains connected components that are not of finite type over $S$*.
\oldpage{232-08}
For example, let $X_0$ be a non-singular projective algebraic variety over an algebraically closed field $k$, endowed with an automorphism $u$ and an element $\xi$ of the Néron--Severi group of $X_0$ such that the $u^n(\xi)$ are pairwise distinct.
We can, for example, take $X_0$ to be the product of an elliptic curve $E$ with itself, and $u$ to be the automorphism $(x,y)\mapsto(x,y+x)$ of $E\times E$.
Let $S$ be the union of two non-singular irreducible curves that meet at two points $a$ and $b$.
There is a connected principal covering $P$ on $S$ of the group $\mathbb{Z}$, and using the action of $\mathbb{Z}$ on $X_0$ defined by $u$ we thus obtain an associated bundle on $S$, with fibre $X_0$ (trivial on $S\setminus\{a\}$ and $S\setminus\{b\}$), which is in fact an *abelian* scheme over $S$ in the particular case in question.
We easily see that $\repPic_{X/S}$, which is also the bundle associated to $P$ and to the action of $\mathbb{Z}$ on $\repPic_{X_0/k}$ via $u$, contains a connected component that is isomorphic to $P\times\repPic_{X_0/k}^0$ (where $\repPic^0$ denotes the connected component of the identity element in $\repPic$), which is not of finite type over $S$.
(One can equally produce analogous phenomena in various cases of non-separated Picard preschemes over $S$, as described in [(3.3)](#fga-3-v-remark-3.3)).
:::


## Relative Cartier divisors and projective bundles {#fga-3-v-section-4}

We will only need to use positive divisors, and we omit the qualification of "positive" in the rest of this section.

Let $X$ be a prescheme.
A *Cartier divisor*, or simply divisor, on $X$ is a closed subprescheme $D$ of $X$ defined by an ideal $\scr{J}$ that is an *invertible* module, i.e. locally generated by a section that is a *non-zero divisor* of $\OO_X$.
To $D$ we associate the invertible module
$$
  \scr{L}(D)
  = \scr{J}^{-1}
$$
and the canonical injection $\scr{J}\to\OO_X$ gives a canonical homomorphism
$$
  s_D\colon \OO_X
  \to \scr{J}^{-1}
  = \scr{L}(D)
$$
i.e. $s_D\in\Gamma(X,\scr{L}(D))$.
The data of a divisor is essentially *equivalent* to the data of an invertible module $\scr{L}$ on $X$ endowed with a section $s$ that is nowhere a zero divisor, by associating to such a pair $(\scr{L},s)$ the "divisor" of $s$, denoted by $\div(s)$.
\oldpage{232-09}
For a given invertible $\scr{L}$ on $X$, the set of divisors $D$ that define $\scr{L}$ is in bijective correspondence with the quotient set $\Gamma(X,\scr{L})^\times/\Gamma(X,\OO_X^\times)$, where $\Gamma(X,\scr{L})^\times$ denotes the subset of $\Gamma(X,\scr{L})$ consisting of sections that are nowhere zero divisors.

Now suppose that we have a morphism $f\colon X\to S$ that is locally of finite type, and suppose, for simplicity, that $S$ is locally Noetherian.
Let $\scr{J}$ be a coherent ideal on $X$, with $D$ the subscheme of $X$ that it defines, and let $x\in X$ and $s=f(x)$.
We will show that the following conditions are equivalent:

i. $\scr{J}$ is invertible at $x$ (i.e. $\scr{J}_x$ is generated by a regular element of $\OO_{X,x}$) and $D$ is flat over $S$ at $x$.
ii. $X$ and $D$ are flat over $S$ at $x$, and $D_s$ is a Cartier divisor on the fibre $X_s$ at the point $x$.
iii. $X$ is flat over $S$ at $x$, and $\scr{J}_x$ is generated by an element $f_x$ that induces on $X_s$ a non-zero divisor germ.

We then say that $D$ is a *relative Cartier divisor*m or simply a relative divisor, on $X/S$ at the point in question.
We note that, in (i), $D$ is also a relative divisor at points in a neighbourhood of $x$, so if $X$ and $D$ are flat over $S$, with $D$ proper over $S$, then the set of $s\in S$ such that $D_s$ is a Cartier divisor in $X_s$ (i.e. such that $D$ is a relative Cartier divisor at the points of $X_s$) is an open subset of $S$.
We have also done what is necessary in the definition above in order to ensure that the notion of relative Cartier divisor be stable under arbitrary base change $S'\to S$.
So consider the set $\Div(X/S)$ of relative divisors on $X/S$, and then the contravariant functor in $S'$ (that varies over $S$) defined by
$$
  \shDiv_{X/S}(S')
  = \Div(X\times_S S'/S').
$$
Suppose that $X$ is flat and proper over $S$.
Then by the characterisation (ii) of relative Cartier divisors, $\shDiv_{X/S}$ can be considered as a sub-functor of the functor $\shHilb_{X/S}$ defined in [@Gro1959, IV], and the inclusion morphism
$$
  \shDiv_{X/S}
  \to \shHilb_{X/S}
$$
is "representable by open immersions" (cf. [@Gro1960a, IV, 3.13]) by the above remarks.
Using the principal existence theorem of [@Gro1959, IV], we find:

::: {.itenv #proposition-4.1 title="Proposition 4.1" latex="{Proposition 4.1}"}
Suppose that $f\colon X\to S$ is projective and flat.
\oldpage{232-10}
Then
:::
