name: Bookdown

on:
  push:
    branches:
      - main

jobs:
  bookdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup R
        uses: r-lib/actions/setup-r@master
          
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('DESCRIPTION') }}

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install Bookdown packages
        run: |
          R -e "install.packages('remotes')"
          R -e "remotes::install_github('rstudio/bookdown')"

      - name: Build site
        run: |
          ./build_html.R

      - name: Deploy to build branch
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: build
          folder: book
